/* Generated by nova-codegen. Do not edit. */
#include "nova_rt/nova_rt.h"

typedef struct { nova_int f0; } _NovaTuple1;
typedef struct { nova_int f0; nova_int f1; } _NovaTuple2;
typedef struct { nova_int f0; nova_int f1; nova_int f2; } _NovaTuple3;
typedef struct { nova_int f0; nova_int f1; nova_int f2; nova_int f3; } _NovaTuple4;
typedef struct { nova_int f0; nova_int f1; nova_int f2; nova_int f3; nova_int f4; } _NovaTuple5;
typedef struct { nova_int f0; nova_int f1; nova_int f2; nova_int f3; nova_int f4; nova_int f5; } _NovaTuple6;
typedef struct { nova_int f0; nova_int f1; nova_int f2; nova_int f3; nova_int f4; nova_int f5; nova_int f6; } _NovaTuple7;
typedef struct { nova_int f0; nova_int f1; nova_int f2; nova_int f3; nova_int f4; nova_int f5; nova_int f6; nova_int f7; } _NovaTuple8;

typedef enum {
    NOVA_TAG_SnowflakeError_InvalidMachineId,
    NOVA_TAG_SnowflakeError_ClockBackwards,
} Nova_SnowflakeError_Tag;
typedef struct Nova_SnowflakeError Nova_SnowflakeError;
struct Nova_SnowflakeError {
    Nova_SnowflakeError_Tag tag;
    union {
        struct {
            nova_int value;
        } InvalidMachineId;
        struct {
            nova_int now;
            nova_int last;
        } ClockBackwards;
    } payload;
};

static Nova_SnowflakeError* nova_make_SnowflakeError_InvalidMachineId(nova_int _0) {
    Nova_SnowflakeError* _r = (Nova_SnowflakeError*)nova_alloc(sizeof(Nova_SnowflakeError));
    _r->tag = NOVA_TAG_SnowflakeError_InvalidMachineId;
    _r->payload.InvalidMachineId.value = _0;
    return _r;
}

static Nova_SnowflakeError* nova_make_SnowflakeError_ClockBackwards(nova_int _0, nova_int _1) {
    Nova_SnowflakeError* _r = (Nova_SnowflakeError*)nova_alloc(sizeof(Nova_SnowflakeError));
    _r->tag = NOVA_TAG_SnowflakeError_ClockBackwards;
    _r->payload.ClockBackwards.now = _0;
    _r->payload.ClockBackwards.last = _1;
    return _r;
}

typedef struct Nova_SnowflakeGen Nova_SnowflakeGen;
struct Nova_SnowflakeGen {
    nova_int machine_id;
    nova_int last_ms;
    nova_int sequence;
};

typedef struct Nova_SnowflakeParts Nova_SnowflakeParts;
struct Nova_SnowflakeParts {
    nova_int timestamp_ms;
    nova_int machine_id;
    nova_int sequence;
};

static const nova_int TWITTER_EPOCH_MS = ((nova_int)1577836800000LL);
static Nova_SnowflakeGen* Nova_SnowflakeGen_static_new(nova_int machine_id);
static nova_int Nova_SnowflakeGen_method_next(Nova_SnowflakeGen* nova_self);
static Nova_SnowflakeParts* Nova_Snowflake_static_parse(nova_int id);
static nova_unit nova_test_next__monotonic_________ms_0(void);
static nova_unit nova_test_next_________ms__________ID_1(void);
static nova_unit nova_test_parse__round_trip_____________2(void);
static nova_unit nova_test_____________________machine_id_3(void);
static nova_unit nova_test__________clock_backwards_4(void);

static Nova_SnowflakeGen* Nova_SnowflakeGen_static_new(nova_int machine_id) {
    /* SRC: if machine_id < 0 || machine_id > 1023 { */
    nova_unit _nv_if_0;
    if (((machine_id < ((nova_int)0LL)) || (machine_id > ((nova_int)1023LL)))) {
        /* SRC: throw InvalidMachineId { value: machine_id } */
        Nova_SnowflakeError* _nv_tmp_1 = nova_make_SnowflakeError_InvalidMachineId(machine_id);
        Nova_Fail_fail(nova_int_to_str((nova_int)(_nv_tmp_1)));
        _nv_if_0 = NOVA_UNIT;
    }
    _nv_if_0;
    /* SRC: { */
    Nova_SnowflakeGen* _nv_tmp_2 = (Nova_SnowflakeGen*)nova_alloc(sizeof(Nova_SnowflakeGen));
    _nv_tmp_2->machine_id = machine_id;
    _nv_tmp_2->last_ms = ((nova_int)0LL);
    _nv_tmp_2->sequence = ((nova_int)0LL);
    return _nv_tmp_2;
}

static nova_int Nova_SnowflakeGen_method_next(Nova_SnowflakeGen* nova_self) {
    /* SRC: let now = Time.now_ms() as i64 */
    nova_int now = Nova_Time_now_ms();
    /* SRC: if now < @last_ms { */
    nova_unit _nv_if_3;
    if ((now < (nova_self->last_ms))) {
        /* SRC: throw ClockBackwards { now: now, last: @last_ms } */
        Nova_SnowflakeError* _nv_tmp_4 = nova_make_SnowflakeError_ClockBackwards(now, (nova_self->last_ms));
        Nova_Fail_fail(nova_int_to_str((nova_int)(_nv_tmp_4)));
        _nv_if_3 = NOVA_UNIT;
    }
    _nv_if_3;
    /* SRC: if now == @last_ms { */
    nova_unit _nv_if_5;
    if ((now == (nova_self->last_ms))) {
        /* SRC: @sequence = @sequence + 1 */
        (nova_self->sequence) = ((nova_self->sequence) + ((nova_int)1LL));
        nova_unit _nv_if_6;
        if (((nova_self->sequence) >= ((nova_int)4096LL))) {
            /* SRC: @last_ms = @last_ms + 1 */
            (nova_self->last_ms) = ((nova_self->last_ms) + ((nova_int)1LL));
            /* SRC: @sequence = 0 */
            (nova_self->sequence) = ((nova_int)0LL);
            _nv_if_6 = NOVA_UNIT;
        }
        _nv_if_5 = NOVA_UNIT; (void)(_nv_if_6);
    } else {
        /* SRC: @sequence = 0 */
        (nova_self->sequence) = ((nova_int)0LL);
        /* SRC: @last_ms = now */
        (nova_self->last_ms) = now;
        _nv_if_5 = NOVA_UNIT;
    }
    _nv_if_5;
    /* SRC: let ts_offset = @last_ms - TWITTER_EPOCH_MS */
    nova_int ts_offset = ((nova_self->last_ms) - TWITTER_EPOCH_MS);
    /* SRC: ts_offset << 22) | (@machine_id << 12) | @sequence */
    return (((ts_offset << ((nova_int)22LL)) | ((nova_self->machine_id) << ((nova_int)12LL))) | (nova_self->sequence));
}

static Nova_SnowflakeParts* Nova_Snowflake_static_parse(nova_int id) {
    /* SRC: let sequence = (id & 0xFFF) as int */
    nova_int sequence = (id & ((nova_int)4095LL));
    /* SRC: let machine_id = ((id >> 12) & 0x3FF) as int */
    nova_int machine_id = ((id >> ((nova_int)12LL)) & ((nova_int)1023LL));
    /* SRC: let ts_offset = id >> 22 */
    nova_int ts_offset = (id >> ((nova_int)22LL));
    /* SRC: let timestamp_ms = ts_offset + TWITTER_EPOCH_MS */
    nova_int timestamp_ms = (ts_offset + TWITTER_EPOCH_MS);
    /* SRC: { timestamp_ms, machine_id, sequence } */
    Nova_SnowflakeParts* _nv_tmp_7 = (Nova_SnowflakeParts*)nova_alloc(sizeof(Nova_SnowflakeParts));
    _nv_tmp_7->timestamp_ms = timestamp_ms;
    _nv_tmp_7->machine_id = machine_id;
    _nv_tmp_7->sequence = sequence;
    return _nv_tmp_7;
}

static nova_unit nova_test_next__monotonic_________ms_0(void) {
    /* SRC: let mut gen = SnowflakeGen.new(1) */
    Nova_SnowflakeGen* gen = Nova_SnowflakeGen_static_new(((nova_int)1LL));
    /* SRC: with Time = fixed_ms(1700000000000) { */
    NovaVtable_Time* _nv_tmp_8 = _nova_handler_Time;
    _nova_handler_Time = nova_fn_fixed_ms(((nova_int)1700000000000LL));
    NovaInterruptFrame _nv_tmp_9;
    nova_int _nv_tmp_10;
    nova_interrupt_push(&_nv_tmp_9);
    if (setjmp(_nv_tmp_9.jmp) == 0) {
        {
            /* SRC: let a = gen.next() */
            nova_int a = Nova_SnowflakeGen_method_next(gen);
            /* SRC: let b = gen.next() */
            nova_int b = Nova_SnowflakeGen_method_next(gen);
            /* SRC: let c = gen.next() */
            nova_int c = Nova_SnowflakeGen_method_next(gen);
            /* SRC: assert(a < b) */
            nova_assert((a < b), "a < b");
            (void)(nova_assert((b < c), "b < c"));
            _nv_tmp_10 = ((nova_int)0LL);
        }
    } else {
        _nv_tmp_10 = _nv_tmp_9.value;
    }
    _nova_handler_Time = _nv_tmp_8;
    nova_interrupt_pop();
    _nv_tmp_10;
    return NOVA_UNIT;
}

static nova_unit nova_test_next_________ms__________ID_1(void) {
    /* SRC: let mut gen = SnowflakeGen.new(5) */
    Nova_SnowflakeGen* gen = Nova_SnowflakeGen_static_new(((nova_int)5LL));
    /* SRC: let id1 = with Time = fixed_ms(1000) { gen.next() } */
    NovaVtable_Time* _nv_tmp_11 = _nova_handler_Time;
    _nova_handler_Time = nova_fn_fixed_ms(((nova_int)1000LL));
    NovaInterruptFrame _nv_tmp_12;
    nova_int _nv_tmp_13;
    nova_interrupt_push(&_nv_tmp_12);
    if (setjmp(_nv_tmp_12.jmp) == 0) {
        {
            _nv_tmp_13 = (nova_int)(Nova_SnowflakeGen_method_next(gen));
        }
    } else {
        _nv_tmp_13 = _nv_tmp_12.value;
    }
    _nova_handler_Time = _nv_tmp_11;
    nova_interrupt_pop();
    nova_int id1 = _nv_tmp_13;
    /* SRC: let id2 = with Time = fixed_ms(2000) { gen.next() } */
    NovaVtable_Time* _nv_tmp_14 = _nova_handler_Time;
    _nova_handler_Time = nova_fn_fixed_ms(((nova_int)2000LL));
    NovaInterruptFrame _nv_tmp_15;
    nova_int _nv_tmp_16;
    nova_interrupt_push(&_nv_tmp_15);
    if (setjmp(_nv_tmp_15.jmp) == 0) {
        {
            _nv_tmp_16 = (nova_int)(Nova_SnowflakeGen_method_next(gen));
        }
    } else {
        _nv_tmp_16 = _nv_tmp_15.value;
    }
    _nova_handler_Time = _nv_tmp_14;
    nova_interrupt_pop();
    nova_int id2 = _nv_tmp_16;
    /* SRC: assert(id1 < id2) */
    nova_assert((id1 < id2), "id1 < id2");
    return NOVA_UNIT;
}

static nova_unit nova_test_parse__round_trip_____________2(void) {
    /* SRC: let mut gen = SnowflakeGen.new(42) */
    Nova_SnowflakeGen* gen = Nova_SnowflakeGen_static_new(((nova_int)42LL));
    /* SRC: let id = with Time = fixed_ms(1700000000000) { gen.next() } */
    NovaVtable_Time* _nv_tmp_17 = _nova_handler_Time;
    _nova_handler_Time = nova_fn_fixed_ms(((nova_int)1700000000000LL));
    NovaInterruptFrame _nv_tmp_18;
    nova_int _nv_tmp_19;
    nova_interrupt_push(&_nv_tmp_18);
    if (setjmp(_nv_tmp_18.jmp) == 0) {
        {
            _nv_tmp_19 = (nova_int)(Nova_SnowflakeGen_method_next(gen));
        }
    } else {
        _nv_tmp_19 = _nv_tmp_18.value;
    }
    _nova_handler_Time = _nv_tmp_17;
    nova_interrupt_pop();
    nova_int id = _nv_tmp_19;
    /* SRC: let parts = Snowflake.parse(id) */
    Nova_SnowflakeParts* parts = Nova_Snowflake_static_parse(id);
    /* SRC: assert(parts.timestamp_ms == 1700000000000) */
    nova_assert(((parts->timestamp_ms) == ((nova_int)1700000000000LL)), "assert == 1700000000000");
    /* SRC: assert(parts.machine_id == 42) */
    nova_assert(((parts->machine_id) == ((nova_int)42LL)), "assert == 42");
    /* SRC: assert(parts.sequence == 0) */
    nova_assert(((parts->sequence) == ((nova_int)0LL)), "assert == 0");
    return NOVA_UNIT;
}

static nova_int nova_lambda_0_body(void* _env_ptr, nova_int e);
typedef struct { int _dummy; } nova_lambda_0_env;
static nova_int nova_lambda_0_body(void* _env_ptr, nova_int e) {
    nova_interrupt((nova_int)(nova_make_Option_Some(e)));
    return NOVA_UNIT;
}

static nova_unit nova_test_____________________machine_id_3(void) {
    /* SRC: let r = with Fail[SnowflakeError] = (e) => interrupt Some(e) { */
    nova_lambda_0_env* _nv_tmp_20 = (nova_lambda_0_env*)nova_alloc(sizeof(nova_lambda_0_env));
    NovaClos_ii* _nv_tmp_21 = (NovaClos_ii*)nova_alloc(sizeof(NovaClos_ii));
    _nv_tmp_21->fn = (nova_fn_ii)(nova_lambda_0_body);
    _nv_tmp_21->env = (void*)(_nv_tmp_20);
    NovaVtable_Fail* _nv_tmp_22 = _nova_handler_Fail;
    _nova_handler_Fail = (void*)(_nv_tmp_21);
    NovaFailFrame _nv_tmp_23;
    nova_fail_push(&_nv_tmp_23);
    NovaInterruptFrame _nv_tmp_24;
    nova_int _nv_tmp_25;
    nova_interrupt_push(&_nv_tmp_24);
    if (setjmp(_nv_tmp_23.jmp) == 0) {
        if (setjmp(_nv_tmp_24.jmp) == 0) {
            {
                /* SRC: let _ = SnowflakeGen.new(2000) */
                Nova_SnowflakeGen* _nv_tmp_26 = Nova_SnowflakeGen_static_new(((nova_int)2000LL));
                (void)(nova_make_Option_None());
                _nv_tmp_25 = ((nova_int)0LL);
            }
        } else {
            _nv_tmp_25 = _nv_tmp_24.value;
        }
    } else {
        _nv_tmp_25 = ((nova_int)0LL);
    }
    nova_fail_pop();
    _nova_handler_Fail = _nv_tmp_22;
    nova_interrupt_pop();
    nova_int r = _nv_tmp_25;
    /* SRC: assert(match r { */
    nova_int _nv_scr_27 = r;
    nova_bool _nv_match_28;
    int _nv_matched_29 = 0;
    if (!_nv_matched_29 && (((_nv_scr_27->tag == NOVA_TAG_Option_Some) && ((_nv_scr_27->payload.Some._0->tag == NOVA_TAG_SnowflakeError_InvalidMachineId))))) {
        _nv_match_28 = true;
        _nv_matched_29 = 1;
    }
    if (!_nv_matched_29 && (true)) {
        _nv_match_28 = false;
        _nv_matched_29 = 1;
    }
    nova_assert(_nv_match_28, "assert");
    return NOVA_UNIT;
}

static nova_int nova_lambda_1_body(void* _env_ptr, nova_int e);
typedef struct { int _dummy; } nova_lambda_1_env;
static nova_int nova_lambda_1_body(void* _env_ptr, nova_int e) {
    nova_interrupt((nova_int)(nova_make_Option_Some(e)));
    return NOVA_UNIT;
}

static nova_unit nova_test__________clock_backwards_4(void) {
    /* SRC: let mut gen = SnowflakeGen.new(0) */
    Nova_SnowflakeGen* gen = Nova_SnowflakeGen_static_new(((nova_int)0LL));
    /* SRC: let _ = with Time = fixed_ms(2000) { gen.next() } */
    NovaVtable_Time* _nv_tmp_31 = _nova_handler_Time;
    _nova_handler_Time = nova_fn_fixed_ms(((nova_int)2000LL));
    NovaInterruptFrame _nv_tmp_32;
    nova_int _nv_tmp_33;
    nova_interrupt_push(&_nv_tmp_32);
    if (setjmp(_nv_tmp_32.jmp) == 0) {
        {
            _nv_tmp_33 = (nova_int)(Nova_SnowflakeGen_method_next(gen));
        }
    } else {
        _nv_tmp_33 = _nv_tmp_32.value;
    }
    _nova_handler_Time = _nv_tmp_31;
    nova_interrupt_pop();
    nova_int _nv_tmp_30 = _nv_tmp_33;
    /* SRC: let r = with Time = fixed_ms(1000), Fail[SnowflakeError] = (e) => interrupt Some(e) { */
    NovaVtable_Time* _nv_tmp_34 = _nova_handler_Time;
    _nova_handler_Time = nova_fn_fixed_ms(((nova_int)1000LL));
    nova_lambda_1_env* _nv_tmp_35 = (nova_lambda_1_env*)nova_alloc(sizeof(nova_lambda_1_env));
    NovaClos_ii* _nv_tmp_36 = (NovaClos_ii*)nova_alloc(sizeof(NovaClos_ii));
    _nv_tmp_36->fn = (nova_fn_ii)(nova_lambda_1_body);
    _nv_tmp_36->env = (void*)(_nv_tmp_35);
    NovaVtable_Fail* _nv_tmp_37 = _nova_handler_Fail;
    _nova_handler_Fail = (void*)(_nv_tmp_36);
    NovaFailFrame _nv_tmp_38;
    nova_fail_push(&_nv_tmp_38);
    NovaInterruptFrame _nv_tmp_39;
    nova_int _nv_tmp_40;
    nova_interrupt_push(&_nv_tmp_39);
    if (setjmp(_nv_tmp_38.jmp) == 0) {
        if (setjmp(_nv_tmp_39.jmp) == 0) {
            {
                /* SRC: let _ = gen.next() */
                nova_int _nv_tmp_41 = Nova_SnowflakeGen_method_next(gen);
                (void)(nova_make_Option_None());
                _nv_tmp_40 = ((nova_int)0LL);
            }
        } else {
            _nv_tmp_40 = _nv_tmp_39.value;
        }
    } else {
        _nv_tmp_40 = ((nova_int)0LL);
    }
    nova_fail_pop();
    _nova_handler_Fail = _nv_tmp_37;
    _nova_handler_Time = _nv_tmp_34;
    nova_interrupt_pop();
    nova_int r = _nv_tmp_40;
    /* SRC: assert(match r { */
    nova_int _nv_scr_42 = r;
    nova_bool _nv_match_43;
    int _nv_matched_44 = 0;
    if (!_nv_matched_44 && (((_nv_scr_42->tag == NOVA_TAG_Option_Some) && ((_nv_scr_42->payload.Some._0->tag == NOVA_TAG_SnowflakeError_ClockBackwards))))) {
        _nv_match_43 = true;
        _nv_matched_44 = 1;
    }
    if (!_nv_matched_44 && (true)) {
        _nv_match_43 = false;
        _nv_matched_44 = 1;
    }
    nova_assert(_nv_match_43, "assert");
    return NOVA_UNIT;
}

static nova_unit nova_fn_main_impl(void) {
    int _nova_tests_total = 5;
    int _nova_tests_failed = 0;
    printf("Running %d tests...\n", _nova_tests_total);
    {
        NovaTestFrame _tf;
        _tf.fail_msg = NULL;
        _nova_test_frame = &_tf;
        NovaFailFrame _tf_fail;
        _tf_fail.error_msg = (nova_str){.ptr=NULL, .len=0};
        nova_fail_push(&_tf_fail);
        int _tf_jmp = setjmp(_tf.jmp);
        int _tf_fail_jmp = (_tf_jmp == 0) ? setjmp(_tf_fail.jmp) : 0;
        if (_tf_jmp == 0 && _tf_fail_jmp == 0) {
            nova_test_next__monotonic_________ms_0();
            printf("  PASS: next: monotonic в одной ms\n");
        } else {
            const char* _tf_msg = _tf.fail_msg ? _tf.fail_msg : (_tf_fail.error_msg.ptr ? _tf_fail.error_msg.ptr : "assertion failed");
            printf("  FAIL: next: monotonic в одной ms — %s\n", _tf_msg);
            _nova_tests_failed++;
        }
        nova_fail_pop();
        _nova_test_frame = NULL;
    }
    {
        NovaTestFrame _tf;
        _tf.fail_msg = NULL;
        _nova_test_frame = &_tf;
        NovaFailFrame _tf_fail;
        _tf_fail.error_msg = (nova_str){.ptr=NULL, .len=0};
        nova_fail_push(&_tf_fail);
        int _tf_jmp = setjmp(_tf.jmp);
        int _tf_fail_jmp = (_tf_jmp == 0) ? setjmp(_tf_fail.jmp) : 0;
        if (_tf_jmp == 0 && _tf_fail_jmp == 0) {
            nova_test_next_________ms__________ID_1();
            printf("  PASS: next: разные ms → разные ID\n");
        } else {
            const char* _tf_msg = _tf.fail_msg ? _tf.fail_msg : (_tf_fail.error_msg.ptr ? _tf_fail.error_msg.ptr : "assertion failed");
            printf("  FAIL: next: разные ms → разные ID — %s\n", _tf_msg);
            _nova_tests_failed++;
        }
        nova_fail_pop();
        _nova_test_frame = NULL;
    }
    {
        NovaTestFrame _tf;
        _tf.fail_msg = NULL;
        _nova_test_frame = &_tf;
        NovaFailFrame _tf_fail;
        _tf_fail.error_msg = (nova_str){.ptr=NULL, .len=0};
        nova_fail_push(&_tf_fail);
        int _tf_jmp = setjmp(_tf.jmp);
        int _tf_fail_jmp = (_tf_jmp == 0) ? setjmp(_tf_fail.jmp) : 0;
        if (_tf_jmp == 0 && _tf_fail_jmp == 0) {
            nova_test_parse__round_trip_____________2();
            printf("  PASS: parse: round-trip компонентов\n");
        } else {
            const char* _tf_msg = _tf.fail_msg ? _tf.fail_msg : (_tf_fail.error_msg.ptr ? _tf_fail.error_msg.ptr : "assertion failed");
            printf("  FAIL: parse: round-trip компонентов — %s\n", _tf_msg);
            _nova_tests_failed++;
        }
        nova_fail_pop();
        _nova_test_frame = NULL;
    }
    {
        NovaTestFrame _tf;
        _tf.fail_msg = NULL;
        _nova_test_frame = &_tf;
        NovaFailFrame _tf_fail;
        _tf_fail.error_msg = (nova_str){.ptr=NULL, .len=0};
        nova_fail_push(&_tf_fail);
        int _tf_jmp = setjmp(_tf.jmp);
        int _tf_fail_jmp = (_tf_jmp == 0) ? setjmp(_tf_fail.jmp) : 0;
        if (_tf_jmp == 0 && _tf_fail_jmp == 0) {
            nova_test_____________________machine_id_3();
            printf("  PASS: ошибка — невалидный machine_id\n");
        } else {
            const char* _tf_msg = _tf.fail_msg ? _tf.fail_msg : (_tf_fail.error_msg.ptr ? _tf_fail.error_msg.ptr : "assertion failed");
            printf("  FAIL: ошибка — невалидный machine_id — %s\n", _tf_msg);
            _nova_tests_failed++;
        }
        nova_fail_pop();
        _nova_test_frame = NULL;
    }
    {
        NovaTestFrame _tf;
        _tf.fail_msg = NULL;
        _nova_test_frame = &_tf;
        NovaFailFrame _tf_fail;
        _tf_fail.error_msg = (nova_str){.ptr=NULL, .len=0};
        nova_fail_push(&_tf_fail);
        int _tf_jmp = setjmp(_tf.jmp);
        int _tf_fail_jmp = (_tf_jmp == 0) ? setjmp(_tf_fail.jmp) : 0;
        if (_tf_jmp == 0 && _tf_fail_jmp == 0) {
            nova_test__________clock_backwards_4();
            printf("  PASS: ошибка — clock backwards\n");
        } else {
            const char* _tf_msg = _tf.fail_msg ? _tf.fail_msg : (_tf_fail.error_msg.ptr ? _tf_fail.error_msg.ptr : "assertion failed");
            printf("  FAIL: ошибка — clock backwards — %s\n", _tf_msg);
            _nova_tests_failed++;
        }
        nova_fail_pop();
        _nova_test_frame = NULL;
    }
    printf("%d/%d passed\n", _nova_tests_total - _nova_tests_failed, _nova_tests_total);
    if (_nova_tests_failed > 0) { exit(1); }
    return NOVA_UNIT;
}

int main(void) {
    nova_gc_init();
    nova_register_effect_storage((void**)&_nova_handler_Fail);
    nova_register_effect_storage((void**)&_nova_handler_Time);
    nova_fn_main_impl();
    nova_gc_shutdown();
    return 0;
}
