/* Generated by nova-codegen. Do not edit. */
#include "nova_rt/nova_rt.h"

typedef struct { nova_int f0; } _NovaTuple1;
typedef struct { nova_int f0; nova_int f1; } _NovaTuple2;
typedef struct { nova_int f0; nova_int f1; nova_int f2; } _NovaTuple3;
typedef struct { nova_int f0; nova_int f1; nova_int f2; nova_int f3; } _NovaTuple4;
typedef struct { nova_int f0; nova_int f1; nova_int f2; nova_int f3; nova_int f4; } _NovaTuple5;
typedef struct { nova_int f0; nova_int f1; nova_int f2; nova_int f3; nova_int f4; nova_int f5; } _NovaTuple6;
typedef struct { nova_int f0; nova_int f1; nova_int f2; nova_int f3; nova_int f4; nova_int f5; nova_int f6; } _NovaTuple7;
typedef struct { nova_int f0; nova_int f1; nova_int f2; nova_int f3; nova_int f4; nova_int f5; nova_int f6; nova_int f7; } _NovaTuple8;

typedef enum {
    NOVA_TAG_Comparator_Eq,
    NOVA_TAG_Comparator_Gt,
    NOVA_TAG_Comparator_Ge,
    NOVA_TAG_Comparator_Lt,
    NOVA_TAG_Comparator_Le,
} Nova_Comparator_Tag;
typedef struct Nova_Comparator Nova_Comparator;
struct Nova_Comparator {
    Nova_Comparator_Tag tag;
    union {
        struct {
            Nova_Version* _0;
        } Eq;
        struct {
            Nova_Version* _0;
        } Gt;
        struct {
            Nova_Version* _0;
        } Ge;
        struct {
            Nova_Version* _0;
        } Lt;
        struct {
            Nova_Version* _0;
        } Le;
    } payload;
};

static Nova_Comparator* nova_make_Comparator_Eq(Nova_Version* _0) {
    Nova_Comparator* _r = (Nova_Comparator*)nova_alloc(sizeof(Nova_Comparator));
    _r->tag = NOVA_TAG_Comparator_Eq;
    _r->payload.Eq._0 = _0;
    return _r;
}

static Nova_Comparator* nova_make_Comparator_Gt(Nova_Version* _0) {
    Nova_Comparator* _r = (Nova_Comparator*)nova_alloc(sizeof(Nova_Comparator));
    _r->tag = NOVA_TAG_Comparator_Gt;
    _r->payload.Gt._0 = _0;
    return _r;
}

static Nova_Comparator* nova_make_Comparator_Ge(Nova_Version* _0) {
    Nova_Comparator* _r = (Nova_Comparator*)nova_alloc(sizeof(Nova_Comparator));
    _r->tag = NOVA_TAG_Comparator_Ge;
    _r->payload.Ge._0 = _0;
    return _r;
}

static Nova_Comparator* nova_make_Comparator_Lt(Nova_Version* _0) {
    Nova_Comparator* _r = (Nova_Comparator*)nova_alloc(sizeof(Nova_Comparator));
    _r->tag = NOVA_TAG_Comparator_Lt;
    _r->payload.Lt._0 = _0;
    return _r;
}

static Nova_Comparator* nova_make_Comparator_Le(Nova_Version* _0) {
    Nova_Comparator* _r = (Nova_Comparator*)nova_alloc(sizeof(Nova_Comparator));
    _r->tag = NOVA_TAG_Comparator_Le;
    _r->payload.Le._0 = _0;
    return _r;
}

typedef struct Nova_ComparatorSet Nova_ComparatorSet;
struct Nova_ComparatorSet {
    NovaArray_nova_int* comparators;
};

typedef struct Nova_VersionReq Nova_VersionReq;
struct Nova_VersionReq {
    NovaArray_nova_int* sets;
    nova_bool any_match;
};

typedef enum {
    NOVA_TAG_ParseRangeError_EmptyInput,
    NOVA_TAG_ParseRangeError_InvalidComparator,
    NOVA_TAG_ParseRangeError_InvalidVersion,
} Nova_ParseRangeError_Tag;
typedef struct Nova_ParseRangeError Nova_ParseRangeError;
struct Nova_ParseRangeError {
    Nova_ParseRangeError_Tag tag;
    union {
        struct {
            nova_str value;
        } InvalidComparator;
        struct {
            nova_str value;
        } InvalidVersion;
    } payload;
};

static Nova_ParseRangeError* nova_make_ParseRangeError_EmptyInput(void) {
    Nova_ParseRangeError* _r = (Nova_ParseRangeError*)nova_alloc(sizeof(Nova_ParseRangeError));
    _r->tag = NOVA_TAG_ParseRangeError_EmptyInput;
    return _r;
}

static Nova_ParseRangeError* nova_make_ParseRangeError_InvalidComparator(nova_str _0) {
    Nova_ParseRangeError* _r = (Nova_ParseRangeError*)nova_alloc(sizeof(Nova_ParseRangeError));
    _r->tag = NOVA_TAG_ParseRangeError_InvalidComparator;
    _r->payload.InvalidComparator.value = _0;
    return _r;
}

static Nova_ParseRangeError* nova_make_ParseRangeError_InvalidVersion(nova_str _0) {
    Nova_ParseRangeError* _r = (Nova_ParseRangeError*)nova_alloc(sizeof(Nova_ParseRangeError));
    _r->tag = NOVA_TAG_ParseRangeError_InvalidVersion;
    _r->payload.InvalidVersion.value = _0;
    return _r;
}

static Nova_VersionReq* Nova_VersionReq_static_parse(nova_str s);
static NovaArray_nova_int* nova_fn_parse_comparator_set(nova_str s);
static NovaArray_nova_int* nova_fn_parse_one_comparator(nova_str s);
static Nova_Version* nova_fn_parse_version(nova_str s);
static nova_bool Nova_VersionReq_method_matches(Nova_VersionReq* nova_self, Nova_Version* v);
static nova_bool nova_fn_set_matches(Nova_ComparatorSet* set, Nova_Version* v);
static nova_bool nova_fn_comparator_matches(Nova_Comparator* c, Nova_Version* v);
static nova_unit nova_test_exact__1_2_3_matches________1_2_3_0(void);
static nova_unit nova_test_caret__1_2_3_____1_2_3__2_0_0_1(void);
static nova_unit nova_test_tilde__1_2_3_____1_2_3__1_3_0_2(void);
static nova_unit nova_test___1_0_0__________________3(void);
static nova_unit nova_test_AND___1_0_0__2_0_0_4(void);
static nova_unit nova_test_OR__1_0_0____2_0_0_5(void);
static nova_unit nova_test_wildcard____matches_anything_6(void);

static Nova_VersionReq* Nova_VersionReq_static_parse(nova_str s) {
    /* SRC: let trimmed = s.trim() */
    nova_str trimmed = nova_str_trim(s);
    /* SRC: if trimmed.len == 0 { throw EmptyInput } */
    nova_unit _nv_if_0;
    if ((nova_str_char_len(trimmed) == ((nova_int)0LL))) {
        /* SRC: throw EmptyInput */
        Nova_Fail_fail(nova_int_to_str((nova_int)(nova_make_ParseRangeError_EmptyInput())));
        _nv_if_0 = NOVA_UNIT;
    }
    _nv_if_0;
    /* SRC: if trimmed == "*" { */
    nova_unit _nv_if_1;
    if ((nova_str_eq(trimmed, (nova_str){.ptr="*", .len=1}))) {
        /* SRC: return { sets: [], any_match: true } */
        Nova_VersionReq* _nv_tmp_2 = (Nova_VersionReq*)nova_alloc(sizeof(Nova_VersionReq));
        NovaArray_nova_int* _nv_tmp_3 = nova_array_new_nova_int(8);
        _nv_tmp_2->sets = _nv_tmp_3;
        _nv_tmp_2->any_match = true;
        return _nv_tmp_2;
        _nv_if_1 = NOVA_UNIT;
    }
    _nv_if_1;
    /* SRC: let mut sets []ComparatorSet = [] */
    NovaArray_nova_int* _nv_tmp_4 = nova_array_new_nova_int(8);
    NovaArray_nova_int* sets = _nv_tmp_4;
    /* SRC: let or_groups = trimmed.split("||") */
    NovaArray_nova_str* or_groups = nova_str_split(trimmed, (nova_str){.ptr="||", .len=2});
    /* SRC: for group in or_groups { */
    NovaArray_nova_str* _nv_tmp_5 = or_groups;
    nova_unit _nv_tmp_7;
    for (nova_int _nv_tmp_6 = 0; _nv_tmp_6 < _nv_tmp_5->len; _nv_tmp_6++) {
        nova_str group = _nv_tmp_5->data[_nv_tmp_6];
        /* SRC: let comps = parse_comparator_set(group.trim()) */
        NovaArray_nova_int* comps = nova_fn_parse_comparator_set(nova_str_trim(group));
        Nova_VersionReq* _nv_tmp_8 = (Nova_VersionReq*)nova_alloc(sizeof(Nova_VersionReq));
        _nv_tmp_8->comparators = comps;
        nova_array_push_nova_int(sets, _nv_tmp_8);
        (void)(NOVA_UNIT);
    }
    _nv_tmp_7 = NOVA_UNIT;
    _nv_tmp_7;
    /* SRC: { sets, any_match: false } */
    Nova_VersionReq* _nv_tmp_9 = (Nova_VersionReq*)nova_alloc(sizeof(Nova_VersionReq));
    _nv_tmp_9->sets = sets;
    _nv_tmp_9->any_match = false;
    return _nv_tmp_9;
}

static NovaArray_nova_int* nova_fn_parse_comparator_set(nova_str s) {
    /* SRC: let mut out []Comparator = [] */
    NovaArray_nova_int* _nv_tmp_10 = nova_array_new_nova_int(8);
    NovaArray_nova_int* out = _nv_tmp_10;
    /* SRC: let tokens = s.split(" ") */
    NovaArray_nova_str* tokens = nova_str_split(s, (nova_str){.ptr=" ", .len=1});
    /* SRC: for tok in tokens { */
    NovaArray_nova_str* _nv_tmp_11 = tokens;
    nova_unit _nv_tmp_13;
    for (nova_int _nv_tmp_12 = 0; _nv_tmp_12 < _nv_tmp_11->len; _nv_tmp_12++) {
        nova_str tok = _nv_tmp_11->data[_nv_tmp_12];
        /* SRC: let t = tok.trim() */
        nova_str t = nova_str_trim(tok);
        /* SRC: if t.len == 0 { continue } */
        nova_unit _nv_if_14;
        if ((nova_str_char_len(t) == ((nova_int)0LL))) {
            /* SRC: continue */
            continue;
            _nv_if_14 = NOVA_UNIT;
        }
        _nv_if_14;
        /* SRC: let comps = parse_one_comparator(t) */
        NovaArray_nova_int* comps = nova_fn_parse_one_comparator(t);
        NovaArray_nova_int* _nv_tmp_15 = comps;
        nova_unit _nv_tmp_17;
        for (nova_int _nv_tmp_16 = 0; _nv_tmp_16 < _nv_tmp_15->len; _nv_tmp_16++) {
            nova_int c = _nv_tmp_15->data[_nv_tmp_16];
            nova_array_push_nova_int(out, c);
            (void)(NOVA_UNIT);
        }
        _nv_tmp_17 = NOVA_UNIT;
        (void)(_nv_tmp_17);
    }
    _nv_tmp_13 = NOVA_UNIT;
    _nv_tmp_13;
    /* SRC: out */
    return out;
}

static NovaArray_nova_int* nova_fn_parse_one_comparator(nova_str s) {
    /* SRC: if s.starts_with("^") { */
    nova_unit _nv_if_18;
    if (nova_str_starts_with(s, (nova_str){.ptr="^", .len=1})) {
        /* SRC: let v = parse_version(s.slice(1, s.len)) */
        Nova_Version* v = nova_fn_parse_version(nova_str_slice(s, ((nova_int)1LL), nova_str_char_len(s)));
        /* SRC: let upper = Version.new(v.major + 1, 0, 0) */
        nova_int upper = nova_fn_Version_new(((v->major) + ((nova_int)1LL)), ((nova_int)0LL), ((nova_int)0LL));
        /* SRC: return [Ge(v), Lt(upper)] */
        NovaArray_nova_int* _nv_tmp_19 = nova_array_new_nova_int(2);
        nova_array_push_nova_int(_nv_tmp_19, (nova_int)(nova_make_Comparator_Ge(v)));
        nova_array_push_nova_int(_nv_tmp_19, (nova_int)(nova_make_Comparator_Lt(upper)));
        return _nv_tmp_19;
        _nv_if_18 = NOVA_UNIT;
    }
    _nv_if_18;
    /* SRC: if s.starts_with("~") { */
    nova_unit _nv_if_20;
    if (nova_str_starts_with(s, (nova_str){.ptr="~", .len=1})) {
        /* SRC: let v = parse_version(s.slice(1, s.len)) */
        Nova_Version* v = nova_fn_parse_version(nova_str_slice(s, ((nova_int)1LL), nova_str_char_len(s)));
        /* SRC: let upper = Version.new(v.major, v.minor + 1, 0) */
        nova_int upper = nova_fn_Version_new((v->major), ((v->minor) + ((nova_int)1LL)), ((nova_int)0LL));
        /* SRC: return [Ge(v), Lt(upper)] */
        NovaArray_nova_int* _nv_tmp_21 = nova_array_new_nova_int(2);
        nova_array_push_nova_int(_nv_tmp_21, (nova_int)(nova_make_Comparator_Ge(v)));
        nova_array_push_nova_int(_nv_tmp_21, (nova_int)(nova_make_Comparator_Lt(upper)));
        return _nv_tmp_21;
        _nv_if_20 = NOVA_UNIT;
    }
    _nv_if_20;
    /* SRC: if s.starts_with(">=") { */
    nova_unit _nv_if_22;
    if (nova_str_starts_with(s, (nova_str){.ptr=">=", .len=2})) {
        /* SRC: return [Ge(parse_version(s.slice(2, s.len)))] */
        NovaArray_nova_int* _nv_tmp_23 = nova_array_new_nova_int(1);
        nova_array_push_nova_int(_nv_tmp_23, (nova_int)(nova_make_Comparator_Ge(nova_fn_parse_version(nova_str_slice(s, ((nova_int)2LL), nova_str_char_len(s))))));
        return _nv_tmp_23;
        _nv_if_22 = NOVA_UNIT;
    }
    _nv_if_22;
    /* SRC: if s.starts_with("<=") { */
    nova_unit _nv_if_24;
    if (nova_str_starts_with(s, (nova_str){.ptr="<=", .len=2})) {
        /* SRC: return [Le(parse_version(s.slice(2, s.len)))] */
        NovaArray_nova_int* _nv_tmp_25 = nova_array_new_nova_int(1);
        nova_array_push_nova_int(_nv_tmp_25, (nova_int)(nova_make_Comparator_Le(nova_fn_parse_version(nova_str_slice(s, ((nova_int)2LL), nova_str_char_len(s))))));
        return _nv_tmp_25;
        _nv_if_24 = NOVA_UNIT;
    }
    _nv_if_24;
    /* SRC: if s.starts_with(">") { */
    nova_unit _nv_if_26;
    if (nova_str_starts_with(s, (nova_str){.ptr=">", .len=1})) {
        /* SRC: return [Gt(parse_version(s.slice(1, s.len)))] */
        NovaArray_nova_int* _nv_tmp_27 = nova_array_new_nova_int(1);
        nova_array_push_nova_int(_nv_tmp_27, (nova_int)(nova_make_Comparator_Gt(nova_fn_parse_version(nova_str_slice(s, ((nova_int)1LL), nova_str_char_len(s))))));
        return _nv_tmp_27;
        _nv_if_26 = NOVA_UNIT;
    }
    _nv_if_26;
    /* SRC: if s.starts_with("<") { */
    nova_unit _nv_if_28;
    if (nova_str_starts_with(s, (nova_str){.ptr="<", .len=1})) {
        /* SRC: return [Lt(parse_version(s.slice(1, s.len)))] */
        NovaArray_nova_int* _nv_tmp_29 = nova_array_new_nova_int(1);
        nova_array_push_nova_int(_nv_tmp_29, (nova_int)(nova_make_Comparator_Lt(nova_fn_parse_version(nova_str_slice(s, ((nova_int)1LL), nova_str_char_len(s))))));
        return _nv_tmp_29;
        _nv_if_28 = NOVA_UNIT;
    }
    _nv_if_28;
    /* SRC: if s.starts_with("=") { */
    nova_unit _nv_if_30;
    if (nova_str_starts_with(s, (nova_str){.ptr="=", .len=1})) {
        /* SRC: return [Eq(parse_version(s.slice(1, s.len)))] */
        NovaArray_nova_int* _nv_tmp_31 = nova_array_new_nova_int(1);
        nova_array_push_nova_int(_nv_tmp_31, (nova_int)(nova_make_Comparator_Eq(nova_fn_parse_version(nova_str_slice(s, ((nova_int)1LL), nova_str_char_len(s))))));
        return _nv_tmp_31;
        _nv_if_30 = NOVA_UNIT;
    }
    _nv_if_30;
    /* SRC: [Eq(parse_version(s))] */
    NovaArray_nova_int* _nv_tmp_32 = nova_array_new_nova_int(1);
    nova_array_push_nova_int(_nv_tmp_32, (nova_int)(nova_make_Comparator_Eq(nova_fn_parse_version(s))));
    return _nv_tmp_32;
}

static nova_int nova_lambda_0_body(void* _env_ptr, nova_int e);
typedef struct { int _dummy; } nova_lambda_0_env;
static nova_int nova_lambda_0_body(void* _env_ptr, nova_int e) {
    nova_interrupt((nova_int)(nova_make_Result_Err(e)));
    return NOVA_UNIT;
}

static Nova_Version* nova_fn_parse_version(nova_str s) {
    /* SRC: let r = with Fail[ParseVersionError] = (e) => interrupt Err(e) { */
    nova_lambda_0_env* _nv_tmp_33 = (nova_lambda_0_env*)nova_alloc(sizeof(nova_lambda_0_env));
    NovaClos_ii* _nv_tmp_34 = (NovaClos_ii*)nova_alloc(sizeof(NovaClos_ii));
    _nv_tmp_34->fn = (nova_fn_ii)(nova_lambda_0_body);
    _nv_tmp_34->env = (void*)(_nv_tmp_33);
    NovaVtable_Fail* _nv_tmp_35 = _nova_handler_Fail;
    _nova_handler_Fail = (void*)(_nv_tmp_34);
    NovaFailFrame _nv_tmp_36;
    nova_fail_push(&_nv_tmp_36);
    NovaInterruptFrame _nv_tmp_37;
    nova_int _nv_tmp_38;
    nova_interrupt_push(&_nv_tmp_37);
    if (setjmp(_nv_tmp_36.jmp) == 0) {
        if (setjmp(_nv_tmp_37.jmp) == 0) {
            {
                (void)(nova_make_Result_Ok(nova_fn_Version_from(s)));
                _nv_tmp_38 = ((nova_int)0LL);
            }
        } else {
            _nv_tmp_38 = _nv_tmp_37.value;
        }
    } else {
        _nv_tmp_38 = ((nova_int)0LL);
    }
    nova_fail_pop();
    _nova_handler_Fail = _nv_tmp_35;
    nova_interrupt_pop();
    nova_int r = _nv_tmp_38;
    /* SRC: match r { */
    nova_int _nv_scr_39 = r;
    Nova_Version* _nv_match_40;
    int _nv_matched_41 = 0;
    if (!_nv_matched_41 && ((_nv_scr_39->tag == NOVA_TAG_Result_Ok))) {
        nova_int v = _nv_scr_39->payload.Ok._0;
        _nv_match_40 = v;
        _nv_matched_41 = 1;
    }
    if (!_nv_matched_41 && ((_nv_scr_39->tag == NOVA_TAG_Result_Err))) {
        Nova_ParseRangeError* _nv_tmp_42 = nova_make_ParseRangeError_InvalidVersion(s);
        Nova_Fail_fail(_nv_tmp_42);
        _nv_match_40 = ((nova_int)0LL);
        _nv_matched_41 = 1;
    }
    return _nv_match_40;
}

static nova_bool Nova_VersionReq_method_matches(Nova_VersionReq* nova_self, Nova_Version* v) {
    /* SRC: if @any_match { return true } */
    nova_unit _nv_if_43;
    if ((nova_self->any_match)) {
        /* SRC: return true */
        return true;
        _nv_if_43 = NOVA_UNIT;
    }
    _nv_if_43;
    /* SRC: for set in @sets { */
    NovaArray_nova_int* _nv_tmp_44 = (nova_self->sets);
    nova_unit _nv_tmp_46;
    for (nova_int _nv_tmp_45 = 0; _nv_tmp_45 < _nv_tmp_44->len; _nv_tmp_45++) {
        nova_int set = _nv_tmp_44->data[_nv_tmp_45];
        nova_unit _nv_if_47;
        if (nova_fn_set_matches(set, v)) {
            /* SRC: return true */
            return true;
            _nv_if_47 = NOVA_UNIT;
        }
        (void)(_nv_if_47);
    }
    _nv_tmp_46 = NOVA_UNIT;
    _nv_tmp_46;
    /* SRC: false */
    return false;
}

static nova_bool nova_fn_set_matches(Nova_ComparatorSet* set, Nova_Version* v) {
    /* SRC: for c in set.comparators { */
    NovaArray_nova_int* _nv_tmp_48 = (set->comparators);
    nova_unit _nv_tmp_50;
    for (nova_int _nv_tmp_49 = 0; _nv_tmp_49 < _nv_tmp_48->len; _nv_tmp_49++) {
        nova_int c = _nv_tmp_48->data[_nv_tmp_49];
        nova_unit _nv_if_51;
        if ((!nova_fn_comparator_matches(c, v))) {
            /* SRC: return false */
            return false;
            _nv_if_51 = NOVA_UNIT;
        }
        (void)(_nv_if_51);
    }
    _nv_tmp_50 = NOVA_UNIT;
    _nv_tmp_50;
    /* SRC: true */
    return true;
}

static nova_bool nova_fn_comparator_matches(Nova_Comparator* c, Nova_Version* v) {
    /* SRC: match c { */
    Nova_Comparator* _nv_scr_52 = c;
    nova_int _nv_match_53;
    int _nv_matched_54 = 0;
    if (!_nv_matched_54 && ((_nv_scr_52->tag == NOVA_TAG_Comparator_Eq))) {
        Nova_Version* req = _nv_scr_52->payload.Eq._0;
        _nv_match_53 = v->eq(req);
        _nv_matched_54 = 1;
    }
    if (!_nv_matched_54 && ((_nv_scr_52->tag == NOVA_TAG_Comparator_Gt))) {
        Nova_Version* req = _nv_scr_52->payload.Gt._0;
        _nv_match_53 = v->gt(req);
        _nv_matched_54 = 1;
    }
    if (!_nv_matched_54 && ((_nv_scr_52->tag == NOVA_TAG_Comparator_Ge))) {
        Nova_Version* req = _nv_scr_52->payload.Ge._0;
        _nv_match_53 = v->ge(req);
        _nv_matched_54 = 1;
    }
    if (!_nv_matched_54 && ((_nv_scr_52->tag == NOVA_TAG_Comparator_Lt))) {
        Nova_Version* req = _nv_scr_52->payload.Lt._0;
        _nv_match_53 = v->lt(req);
        _nv_matched_54 = 1;
    }
    if (!_nv_matched_54 && ((_nv_scr_52->tag == NOVA_TAG_Comparator_Le))) {
        Nova_Version* req = _nv_scr_52->payload.Le._0;
        _nv_match_53 = v->le(req);
        _nv_matched_54 = 1;
    }
    return _nv_match_53;
}

static nova_unit nova_test_exact__1_2_3_matches________1_2_3_0(void) {
    /* SRC: let req = VersionReq.parse("1.2.3") */
    Nova_VersionReq* req = Nova_VersionReq_static_parse((nova_str){.ptr="1.2.3", .len=5});
    /* SRC: assert(req.matches(Version.from("1.2.3"))) */
    nova_assert(Nova_VersionReq_method_matches(req, nova_fn_Version_from((nova_str){.ptr="1.2.3", .len=5})), "assert(assert(\"1.2.3\"))");
    /* SRC: assert(!req.matches(Version.from("1.2.4"))) */
    nova_assert((!Nova_VersionReq_method_matches(req, nova_fn_Version_from((nova_str){.ptr="1.2.4", .len=5}))), "!assert(assert(\"1.2.4\"))");
    /* SRC: assert(!req.matches(Version.from("1.2.2"))) */
    nova_assert((!Nova_VersionReq_method_matches(req, nova_fn_Version_from((nova_str){.ptr="1.2.2", .len=5}))), "!assert(assert(\"1.2.2\"))");
    return NOVA_UNIT;
}

static nova_unit nova_test_caret__1_2_3_____1_2_3__2_0_0_1(void) {
    /* SRC: let req = VersionReq.parse("^1.2.3") */
    Nova_VersionReq* req = Nova_VersionReq_static_parse((nova_str){.ptr="^1.2.3", .len=6});
    /* SRC: assert(req.matches(Version.from("1.2.3"))) */
    nova_assert(Nova_VersionReq_method_matches(req, nova_fn_Version_from((nova_str){.ptr="1.2.3", .len=5})), "assert(assert(\"1.2.3\"))");
    /* SRC: assert(req.matches(Version.from("1.2.4"))) */
    nova_assert(Nova_VersionReq_method_matches(req, nova_fn_Version_from((nova_str){.ptr="1.2.4", .len=5})), "assert(assert(\"1.2.4\"))");
    /* SRC: assert(req.matches(Version.from("1.5.0"))) */
    nova_assert(Nova_VersionReq_method_matches(req, nova_fn_Version_from((nova_str){.ptr="1.5.0", .len=5})), "assert(assert(\"1.5.0\"))");
    /* SRC: assert(req.matches(Version.from("1.99.99"))) */
    nova_assert(Nova_VersionReq_method_matches(req, nova_fn_Version_from((nova_str){.ptr="1.99.99", .len=7})), "assert(assert(\"1.99.99\"))");
    /* SRC: assert(!req.matches(Version.from("2.0.0"))) */
    nova_assert((!Nova_VersionReq_method_matches(req, nova_fn_Version_from((nova_str){.ptr="2.0.0", .len=5}))), "!assert(assert(\"2.0.0\"))");
    /* SRC: assert(!req.matches(Version.from("1.2.2"))) */
    nova_assert((!Nova_VersionReq_method_matches(req, nova_fn_Version_from((nova_str){.ptr="1.2.2", .len=5}))), "!assert(assert(\"1.2.2\"))");
    return NOVA_UNIT;
}

static nova_unit nova_test_tilde__1_2_3_____1_2_3__1_3_0_2(void) {
    /* SRC: let req = VersionReq.parse("~1.2.3") */
    Nova_VersionReq* req = Nova_VersionReq_static_parse((nova_str){.ptr="~1.2.3", .len=6});
    /* SRC: assert(req.matches(Version.from("1.2.3"))) */
    nova_assert(Nova_VersionReq_method_matches(req, nova_fn_Version_from((nova_str){.ptr="1.2.3", .len=5})), "assert(assert(\"1.2.3\"))");
    /* SRC: assert(req.matches(Version.from("1.2.99"))) */
    nova_assert(Nova_VersionReq_method_matches(req, nova_fn_Version_from((nova_str){.ptr="1.2.99", .len=6})), "assert(assert(\"1.2.99\"))");
    /* SRC: assert(!req.matches(Version.from("1.3.0"))) */
    nova_assert((!Nova_VersionReq_method_matches(req, nova_fn_Version_from((nova_str){.ptr="1.3.0", .len=5}))), "!assert(assert(\"1.3.0\"))");
    /* SRC: assert(!req.matches(Version.from("1.2.2"))) */
    nova_assert((!Nova_VersionReq_method_matches(req, nova_fn_Version_from((nova_str){.ptr="1.2.2", .len=5}))), "!assert(assert(\"1.2.2\"))");
    return NOVA_UNIT;
}

static nova_unit nova_test___1_0_0__________________3(void) {
    /* SRC: let req = VersionReq.parse(">=1.0.0") */
    Nova_VersionReq* req = Nova_VersionReq_static_parse((nova_str){.ptr=">=1.0.0", .len=7});
    /* SRC: assert(req.matches(Version.from("1.0.0"))) */
    nova_assert(Nova_VersionReq_method_matches(req, nova_fn_Version_from((nova_str){.ptr="1.0.0", .len=5})), "assert(assert(\"1.0.0\"))");
    /* SRC: assert(req.matches(Version.from("99.0.0"))) */
    nova_assert(Nova_VersionReq_method_matches(req, nova_fn_Version_from((nova_str){.ptr="99.0.0", .len=6})), "assert(assert(\"99.0.0\"))");
    /* SRC: assert(!req.matches(Version.from("0.9.9"))) */
    nova_assert((!Nova_VersionReq_method_matches(req, nova_fn_Version_from((nova_str){.ptr="0.9.9", .len=5}))), "!assert(assert(\"0.9.9\"))");
    return NOVA_UNIT;
}

static nova_unit nova_test_AND___1_0_0__2_0_0_4(void) {
    /* SRC: let req = VersionReq.parse(">1.0.0 <2.0.0") */
    Nova_VersionReq* req = Nova_VersionReq_static_parse((nova_str){.ptr=">1.0.0 <2.0.0", .len=13});
    /* SRC: assert(req.matches(Version.from("1.5.0"))) */
    nova_assert(Nova_VersionReq_method_matches(req, nova_fn_Version_from((nova_str){.ptr="1.5.0", .len=5})), "assert(assert(\"1.5.0\"))");
    /* SRC: assert(!req.matches(Version.from("1.0.0"))) */
    nova_assert((!Nova_VersionReq_method_matches(req, nova_fn_Version_from((nova_str){.ptr="1.0.0", .len=5}))), "!assert(assert(\"1.0.0\"))");
    /* SRC: assert(!req.matches(Version.from("2.0.0"))) */
    nova_assert((!Nova_VersionReq_method_matches(req, nova_fn_Version_from((nova_str){.ptr="2.0.0", .len=5}))), "!assert(assert(\"2.0.0\"))");
    return NOVA_UNIT;
}

static nova_unit nova_test_OR__1_0_0____2_0_0_5(void) {
    /* SRC: let req = VersionReq.parse("1.0.0 || 2.0.0") */
    Nova_VersionReq* req = Nova_VersionReq_static_parse((nova_str){.ptr="1.0.0 || 2.0.0", .len=14});
    /* SRC: assert(req.matches(Version.from("1.0.0"))) */
    nova_assert(Nova_VersionReq_method_matches(req, nova_fn_Version_from((nova_str){.ptr="1.0.0", .len=5})), "assert(assert(\"1.0.0\"))");
    /* SRC: assert(req.matches(Version.from("2.0.0"))) */
    nova_assert(Nova_VersionReq_method_matches(req, nova_fn_Version_from((nova_str){.ptr="2.0.0", .len=5})), "assert(assert(\"2.0.0\"))");
    /* SRC: assert(!req.matches(Version.from("1.5.0"))) */
    nova_assert((!Nova_VersionReq_method_matches(req, nova_fn_Version_from((nova_str){.ptr="1.5.0", .len=5}))), "!assert(assert(\"1.5.0\"))");
    return NOVA_UNIT;
}

static nova_unit nova_test_wildcard____matches_anything_6(void) {
    /* SRC: let req = VersionReq.parse("*") */
    Nova_VersionReq* req = Nova_VersionReq_static_parse((nova_str){.ptr="*", .len=1});
    /* SRC: assert(req.matches(Version.from("0.0.1"))) */
    nova_assert(Nova_VersionReq_method_matches(req, nova_fn_Version_from((nova_str){.ptr="0.0.1", .len=5})), "assert(assert(\"0.0.1\"))");
    /* SRC: assert(req.matches(Version.from("99.99.99"))) */
    nova_assert(Nova_VersionReq_method_matches(req, nova_fn_Version_from((nova_str){.ptr="99.99.99", .len=8})), "assert(assert(\"99.99.99\"))");
    return NOVA_UNIT;
}

static nova_unit nova_fn_main_impl(void) {
    int _nova_tests_total = 7;
    int _nova_tests_failed = 0;
    printf("Running %d tests...\n", _nova_tests_total);
    {
        NovaTestFrame _tf;
        _tf.fail_msg = NULL;
        _nova_test_frame = &_tf;
        NovaFailFrame _tf_fail;
        _tf_fail.error_msg = (nova_str){.ptr=NULL, .len=0};
        nova_fail_push(&_tf_fail);
        int _tf_jmp = setjmp(_tf.jmp);
        int _tf_fail_jmp = (_tf_jmp == 0) ? setjmp(_tf_fail.jmp) : 0;
        if (_tf_jmp == 0 && _tf_fail_jmp == 0) {
            nova_test_exact__1_2_3_matches________1_2_3_0();
            printf("  PASS: exact: 1.2.3 matches только 1.2.3\n");
        } else {
            const char* _tf_msg = _tf.fail_msg ? _tf.fail_msg : (_tf_fail.error_msg.ptr ? _tf_fail.error_msg.ptr : "assertion failed");
            printf("  FAIL: exact: 1.2.3 matches только 1.2.3 — %s\n", _tf_msg);
            _nova_tests_failed++;
        }
        nova_fail_pop();
        _nova_test_frame = NULL;
    }
    {
        NovaTestFrame _tf;
        _tf.fail_msg = NULL;
        _nova_test_frame = &_tf;
        NovaFailFrame _tf_fail;
        _tf_fail.error_msg = (nova_str){.ptr=NULL, .len=0};
        nova_fail_push(&_tf_fail);
        int _tf_jmp = setjmp(_tf.jmp);
        int _tf_fail_jmp = (_tf_jmp == 0) ? setjmp(_tf_fail.jmp) : 0;
        if (_tf_jmp == 0 && _tf_fail_jmp == 0) {
            nova_test_caret__1_2_3_____1_2_3__2_0_0_1();
            printf("  PASS: caret ^1.2.3 = >=1.2.3 <2.0.0\n");
        } else {
            const char* _tf_msg = _tf.fail_msg ? _tf.fail_msg : (_tf_fail.error_msg.ptr ? _tf_fail.error_msg.ptr : "assertion failed");
            printf("  FAIL: caret ^1.2.3 = >=1.2.3 <2.0.0 — %s\n", _tf_msg);
            _nova_tests_failed++;
        }
        nova_fail_pop();
        _nova_test_frame = NULL;
    }
    {
        NovaTestFrame _tf;
        _tf.fail_msg = NULL;
        _nova_test_frame = &_tf;
        NovaFailFrame _tf_fail;
        _tf_fail.error_msg = (nova_str){.ptr=NULL, .len=0};
        nova_fail_push(&_tf_fail);
        int _tf_jmp = setjmp(_tf.jmp);
        int _tf_fail_jmp = (_tf_jmp == 0) ? setjmp(_tf_fail.jmp) : 0;
        if (_tf_jmp == 0 && _tf_fail_jmp == 0) {
            nova_test_tilde__1_2_3_____1_2_3__1_3_0_2();
            printf("  PASS: tilde ~1.2.3 = >=1.2.3 <1.3.0\n");
        } else {
            const char* _tf_msg = _tf.fail_msg ? _tf.fail_msg : (_tf_fail.error_msg.ptr ? _tf_fail.error_msg.ptr : "assertion failed");
            printf("  FAIL: tilde ~1.2.3 = >=1.2.3 <1.3.0 — %s\n", _tf_msg);
            _nova_tests_failed++;
        }
        nova_fail_pop();
        _nova_test_frame = NULL;
    }
    {
        NovaTestFrame _tf;
        _tf.fail_msg = NULL;
        _nova_test_frame = &_tf;
        NovaFailFrame _tf_fail;
        _tf_fail.error_msg = (nova_str){.ptr=NULL, .len=0};
        nova_fail_push(&_tf_fail);
        int _tf_jmp = setjmp(_tf.jmp);
        int _tf_fail_jmp = (_tf_jmp == 0) ? setjmp(_tf_fail.jmp) : 0;
        if (_tf_jmp == 0 && _tf_fail_jmp == 0) {
            nova_test___1_0_0__________________3();
            printf("  PASS: >=1.0.0 — нижняя граница\n");
        } else {
            const char* _tf_msg = _tf.fail_msg ? _tf.fail_msg : (_tf_fail.error_msg.ptr ? _tf_fail.error_msg.ptr : "assertion failed");
            printf("  FAIL: >=1.0.0 — нижняя граница — %s\n", _tf_msg);
            _nova_tests_failed++;
        }
        nova_fail_pop();
        _nova_test_frame = NULL;
    }
    {
        NovaTestFrame _tf;
        _tf.fail_msg = NULL;
        _nova_test_frame = &_tf;
        NovaFailFrame _tf_fail;
        _tf_fail.error_msg = (nova_str){.ptr=NULL, .len=0};
        nova_fail_push(&_tf_fail);
        int _tf_jmp = setjmp(_tf.jmp);
        int _tf_fail_jmp = (_tf_jmp == 0) ? setjmp(_tf_fail.jmp) : 0;
        if (_tf_jmp == 0 && _tf_fail_jmp == 0) {
            nova_test_AND___1_0_0__2_0_0_4();
            printf("  PASS: AND: >1.0.0 <2.0.0\n");
        } else {
            const char* _tf_msg = _tf.fail_msg ? _tf.fail_msg : (_tf_fail.error_msg.ptr ? _tf_fail.error_msg.ptr : "assertion failed");
            printf("  FAIL: AND: >1.0.0 <2.0.0 — %s\n", _tf_msg);
            _nova_tests_failed++;
        }
        nova_fail_pop();
        _nova_test_frame = NULL;
    }
    {
        NovaTestFrame _tf;
        _tf.fail_msg = NULL;
        _nova_test_frame = &_tf;
        NovaFailFrame _tf_fail;
        _tf_fail.error_msg = (nova_str){.ptr=NULL, .len=0};
        nova_fail_push(&_tf_fail);
        int _tf_jmp = setjmp(_tf.jmp);
        int _tf_fail_jmp = (_tf_jmp == 0) ? setjmp(_tf_fail.jmp) : 0;
        if (_tf_jmp == 0 && _tf_fail_jmp == 0) {
            nova_test_OR__1_0_0____2_0_0_5();
            printf("  PASS: OR: 1.0.0 || 2.0.0\n");
        } else {
            const char* _tf_msg = _tf.fail_msg ? _tf.fail_msg : (_tf_fail.error_msg.ptr ? _tf_fail.error_msg.ptr : "assertion failed");
            printf("  FAIL: OR: 1.0.0 || 2.0.0 — %s\n", _tf_msg);
            _nova_tests_failed++;
        }
        nova_fail_pop();
        _nova_test_frame = NULL;
    }
    {
        NovaTestFrame _tf;
        _tf.fail_msg = NULL;
        _nova_test_frame = &_tf;
        NovaFailFrame _tf_fail;
        _tf_fail.error_msg = (nova_str){.ptr=NULL, .len=0};
        nova_fail_push(&_tf_fail);
        int _tf_jmp = setjmp(_tf.jmp);
        int _tf_fail_jmp = (_tf_jmp == 0) ? setjmp(_tf_fail.jmp) : 0;
        if (_tf_jmp == 0 && _tf_fail_jmp == 0) {
            nova_test_wildcard____matches_anything_6();
            printf("  PASS: wildcard *: matches anything\n");
        } else {
            const char* _tf_msg = _tf.fail_msg ? _tf.fail_msg : (_tf_fail.error_msg.ptr ? _tf_fail.error_msg.ptr : "assertion failed");
            printf("  FAIL: wildcard *: matches anything — %s\n", _tf_msg);
            _nova_tests_failed++;
        }
        nova_fail_pop();
        _nova_test_frame = NULL;
    }
    printf("%d/%d passed\n", _nova_tests_total - _nova_tests_failed, _nova_tests_total);
    if (_nova_tests_failed > 0) { exit(1); }
    return NOVA_UNIT;
}

int main(void) {
    nova_gc_init();
    nova_register_effect_storage((void**)&_nova_handler_Fail);
    nova_register_effect_storage((void**)&_nova_handler_Time);
    nova_fn_main_impl();
    nova_gc_shutdown();
    return 0;
}
