/* Generated by nova-codegen. Do not edit. */
#include "nova_rt/nova_rt.h"

typedef struct { nova_int f0; } _NovaTuple1;
typedef struct { nova_int f0; nova_int f1; } _NovaTuple2;
typedef struct { nova_int f0; nova_int f1; nova_int f2; } _NovaTuple3;
typedef struct { nova_int f0; nova_int f1; nova_int f2; nova_int f3; } _NovaTuple4;
typedef struct { nova_int f0; nova_int f1; nova_int f2; nova_int f3; nova_int f4; } _NovaTuple5;
typedef struct { nova_int f0; nova_int f1; nova_int f2; nova_int f3; nova_int f4; nova_int f5; } _NovaTuple6;
typedef struct { nova_int f0; nova_int f1; nova_int f2; nova_int f3; nova_int f4; nova_int f5; nova_int f6; } _NovaTuple7;
typedef struct { nova_int f0; nova_int f1; nova_int f2; nova_int f3; nova_int f4; nova_int f5; nova_int f6; nova_int f7; } _NovaTuple8;

typedef enum {
    NOVA_TAG_DiffOp_Equal,
    NOVA_TAG_DiffOp_Insert,
    NOVA_TAG_DiffOp_Delete,
} Nova_DiffOp_Tag;
typedef struct Nova_DiffOp Nova_DiffOp;
struct Nova_DiffOp {
    Nova_DiffOp_Tag tag;
    union {
        struct {
            nova_str _0;
        } Equal;
        struct {
            nova_str _0;
        } Insert;
        struct {
            nova_str _0;
        } Delete;
    } payload;
};

static Nova_DiffOp* nova_make_DiffOp_Equal(nova_str _0) {
    Nova_DiffOp* _r = (Nova_DiffOp*)nova_alloc(sizeof(Nova_DiffOp));
    _r->tag = NOVA_TAG_DiffOp_Equal;
    _r->payload.Equal._0 = _0;
    return _r;
}

static Nova_DiffOp* nova_make_DiffOp_Insert(nova_str _0) {
    Nova_DiffOp* _r = (Nova_DiffOp*)nova_alloc(sizeof(Nova_DiffOp));
    _r->tag = NOVA_TAG_DiffOp_Insert;
    _r->payload.Insert._0 = _0;
    return _r;
}

static Nova_DiffOp* nova_make_DiffOp_Delete(nova_str _0) {
    Nova_DiffOp* _r = (Nova_DiffOp*)nova_alloc(sizeof(Nova_DiffOp));
    _r->tag = NOVA_TAG_DiffOp_Delete;
    _r->payload.Delete._0 = _0;
    return _r;
}

static NovaArray_nova_int* Nova_Diff_static_compute(NovaArray_nova_str* a, NovaArray_nova_str* b);
static nova_str Nova_Diff_static_format(NovaArray_nova_int* ops);
static nova_unit nova_test_diff__identical_arrays_0(void);
static nova_unit nova_test_diff__complete_change_1(void);
static nova_unit nova_test_diff__insertion____________2(void);
static nova_unit nova_test_diff__deletion____________3(void);

static NovaArray_nova_int* Nova_Diff_static_compute(NovaArray_nova_str* a, NovaArray_nova_str* b) {
    /* SRC: let n = a.len */
    nova_int n = (a->len);
    /* SRC: let m = b.len */
    nova_int m = (b->len);
    /* SRC: let mut lcs [][]int = [] */
    NovaArray_nova_int* _nv_tmp_0 = nova_array_new_nova_int(8);
    NovaArray_nova_int* lcs = _nv_tmp_0;
    /* SRC: let mut i = 0 */
    nova_int i = ((nova_int)0LL);
    /* SRC: while i <= n { */
    nova_unit _nv_while_1;
    while ((i <= n)) {
        /* SRC: let mut row []int = [] */
        NovaArray_nova_int* _nv_tmp_2 = nova_array_new_nova_int(8);
        NovaArray_nova_int* row = _nv_tmp_2;
        /* SRC: let mut j = 0 */
        nova_int j = ((nova_int)0LL);
        /* SRC: while j <= m { row.push(0); j += 1 } */
        nova_unit _nv_while_3;
        while ((j <= m)) {
            /* SRC: row.push(0) */
            nova_array_push_nova_int(row, ((nova_int)0LL));
            NOVA_UNIT;
            /* SRC: j += 1 */
            j += ((nova_int)1LL);
        }
        _nv_while_3 = NOVA_UNIT;
        _nv_while_3;
        /* SRC: lcs.push(row) */
        nova_array_push_nova_int(lcs, row);
        NOVA_UNIT;
        /* SRC: i += 1 */
        i += ((nova_int)1LL);
    }
    _nv_while_1 = NOVA_UNIT;
    _nv_while_1;
    /* SRC: let mut ii = 1 */
    nova_int ii = ((nova_int)1LL);
    /* SRC: while ii <= n { */
    nova_unit _nv_while_4;
    while ((ii <= n)) {
        /* SRC: let mut jj = 1 */
        nova_int jj = ((nova_int)1LL);
        /* SRC: while jj <= m { */
        nova_unit _nv_while_5;
        while ((jj <= m)) {
            /* SRC: if a[ii - 1] == b[jj - 1] { */
            nova_unit _nv_if_6;
            if ((nova_str_eq((a)->data[(ii - ((nova_int)1LL))], (b)->data[(jj - ((nova_int)1LL))]))) {
                /* SRC: lcs[ii][jj] = lcs[ii - 1][jj - 1] + 1 */
                ((lcs)->data[ii])[jj] = (((lcs)->data[(ii - ((nova_int)1LL))])[(jj - ((nova_int)1LL))] + ((nova_int)1LL));
                _nv_if_6 = NOVA_UNIT;
            } else {
                /* SRC: let up = lcs[ii - 1][jj] */
                nova_int up = ((lcs)->data[(ii - ((nova_int)1LL))])[jj];
                /* SRC: let left = lcs[ii][jj - 1] */
                nova_int left = ((lcs)->data[ii])[(jj - ((nova_int)1LL))];
                /* SRC: lcs[ii][jj] = if up > left { up } */
                nova_int _nv_if_7;
                if ((up > left)) {
                    _nv_if_7 = (nova_int)(up);
                } else {
                    _nv_if_7 = (nova_int)(left);
                }
                ((lcs)->data[ii])[jj] = _nv_if_7;
                _nv_if_6 = NOVA_UNIT;
            }
            _nv_if_6;
            /* SRC: jj += 1 */
            jj += ((nova_int)1LL);
        }
        _nv_while_5 = NOVA_UNIT;
        _nv_while_5;
        /* SRC: ii += 1 */
        ii += ((nova_int)1LL);
    }
    _nv_while_4 = NOVA_UNIT;
    _nv_while_4;
    /* SRC: let mut ops_rev []DiffOp = [] */
    NovaArray_nova_int* _nv_tmp_8 = nova_array_new_nova_int(8);
    NovaArray_nova_int* ops_rev = _nv_tmp_8;
    /* SRC: let mut x = n */
    nova_int x = n;
    /* SRC: let mut y = m */
    nova_int y = m;
    /* SRC: while x > 0 || y > 0 { */
    nova_unit _nv_while_9;
    while (((x > ((nova_int)0LL)) || (y > ((nova_int)0LL)))) {
    }
    _nv_while_9 = NOVA_UNIT;
    _nv_while_9;
    /* SRC: let mut ops []DiffOp = [] */
    NovaArray_nova_int* _nv_tmp_10 = nova_array_new_nova_int(8);
    NovaArray_nova_int* ops = _nv_tmp_10;
    /* SRC: let mut k = ops_rev.len - 1 */
    nova_int k = ((ops_rev->len) - ((nova_int)1LL));
    /* SRC: while k >= 0 { */
    nova_unit _nv_while_11;
    while ((k >= ((nova_int)0LL))) {
        /* SRC: ops.push(ops_rev[k]) */
        nova_array_push_nova_int(ops, (ops_rev)->data[k]);
        NOVA_UNIT;
        /* SRC: k -= 1 */
        k -= ((nova_int)1LL);
    }
    _nv_while_11 = NOVA_UNIT;
    _nv_while_11;
    /* SRC: ops */
    return ops;
}

static nova_str Nova_Diff_static_format(NovaArray_nova_int* ops) {
    /* SRC: let mut buf = Buffer.new() */
    Nova_Buffer* buf = Nova_Buffer_static_new();
    /* SRC: for op in ops { */
    NovaArray_nova_int* _nv_tmp_12 = ops;
    nova_unit _nv_tmp_14;
    for (nova_int _nv_tmp_13 = 0; _nv_tmp_13 < _nv_tmp_12->len; _nv_tmp_13++) {
        Nova_DiffOp* op = (Nova_DiffOp*)_nv_tmp_12->data[_nv_tmp_13];
        /* SRC: match op { */
        Nova_DiffOp* _nv_scr_15 = op;
        nova_unit _nv_match_16;
        int _nv_matched_17 = 0;
        if (!_nv_matched_17 && ((_nv_scr_15->tag == NOVA_TAG_DiffOp_Equal))) {
            nova_str s = _nv_scr_15->payload.Equal._0;
            /* SRC: buf.add_char(' ') */
            Nova_Buffer_method_add_char(buf, ((nova_int)32LL));
            _nv_match_16 = Nova_Buffer_method_add_str(buf, s);
            _nv_matched_17 = 1;
        }
        if (!_nv_matched_17 && ((_nv_scr_15->tag == NOVA_TAG_DiffOp_Insert))) {
            nova_str s = _nv_scr_15->payload.Insert._0;
            /* SRC: buf.add_char('+') */
            Nova_Buffer_method_add_char(buf, ((nova_int)43LL));
            _nv_match_16 = Nova_Buffer_method_add_str(buf, s);
            _nv_matched_17 = 1;
        }
        if (!_nv_matched_17 && ((_nv_scr_15->tag == NOVA_TAG_DiffOp_Delete))) {
            nova_str s = _nv_scr_15->payload.Delete._0;
            /* SRC: buf.add_char('-') */
            Nova_Buffer_method_add_char(buf, ((nova_int)45LL));
            _nv_match_16 = Nova_Buffer_method_add_str(buf, s);
            _nv_matched_17 = 1;
        }
        _nv_match_16;
        (void)(Nova_Buffer_method_add_char(buf, ((nova_int)10LL)));
    }
    _nv_tmp_14 = NOVA_UNIT;
    _nv_tmp_14;
    /* SRC: buf.into_str_unchecked() */
    return Nova_Buffer_method_into_str_unchecked(buf);
}

static nova_unit nova_test_diff__identical_arrays_0(void) {
    /* SRC: let ops = Diff.compute(["a", "b", "c"], ["a", "b", "c"]) */
    NovaArray_nova_int* _nv_tmp_18 = nova_array_new_nova_int(3);
    nova_str* _nv_tmp_19 = (nova_str*)nova_alloc(sizeof(nova_str));
    *_nv_tmp_19 = (nova_str){.ptr="a", .len=1};
    nova_array_push_nova_int(_nv_tmp_18, (nova_int)(_nv_tmp_19)  );
    nova_str* _nv_tmp_20 = (nova_str*)nova_alloc(sizeof(nova_str));
    *_nv_tmp_20 = (nova_str){.ptr="b", .len=1};
    nova_array_push_nova_int(_nv_tmp_18, (nova_int)(_nv_tmp_20)  );
    nova_str* _nv_tmp_21 = (nova_str*)nova_alloc(sizeof(nova_str));
    *_nv_tmp_21 = (nova_str){.ptr="c", .len=1};
    nova_array_push_nova_int(_nv_tmp_18, (nova_int)(_nv_tmp_21)  );
    NovaArray_nova_int* _nv_tmp_22 = nova_array_new_nova_int(3);
    nova_str* _nv_tmp_23 = (nova_str*)nova_alloc(sizeof(nova_str));
    *_nv_tmp_23 = (nova_str){.ptr="a", .len=1};
    nova_array_push_nova_int(_nv_tmp_22, (nova_int)(_nv_tmp_23)  );
    nova_str* _nv_tmp_24 = (nova_str*)nova_alloc(sizeof(nova_str));
    *_nv_tmp_24 = (nova_str){.ptr="b", .len=1};
    nova_array_push_nova_int(_nv_tmp_22, (nova_int)(_nv_tmp_24)  );
    nova_str* _nv_tmp_25 = (nova_str*)nova_alloc(sizeof(nova_str));
    *_nv_tmp_25 = (nova_str){.ptr="c", .len=1};
    nova_array_push_nova_int(_nv_tmp_22, (nova_int)(_nv_tmp_25)  );
    NovaArray_nova_int* ops = Nova_Diff_static_compute(_nv_tmp_18, _nv_tmp_22);
    /* SRC: for op in ops { */
    NovaArray_nova_int* _nv_tmp_26 = ops;
    nova_unit _nv_tmp_28;
    for (nova_int _nv_tmp_27 = 0; _nv_tmp_27 < _nv_tmp_26->len; _nv_tmp_27++) {
        Nova_DiffOp* op = (Nova_DiffOp*)_nv_tmp_26->data[_nv_tmp_27];
        Nova_DiffOp* _nv_scr_29 = op;
        nova_unit _nv_match_30;
        int _nv_matched_31 = 0;
        if (!_nv_matched_31 && ((_nv_scr_29->tag == NOVA_TAG_DiffOp_Equal))) {
            _nv_match_30 = NOVA_UNIT;
            _nv_matched_31 = 1;
        }
        if (!_nv_matched_31 && (true)) {
            _nv_match_30 = nova_assert(false, "false");
            _nv_matched_31 = 1;
        }
        (void)(_nv_match_30);
    }
    _nv_tmp_28 = NOVA_UNIT;
    _nv_tmp_28;
    return NOVA_UNIT;
}

static nova_unit nova_test_diff__complete_change_1(void) {
    /* SRC: let ops = Diff.compute(["a"], ["b"]) */
    NovaArray_nova_int* _nv_tmp_32 = nova_array_new_nova_int(1);
    nova_str* _nv_tmp_33 = (nova_str*)nova_alloc(sizeof(nova_str));
    *_nv_tmp_33 = (nova_str){.ptr="a", .len=1};
    nova_array_push_nova_int(_nv_tmp_32, (nova_int)(_nv_tmp_33)  );
    NovaArray_nova_int* _nv_tmp_34 = nova_array_new_nova_int(1);
    nova_str* _nv_tmp_35 = (nova_str*)nova_alloc(sizeof(nova_str));
    *_nv_tmp_35 = (nova_str){.ptr="b", .len=1};
    nova_array_push_nova_int(_nv_tmp_34, (nova_int)(_nv_tmp_35)  );
    NovaArray_nova_int* ops = Nova_Diff_static_compute(_nv_tmp_32, _nv_tmp_34);
    /* SRC: let mut has_delete = false */
    nova_bool has_delete = false;
    /* SRC: let mut has_insert = false */
    nova_bool has_insert = false;
    /* SRC: for op in ops { */
    NovaArray_nova_int* _nv_tmp_36 = ops;
    nova_unit _nv_tmp_38;
    for (nova_int _nv_tmp_37 = 0; _nv_tmp_37 < _nv_tmp_36->len; _nv_tmp_37++) {
        Nova_DiffOp* op = (Nova_DiffOp*)_nv_tmp_36->data[_nv_tmp_37];
        Nova_DiffOp* _nv_scr_39 = op;
        nova_unit _nv_match_40;
        int _nv_matched_41 = 0;
        if (!_nv_matched_41 && (((_nv_scr_39->tag == NOVA_TAG_DiffOp_Delete) && (_nv_scr_39->payload.Delete._0.len == 1 && memcmp(_nv_scr_39->payload.Delete._0.ptr, "a", 1) == 0)))) {
            /* SRC: has_delete = true */
            has_delete = true;
            _nv_matched_41 = 1;
        }
        if (!_nv_matched_41 && (((_nv_scr_39->tag == NOVA_TAG_DiffOp_Insert) && (_nv_scr_39->payload.Insert._0.len == 1 && memcmp(_nv_scr_39->payload.Insert._0.ptr, "b", 1) == 0)))) {
            /* SRC: has_insert = true */
            has_insert = true;
            _nv_matched_41 = 1;
        }
        if (!_nv_matched_41 && (true)) {
            _nv_match_40 = NOVA_UNIT;
            _nv_matched_41 = 1;
        }
        (void)(_nv_match_40);
    }
    _nv_tmp_38 = NOVA_UNIT;
    _nv_tmp_38;
    /* SRC: assert(has_delete) */
    nova_assert(has_delete, "has_delete");
    /* SRC: assert(has_insert) */
    nova_assert(has_insert, "has_insert");
    return NOVA_UNIT;
}

static nova_unit nova_test_diff__insertion____________2(void) {
    /* SRC: let ops = Diff.compute(["a", "c"], ["a", "b", "c"]) */
    NovaArray_nova_int* _nv_tmp_42 = nova_array_new_nova_int(2);
    nova_str* _nv_tmp_43 = (nova_str*)nova_alloc(sizeof(nova_str));
    *_nv_tmp_43 = (nova_str){.ptr="a", .len=1};
    nova_array_push_nova_int(_nv_tmp_42, (nova_int)(_nv_tmp_43)  );
    nova_str* _nv_tmp_44 = (nova_str*)nova_alloc(sizeof(nova_str));
    *_nv_tmp_44 = (nova_str){.ptr="c", .len=1};
    nova_array_push_nova_int(_nv_tmp_42, (nova_int)(_nv_tmp_44)  );
    NovaArray_nova_int* _nv_tmp_45 = nova_array_new_nova_int(3);
    nova_str* _nv_tmp_46 = (nova_str*)nova_alloc(sizeof(nova_str));
    *_nv_tmp_46 = (nova_str){.ptr="a", .len=1};
    nova_array_push_nova_int(_nv_tmp_45, (nova_int)(_nv_tmp_46)  );
    nova_str* _nv_tmp_47 = (nova_str*)nova_alloc(sizeof(nova_str));
    *_nv_tmp_47 = (nova_str){.ptr="b", .len=1};
    nova_array_push_nova_int(_nv_tmp_45, (nova_int)(_nv_tmp_47)  );
    nova_str* _nv_tmp_48 = (nova_str*)nova_alloc(sizeof(nova_str));
    *_nv_tmp_48 = (nova_str){.ptr="c", .len=1};
    nova_array_push_nova_int(_nv_tmp_45, (nova_int)(_nv_tmp_48)  );
    NovaArray_nova_int* ops = Nova_Diff_static_compute(_nv_tmp_42, _nv_tmp_45);
    /* SRC: let mut has_insert_b = false */
    nova_bool has_insert_b = false;
    /* SRC: for op in ops { */
    NovaArray_nova_int* _nv_tmp_49 = ops;
    nova_unit _nv_tmp_51;
    for (nova_int _nv_tmp_50 = 0; _nv_tmp_50 < _nv_tmp_49->len; _nv_tmp_50++) {
        Nova_DiffOp* op = (Nova_DiffOp*)_nv_tmp_49->data[_nv_tmp_50];
        Nova_DiffOp* _nv_scr_52 = op;
        nova_unit _nv_match_53;
        int _nv_matched_54 = 0;
        if (!_nv_matched_54 && (((_nv_scr_52->tag == NOVA_TAG_DiffOp_Insert) && (_nv_scr_52->payload.Insert._0.len == 1 && memcmp(_nv_scr_52->payload.Insert._0.ptr, "b", 1) == 0)))) {
            /* SRC: has_insert_b = true */
            has_insert_b = true;
            _nv_matched_54 = 1;
        }
        if (!_nv_matched_54 && (true)) {
            _nv_match_53 = NOVA_UNIT;
            _nv_matched_54 = 1;
        }
        (void)(_nv_match_53);
    }
    _nv_tmp_51 = NOVA_UNIT;
    _nv_tmp_51;
    /* SRC: assert(has_insert_b) */
    nova_assert(has_insert_b, "has_insert_b");
    return NOVA_UNIT;
}

static nova_unit nova_test_diff__deletion____________3(void) {
    /* SRC: let ops = Diff.compute(["a", "b", "c"], ["a", "c"]) */
    NovaArray_nova_int* _nv_tmp_55 = nova_array_new_nova_int(3);
    nova_str* _nv_tmp_56 = (nova_str*)nova_alloc(sizeof(nova_str));
    *_nv_tmp_56 = (nova_str){.ptr="a", .len=1};
    nova_array_push_nova_int(_nv_tmp_55, (nova_int)(_nv_tmp_56)  );
    nova_str* _nv_tmp_57 = (nova_str*)nova_alloc(sizeof(nova_str));
    *_nv_tmp_57 = (nova_str){.ptr="b", .len=1};
    nova_array_push_nova_int(_nv_tmp_55, (nova_int)(_nv_tmp_57)  );
    nova_str* _nv_tmp_58 = (nova_str*)nova_alloc(sizeof(nova_str));
    *_nv_tmp_58 = (nova_str){.ptr="c", .len=1};
    nova_array_push_nova_int(_nv_tmp_55, (nova_int)(_nv_tmp_58)  );
    NovaArray_nova_int* _nv_tmp_59 = nova_array_new_nova_int(2);
    nova_str* _nv_tmp_60 = (nova_str*)nova_alloc(sizeof(nova_str));
    *_nv_tmp_60 = (nova_str){.ptr="a", .len=1};
    nova_array_push_nova_int(_nv_tmp_59, (nova_int)(_nv_tmp_60)  );
    nova_str* _nv_tmp_61 = (nova_str*)nova_alloc(sizeof(nova_str));
    *_nv_tmp_61 = (nova_str){.ptr="c", .len=1};
    nova_array_push_nova_int(_nv_tmp_59, (nova_int)(_nv_tmp_61)  );
    NovaArray_nova_int* ops = Nova_Diff_static_compute(_nv_tmp_55, _nv_tmp_59);
    /* SRC: let mut has_delete_b = false */
    nova_bool has_delete_b = false;
    /* SRC: for op in ops { */
    NovaArray_nova_int* _nv_tmp_62 = ops;
    nova_unit _nv_tmp_64;
    for (nova_int _nv_tmp_63 = 0; _nv_tmp_63 < _nv_tmp_62->len; _nv_tmp_63++) {
        Nova_DiffOp* op = (Nova_DiffOp*)_nv_tmp_62->data[_nv_tmp_63];
        Nova_DiffOp* _nv_scr_65 = op;
        nova_unit _nv_match_66;
        int _nv_matched_67 = 0;
        if (!_nv_matched_67 && (((_nv_scr_65->tag == NOVA_TAG_DiffOp_Delete) && (_nv_scr_65->payload.Delete._0.len == 1 && memcmp(_nv_scr_65->payload.Delete._0.ptr, "b", 1) == 0)))) {
            /* SRC: has_delete_b = true */
            has_delete_b = true;
            _nv_matched_67 = 1;
        }
        if (!_nv_matched_67 && (true)) {
            _nv_match_66 = NOVA_UNIT;
            _nv_matched_67 = 1;
        }
        (void)(_nv_match_66);
    }
    _nv_tmp_64 = NOVA_UNIT;
    _nv_tmp_64;
    /* SRC: assert(has_delete_b) */
    nova_assert(has_delete_b, "has_delete_b");
    return NOVA_UNIT;
}

static nova_unit nova_fn_main_impl(void) {
    int _nova_tests_total = 4;
    int _nova_tests_failed = 0;
    printf("Running %d tests...\n", _nova_tests_total);
    {
        NovaTestFrame _tf;
        _tf.fail_msg = NULL;
        _nova_test_frame = &_tf;
        NovaFailFrame _tf_fail;
        _tf_fail.error_msg = (nova_str){.ptr=NULL, .len=0};
        nova_fail_push(&_tf_fail);
        int _tf_jmp = setjmp(_tf.jmp);
        int _tf_fail_jmp = (_tf_jmp == 0) ? setjmp(_tf_fail.jmp) : 0;
        if (_tf_jmp == 0 && _tf_fail_jmp == 0) {
            nova_test_diff__identical_arrays_0();
            printf("  PASS: diff: identical arrays\n");
        } else {
            const char* _tf_msg = _tf.fail_msg ? _tf.fail_msg : (_tf_fail.error_msg.ptr ? _tf_fail.error_msg.ptr : "assertion failed");
            printf("  FAIL: diff: identical arrays — %s\n", _tf_msg);
            _nova_tests_failed++;
        }
        nova_fail_pop();
        _nova_test_frame = NULL;
    }
    {
        NovaTestFrame _tf;
        _tf.fail_msg = NULL;
        _nova_test_frame = &_tf;
        NovaFailFrame _tf_fail;
        _tf_fail.error_msg = (nova_str){.ptr=NULL, .len=0};
        nova_fail_push(&_tf_fail);
        int _tf_jmp = setjmp(_tf.jmp);
        int _tf_fail_jmp = (_tf_jmp == 0) ? setjmp(_tf_fail.jmp) : 0;
        if (_tf_jmp == 0 && _tf_fail_jmp == 0) {
            nova_test_diff__complete_change_1();
            printf("  PASS: diff: complete change\n");
        } else {
            const char* _tf_msg = _tf.fail_msg ? _tf.fail_msg : (_tf_fail.error_msg.ptr ? _tf_fail.error_msg.ptr : "assertion failed");
            printf("  FAIL: diff: complete change — %s\n", _tf_msg);
            _nova_tests_failed++;
        }
        nova_fail_pop();
        _nova_test_frame = NULL;
    }
    {
        NovaTestFrame _tf;
        _tf.fail_msg = NULL;
        _nova_test_frame = &_tf;
        NovaFailFrame _tf_fail;
        _tf_fail.error_msg = (nova_str){.ptr=NULL, .len=0};
        nova_fail_push(&_tf_fail);
        int _tf_jmp = setjmp(_tf.jmp);
        int _tf_fail_jmp = (_tf_jmp == 0) ? setjmp(_tf_fail.jmp) : 0;
        if (_tf_jmp == 0 && _tf_fail_jmp == 0) {
            nova_test_diff__insertion____________2();
            printf("  PASS: diff: insertion в середине\n");
        } else {
            const char* _tf_msg = _tf.fail_msg ? _tf.fail_msg : (_tf_fail.error_msg.ptr ? _tf_fail.error_msg.ptr : "assertion failed");
            printf("  FAIL: diff: insertion в середине — %s\n", _tf_msg);
            _nova_tests_failed++;
        }
        nova_fail_pop();
        _nova_test_frame = NULL;
    }
    {
        NovaTestFrame _tf;
        _tf.fail_msg = NULL;
        _nova_test_frame = &_tf;
        NovaFailFrame _tf_fail;
        _tf_fail.error_msg = (nova_str){.ptr=NULL, .len=0};
        nova_fail_push(&_tf_fail);
        int _tf_jmp = setjmp(_tf.jmp);
        int _tf_fail_jmp = (_tf_jmp == 0) ? setjmp(_tf_fail.jmp) : 0;
        if (_tf_jmp == 0 && _tf_fail_jmp == 0) {
            nova_test_diff__deletion____________3();
            printf("  PASS: diff: deletion в середине\n");
        } else {
            const char* _tf_msg = _tf.fail_msg ? _tf.fail_msg : (_tf_fail.error_msg.ptr ? _tf_fail.error_msg.ptr : "assertion failed");
            printf("  FAIL: diff: deletion в середине — %s\n", _tf_msg);
            _nova_tests_failed++;
        }
        nova_fail_pop();
        _nova_test_frame = NULL;
    }
    printf("%d/%d passed\n", _nova_tests_total - _nova_tests_failed, _nova_tests_total);
    if (_nova_tests_failed > 0) { exit(1); }
    return NOVA_UNIT;
}

int main(void) {
    nova_gc_init();
    nova_register_effect_storage((void**)&_nova_handler_Fail);
    nova_register_effect_storage((void**)&_nova_handler_Time);
    nova_fn_main_impl();
    nova_gc_shutdown();
    return 0;
}
