#ifndef NOVA_RT_ARRAY_H
#define NOVA_RT_ARRAY_H

#include "alloc.h"
#include <stdint.h>
#include <stdio.h>   /* snprintf — Plan 96 Ф.1 nv_panic_index_oob diagnostic */
#include <string.h>

/*
 * Generic growable array for Nova codegen.
 *
 * Each element type T gets its own concrete struct via the NOVA_ARRAY_DECL
 * macro, which emits:
 *
 *   typedef struct NovaArray_T {
 *       T*      data;
 *       int64_t len;
 *       int64_t cap;
 *   } NovaArray_T;
 *
 * Helper functions (push, get) are generated by NOVA_ARRAY_IMPL.
 *
 * Usage in generated C:
 *   NOVA_ARRAY_DECL(nova_int)
 *   NOVA_ARRAY_IMPL(nova_int)
 *
 * The codegen emits these declarations at the top of the file for each
 * element type actually used.
 *
 * nova_array_new_T(cap)   — allocate with initial capacity
 * nova_array_push_T(a, v) — append element, growing if needed
 * nova_array_get_T(a, i)  — bounds-checked access, returns Option-like tag
 */

/* ---- Option<nova_int> for array.get() ---- *
 *
 * We use a simple tagged struct rather than a full sum-type to keep
 * the array header self-contained. Generated code for `.get(i)` uses
 * this struct directly; the match arms check `.tag`.
 */

/* Tag values shared across all NovaOpt_T structs */
#define NOVA_TAG_Option_None 0
#define NOVA_TAG_Option_Some 1

/* Declare the array struct and Option<T> struct for element type T.
 * T_NAME is the C identifier used in the struct/function names (e.g. nova_int). */
#define NOVA_ARRAY_DECL(T) \
    typedef struct NovaArray_##T { \
        T*      data; \
        int64_t len; \
        int64_t cap; \
    } NovaArray_##T; \
    typedef struct NovaOpt_##T { \
        int     tag; \
        T       value; \
    } NovaOpt_##T;

/* Implement helper functions for element type T.
 * Requires nova_alloc to be available. */
#define NOVA_ARRAY_IMPL(T) \
    static NovaArray_##T* nova_array_new_##T(int64_t init_cap) { \
        NovaArray_##T* a = (NovaArray_##T*)nova_alloc(sizeof(NovaArray_##T)); \
        a->cap  = init_cap > 0 ? init_cap : 8; \
        a->len  = 0; \
        a->data = (T*)nova_alloc((size_t)(a->cap) * sizeof(T)); \
        return a; \
    } \
    static void nova_array_push_##T(NovaArray_##T* a, T v) { \
        if (a->len >= a->cap) { \
            int64_t new_cap = a->cap * 2; \
            T* new_data = (T*)nova_alloc((size_t)new_cap * sizeof(T)); \
            memcpy(new_data, a->data, (size_t)(a->len) * sizeof(T)); \
            a->data = new_data; \
            a->cap  = new_cap; \
        } \
        a->data[a->len++] = v; \
    } \
    static NovaOpt_##T nova_array_get_##T(NovaArray_##T* a, int64_t i) { \
        NovaOpt_##T r; \
        if (i >= 0 && i < a->len) { r.tag = NOVA_TAG_Option_Some; r.value = a->data[i]; } \
        else                       { r.tag = NOVA_TAG_Option_None; r.value = (T){0}; } \
        return r; \
    } \
    static NovaOpt_##T nova_array_pop_##T(NovaArray_##T* a) { \
        NovaOpt_##T r; \
        if (a->len > 0) { a->len--; r.tag = NOVA_TAG_Option_Some; r.value = a->data[a->len]; } \
        else             { r.tag = NOVA_TAG_Option_None; r.value = (T){0}; } \
        return r; \
    } \
    static nova_bool nova_array_eq_##T(NovaArray_##T* a, NovaArray_##T* b) { \
        if (a->len != b->len) return 0; \
        for (int64_t _i = 0; _i < a->len; _i++) { if (a->data[_i] != b->data[_i]) return 0; } \
        return 1; \
    } \
    static void nova_array_copy_from_##T(NovaArray_##T* dst, NovaArray_##T* src) { \
        /* Plan 90.1: strict equal-length + always memmove (overlap safe).           \
         * Breaking change: old silent-truncation removed.                            \
         * Truncation idiom: dst[..n].copy_from(src[..n]) via Plan 96 slicing.        \
         * memmove vs memcpy: overlap-safe by default, paritет с Go; no UB. */       \
        if (src->len != dst->len) { \
            nv_panic((nova_str){ \
                .ptr = "copy_from: length mismatch (use dst[..n].copy_from(src[..n]) for partial copy)", \
                .len = sizeof("copy_from: length mismatch (use dst[..n].copy_from(src[..n]) for partial copy)") - 1 }); } \
        memmove(dst->data, src->data, (size_t)(dst->len) * sizeof(T)); \
    } \
    /* Plan 90.1: extend_from — append with 2x growth, memmove (self-extend safe). */ \
    static void nova_array_extend_from_##T(NovaArray_##T* dst, NovaArray_##T* src) { \
        int64_t src_len = src->len;         /* snapshot before potential realloc */  \
        T* src_data = src->data;            /* snapshot before potential realloc */  \
        int64_t needed = dst->len + src_len; \
        if (needed > dst->cap) { \
            int64_t new_cap = dst->cap * 2; \
            if (new_cap < needed) new_cap = needed; \
            T* new_data = (T*)nova_alloc((size_t)new_cap * sizeof(T)); \
            memcpy(new_data, dst->data, (size_t)(dst->len) * sizeof(T)); \
            dst->data = new_data; \
            dst->cap = new_cap; \
            /* src_data/src_len are snapshots — valid even if src==dst (self-extend). \
             * With Boehm GC, old allocation is retained until next collection.      */ \
        } \
        /* memmove handles src == dst[X..Y] overlap cases correctly. */ \
        memmove(dst->data + dst->len, src_data, (size_t)src_len * sizeof(T)); \
        dst->len = needed; \
    } \
    /* Plan 90.1: insert_from — insert at position i with growth + memmove tail. */ \
    static void nova_array_insert_from_##T(NovaArray_##T* dst, int64_t i, NovaArray_##T* src) { \
        if (i < 0 || i > dst->len) nv_panic_insert_oob(i, dst->len); \
        int64_t src_len = src->len;         /* snapshot before potential realloc */  \
        T* src_data = src->data;            /* snapshot before potential realloc */  \
        int64_t needed = dst->len + src_len; \
        int64_t tail_len = dst->len - i; \
        if (needed > dst->cap) { \
            /* Alloc new: copy prefix [0..i] + leave hole [i..i+src_len] + copy tail. */ \
            int64_t new_cap = dst->cap * 2; \
            if (new_cap < needed) new_cap = needed; \
            T* new_data = (T*)nova_alloc((size_t)new_cap * sizeof(T)); \
            memcpy(new_data, dst->data, (size_t)i * sizeof(T)); \
            memcpy(new_data + i + src_len, dst->data + i, (size_t)tail_len * sizeof(T)); \
            dst->data = new_data; \
            dst->cap = new_cap; \
        } else { \
            /* In-place: memmove tail right by src_len slots. */ \
            memmove(dst->data + i + src_len, dst->data + i, (size_t)tail_len * sizeof(T)); \
        } \
        /* memmove src into hole — handles overlap if src is a view into dst. */ \
        memmove(dst->data + i, src_data, (size_t)src_len * sizeof(T)); \
        dst->len = needed; \
    } \
    /* Plan 90.1: reserve — preallocate hint; len unchanged, only cap grows. */ \
    static void nova_array_reserve_##T(NovaArray_##T* dst, int64_t extra) { \
        if (extra < 0) nv_panic_negative_reserve(extra); \
        int64_t needed = dst->len + extra; \
        if (needed > dst->cap) { \
            int64_t new_cap = dst->cap * 2; \
            if (new_cap < needed) new_cap = needed; \
            T* new_data = (T*)nova_alloc((size_t)new_cap * sizeof(T)); \
            memcpy(new_data, dst->data, (size_t)(dst->len) * sizeof(T)); \
            dst->data = new_data; \
            dst->cap = new_cap; \
        } \
        /* len unchanged — only cap grows. View detach lint (W_VIEW_EXTEND_DETACH) \
         * at call-site covers the case where a view becomes dangling after realloc.*/ \
    } \
    static void nova_array_copy_within_##T(NovaArray_##T* a, int64_t src_from, int64_t dst_from, int64_t len) { \
        if (len < 0 || src_from < 0 || dst_from < 0 || \
            src_from + len > a->len || dst_from + len > a->len) { \
            nv_panic((nova_str){ .ptr = "copy_within: range out of bounds", \
                                 .len = sizeof("copy_within: range out of bounds") - 1 }); } \
        memmove(a->data + dst_from, a->data + src_from, (size_t)len * sizeof(T)); \
    } \
    static void nova_array_fill_##T(NovaArray_##T* a, T v) { \
        for (int64_t _i = 0; _i < a->len; _i++) { a->data[_i] = v; } \
    } \
    /* Plan 96 Ф.4 — sub-slice view `arr[a..b]`. O(1): новый header (24 байта)
     * с data = orig->data + from (interior pointer); len = cap = to - from
     * (D-cap-len: push на view → realloc → silent detach, parent НЕ затронут).
     * GC: backing держится через interior-pointer (Boehm GC_set_all_interior_pointers).
     * Bounds: from < 0 || to < from || to > len → nv_panic (D-neg-panic).
     * Empty slice (from == to) валиден (D-empty-ok). */ \
    static NovaArray_##T* nova_array_slice_##T(NovaArray_##T* a, int64_t from, int64_t to) { \
        if (from < 0 || to < from || to > a->len) { \
            nv_panic_slice_oob(from, to, a->len); \
        } \
        NovaArray_##T* v = (NovaArray_##T*)nova_alloc(sizeof(NovaArray_##T)); \
        v->data = a->data + from; /* interior pointer */ \
        v->len  = to - from; \
        v->cap  = to - from; /* D-cap-len: push → realloc → detach */ \
        return v; \
    }
/* Plan 95.bis Ф.2: Nova_Option_method_or_<T> убран из NOVA_ARRAY_IMPL —
 * перенесён на Nova-body в std/prelude/core.nv. Routing через
 * MethodRouting::DeclaredBody → mono'd Nova_Option_method_or_<T> с тем
 * же C-именем (C-redefinition collision если оставить здесь). */

/* ---- Default instantiations for primitive arrays.
 *
 * Каждый primitive-тип получает собственный NovaArray_T struct с реальным
 * packed `T data[]` (не int64-erasure). Это критично для byte:
 * `[]byte` хранится как `uint8_t[]`, не int64[]. Иначе 8x memory
 * overhead и неправильная FFI-семантика.
 */
NOVA_ARRAY_DECL(nova_int)
NOVA_ARRAY_IMPL(nova_int)

/* Plan 70.3: nova_char distinct typedef над int64_t — same storage
 * как nova_int, но distinct C type для generic mono mangling.
 * Prevents Option[char]↔Option[int] structural collapse. */
NOVA_ARRAY_DECL(nova_char)
NOVA_ARRAY_IMPL(nova_char)

NOVA_ARRAY_DECL(nova_byte)
NOVA_ARRAY_IMPL(nova_byte)

/* Plan 90: compare для []u8 — memcmp-класс, lexicographic.
 * ОДИН примитив: equality (== / eq) — частный случай (compare == 0).
 * Только для nova_byte: memcmp byte-wise; для multi-byte T порядок был
 * бы endianness-зависим. Возвращает -1/0/1 (модель Go/memcmp). */
static int nova_array_compare_nova_byte(NovaArray_nova_byte* a, NovaArray_nova_byte* b) {
    int64_t n = a->len < b->len ? a->len : b->len;
    if (n > 0) {
        int c = memcmp(a->data, b->data, (size_t)n);
        if (c != 0) return c < 0 ? -1 : 1;
    }
    if (a->len < b->len) return -1;
    if (a->len > b->len) return 1;
    return 0;
}

NOVA_ARRAY_DECL(nova_bool)
NOVA_ARRAY_IMPL(nova_bool)

NOVA_ARRAY_DECL(nova_f64)
NOVA_ARRAY_IMPL(nova_f64)

/* Plan 70.4: nova_f32 distinct from nova_f64 — ABI difference (4 vs 8 bytes).
 * []f32 и []f64 must have distinct NovaArray structs to avoid 2x memory cost
 * and silent data corruption when f32 arrays processed as f64. */
NOVA_ARRAY_DECL(nova_f32)
NOVA_ARRAY_IMPL(nova_f32)

/* Plan 70.4 Ф.2: sized-int arrays — distinct packed storage (ABI-real).
 * []i32 → NovaArray_int32_t* (4-byte elements), not NovaArray_nova_int* (8-byte).
 * Without these, GPU/audio/network buffers silently get 2x memory overhead
 * and wrong FFI alignment. ABI mismatch = silent data corruption. */
NOVA_ARRAY_DECL(int32_t)
NOVA_ARRAY_IMPL(int32_t)
NOVA_ARRAY_DECL(int16_t)
NOVA_ARRAY_IMPL(int16_t)
NOVA_ARRAY_DECL(int8_t)
NOVA_ARRAY_IMPL(int8_t)
NOVA_ARRAY_DECL(uint32_t)
NOVA_ARRAY_IMPL(uint32_t)
NOVA_ARRAY_DECL(uint16_t)
NOVA_ARRAY_IMPL(uint16_t)
NOVA_ARRAY_DECL(uint64_t)
NOVA_ARRAY_IMPL(uint64_t)

/* ---- void_p — array of opaque pointers (used for closures via NovaClosBase*).
 *
 * Plan 55 Ф.1: `[]fn(...) -> T` (array of closures) → NovaArray_void_p*.
 * Closure stored as void* (= NovaClos_X*); call-site routes through
 * NOVA_CLOS_CALL_* / NovaClosBase dispatch. Boehm conservative-scan
 * sees each data[i] as potential pointer → env retained correctly.
 */
typedef void* void_p;
NOVA_ARRAY_DECL(void_p)
static NovaArray_void_p* nova_array_new_void_p(int64_t init_cap) {
    NovaArray_void_p* a = (NovaArray_void_p*)nova_alloc(sizeof(NovaArray_void_p));
    a->cap  = init_cap > 0 ? init_cap : 8;
    a->len  = 0;
    a->data = (void_p*)nova_alloc((size_t)(a->cap) * sizeof(void_p));
    return a;
}
static void nova_array_push_void_p(NovaArray_void_p* a, void_p v) {
    if (a->len >= a->cap) {
        int64_t new_cap = a->cap * 2;
        void_p* new_data = (void_p*)nova_alloc((size_t)new_cap * sizeof(void_p));
        memcpy(new_data, a->data, (size_t)(a->len) * sizeof(void_p));
        a->data = new_data;
        a->cap  = new_cap;
    }
    a->data[a->len++] = v;
}
static NovaOpt_void_p nova_array_get_void_p(NovaArray_void_p* a, int64_t i) {
    NovaOpt_void_p r;
    if (i >= 0 && i < a->len) { r.tag = NOVA_TAG_Option_Some; r.value = a->data[i]; }
    else                       { r.tag = NOVA_TAG_Option_None; r.value = (void_p)0; }
    return r;
}
static NovaOpt_void_p nova_array_pop_void_p(NovaArray_void_p* a) {
    NovaOpt_void_p r;
    if (a->len > 0) { a->len--; r.tag = NOVA_TAG_Option_Some; r.value = a->data[a->len]; }
    else             { r.tag = NOVA_TAG_Option_None; r.value = (void_p)0; }
    return r;
}
static nova_bool nova_array_eq_void_p(NovaArray_void_p* a, NovaArray_void_p* b) {
    if (a->len != b->len) return 0;
    for (int64_t _i = 0; _i < a->len; _i++) { if (a->data[_i] != b->data[_i]) return 0; }
    return 1;
}

/* ---- nova_str array (cannot use macro: eq needs nova_str_eq) ---- */
#ifndef NOVA_RT_H  /* nova_str defined in nova_rt.h; skip if not included yet */
#endif
NOVA_ARRAY_DECL(nova_str)
static NovaArray_nova_str* nova_array_new_nova_str(int64_t init_cap) {
    NovaArray_nova_str* a = (NovaArray_nova_str*)nova_alloc(sizeof(NovaArray_nova_str));
    a->cap  = init_cap > 0 ? init_cap : 8;
    a->len  = 0;
    a->data = (nova_str*)nova_alloc((size_t)(a->cap) * sizeof(nova_str));
    return a;
}
static void nova_array_push_nova_str(NovaArray_nova_str* a, nova_str v) {
    if (a->len >= a->cap) {
        int64_t new_cap = a->cap * 2;
        nova_str* new_data = (nova_str*)nova_alloc((size_t)new_cap * sizeof(nova_str));
        memcpy(new_data, a->data, (size_t)(a->len) * sizeof(nova_str));
        a->data = new_data;
        a->cap  = new_cap;
    }
    a->data[a->len++] = v;
}
static NovaOpt_nova_str nova_array_get_nova_str(NovaArray_nova_str* a, int64_t i) {
    NovaOpt_nova_str r;
    if (i >= 0 && i < a->len) { r.tag = NOVA_TAG_Option_Some; r.value = a->data[i]; }
    else                       { r.tag = NOVA_TAG_Option_None; r.value = (nova_str){0,0}; }
    return r;
}
static NovaOpt_nova_str nova_array_pop_nova_str(NovaArray_nova_str* a) {
    NovaOpt_nova_str r;
    if (a->len > 0) { a->len--; r.tag = NOVA_TAG_Option_Some; r.value = a->data[a->len]; }
    else             { r.tag = NOVA_TAG_Option_None; r.value = (nova_str){0,0}; }
    return r;
}

/* ---- Option constructors for nova_int (for match compatibility) ---- */
/* Both naming conventions supported: Option and NovaOpt_nova_int */
static inline NovaOpt_nova_int nova_make_Option_Some(nova_int v) {
    NovaOpt_nova_int r; r.tag = NOVA_TAG_Option_Some; r.value = v; return r;
}
static inline NovaOpt_nova_int nova_make_Option_None(void) {
    NovaOpt_nova_int r; r.tag = NOVA_TAG_Option_None; r.value = 0; return r;
}
static inline NovaOpt_nova_int nova_make_NovaOpt_nova_int_Some(nova_int v) {
    NovaOpt_nova_int r; r.tag = NOVA_TAG_Option_Some; r.value = v; return r;
}
static inline NovaOpt_nova_int nova_make_NovaOpt_nova_int_None(void) {
    NovaOpt_nova_int r; r.tag = NOVA_TAG_Option_None; r.value = 0; return r;
}
static inline nova_bool nova_opt_eq_nova_int(NovaOpt_nova_int a, NovaOpt_nova_int b) {
    if (a.tag != b.tag) return 0;
    if (a.tag == NOVA_TAG_Option_None) return 1;
    return a.value == b.value;
}
/* Plan 70.3: nova_char Option constructors/eq mirror nova_int. */
static inline NovaOpt_nova_char nova_make_NovaOpt_nova_char_Some(nova_char v) {
    NovaOpt_nova_char r; r.tag = NOVA_TAG_Option_Some; r.value = v; return r;
}
static inline NovaOpt_nova_char nova_make_NovaOpt_nova_char_None(void) {
    NovaOpt_nova_char r; r.tag = NOVA_TAG_Option_None; r.value = 0; return r;
}
static inline nova_bool nova_opt_eq_nova_char(NovaOpt_nova_char a, NovaOpt_nova_char b) {
    if (a.tag != b.tag) return 0;
    if (a.tag == NOVA_TAG_Option_None) return 1;
    return a.value == b.value;
}
/* Plan 95.bis Ф.2: unwrap_or → Nova-body (std/prelude/core.nv).
 * is_some/is_none — Plan 95 Ф.4.2. Все три убраны. */
static inline nova_bool nova_opt_eq_nova_str(NovaOpt_nova_str a, NovaOpt_nova_str b) {
    if (a.tag != b.tag) return 0;
    if (a.tag == NOVA_TAG_Option_None) return 1;
    return nova_str_eq(a.value, b.value);
}
static inline nova_bool nova_opt_eq_nova_bool(NovaOpt_nova_bool a, NovaOpt_nova_bool b) {
    if (a.tag != b.tag) return 0;
    if (a.tag == NOVA_TAG_Option_None) return 1;
    return a.value == b.value;
}
/* Plan 70.4 Ф.4: nova_byte Option constructors + methods mirror nova_int. */
static inline NovaOpt_nova_byte nova_make_NovaOpt_nova_byte_Some(nova_byte v) {
    NovaOpt_nova_byte r; r.tag = NOVA_TAG_Option_Some; r.value = v; return r;
}
static inline NovaOpt_nova_byte nova_make_NovaOpt_nova_byte_None(void) {
    NovaOpt_nova_byte r; r.tag = NOVA_TAG_Option_None; r.value = 0; return r;
}
static inline nova_bool nova_opt_eq_nova_byte(NovaOpt_nova_byte a, NovaOpt_nova_byte b) {
    if (a.tag != b.tag) return 0;
    if (a.tag == NOVA_TAG_Option_None) return 1;
    return a.value == b.value;
}
/* Plan 95 Ф.4.2 + 95.bis Ф.2: is_some/is_none + unwrap_or → Nova-body. */
static inline nova_bool nova_opt_eq_nova_f64(NovaOpt_nova_f64 a, NovaOpt_nova_f64 b) {
    if (a.tag != b.tag) return 0;
    if (a.tag == NOVA_TAG_Option_None) return 1;
    return a.value == b.value;
}
/* D26 Option methods for nova_f64. Plan 95 Ф.4.2 + 95.bis Ф.2:
 * is_some/is_none + unwrap_or → Nova-body. */
/* Plan 70.4: nova_f32 Option constructors/eq mirror nova_f64. */
static inline NovaOpt_nova_f32 nova_make_NovaOpt_nova_f32_Some(nova_f32 v) {
    NovaOpt_nova_f32 r; r.tag = NOVA_TAG_Option_Some; r.value = v; return r;
}
static inline NovaOpt_nova_f32 nova_make_NovaOpt_nova_f32_None(void) {
    NovaOpt_nova_f32 r; r.tag = NOVA_TAG_Option_None; r.value = 0.0f; return r;
}
static inline nova_bool nova_opt_eq_nova_f32(NovaOpt_nova_f32 a, NovaOpt_nova_f32 b) {
    if (a.tag != b.tag) return 0;
    if (a.tag == NOVA_TAG_Option_None) return 1;
    return a.value == b.value;
}
/* Plan 70.4: D26 Option methods for nova_f32. Plan 95 Ф.4.2 + 95.bis
 * Ф.2: is_some/is_none + unwrap_or → Nova-body. */

/* Plan 70.4 Ф.2: sized-int Option constructors/eq/methods — one block per type. */
static inline NovaOpt_int32_t nova_make_NovaOpt_int32_t_Some(int32_t v) {
    NovaOpt_int32_t r; r.tag = NOVA_TAG_Option_Some; r.value = v; return r;
}
static inline NovaOpt_int32_t nova_make_NovaOpt_int32_t_None(void) {
    NovaOpt_int32_t r; r.tag = NOVA_TAG_Option_None; r.value = 0; return r;
}
static inline nova_bool nova_opt_eq_int32_t(NovaOpt_int32_t a, NovaOpt_int32_t b) {
    if (a.tag != b.tag) return 0;
    if (a.tag == NOVA_TAG_Option_None) return 1;
    return a.value == b.value;
}
/* Plan 95 Ф.4.2 + 95.bis Ф.2: is_some/is_none + unwrap_or → Nova-body. */

static inline NovaOpt_int16_t nova_make_NovaOpt_int16_t_Some(int16_t v) {
    NovaOpt_int16_t r; r.tag = NOVA_TAG_Option_Some; r.value = v; return r;
}
static inline NovaOpt_int16_t nova_make_NovaOpt_int16_t_None(void) {
    NovaOpt_int16_t r; r.tag = NOVA_TAG_Option_None; r.value = 0; return r;
}
static inline nova_bool nova_opt_eq_int16_t(NovaOpt_int16_t a, NovaOpt_int16_t b) {
    if (a.tag != b.tag) return 0;
    if (a.tag == NOVA_TAG_Option_None) return 1;
    return a.value == b.value;
}
/* Plan 95 Ф.4.2 + 95.bis Ф.2: is_some/is_none + unwrap_or → Nova-body. */

static inline NovaOpt_int8_t nova_make_NovaOpt_int8_t_Some(int8_t v) {
    NovaOpt_int8_t r; r.tag = NOVA_TAG_Option_Some; r.value = v; return r;
}
static inline NovaOpt_int8_t nova_make_NovaOpt_int8_t_None(void) {
    NovaOpt_int8_t r; r.tag = NOVA_TAG_Option_None; r.value = 0; return r;
}
static inline nova_bool nova_opt_eq_int8_t(NovaOpt_int8_t a, NovaOpt_int8_t b) {
    if (a.tag != b.tag) return 0;
    if (a.tag == NOVA_TAG_Option_None) return 1;
    return a.value == b.value;
}
/* Plan 95 Ф.4.2 + 95.bis Ф.2: is_some/is_none + unwrap_or → Nova-body. */

static inline NovaOpt_uint32_t nova_make_NovaOpt_uint32_t_Some(uint32_t v) {
    NovaOpt_uint32_t r; r.tag = NOVA_TAG_Option_Some; r.value = v; return r;
}
static inline NovaOpt_uint32_t nova_make_NovaOpt_uint32_t_None(void) {
    NovaOpt_uint32_t r; r.tag = NOVA_TAG_Option_None; r.value = 0; return r;
}
static inline nova_bool nova_opt_eq_uint32_t(NovaOpt_uint32_t a, NovaOpt_uint32_t b) {
    if (a.tag != b.tag) return 0;
    if (a.tag == NOVA_TAG_Option_None) return 1;
    return a.value == b.value;
}
/* Plan 95 Ф.4.2 + 95.bis Ф.2: is_some/is_none + unwrap_or → Nova-body. */

static inline NovaOpt_uint16_t nova_make_NovaOpt_uint16_t_Some(uint16_t v) {
    NovaOpt_uint16_t r; r.tag = NOVA_TAG_Option_Some; r.value = v; return r;
}
static inline NovaOpt_uint16_t nova_make_NovaOpt_uint16_t_None(void) {
    NovaOpt_uint16_t r; r.tag = NOVA_TAG_Option_None; r.value = 0; return r;
}
static inline nova_bool nova_opt_eq_uint16_t(NovaOpt_uint16_t a, NovaOpt_uint16_t b) {
    if (a.tag != b.tag) return 0;
    if (a.tag == NOVA_TAG_Option_None) return 1;
    return a.value == b.value;
}
/* Plan 95 Ф.4.2 + 95.bis Ф.2: is_some/is_none + unwrap_or → Nova-body. */

static inline NovaOpt_uint64_t nova_make_NovaOpt_uint64_t_Some(uint64_t v) {
    NovaOpt_uint64_t r; r.tag = NOVA_TAG_Option_Some; r.value = v; return r;
}
static inline NovaOpt_uint64_t nova_make_NovaOpt_uint64_t_None(void) {
    NovaOpt_uint64_t r; r.tag = NOVA_TAG_Option_None; r.value = 0; return r;
}
static inline nova_bool nova_opt_eq_uint64_t(NovaOpt_uint64_t a, NovaOpt_uint64_t b) {
    if (a.tag != b.tag) return 0;
    if (a.tag == NOVA_TAG_Option_None) return 1;
    return a.value == b.value;
}
/* Plan 95 Ф.4.2 + 95.bis Ф.2: is_some/is_none + unwrap_or → Nova-body. */

/* ---- D26 Option methods ---- (Plan 95 Ф.4.2 is_some/is_none + 95.bis
 * Ф.2 unwrap_or + or — все перенесены на Nova-body в std/prelude/core.nv,
 * dispatch через MethodRouting::DeclaredBody с тем же C-именем
 * Nova_Option_method_<m>_<T_sani>. C-redefinition collision если
 * оставить здесь.)
 *
 * Note: @unwrap() throws Fail on None — реализация в codegen через
 * Nova_Fail_fail (effects.h инклюдится после array.h в nova_rt.h);
 * codegen emits inline check + fail call. */


/* ---- D26 string search: find / rfind (codepoint-offsets, school B) ---- *
 *
 * Возвращают Option[int] с **codepoint-offset** первого/последнего
 * вхождения needle (школа B — Python/Swift). Empty needle → Some(0)
 * для find, Some(s.char_len) для rfind. needle.len в байтах > s.len
 * → None. Совпадение проверяется byte-wise (memcmp), но возвращаемая
 * позиция — codepoint-индекс начала match. Считается, что needle
 * начинается на границе UTF-8 codepoint (если нет — match не найдётся
 * на границе, и мы вернём None / следующее найденное вхождение). */
static inline NovaOpt_nova_int nova_str_find(nova_str s, nova_str needle) {
    NovaOpt_nova_int r;
    if (needle.len == 0) {
        r.tag = NOVA_TAG_Option_Some; r.value = 0; return r;
    }
    if (needle.len > s.len) {
        r.tag = NOVA_TAG_Option_None; r.value = 0; return r;
    }
    /* Walk UTF-8: i — byte offset, cp — codepoint offset.
     * Совпадение допустимо только на codepoint-границе. */
    nova_int cp = 0;
    for (size_t i = 0; i + needle.len <= s.len; ) {
        if (memcmp(s.ptr + i, needle.ptr, needle.len) == 0) {
            r.tag = NOVA_TAG_Option_Some;
            r.value = cp;
            return r;
        }
        unsigned char b = (unsigned char)s.ptr[i];
        if      (b < 0x80) i += 1;
        else if ((b & 0xE0) == 0xC0) i += 2;
        else if ((b & 0xF0) == 0xE0) i += 3;
        else if ((b & 0xF8) == 0xF0) i += 4;
        else                          i += 1;
        cp++;
    }
    r.tag = NOVA_TAG_Option_None; r.value = 0;
    return r;
}

static inline NovaOpt_nova_int nova_str_rfind(nova_str s, nova_str needle) {
    NovaOpt_nova_int r;
    /* Сначала посчитаем общее число codepoint'ов в s. */
    nova_int total_cp = 0;
    for (size_t i = 0; i < s.len; i++) {
        unsigned char c = (unsigned char)s.ptr[i];
        if ((c & 0xC0) != 0x80) total_cp++;
    }
    if (needle.len == 0) {
        r.tag = NOVA_TAG_Option_Some; r.value = total_cp; return r;
    }
    if (needle.len > s.len) {
        r.tag = NOVA_TAG_Option_None; r.value = 0; return r;
    }
    /* Идём слева направо, запоминаем последний match как codepoint-индекс. */
    nova_int last_cp = -1;
    nova_int cp = 0;
    for (size_t i = 0; i + needle.len <= s.len; ) {
        if (memcmp(s.ptr + i, needle.ptr, needle.len) == 0) {
            last_cp = cp;
        }
        unsigned char b = (unsigned char)s.ptr[i];
        if      (b < 0x80) i += 1;
        else if ((b & 0xE0) == 0xC0) i += 2;
        else if ((b & 0xF0) == 0xE0) i += 3;
        else if ((b & 0xF8) == 0xF0) i += 4;
        else                          i += 1;
        cp++;
    }
    if (last_cp < 0) { r.tag = NOVA_TAG_Option_None; r.value = 0; return r; }
    r.tag = NOVA_TAG_Option_Some; r.value = last_cp;
    return r;
}

/* ---- byte_len: длина в байтах (school B вспомогательное) ---- */
static inline nova_int nova_str_byte_len(nova_str s) {
    return (nova_int)s.len;
}

/* ---- nova_str_bytes: возвращает []byte (packed UTF-8 байты).
 * `[]byte` codegen-маппится в `NovaArray_nova_byte*` — реальный
 * uint8_t[] storage, без int64-erasure. */
static inline NovaArray_nova_byte* nova_str_bytes(nova_str s) {
    NovaArray_nova_byte* a = nova_array_new_nova_byte((int64_t)s.len);
    for (size_t i = 0; i < s.len; i++) {
        nova_array_push_nova_byte(a, (nova_byte)(unsigned char)s.ptr[i]);
    }
    return a;
}

/* ---- nova_str_split: разбивает строку по разделителю.
 * D26 spec: `fn str @split(sep str) -> Iter[str]`. Bootstrap делает
 * eager массив string-view'ов. Пустой sep — пограничный случай: возвращаем
 * массив с одной строкой (исходная). */
static inline NovaArray_nova_str* nova_str_split(nova_str s, nova_str sep) {
    NovaArray_nova_str* a = nova_array_new_nova_str(0);
    if (sep.len == 0) {
        nova_array_push_nova_str(a, s);
        return a;
    }
    size_t start = 0;
    size_t i = 0;
    while (i + sep.len <= s.len) {
        if (memcmp(s.ptr + i, sep.ptr, sep.len) == 0) {
            nova_str part = { s.ptr + start, i - start };
            nova_array_push_nova_str(a, part);
            i += sep.len;
            start = i;
        } else {
            i++;
        }
    }
    /* Tail */
    nova_str tail = { s.ptr + start, s.len - start };
    nova_array_push_nova_str(a, tail);
    return a;
}

/* ---- nova_str_chars: возвращает []char (eager массив codepoints).
 * D26 spec говорит про `Iter[char]` (lazy), bootstrap делает eager
 * массив codepoints. Каждый codepoint — uint32_t, хранится как
 * nova_int в NovaArray_nova_int*. */
static inline NovaArray_nova_int* nova_str_chars(nova_str s) {
    NovaArray_nova_int* a = nova_array_new_nova_int((int64_t)s.len);
    for (size_t i = 0; i < s.len; ) {
        unsigned char b = (unsigned char)s.ptr[i];
        nova_int cp = 0;
        size_t step = 1;
        if (b < 0x80) {
            cp = b;
            step = 1;
        } else if ((b & 0xE0) == 0xC0 && i + 1 < s.len) {
            cp = ((nova_int)(b & 0x1F) << 6)
               | ((nova_int)((unsigned char)s.ptr[i+1] & 0x3F));
            step = 2;
        } else if ((b & 0xF0) == 0xE0 && i + 2 < s.len) {
            cp = ((nova_int)(b & 0x0F) << 12)
               | ((nova_int)((unsigned char)s.ptr[i+1] & 0x3F) << 6)
               | ((nova_int)((unsigned char)s.ptr[i+2] & 0x3F));
            step = 3;
        } else if ((b & 0xF8) == 0xF0 && i + 3 < s.len) {
            cp = ((nova_int)(b & 0x07) << 18)
               | ((nova_int)((unsigned char)s.ptr[i+1] & 0x3F) << 12)
               | ((nova_int)((unsigned char)s.ptr[i+2] & 0x3F) << 6)
               | ((nova_int)((unsigned char)s.ptr[i+3] & 0x3F));
            step = 4;
        } else {
            cp = b;
            step = 1;
        }
        nova_array_push_nova_int(a, cp);
        i += step;
    }
    return a;
}

/* ---- nova_str_char_at: codepoint по codepoint-индексу.
 * Возвращает Option[char] = NovaOpt_nova_char (Plan 70.3: distinct typedef).
 * None если idx out-of-range или невалидный UTF-8. O(idx) — линейная
 * итерация по UTF-8. */
static inline NovaOpt_nova_char nova_str_char_at(nova_str s, nova_int idx) {
    NovaOpt_nova_char r;
    r.tag = NOVA_TAG_Option_None;
    r.value = 0;
    if (idx < 0) return r;
    nova_int cp_idx = 0;
    for (size_t i = 0; i < s.len; ) {
        unsigned char b = (unsigned char)s.ptr[i];
        nova_int cp = 0;
        size_t step = 1;
        if (b < 0x80) {
            cp = b; step = 1;
        } else if ((b & 0xE0) == 0xC0 && i + 1 < s.len) {
            cp = ((nova_int)(b & 0x1F) << 6)
               | ((nova_int)((unsigned char)s.ptr[i+1] & 0x3F));
            step = 2;
        } else if ((b & 0xF0) == 0xE0 && i + 2 < s.len) {
            cp = ((nova_int)(b & 0x0F) << 12)
               | ((nova_int)((unsigned char)s.ptr[i+1] & 0x3F) << 6)
               | ((nova_int)((unsigned char)s.ptr[i+2] & 0x3F));
            step = 3;
        } else if ((b & 0xF8) == 0xF0 && i + 3 < s.len) {
            cp = ((nova_int)(b & 0x07) << 18)
               | ((nova_int)((unsigned char)s.ptr[i+1] & 0x3F) << 12)
               | ((nova_int)((unsigned char)s.ptr[i+2] & 0x3F) << 6)
               | ((nova_int)((unsigned char)s.ptr[i+3] & 0x3F));
            step = 4;
        } else {
            cp = b; step = 1;
        }
        if (cp_idx == idx) {
            r.tag = NOVA_TAG_Option_Some;
            r.value = cp;
            return r;
        }
        cp_idx++;
        i += step;
    }
    return r;
}

/* ---- Built-in Result type (Ok carries nova_int, Err carries nova_str) ----
 *
 * Plan 61 followup #3: typed Err payload via err_typed_payload + tid.
 * Backward compat: legacy `Err(nova_str)` использует payload.Err._0;
 * custom `Err(T)` (T ≠ nova_str) использует err_typed_payload + tid.
 * `!!` dispatch по tid (NOVA_TID_NONE → legacy string path; иначе typed
 * throw через nova_throw_typed).
 *
 * Full mono'd NovaResult_<T>_<E> per-(T,E) struct — Plan 14/56 territory
 * (sum-type monomorphization pass). Hybrid дает equivalent semantics для
 * custom Err без полного mono refactor. */
#define NOVA_TAG_Result_Ok  0
#define NOVA_TAG_Result_Err 1

/* Plan 59 Ф.7.5 D3: канонический mono'd Result для erased (T,E) =
 * (int, str). Раньше назывался `Nova_Result` (single hardcoded
 * representation). Теперь — `NovaRes_nova_int_nova_str`, инстанс
 * семейства `NovaRes_<ok>_<err>` (per-(T,E) мономорфизация). Определён
 * руками здесь (а не lazy-generated в `__NOVARES_TYPEDEFS__`), потому
 * что runtime-заголовки (`read_buffer.h`, `string_builder.h`, `cast.h`)
 * ссылаются на него, а они включаются ДО splice-маркера.
 *
 * `Nova_Result` / `nova_make_Result_*` / `Nova_Result_method_*` —
 * back-compat алиасы на время перехода (шаг E их удалит). */
typedef struct NovaRes_nova_int_nova_str {
    int tag;
    union {
        struct { nova_int _0; } Ok;
        struct { nova_str _0; } Err;
    } payload;
    /* Plan 61 followup #3: typed Err payload (NULL для legacy string Err). */
    void*       err_typed_payload;
    NovaTypeId  err_typed_type_id;
} NovaRes_nova_int_nova_str;

#define Nova_Result NovaRes_nova_int_nova_str

static inline NovaRes_nova_int_nova_str* nova_make_NovaRes_nova_int_nova_str_Ok(nova_int v) {
    NovaRes_nova_int_nova_str* r = (NovaRes_nova_int_nova_str*)nova_alloc(sizeof(NovaRes_nova_int_nova_str));
    r->tag = NOVA_TAG_Result_Ok; r->payload.Ok._0 = v;
    r->err_typed_payload = NULL; r->err_typed_type_id = NOVA_TID_NONE;
    return r;
}
static inline NovaRes_nova_int_nova_str* nova_make_NovaRes_nova_int_nova_str_Err(nova_str v) {
    NovaRes_nova_int_nova_str* r = (NovaRes_nova_int_nova_str*)nova_alloc(sizeof(NovaRes_nova_int_nova_str));
    r->tag = NOVA_TAG_Result_Err; r->payload.Err._0 = v;
    r->err_typed_payload = NULL; r->err_typed_type_id = NOVA_TID_NONE;
    return r;
}
/* Plan 61 followup #3: typed Err constructor. payload — heap-allocated
 * copy of typed value (caller responsible — обычно codegen эмитит
 * `T* p = nova_alloc(sizeof(T)); *p = val;` inline). tid = NOVA_TID_<T>. */
static inline NovaRes_nova_int_nova_str* nova_make_NovaRes_nova_int_nova_str_Err_typed(void* payload, NovaTypeId tid) {
    NovaRes_nova_int_nova_str* r = (NovaRes_nova_int_nova_str*)nova_alloc(sizeof(NovaRes_nova_int_nova_str));
    r->tag = NOVA_TAG_Result_Err;
    r->payload.Err._0 = (nova_str){.ptr = "<typed err>", .len = 11};  /* diag fallback */
    r->err_typed_payload = payload;
    r->err_typed_type_id = tid;
    return r;
}
/* Back-compat алиасы (шаг E удалит). */
#define nova_make_Result_Ok        nova_make_NovaRes_nova_int_nova_str_Ok
#define nova_make_Result_Err       nova_make_NovaRes_nova_int_nova_str_Err
#define nova_make_Result_Err_typed nova_make_NovaRes_nova_int_nova_str_Err_typed

static inline nova_bool nova_result_eq(NovaRes_nova_int_nova_str* a, NovaRes_nova_int_nova_str* b) {
    if (a->tag != b->tag) return 0;
    if (a->tag == NOVA_TAG_Result_Ok)  return a->payload.Ok._0  == b->payload.Ok._0;
    return nova_str_eq(a->payload.Err._0, b->payload.Err._0);
}

/* ---- D26 Result methods: unwrap_or / ok ----
 * Plan 59 Ф.7.5 D3: суффикс `_nova_int_nova_str` — инстанс семейства
 * `Nova_Result_method_*_<n>`. Back-compat алиасы без суффикса ниже.
 *
 * Plan 95 Ф.5.2: `is_ok` / `is_err` УДАЛЕНЫ — перенесены на Nova-body
 * в std/prelude/core.nv; mono'd через DeclaredBody-dispatch + worklist
 * drain. C-redefinition collision (тот же C-symbol) если оставить. */
/* Plan 95.bis Ф.2: unwrap_or + ok трамплины + back-compat алиасы
 * убраны — перенесены на Nova-body в std/prelude/core.nv через
 * MethodRouting::DeclaredBody. Mono'd C-имя
 * Nova_Result_method_<m>_<n> эмитится из Nova-body; legacy
 * `Nova_Result*` callsites не существуют (Plan 59 mono'd всё).
 * is_ok/is_err — Plan 95 Ф.5.2. err — был inline emit
 * (emit_c.rs:11903+), теперь Nova-body. */

/* Plan 08 Ф.1: D73/D77 prelude конверсии (str↔numeric, char↔str, etc.).
 * Подключаем здесь — после определения nova_alloc (alloc.h) и nova_str
 * (nova_rt.h), чтобы conv.h мог их использовать. */
#include "conv.h"

/* ---- D26 prelude: Error — record для quick-and-dirty ошибок с msg ---- */
typedef struct Nova_Error {
    nova_str msg;
} Nova_Error;

static inline Nova_Error* Nova_Error_static_new(nova_str msg) {
    Nova_Error* e = (Nova_Error*)nova_alloc(sizeof(Nova_Error));
    e->msg = msg;
    return e;
}

/* ---- D26 prelude: RuntimeError — sum-тип встроенных runtime-сбоев ----
 * Бросается встроенными операциями (D65):
 *   - DivByZero               — `a / 0`
 *   - Overflow                — численное переполнение
 *   - IndexOutOfBounds {i, n} — arr[i] на out-of-range
 *   - TypeMismatch(str)       — runtime type-check провален
 *   - AssertFailed(str)       — assert(...) провален
 *   - NoHandler(str)          — эффект без handler'а
 *
 * StackOverflow и OutOfMemory не входят — это panic, не Fail (D13).
 *
 * Bootstrap: представлены как pointer-to-tag-union. Конструкторы
 * `nova_make_RuntimeError_<Variant>` создают boxed копию. */
#define NOVA_TAG_RuntimeError_DivByZero        0
#define NOVA_TAG_RuntimeError_Overflow         1
#define NOVA_TAG_RuntimeError_IndexOutOfBounds 2
#define NOVA_TAG_RuntimeError_TypeMismatch     3
#define NOVA_TAG_RuntimeError_AssertFailed     4
#define NOVA_TAG_RuntimeError_NoHandler        5

typedef struct Nova_RuntimeError {
    int tag;
    union {
        struct { int _dummy; } DivByZero;
        struct { int _dummy; } Overflow;
        struct { nova_int index; nova_int length; } IndexOutOfBounds;
        struct { nova_str _0; } TypeMismatch;
        struct { nova_str _0; } AssertFailed;
        struct { nova_str _0; } NoHandler;
    } payload;
} Nova_RuntimeError;

static inline Nova_RuntimeError* nova_make_RuntimeError_DivByZero(void) {
    Nova_RuntimeError* e = (Nova_RuntimeError*)nova_alloc(sizeof(Nova_RuntimeError));
    e->tag = NOVA_TAG_RuntimeError_DivByZero;
    return e;
}
static inline Nova_RuntimeError* nova_make_RuntimeError_Overflow(void) {
    Nova_RuntimeError* e = (Nova_RuntimeError*)nova_alloc(sizeof(Nova_RuntimeError));
    e->tag = NOVA_TAG_RuntimeError_Overflow;
    return e;
}
static inline Nova_RuntimeError* nova_make_RuntimeError_IndexOutOfBounds(nova_int idx, nova_int len) {
    Nova_RuntimeError* e = (Nova_RuntimeError*)nova_alloc(sizeof(Nova_RuntimeError));
    e->tag = NOVA_TAG_RuntimeError_IndexOutOfBounds;
    e->payload.IndexOutOfBounds.index = idx;
    e->payload.IndexOutOfBounds.length = len;
    return e;
}
static inline Nova_RuntimeError* nova_make_RuntimeError_TypeMismatch(nova_str msg) {
    Nova_RuntimeError* e = (Nova_RuntimeError*)nova_alloc(sizeof(Nova_RuntimeError));
    e->tag = NOVA_TAG_RuntimeError_TypeMismatch;
    e->payload.TypeMismatch._0 = msg;
    return e;
}
static inline Nova_RuntimeError* nova_make_RuntimeError_AssertFailed(nova_str msg) {
    Nova_RuntimeError* e = (Nova_RuntimeError*)nova_alloc(sizeof(Nova_RuntimeError));
    e->tag = NOVA_TAG_RuntimeError_AssertFailed;
    e->payload.AssertFailed._0 = msg;
    return e;
}
static inline Nova_RuntimeError* nova_make_RuntimeError_NoHandler(nova_str msg) {
    Nova_RuntimeError* e = (Nova_RuntimeError*)nova_alloc(sizeof(Nova_RuntimeError));
    e->tag = NOVA_TAG_RuntimeError_NoHandler;
    e->payload.NoHandler._0 = msg;
    return e;
}

/* Plan 95.bis Ф.2: Nova_Option_method_or_nova_str — explicit
 * specialization тоже убрана. Метод or перенесён на Nova-body в
 * std/prelude/core.nv; mono'd Nova_Option_method_or_<T> с тем же
 * C-именем эмитится из Nova-body через MethodRouting::DeclaredBody. */

/* Plan 96 Ф.1 — bounds-check для raw arr[i] (D27 §1632 drift fix).
 *
 * До Plan 96 codegen эмитил `(arr)->data[i]` без проверки границ —
 * controlled buffer overflow на запись, UB на чтение. D27 §1632 спека
 * требовала panic при OOB. Wrapper форматирует диагностику и вызывает
 * nv_panic (D13 — смерть текущего fiber'а). Сообщение формата
 * "array: index N out of bounds for length L" — паритет с Go/Rust.
 *
 * Allocation через nova_alloc — Boehm thread-safe; panic-path, cost
 * нерелевантен; буфер становится GC-mature после nv_panic (longjmp/exit).
 */
static inline void nv_panic_index_oob(nova_int idx, nova_int len) {
    char* buf = (char*)nova_alloc(96);
    int n = snprintf(buf, 96,
        "array: index %lld out of bounds for length %lld",
        (long long)idx, (long long)len);
    if (n < 0) n = 0;
    if (n > 95) n = 95;
    nv_panic((nova_str){ .ptr = buf, .len = (size_t)n });
}

/* Plan 96 Ф.4 — bounds-check для slice creation (arr[a..b]).
 * Отдельное сообщение от raw-index OOB — диапазон вместо одного индекса. */
static inline void nv_panic_slice_oob(nova_int from, nova_int to, nova_int len) {
    char* buf = (char*)nova_alloc(112);
    int n = snprintf(buf, 112,
        "array: slice [%lld..%lld] out of bounds for length %lld",
        (long long)from, (long long)to, (long long)len);
    if (n < 0) n = 0;
    if (n > 111) n = 111;
    nv_panic((nova_str){ .ptr = buf, .len = (size_t)n });
}

/* Plan 90.1 — bounds-check для insert_from(i, src) position.
 * i должен быть в [0, dst.len] (включая len — append-at-end допустим). */
static inline void nv_panic_insert_oob(nova_int i, nova_int len) {
    char* buf = (char*)nova_alloc(96);
    int n = snprintf(buf, 96,
        "insert_from: index %lld out of bounds for length %lld (valid range [0, len])",
        (long long)i, (long long)len);
    if (n < 0) n = 0;
    if (n > 95) n = 95;
    nv_panic((nova_str){ .ptr = buf, .len = (size_t)n });
}

/* Plan 90.1 — bounds-check для reserve(extra) argument.
 * extra < 0 не имеет смысла и указывает на баг в коде пользователя. */
static inline void nv_panic_negative_reserve(nova_int extra) {
    char* buf = (char*)nova_alloc(80);
    int n = snprintf(buf, 80,
        "reserve: extra must be >= 0, got %lld",
        (long long)extra);
    if (n < 0) n = 0;
    if (n > 79) n = 79;
    nv_panic((nova_str){ .ptr = buf, .len = (size_t)n });
}

#endif /* NOVA_RT_ARRAY_H */
