#ifndef NOVA_RT_ARRAY_H
#define NOVA_RT_ARRAY_H

#include "alloc.h"
#include <stdint.h>
#include <string.h>

/*
 * Generic growable array for Nova codegen.
 *
 * Each element type T gets its own concrete struct via the NOVA_ARRAY_DECL
 * macro, which emits:
 *
 *   typedef struct NovaArray_T {
 *       T*      data;
 *       int64_t len;
 *       int64_t cap;
 *   } NovaArray_T;
 *
 * Helper functions (push, get) are generated by NOVA_ARRAY_IMPL.
 *
 * Usage in generated C:
 *   NOVA_ARRAY_DECL(nova_int)
 *   NOVA_ARRAY_IMPL(nova_int)
 *
 * The codegen emits these declarations at the top of the file for each
 * element type actually used.
 *
 * nova_array_new_T(cap)   — allocate with initial capacity
 * nova_array_push_T(a, v) — append element, growing if needed
 * nova_array_get_T(a, i)  — bounds-checked access, returns Option-like tag
 */

/* ---- Option<nova_int> for array.get() ---- *
 *
 * We use a simple tagged struct rather than a full sum-type to keep
 * the array header self-contained. Generated code for `.get(i)` uses
 * this struct directly; the match arms check `.tag`.
 */

/* Tag values shared across all NovaOpt_T structs */
#define NOVA_TAG_Option_None 0
#define NOVA_TAG_Option_Some 1

/* Declare the array struct and Option<T> struct for element type T.
 * T_NAME is the C identifier used in the struct/function names (e.g. nova_int). */
#define NOVA_ARRAY_DECL(T) \
    typedef struct NovaArray_##T { \
        T*      data; \
        int64_t len; \
        int64_t cap; \
    } NovaArray_##T; \
    typedef struct NovaOpt_##T { \
        int     tag; \
        T       value; \
    } NovaOpt_##T;

/* Implement helper functions for element type T.
 * Requires nova_alloc to be available. */
#define NOVA_ARRAY_IMPL(T) \
    static NovaArray_##T* nova_array_new_##T(int64_t init_cap) { \
        NovaArray_##T* a = (NovaArray_##T*)nova_alloc(sizeof(NovaArray_##T)); \
        a->cap  = init_cap > 0 ? init_cap : 8; \
        a->len  = 0; \
        a->data = (T*)nova_alloc((size_t)(a->cap) * sizeof(T)); \
        return a; \
    } \
    static void nova_array_push_##T(NovaArray_##T* a, T v) { \
        if (a->len >= a->cap) { \
            int64_t new_cap = a->cap * 2; \
            T* new_data = (T*)nova_alloc((size_t)new_cap * sizeof(T)); \
            memcpy(new_data, a->data, (size_t)(a->len) * sizeof(T)); \
            a->data = new_data; \
            a->cap  = new_cap; \
        } \
        a->data[a->len++] = v; \
    } \
    static NovaOpt_##T nova_array_get_##T(NovaArray_##T* a, int64_t i) { \
        NovaOpt_##T r; \
        if (i >= 0 && i < a->len) { r.tag = NOVA_TAG_Option_Some; r.value = a->data[i]; } \
        else                       { r.tag = NOVA_TAG_Option_None; r.value = (T){0}; } \
        return r; \
    }

/* ---- Default instantiation for nova_int arrays ---- */
NOVA_ARRAY_DECL(nova_int)
NOVA_ARRAY_IMPL(nova_int)

#endif /* NOVA_RT_ARRAY_H */
