#ifndef NOVA_RT_ARRAY_H
#define NOVA_RT_ARRAY_H

#include "alloc.h"
#include <stdint.h>
#include <string.h>

/*
 * Generic growable array for Nova codegen.
 *
 * Each element type T gets its own concrete struct via the NOVA_ARRAY_DECL
 * macro, which emits:
 *
 *   typedef struct NovaArray_T {
 *       T*      data;
 *       int64_t len;
 *       int64_t cap;
 *   } NovaArray_T;
 *
 * Helper functions (push, get) are generated by NOVA_ARRAY_IMPL.
 *
 * Usage in generated C:
 *   NOVA_ARRAY_DECL(nova_int)
 *   NOVA_ARRAY_IMPL(nova_int)
 *
 * The codegen emits these declarations at the top of the file for each
 * element type actually used.
 *
 * nova_array_new_T(cap)   — allocate with initial capacity
 * nova_array_push_T(a, v) — append element, growing if needed
 * nova_array_get_T(a, i)  — bounds-checked access, returns Option-like tag
 */

/* ---- Option<nova_int> for array.get() ---- *
 *
 * We use a simple tagged struct rather than a full sum-type to keep
 * the array header self-contained. Generated code for `.get(i)` uses
 * this struct directly; the match arms check `.tag`.
 */

/* Tag values shared across all NovaOpt_T structs */
#define NOVA_TAG_Option_None 0
#define NOVA_TAG_Option_Some 1

/* Declare the array struct and Option<T> struct for element type T.
 * T_NAME is the C identifier used in the struct/function names (e.g. nova_int). */
#define NOVA_ARRAY_DECL(T) \
    typedef struct NovaArray_##T { \
        T*      data; \
        int64_t len; \
        int64_t cap; \
    } NovaArray_##T; \
    typedef struct NovaOpt_##T { \
        int     tag; \
        T       value; \
    } NovaOpt_##T;

/* Implement helper functions for element type T.
 * Requires nova_alloc to be available. */
#define NOVA_ARRAY_IMPL(T) \
    static NovaArray_##T* nova_array_new_##T(int64_t init_cap) { \
        NovaArray_##T* a = (NovaArray_##T*)nova_alloc(sizeof(NovaArray_##T)); \
        a->cap  = init_cap > 0 ? init_cap : 8; \
        a->len  = 0; \
        a->data = (T*)nova_alloc((size_t)(a->cap) * sizeof(T)); \
        return a; \
    } \
    static void nova_array_push_##T(NovaArray_##T* a, T v) { \
        if (a->len >= a->cap) { \
            int64_t new_cap = a->cap * 2; \
            T* new_data = (T*)nova_alloc((size_t)new_cap * sizeof(T)); \
            memcpy(new_data, a->data, (size_t)(a->len) * sizeof(T)); \
            a->data = new_data; \
            a->cap  = new_cap; \
        } \
        a->data[a->len++] = v; \
    } \
    static NovaOpt_##T nova_array_get_##T(NovaArray_##T* a, int64_t i) { \
        NovaOpt_##T r; \
        if (i >= 0 && i < a->len) { r.tag = NOVA_TAG_Option_Some; r.value = a->data[i]; } \
        else                       { r.tag = NOVA_TAG_Option_None; r.value = (T){0}; } \
        return r; \
    } \
    static NovaOpt_##T nova_array_pop_##T(NovaArray_##T* a) { \
        NovaOpt_##T r; \
        if (a->len > 0) { a->len--; r.tag = NOVA_TAG_Option_Some; r.value = a->data[a->len]; } \
        else             { r.tag = NOVA_TAG_Option_None; r.value = (T){0}; } \
        return r; \
    } \
    static nova_bool nova_array_eq_##T(NovaArray_##T* a, NovaArray_##T* b) { \
        if (a->len != b->len) return 0; \
        for (int64_t _i = 0; _i < a->len; _i++) { if (a->data[_i] != b->data[_i]) return 0; } \
        return 1; \
    }

/* ---- Default instantiations for primitive arrays.
 *
 * Каждый primitive-тип получает собственный NovaArray_T struct с реальным
 * packed `T data[]` (не int64-erasure). Это критично для byte:
 * `[]byte` хранится как `uint8_t[]`, не int64[]. Иначе 8x memory
 * overhead и неправильная FFI-семантика.
 */
NOVA_ARRAY_DECL(nova_int)
NOVA_ARRAY_IMPL(nova_int)

NOVA_ARRAY_DECL(nova_byte)
NOVA_ARRAY_IMPL(nova_byte)

NOVA_ARRAY_DECL(nova_bool)
NOVA_ARRAY_IMPL(nova_bool)

NOVA_ARRAY_DECL(nova_f64)
NOVA_ARRAY_IMPL(nova_f64)

/* ---- nova_str array (cannot use macro: eq needs nova_str_eq) ---- */
#ifndef NOVA_RT_H  /* nova_str defined in nova_rt.h; skip if not included yet */
#endif
NOVA_ARRAY_DECL(nova_str)
static NovaArray_nova_str* nova_array_new_nova_str(int64_t init_cap) {
    NovaArray_nova_str* a = (NovaArray_nova_str*)nova_alloc(sizeof(NovaArray_nova_str));
    a->cap  = init_cap > 0 ? init_cap : 8;
    a->len  = 0;
    a->data = (nova_str*)nova_alloc((size_t)(a->cap) * sizeof(nova_str));
    return a;
}
static void nova_array_push_nova_str(NovaArray_nova_str* a, nova_str v) {
    if (a->len >= a->cap) {
        int64_t new_cap = a->cap * 2;
        nova_str* new_data = (nova_str*)nova_alloc((size_t)new_cap * sizeof(nova_str));
        memcpy(new_data, a->data, (size_t)(a->len) * sizeof(nova_str));
        a->data = new_data;
        a->cap  = new_cap;
    }
    a->data[a->len++] = v;
}
static NovaOpt_nova_str nova_array_get_nova_str(NovaArray_nova_str* a, int64_t i) {
    NovaOpt_nova_str r;
    if (i >= 0 && i < a->len) { r.tag = NOVA_TAG_Option_Some; r.value = a->data[i]; }
    else                       { r.tag = NOVA_TAG_Option_None; r.value = (nova_str){0,0}; }
    return r;
}
static NovaOpt_nova_str nova_array_pop_nova_str(NovaArray_nova_str* a) {
    NovaOpt_nova_str r;
    if (a->len > 0) { a->len--; r.tag = NOVA_TAG_Option_Some; r.value = a->data[a->len]; }
    else             { r.tag = NOVA_TAG_Option_None; r.value = (nova_str){0,0}; }
    return r;
}

/* ---- Option constructors for nova_int (for match compatibility) ---- */
/* Both naming conventions supported: Option and NovaOpt_nova_int */
static inline NovaOpt_nova_int nova_make_Option_Some(nova_int v) {
    NovaOpt_nova_int r; r.tag = NOVA_TAG_Option_Some; r.value = v; return r;
}
static inline NovaOpt_nova_int nova_make_Option_None(void) {
    NovaOpt_nova_int r; r.tag = NOVA_TAG_Option_None; r.value = 0; return r;
}
static inline NovaOpt_nova_int nova_make_NovaOpt_nova_int_Some(nova_int v) {
    NovaOpt_nova_int r; r.tag = NOVA_TAG_Option_Some; r.value = v; return r;
}
static inline NovaOpt_nova_int nova_make_NovaOpt_nova_int_None(void) {
    NovaOpt_nova_int r; r.tag = NOVA_TAG_Option_None; r.value = 0; return r;
}
static inline nova_bool nova_opt_eq_nova_int(NovaOpt_nova_int a, NovaOpt_nova_int b) {
    if (a.tag != b.tag) return 0;
    if (a.tag == NOVA_TAG_Option_None) return 1;
    return a.value == b.value;
}

/* ---- D26 Option methods: is_some / is_none / unwrap_or ---- */
static inline nova_bool Nova_Option_method_is_some_nova_int(NovaOpt_nova_int o) {
    return o.tag == NOVA_TAG_Option_Some;
}
static inline nova_bool Nova_Option_method_is_none_nova_int(NovaOpt_nova_int o) {
    return o.tag == NOVA_TAG_Option_None;
}
static inline nova_int Nova_Option_method_unwrap_or_nova_int(NovaOpt_nova_int o, nova_int default_v) {
    return o.tag == NOVA_TAG_Option_Some ? o.value : default_v;
}
/* nova_str-specialized variants — avoid name clash; codegen dispatches by elem type */
static inline nova_bool Nova_Option_method_is_some_nova_str(NovaOpt_nova_str o) {
    return o.tag == NOVA_TAG_Option_Some;
}
static inline nova_bool Nova_Option_method_is_none_nova_str(NovaOpt_nova_str o) {
    return o.tag == NOVA_TAG_Option_None;
}
static inline nova_str Nova_Option_method_unwrap_or_nova_str(NovaOpt_nova_str o, nova_str default_v) {
    return o.tag == NOVA_TAG_Option_Some ? o.value : default_v;
}
/* Note: @unwrap() throws Fail on None — реализация в codegen через
 * Nova_Fail_fail (effects.h инклюдится после array.h в nova_rt.h);
 * codegen emits inline check + fail call. */

/* ---- D26 string search: find / rfind (codepoint-offsets, school B) ---- *
 *
 * Возвращают Option[int] с **codepoint-offset** первого/последнего
 * вхождения needle (школа B — Python/Swift). Empty needle → Some(0)
 * для find, Some(s.char_len) для rfind. needle.len в байтах > s.len
 * → None. Совпадение проверяется byte-wise (memcmp), но возвращаемая
 * позиция — codepoint-индекс начала match. Считается, что needle
 * начинается на границе UTF-8 codepoint (если нет — match не найдётся
 * на границе, и мы вернём None / следующее найденное вхождение). */
static inline NovaOpt_nova_int nova_str_find(nova_str s, nova_str needle) {
    NovaOpt_nova_int r;
    if (needle.len == 0) {
        r.tag = NOVA_TAG_Option_Some; r.value = 0; return r;
    }
    if (needle.len > s.len) {
        r.tag = NOVA_TAG_Option_None; r.value = 0; return r;
    }
    /* Walk UTF-8: i — byte offset, cp — codepoint offset.
     * Совпадение допустимо только на codepoint-границе. */
    nova_int cp = 0;
    for (size_t i = 0; i + needle.len <= s.len; ) {
        if (memcmp(s.ptr + i, needle.ptr, needle.len) == 0) {
            r.tag = NOVA_TAG_Option_Some;
            r.value = cp;
            return r;
        }
        unsigned char b = (unsigned char)s.ptr[i];
        if      (b < 0x80) i += 1;
        else if ((b & 0xE0) == 0xC0) i += 2;
        else if ((b & 0xF0) == 0xE0) i += 3;
        else if ((b & 0xF8) == 0xF0) i += 4;
        else                          i += 1;
        cp++;
    }
    r.tag = NOVA_TAG_Option_None; r.value = 0;
    return r;
}

static inline NovaOpt_nova_int nova_str_rfind(nova_str s, nova_str needle) {
    NovaOpt_nova_int r;
    /* Сначала посчитаем общее число codepoint'ов в s. */
    nova_int total_cp = 0;
    for (size_t i = 0; i < s.len; i++) {
        unsigned char c = (unsigned char)s.ptr[i];
        if ((c & 0xC0) != 0x80) total_cp++;
    }
    if (needle.len == 0) {
        r.tag = NOVA_TAG_Option_Some; r.value = total_cp; return r;
    }
    if (needle.len > s.len) {
        r.tag = NOVA_TAG_Option_None; r.value = 0; return r;
    }
    /* Идём слева направо, запоминаем последний match как codepoint-индекс. */
    nova_int last_cp = -1;
    nova_int cp = 0;
    for (size_t i = 0; i + needle.len <= s.len; ) {
        if (memcmp(s.ptr + i, needle.ptr, needle.len) == 0) {
            last_cp = cp;
        }
        unsigned char b = (unsigned char)s.ptr[i];
        if      (b < 0x80) i += 1;
        else if ((b & 0xE0) == 0xC0) i += 2;
        else if ((b & 0xF0) == 0xE0) i += 3;
        else if ((b & 0xF8) == 0xF0) i += 4;
        else                          i += 1;
        cp++;
    }
    if (last_cp < 0) { r.tag = NOVA_TAG_Option_None; r.value = 0; return r; }
    r.tag = NOVA_TAG_Option_Some; r.value = last_cp;
    return r;
}

/* ---- byte_len: длина в байтах (school B вспомогательное) ---- */
static inline nova_int nova_str_byte_len(nova_str s) {
    return (nova_int)s.len;
}

/* ---- nova_str_bytes: возвращает []byte (packed UTF-8 байты).
 * `[]byte` codegen-маппится в `NovaArray_nova_byte*` — реальный
 * uint8_t[] storage, без int64-erasure. */
static inline NovaArray_nova_byte* nova_str_bytes(nova_str s) {
    NovaArray_nova_byte* a = nova_array_new_nova_byte((int64_t)s.len);
    for (size_t i = 0; i < s.len; i++) {
        nova_array_push_nova_byte(a, (nova_byte)(unsigned char)s.ptr[i]);
    }
    return a;
}

/* ---- nova_str_split: разбивает строку по разделителю.
 * D26 spec: `fn str @split(sep str) -> Iter[str]`. Bootstrap делает
 * eager массив string-view'ов. Пустой sep — пограничный случай: возвращаем
 * массив с одной строкой (исходная). */
static inline NovaArray_nova_str* nova_str_split(nova_str s, nova_str sep) {
    NovaArray_nova_str* a = nova_array_new_nova_str(0);
    if (sep.len == 0) {
        nova_array_push_nova_str(a, s);
        return a;
    }
    size_t start = 0;
    size_t i = 0;
    while (i + sep.len <= s.len) {
        if (memcmp(s.ptr + i, sep.ptr, sep.len) == 0) {
            nova_str part = { s.ptr + start, i - start };
            nova_array_push_nova_str(a, part);
            i += sep.len;
            start = i;
        } else {
            i++;
        }
    }
    /* Tail */
    nova_str tail = { s.ptr + start, s.len - start };
    nova_array_push_nova_str(a, tail);
    return a;
}

/* ---- nova_str_chars: возвращает []char (eager массив codepoints).
 * D26 spec говорит про `Iter[char]` (lazy), bootstrap делает eager
 * массив codepoints. Каждый codepoint — uint32_t, хранится как
 * nova_int в NovaArray_nova_int*. */
static inline NovaArray_nova_int* nova_str_chars(nova_str s) {
    NovaArray_nova_int* a = nova_array_new_nova_int((int64_t)s.len);
    for (size_t i = 0; i < s.len; ) {
        unsigned char b = (unsigned char)s.ptr[i];
        nova_int cp = 0;
        size_t step = 1;
        if (b < 0x80) {
            cp = b;
            step = 1;
        } else if ((b & 0xE0) == 0xC0 && i + 1 < s.len) {
            cp = ((nova_int)(b & 0x1F) << 6)
               | ((nova_int)((unsigned char)s.ptr[i+1] & 0x3F));
            step = 2;
        } else if ((b & 0xF0) == 0xE0 && i + 2 < s.len) {
            cp = ((nova_int)(b & 0x0F) << 12)
               | ((nova_int)((unsigned char)s.ptr[i+1] & 0x3F) << 6)
               | ((nova_int)((unsigned char)s.ptr[i+2] & 0x3F));
            step = 3;
        } else if ((b & 0xF8) == 0xF0 && i + 3 < s.len) {
            cp = ((nova_int)(b & 0x07) << 18)
               | ((nova_int)((unsigned char)s.ptr[i+1] & 0x3F) << 12)
               | ((nova_int)((unsigned char)s.ptr[i+2] & 0x3F) << 6)
               | ((nova_int)((unsigned char)s.ptr[i+3] & 0x3F));
            step = 4;
        } else {
            cp = b;
            step = 1;
        }
        nova_array_push_nova_int(a, cp);
        i += step;
    }
    return a;
}

/* ---- nova_str_char_at: codepoint по codepoint-индексу.
 * Возвращает Option[char] = NovaOpt_nova_int. None если idx out-of-range
 * или невалидный UTF-8. O(idx) — линейная итерация по UTF-8. */
static inline NovaOpt_nova_int nova_str_char_at(nova_str s, nova_int idx) {
    NovaOpt_nova_int r;
    r.tag = NOVA_TAG_Option_None;
    r.value = 0;
    if (idx < 0) return r;
    nova_int cp_idx = 0;
    for (size_t i = 0; i < s.len; ) {
        unsigned char b = (unsigned char)s.ptr[i];
        nova_int cp = 0;
        size_t step = 1;
        if (b < 0x80) {
            cp = b; step = 1;
        } else if ((b & 0xE0) == 0xC0 && i + 1 < s.len) {
            cp = ((nova_int)(b & 0x1F) << 6)
               | ((nova_int)((unsigned char)s.ptr[i+1] & 0x3F));
            step = 2;
        } else if ((b & 0xF0) == 0xE0 && i + 2 < s.len) {
            cp = ((nova_int)(b & 0x0F) << 12)
               | ((nova_int)((unsigned char)s.ptr[i+1] & 0x3F) << 6)
               | ((nova_int)((unsigned char)s.ptr[i+2] & 0x3F));
            step = 3;
        } else if ((b & 0xF8) == 0xF0 && i + 3 < s.len) {
            cp = ((nova_int)(b & 0x07) << 18)
               | ((nova_int)((unsigned char)s.ptr[i+1] & 0x3F) << 12)
               | ((nova_int)((unsigned char)s.ptr[i+2] & 0x3F) << 6)
               | ((nova_int)((unsigned char)s.ptr[i+3] & 0x3F));
            step = 4;
        } else {
            cp = b; step = 1;
        }
        if (cp_idx == idx) {
            r.tag = NOVA_TAG_Option_Some;
            r.value = cp;
            return r;
        }
        cp_idx++;
        i += step;
    }
    return r;
}

/* ---- Built-in Result type (Ok carries nova_int, Err carries nova_str) ---- */
#define NOVA_TAG_Result_Ok  0
#define NOVA_TAG_Result_Err 1

typedef struct Nova_Result {
    int tag;
    union {
        struct { nova_int _0; } Ok;
        struct { nova_str _0; } Err;
    } payload;
} Nova_Result;

static inline Nova_Result* nova_make_Result_Ok(nova_int v) {
    Nova_Result* r = (Nova_Result*)nova_alloc(sizeof(Nova_Result));
    r->tag = NOVA_TAG_Result_Ok; r->payload.Ok._0 = v; return r;
}
static inline Nova_Result* nova_make_Result_Err(nova_str v) {
    Nova_Result* r = (Nova_Result*)nova_alloc(sizeof(Nova_Result));
    r->tag = NOVA_TAG_Result_Err; r->payload.Err._0 = v; return r;
}
static inline nova_bool nova_result_eq(Nova_Result* a, Nova_Result* b) {
    if (a->tag != b->tag) return 0;
    if (a->tag == NOVA_TAG_Result_Ok)  return a->payload.Ok._0  == b->payload.Ok._0;
    return nova_str_eq(a->payload.Err._0, b->payload.Err._0);
}

/* ---- D26 Result methods: is_ok / is_err / unwrap_or / ok ---- */
static inline nova_bool Nova_Result_method_is_ok(Nova_Result* r) {
    return r->tag == NOVA_TAG_Result_Ok;
}
static inline nova_bool Nova_Result_method_is_err(Nova_Result* r) {
    return r->tag == NOVA_TAG_Result_Err;
}
static inline nova_int Nova_Result_method_unwrap_or(Nova_Result* r, nova_int default_v) {
    return r->tag == NOVA_TAG_Result_Ok ? r->payload.Ok._0 : default_v;
}
static inline NovaOpt_nova_int Nova_Result_method_ok(Nova_Result* r) {
    NovaOpt_nova_int o;
    if (r->tag == NOVA_TAG_Result_Ok) {
        o.tag = NOVA_TAG_Option_Some; o.value = r->payload.Ok._0;
    } else {
        o.tag = NOVA_TAG_Option_None; o.value = 0;
    }
    return o;
}

#endif /* NOVA_RT_ARRAY_H */
