#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""scripts/tools/gen-pow5-table.py -- the 128-bit powers-of-five table of the
float parser (std/src/runtime/float_parse/pow5_table.nv): re-derive it with exact
integers and compare bit for bit, or write it out.

Plan: docs/plans/283-float-parse-own-rounding.md, phase 1. The gate calls the
check through scripts/guards/check-pow5-table.sh (tier loop: text only).

WHY A SCRIPT OWNS THE TABLE. 651 rows of two 64-bit words are 1302 hex
literals. One wrong digit gives a float parser that is correct on every input
except the ones whose decimal exponent lands on that row -- and no finite
differential corpus is guaranteed to touch that row. So the table is DATA THE
SCRIPT OWNS: it writes the .nv file, and the gate re-derives every word from
5**q on every run and refuses a single-bit difference, naming the row (q) and
the half (hi / lo) that differs.

WHAT IS COMPUTED -- the donor's algorithm (Rust src/etc/dec2flt_table.py,
itself Lemire's fast_float script/table_generation.py), with Python integers:
  * q in [SMALLEST_Q, LARGEST_Q] = [-342, 308]. -342 is the smallest decimal
    exponent at which a 64-bit significand can still reach the smallest
    subnormal (ceil(log10(5e-324) - log10(2**64 - 1))), 308 the decade of the
    largest finite f64 (floor(log10(1.7976931348623157e308)));
  * q >= 0: 5**q shifted so that its top bit is bit 127, truncated to 128 bits;
  * -27 <= q < 0: floor(2**(z + 127) / 5**-q) + 1 with z the bit length of
    5**-q -- the 128-bit reciprocal rounded UP, which is what makes the
    round-to-even check in the Lemire step exact for these q;
  * q < -27: the same reciprocal computed at 2z + 128 bits and truncated to
    128 -- exactness is not needed there (Lemire, section 9.1).
  hi = c >> 64, lo = c & (2**64 - 1).

USAGE (ROOT defaults to the repository that holds this script):
  python scripts/tools/gen-pow5-table.py --check [ROOT]
      default; exit 0 with the row count on a bit-exact match, exit 1 naming
      every differing row, exit 2 when the table file is missing or unparseable
  python scripts/tools/gen-pow5-table.py --write [ROOT]
      (re)write std/src/runtime/float_parse/pow5_table.nv
  python scripts/tools/gen-pow5-table.py --against-rust PATH/table.rs
      development aid: compare the generator with the donor's table.rs pair by
      pair (the donor file is not in this tree; fetch it at the pinned commit)
Output is ASCII and LF regardless of platform.
"""
from __future__ import print_function

import io
import os
import re
import sys

sys.stdout.reconfigure(encoding="utf-8", errors="replace", newline="\n")
sys.stderr.reconfigure(encoding="utf-8", errors="replace", newline="\n")

NAME = "gen-pow5-table"
TABLE_REL = os.path.join("std", "src", "runtime", "float_parse", "pow5_table.nv")

SMALLEST_Q = -342
LARGEST_Q = 308
ROWS = LARGEST_Q - SMALLEST_Q + 1  # 651

MASK64 = (1 << 64) - 1


def bit_length_pow5(power5):
    """Smallest z with 2**z >= power5 (the donor's `while (1 << z) < power5`)."""
    z = 0
    while (1 << z) < power5:
        z += 1
    return z


def compute_rows():
    """Return [(q, hi, lo)] for q in [SMALLEST_Q, LARGEST_Q], donor algorithm."""
    rows = []
    for q in range(SMALLEST_Q, 0):
        power5 = 5 ** (-q)
        z = bit_length_pow5(power5)
        if q >= -27:
            b = z + 127
            c = 2 ** b // power5 + 1
        else:
            b = 2 * z + 2 * 64
            c = 2 ** b // power5 + 1
            while c >= (1 << 128):
                c //= 2
        rows.append((q, c >> 64, c & MASK64))
    for q in range(0, LARGEST_Q + 1):
        power5 = 5 ** q
        while power5 < (1 << 127):
            power5 *= 2
        while power5 >= (1 << 128):
            power5 //= 2
        rows.append((q, power5 >> 64, power5 & MASK64))
    assert len(rows) == ROWS
    return rows


HEADER = """\
// AUTO-GENERATED by `scripts/tools/gen-pow5-table.py`. DO NOT EDIT BY HAND.
// Regenerate: python scripts/tools/gen-pow5-table.py --write
// Verify:     python scripts/tools/gen-pow5-table.py --check   (gate: check-pow5-table)
//
// Co-equal file of module `runtime.string` (folder = one module).
// Role: data for the Eisel-Lemire step of `str @to_f64()`: 5^q for every q in
// [{smallest}, {largest}] as a 128-bit significand -- truncated for q >= 0, rounded up
// for q < 0 -- split into two u64 halves. Row i holds q = i + POW5_SMALLEST_Q.
//
// Port of Rust `library/core/src/num/imp/dec2flt/table.rs` (MIT, see
// THIRD_PARTY/rust-LICENSE and THIRD_PARTY/README.md). The values are RE-DERIVED
// from 5^q by the generator, not copied, and the gate re-derives them again on
// every run; the generator was checked pair by pair against the donor's table.

#no_prelude
module runtime.string

// Decimal exponent of row 0 and of the last row; the row count is their span.
const POW5_SMALLEST_Q = {smallest}
const POW5_LARGEST_Q = {largest}
const POW5_ROWS = {rows}
"""


def render_nv(rows):
    out = io.StringIO()
    out.write(HEADER.format(smallest=SMALLEST_Q, largest=LARGEST_Q, rows=ROWS))
    out.write("\n// Upper 64 bits of the 128-bit 5^q; row i <-> q = i + POW5_SMALLEST_Q.\n")
    out.write("// `[%d]u64` and not `[]u64`: the length belongs to the type, so the row count\n" % ROWS)
    out.write("// is stated by the declaration itself and this script checks it against the exact\n")
    out.write("// recomputation. The `[]u64` spelling was a workaround for registry 221.1 #998 and\n")
    out.write("// #1003, both fixed 2026-09-07. The generator writes the type.\n")
    out.write("const POW5_HI [%d]u64 = [\n" % ROWS)
    for q, hi, _lo in rows:
        out.write("    0x%016X, // 5^%d\n" % (hi, q))
    out.write("]\n")
    out.write("\n// Lower 64 bits of the 128-bit 5^q, same rows.\n")
    out.write("const POW5_LO [%d]u64 = [\n" % ROWS)
    for q, _hi, lo in rows:
        out.write("    0x%016X, // 5^%d\n" % (lo, q))
    out.write("]\n")
    return out.getvalue()


ROW_RE = re.compile(r"^\s*0x([0-9A-Fa-f]{1,16})\s*,\s*//\s*5\^(-?\d+)\s*$")
CONST_RE = re.compile(r"^const (POW5_SMALLEST_Q|POW5_LARGEST_Q|POW5_ROWS) = (-?\d+)\s*$")
# Both the DECLARED length and the number of rows found are checked. They are independent:
# a lost row makes the table disagree with its own declaration, and a declaration edited by
# hand disagrees with the recomputation. The `[]u64` spelling could state neither.
ARRAY_RE = re.compile(r"^const (POW5_HI|POW5_LO) \[(\d+)\]u64 = \[\s*$")


class TableFormatError(Exception):
    pass


def parse_nv(text):
    """Return (consts, {'POW5_HI': [(q, word)], 'POW5_LO': [(q, word)]}).

    `consts` also carries DECL_POW5_HI / DECL_POW5_LO -- the length written in the
    declaration, which `check` compares against the recomputed row count.
    """
    consts = {}
    arrays = {}
    current = None
    for lineno, raw in enumerate(text.splitlines(), 1):
        line = raw.rstrip("\r")
        m = CONST_RE.match(line)
        if m:
            consts[m.group(1)] = int(m.group(2))
            continue
        m = ARRAY_RE.match(line)
        if m:
            current = m.group(1)
            arrays[current] = []
            consts["DECL_" + current] = int(m.group(2))
            continue
        if current is not None:
            if line.strip() == "]":
                current = None
                continue
            m = ROW_RE.match(line)
            if not m:
                raise TableFormatError("line %d: not a table row: %r" % (lineno, line))
            arrays[current].append((int(m.group(2)), int(m.group(1), 16)))
    for key in ("POW5_HI", "POW5_LO"):
        if key not in arrays:
            raise TableFormatError("array %s not found" % key)
    for key in ("POW5_SMALLEST_Q", "POW5_LARGEST_Q", "POW5_ROWS"):
        if key not in consts:
            raise TableFormatError("constant %s not found" % key)
    return consts, arrays


def check(root):
    path = os.path.join(root, TABLE_REL)
    if not os.path.isfile(path):
        print("%s: FAIL -- table file missing: %s (nothing to judge is RED, not zero)" % (NAME, path))
        return 2
    with io.open(path, "r", encoding="utf-8") as f:
        text = f.read()
    try:
        consts, arrays = parse_nv(text)
    except TableFormatError as e:
        print("%s: FAIL -- %s does not parse: %s" % (NAME, TABLE_REL, e))
        return 2

    expected = compute_rows()
    problems = 0
    for key, want in (("POW5_SMALLEST_Q", SMALLEST_Q), ("POW5_LARGEST_Q", LARGEST_Q), ("POW5_ROWS", ROWS)):
        if consts[key] != want:
            print("%s: MISMATCH %s: file=%d expected=%d" % (NAME, key, consts[key], want))
            problems += 1
    for key, idx in (("POW5_HI", 1), ("POW5_LO", 2)):
        got = arrays[key]
        if consts.get("DECL_" + key) != ROWS:
            print("%s: MISMATCH %s declared length: file=%s expected=%d" % (NAME, key, consts.get("DECL_" + key), ROWS))
            problems += 1
        if len(got) != ROWS:
            print("%s: MISMATCH %s row count: file=%d expected=%d" % (NAME, key, len(got), ROWS))
            problems += 1
        half = "hi" if idx == 1 else "lo"
        for i, row in enumerate(expected):
            if i >= len(got):
                break
            q_file, word_file = got[i]
            if q_file != row[0]:
                print("%s: MISMATCH %s row %d: comment says 5^%d, expected 5^%d" % (NAME, key, i, q_file, row[0]))
                problems += 1
                continue
            if word_file != row[idx]:
                print("%s: MISMATCH q=%d %s: file=0x%016X expected=0x%016X" % (NAME, row[0], half, word_file, row[idx]))
                problems += 1
    if problems:
        print("%s: FAIL -- %d difference(s) against the exact recomputation; regenerate with --write" % (NAME, problems))
        return 1
    print("%s ok: %d/%d rows match the exact recomputation (hi and lo), both declared [%d]u64" % (NAME, ROWS, ROWS, ROWS))
    return 0


def write(root):
    path = os.path.join(root, TABLE_REL)
    text = render_nv(compute_rows())
    os.makedirs(os.path.dirname(path), exist_ok=True)
    with io.open(path, "w", encoding="ascii", newline="\n") as f:
        f.write(text)
    print("%s: wrote %s (%d rows)" % (NAME, TABLE_REL, ROWS))
    return 0


RUST_PAIR_RE = re.compile(r"^\s*\(0x([0-9a-fA-F]+),\s*0x([0-9a-fA-F]+)\),\s*//\s*5\^(-?\d+)\s*$")


def against_rust(path):
    if not os.path.isfile(path):
        print("%s: no such file: %s" % (NAME, path))
        return 2
    pairs = []
    with io.open(path, "r", encoding="utf-8") as f:
        for line in f:
            m = RUST_PAIR_RE.match(line)
            if m:
                pairs.append((int(m.group(3)), int(m.group(1), 16), int(m.group(2), 16)))
    ours = compute_rows()
    if len(pairs) != len(ours):
        print("%s: donor has %d pairs, generator %d" % (NAME, len(pairs), len(ours)))
        return 1
    problems = 0
    for (q_r, hi_r, lo_r), (q_o, hi_o, lo_o) in zip(pairs, ours):
        if (q_r, hi_r, lo_r) != (q_o, hi_o, lo_o):
            print("%s: DIFF q=%d/%d donor=(0x%016X, 0x%016X) ours=(0x%016X, 0x%016X)"
                  % (NAME, q_r, q_o, hi_r, lo_r, hi_o, lo_o))
            problems += 1
    if problems:
        print("%s: FAIL -- %d pair(s) differ from the donor table" % (NAME, problems))
        return 1
    print("%s ok: generator matches the donor table.rs pair by pair (%d/%d)" % (NAME, len(pairs), len(pairs)))
    return 0


def default_root():
    here = os.path.dirname(os.path.abspath(__file__))
    return os.path.abspath(os.path.join(here, "..", ".."))


def main(argv):
    args = list(argv)
    mode = "--check"
    if args and args[0].startswith("--"):
        mode = args.pop(0)
    if mode == "--against-rust":
        if len(args) != 1:
            print(__doc__)
            return 2
        return against_rust(args[0])
    root = args[0] if args else default_root()
    if mode == "--check":
        return check(root)
    if mode == "--write":
        return write(root)
    print(__doc__)
    return 2


if __name__ == "__main__":
    sys.exit(main(sys.argv[1:]))
