/* Generated by nova-codegen. Do not edit. */
#include "nova_rt/nova_rt.h"

typedef struct { nova_int f0; } _NovaTuple1;
typedef struct { nova_int f0; nova_int f1; } _NovaTuple2;
typedef struct { nova_int f0; nova_int f1; nova_int f2; } _NovaTuple3;
typedef struct { nova_int f0; nova_int f1; nova_int f2; nova_int f3; } _NovaTuple4;
typedef struct { nova_int f0; nova_int f1; nova_int f2; nova_int f3; nova_int f4; } _NovaTuple5;
typedef struct { nova_int f0; nova_int f1; nova_int f2; nova_int f3; nova_int f4; nova_int f5; } _NovaTuple6;
typedef struct { nova_int f0; nova_int f1; nova_int f2; nova_int f3; nova_int f4; nova_int f5; nova_int f6; } _NovaTuple7;
typedef struct { nova_int f0; nova_int f1; nova_int f2; nova_int f3; nova_int f4; nova_int f5; nova_int f6; nova_int f7; } _NovaTuple8;

typedef struct Nova_BloomFilter Nova_BloomFilter;
struct Nova_BloomFilter {
    nova_int bits_size;
    nova_int num_hashes;
    NovaArray_nova_byte* bits;
};

static Nova_BloomFilter* Nova_BloomFilter_static_new(nova_int bits_size, nova_int num_hashes);
static Nova_BloomFilter* Nova_BloomFilter_static_optimal(nova_int expected_n, nova_f64 false_pos_rate);
static nova_unit Nova_BloomFilter_method_insert(Nova_BloomFilter* nova_self, nova_str s);
static nova_bool Nova_BloomFilter_method_contains(Nova_BloomFilter* nova_self, nova_str s);
static nova_unit Nova_BloomFilter_method_set_bit(Nova_BloomFilter* nova_self, nova_int idx);
static nova_bool Nova_BloomFilter_method_get_bit(Nova_BloomFilter* nova_self, nova_int idx);
static uint64_t nova_fn_hash1(nova_str s);
static uint64_t nova_fn_hash2(nova_str s);
static nova_unit nova_test_no_false_negatives_0(void);
static nova_unit nova_test_empty_filter______________________1(void);
static nova_unit nova_test_optimal_sizing_2(void);
static nova_unit nova_test_false_positive_rate________________small_set_3(void);

static Nova_BloomFilter* Nova_BloomFilter_static_new(nova_int bits_size, nova_int num_hashes) {
    /* SRC: let byte_size = (bits_size + 7) / 8 */
    nova_int byte_size = ((bits_size + ((nova_int)7LL)) / ((nova_int)8LL));
    /* SRC: let mut bits []byte = [] */
    NovaArray_nova_int* _nv_tmp_0 = nova_array_new_nova_int(8);
    NovaArray_nova_byte* bits = _nv_tmp_0;
    /* SRC: let mut i = 0 */
    nova_int i = ((nova_int)0LL);
    /* SRC: while i < byte_size { bits.push(0); i += 1 } */
    nova_unit _nv_while_1;
    while ((i < byte_size)) {
        /* SRC: bits.push(0) */
        nova_array_push_nova_byte(bits, ((nova_int)0LL));
        NOVA_UNIT;
        /* SRC: i += 1 */
        i += ((nova_int)1LL);
    }
    _nv_while_1 = NOVA_UNIT;
    _nv_while_1;
    /* SRC: { */
    Nova_BloomFilter* _nv_tmp_2 = (Nova_BloomFilter*)nova_alloc(sizeof(Nova_BloomFilter));
    _nv_tmp_2->bits_size = bits_size;
    _nv_tmp_2->num_hashes = num_hashes;
    _nv_tmp_2->bits = bits;
    return _nv_tmp_2;
}

static Nova_BloomFilter* Nova_BloomFilter_static_optimal(nova_int expected_n, nova_f64 false_pos_rate) {
    /* SRC: let n = expected_n as f64 */
    nova_int n = expected_n;
    /* SRC: let ln2 = 0.6931471805599453 */
    nova_f64 ln2 = ((nova_f64)0.6931471805599453);
    /* SRC: let m = (-n * false_pos_rate.ln() / (ln2 * ln2)).ceil() as int */
    nova_int m = ceil((((-n) * log(false_pos_rate)) / (ln2 * ln2)));
    /* SRC: let k = ((m as f64 / n) * ln2).ceil() as int */
    nova_int k = ceil(((m / n) * ln2));
    /* SRC: let k_safe = if k < 1 { 1 } */
    nova_int _nv_if_3;
    if ((k < ((nova_int)1LL))) {
        _nv_if_3 = (nova_int)(((nova_int)1LL));
    } else {
        _nv_if_3 = (nova_int)(k);
    }
    nova_int k_safe = _nv_if_3;
    /* SRC: BloomFilter.new(m, k_safe) */
    return Nova_BloomFilter_static_new(m, k_safe);
}

static nova_unit Nova_BloomFilter_method_insert(Nova_BloomFilter* nova_self, nova_str s) {
    /* SRC: let h1 = hash1(s) */
    uint64_t h1 = nova_fn_hash1(s);
    /* SRC: let h2 = hash2(s) */
    uint64_t h2 = nova_fn_hash2(s);
    /* SRC: let mut i = 0 */
    nova_int i = ((nova_int)0LL);
    /* SRC: while i < @num_hashes { */
    nova_unit _nv_while_4;
    while ((i < (nova_self->num_hashes))) {
        /* SRC: let bit_idx = ((h1 + (i as u64) * h2) as int) % @bits_size */
        nova_int bit_idx = ((h1 + (i * h2)) % (nova_self->bits_size));
        /* SRC: let safe_idx = if bit_idx < 0 { bit_idx + @bits_size } */
        nova_int _nv_if_5;
        if ((bit_idx < ((nova_int)0LL))) {
            _nv_if_5 = (nova_int)((bit_idx + (nova_self->bits_size)));
        } else {
            _nv_if_5 = (nova_int)(bit_idx);
        }
        nova_int safe_idx = _nv_if_5;
        /* SRC: @set_bit(safe_idx) */
        Nova_BloomFilter_method_set_bit(nova_self, safe_idx);
        /* SRC: i += 1 */
        i += ((nova_int)1LL);
    }
    _nv_while_4 = NOVA_UNIT;
    _nv_while_4;
    return NOVA_UNIT;
}

static nova_bool Nova_BloomFilter_method_contains(Nova_BloomFilter* nova_self, nova_str s) {
    /* SRC: let h1 = hash1(s) */
    uint64_t h1 = nova_fn_hash1(s);
    /* SRC: let h2 = hash2(s) */
    uint64_t h2 = nova_fn_hash2(s);
    /* SRC: let mut i = 0 */
    nova_int i = ((nova_int)0LL);
    /* SRC: while i < @num_hashes { */
    nova_unit _nv_while_6;
    while ((i < (nova_self->num_hashes))) {
        /* SRC: let bit_idx = ((h1 + (i as u64) * h2) as int) % @bits_size */
        nova_int bit_idx = ((h1 + (i * h2)) % (nova_self->bits_size));
        /* SRC: let safe_idx = if bit_idx < 0 { bit_idx + @bits_size } */
        nova_int _nv_if_7;
        if ((bit_idx < ((nova_int)0LL))) {
            _nv_if_7 = (nova_int)((bit_idx + (nova_self->bits_size)));
        } else {
            _nv_if_7 = (nova_int)(bit_idx);
        }
        nova_int safe_idx = _nv_if_7;
        /* SRC: if !@get_bit(safe_idx) { return false } */
        nova_unit _nv_if_8;
        if ((!Nova_BloomFilter_method_get_bit(nova_self, safe_idx))) {
            /* SRC: return false */
            return false;
            _nv_if_8 = NOVA_UNIT;
        }
        _nv_if_8;
        /* SRC: i += 1 */
        i += ((nova_int)1LL);
    }
    _nv_while_6 = NOVA_UNIT;
    _nv_while_6;
    /* SRC: true */
    return true;
}

static nova_unit Nova_BloomFilter_method_set_bit(Nova_BloomFilter* nova_self, nova_int idx) {
    /* SRC: let byte_idx = idx / 8 */
    nova_int byte_idx = (idx / ((nova_int)8LL));
    /* SRC: let bit_in_byte = idx % 8 */
    nova_int bit_in_byte = (idx % ((nova_int)8LL));
    /* SRC: let mask = (1 << bit_in_byte) as byte */
    nova_int mask = (((nova_int)1LL) << bit_in_byte);
    /* SRC: @bits[byte_idx] = ((@bits[byte_idx] as int) | (mask as int)) as byte */
    ((nova_self->bits))->data[byte_idx] = (((nova_self->bits))->data[byte_idx] | mask);
    return NOVA_UNIT;
}

static nova_bool Nova_BloomFilter_method_get_bit(Nova_BloomFilter* nova_self, nova_int idx) {
    /* SRC: let byte_idx = idx / 8 */
    nova_int byte_idx = (idx / ((nova_int)8LL));
    /* SRC: let bit_in_byte = idx % 8 */
    nova_int bit_in_byte = (idx % ((nova_int)8LL));
    /* SRC: let mask = (1 << bit_in_byte */
    nova_int mask = (((nova_int)1LL) << bit_in_byte);
    /* SRC: @bits[byte_idx] as int) & mask) != 0 */
    return ((((nova_self->bits))->data[byte_idx] & mask) != ((nova_int)0LL));
}

static uint64_t nova_fn_hash1(nova_str s) {
    /* SRC: let mut h u64 = 0xCBF29CE484222325 */
    uint64_t h = ((nova_int)-3750763034362895579LL);
    /* SRC: for c in s.chars() { */
    NovaArray_nova_int* _nv_tmp_9 = nova_str_chars(s);
    nova_unit _nv_tmp_11;
    for (nova_int _nv_tmp_10 = 0; _nv_tmp_10 < _nv_tmp_9->len; _nv_tmp_10++) {
        nova_int c = _nv_tmp_9->data[_nv_tmp_10];
        /* SRC: h = h ^ ((c as int) as u64 */
        h = (h ^ c);
        /* SRC: h = h * 0x100000001B3 */
        h = (h * ((nova_int)1099511628211LL));
    }
    _nv_tmp_11 = NOVA_UNIT;
    _nv_tmp_11;
    /* SRC: h */
    return h;
}

static uint64_t nova_fn_hash2(nova_str s) {
    /* SRC: let mut h u64 = 0x100000001B3 */
    uint64_t h = ((nova_int)1099511628211LL);
    /* SRC: for c in s.chars() { */
    NovaArray_nova_int* _nv_tmp_12 = nova_str_chars(s);
    nova_unit _nv_tmp_14;
    for (nova_int _nv_tmp_13 = 0; _nv_tmp_13 < _nv_tmp_12->len; _nv_tmp_13++) {
        nova_int c = _nv_tmp_12->data[_nv_tmp_13];
        /* SRC: h = h * 31 */
        h = (h * ((nova_int)31LL));
        /* SRC: h = h + ((c as int) as u64 */
        h = (h + c);
    }
    _nv_tmp_14 = NOVA_UNIT;
    _nv_tmp_14;
    /* SRC: h */
    return h;
}

static nova_unit nova_test_no_false_negatives_0(void) {
    /* SRC: let mut bf = BloomFilter.new(1024, 3) */
    Nova_BloomFilter* bf = Nova_BloomFilter_static_new(((nova_int)1024LL), ((nova_int)3LL));
    /* SRC: bf.insert("hello") */
    Nova_BloomFilter_method_insert(bf, (nova_str){.ptr="hello", .len=5});
    /* SRC: bf.insert("world") */
    Nova_BloomFilter_method_insert(bf, (nova_str){.ptr="world", .len=5});
    /* SRC: bf.insert("nova") */
    Nova_BloomFilter_method_insert(bf, (nova_str){.ptr="nova", .len=4});
    /* SRC: assert(bf.contains("hello")) */
    nova_assert(Nova_BloomFilter_method_contains(bf, (nova_str){.ptr="hello", .len=5}), "assert(\"hello\")");
    /* SRC: assert(bf.contains("world")) */
    nova_assert(Nova_BloomFilter_method_contains(bf, (nova_str){.ptr="world", .len=5}), "assert(\"world\")");
    /* SRC: assert(bf.contains("nova")) */
    nova_assert(Nova_BloomFilter_method_contains(bf, (nova_str){.ptr="nova", .len=4}), "assert(\"nova\")");
    return NOVA_UNIT;
}

static nova_unit nova_test_empty_filter______________________1(void) {
    /* SRC: let bf = BloomFilter.new(1024, 3) */
    Nova_BloomFilter* bf = Nova_BloomFilter_static_new(((nova_int)1024LL), ((nova_int)3LL));
    /* SRC: assert(!bf.contains("anything")) */
    nova_assert((!Nova_BloomFilter_method_contains(bf, (nova_str){.ptr="anything", .len=8})), "!assert(\"anything\")");
    return NOVA_UNIT;
}

static nova_unit nova_test_optimal_sizing_2(void) {
    /* SRC: let mut bf = BloomFilter.optimal(100, 0.01) */
    Nova_BloomFilter* bf = Nova_BloomFilter_static_optimal(((nova_int)100LL), ((nova_f64)0.01));
    /* SRC: bf.insert("test1") */
    Nova_BloomFilter_method_insert(bf, (nova_str){.ptr="test1", .len=5});
    /* SRC: bf.insert("test2") */
    Nova_BloomFilter_method_insert(bf, (nova_str){.ptr="test2", .len=5});
    /* SRC: assert(bf.contains("test1")) */
    nova_assert(Nova_BloomFilter_method_contains(bf, (nova_str){.ptr="test1", .len=5}), "assert(\"test1\")");
    /* SRC: assert(bf.contains("test2")) */
    nova_assert(Nova_BloomFilter_method_contains(bf, (nova_str){.ptr="test2", .len=5}), "assert(\"test2\")");
    return NOVA_UNIT;
}

static nova_unit nova_test_false_positive_rate________________small_set_3(void) {
    /* SRC: let mut bf = BloomFilter.new(1024, 4) */
    Nova_BloomFilter* bf = Nova_BloomFilter_static_new(((nova_int)1024LL), ((nova_int)4LL));
    /* SRC: let mut i = 0 */
    nova_int i = ((nova_int)0LL);
    /* SRC: while i < 50 { */
    nova_unit _nv_while_15;
    while ((i < ((nova_int)50LL))) {
        /* SRC: bf.insert("item-" + str.from(i)) */
        Nova_BloomFilter_method_insert(bf, (nova_str_concat((nova_str){.ptr="item-", .len=5}, nova_int_to_str((nova_int)(i)))));
        /* SRC: i += 1 */
        i += ((nova_int)1LL);
    }
    _nv_while_15 = NOVA_UNIT;
    _nv_while_15;
    /* SRC: let mut false_pos = 0 */
    nova_int false_pos = ((nova_int)0LL);
    /* SRC: let mut j = 50 */
    nova_int j = ((nova_int)50LL);
    /* SRC: while j < 150 { */
    nova_unit _nv_while_16;
    while ((j < ((nova_int)150LL))) {
        /* SRC: if bf.contains("item-" + str.from(j)) { */
        nova_unit _nv_if_17;
        if (Nova_BloomFilter_method_contains(bf, (nova_str_concat((nova_str){.ptr="item-", .len=5}, nova_int_to_str((nova_int)(j)))))) {
            /* SRC: false_pos += 1 */
            false_pos += ((nova_int)1LL);
            _nv_if_17 = NOVA_UNIT;
        }
        _nv_if_17;
        /* SRC: j += 1 */
        j += ((nova_int)1LL);
    }
    _nv_while_16 = NOVA_UNIT;
    _nv_while_16;
    /* SRC: assert(false_pos < 50) */
    nova_assert((false_pos < ((nova_int)50LL)), "false_pos < 50");
    return NOVA_UNIT;
}

static nova_unit nova_fn_main_impl(void) {
    int _nova_tests_total = 4;
    int _nova_tests_failed = 0;
    printf("Running %d tests...\n", _nova_tests_total);
    {
        NovaTestFrame _tf;
        _tf.fail_msg = NULL;
        _nova_test_frame = &_tf;
        NovaFailFrame _tf_fail;
        _tf_fail.error_msg = (nova_str){.ptr=NULL, .len=0};
        nova_fail_push(&_tf_fail);
        int _tf_jmp = setjmp(_tf.jmp);
        int _tf_fail_jmp = (_tf_jmp == 0) ? setjmp(_tf_fail.jmp) : 0;
        if (_tf_jmp == 0 && _tf_fail_jmp == 0) {
            nova_test_no_false_negatives_0();
            printf("  PASS: no false negatives\n");
        } else {
            const char* _tf_msg = _tf.fail_msg ? _tf.fail_msg : (_tf_fail.error_msg.ptr ? _tf_fail.error_msg.ptr : "assertion failed");
            printf("  FAIL: no false negatives — %s\n", _tf_msg);
            _nova_tests_failed++;
        }
        nova_fail_pop();
        _nova_test_frame = NULL;
    }
    {
        NovaTestFrame _tf;
        _tf.fail_msg = NULL;
        _nova_test_frame = &_tf;
        NovaFailFrame _tf_fail;
        _tf_fail.error_msg = (nova_str){.ptr=NULL, .len=0};
        nova_fail_push(&_tf_fail);
        int _tf_jmp = setjmp(_tf.jmp);
        int _tf_fail_jmp = (_tf_jmp == 0) ? setjmp(_tf_fail.jmp) : 0;
        if (_tf_jmp == 0 && _tf_fail_jmp == 0) {
            nova_test_empty_filter______________________1();
            printf("  PASS: empty filter — никого не содержит\n");
        } else {
            const char* _tf_msg = _tf.fail_msg ? _tf.fail_msg : (_tf_fail.error_msg.ptr ? _tf_fail.error_msg.ptr : "assertion failed");
            printf("  FAIL: empty filter — никого не содержит — %s\n", _tf_msg);
            _nova_tests_failed++;
        }
        nova_fail_pop();
        _nova_test_frame = NULL;
    }
    {
        NovaTestFrame _tf;
        _tf.fail_msg = NULL;
        _nova_test_frame = &_tf;
        NovaFailFrame _tf_fail;
        _tf_fail.error_msg = (nova_str){.ptr=NULL, .len=0};
        nova_fail_push(&_tf_fail);
        int _tf_jmp = setjmp(_tf.jmp);
        int _tf_fail_jmp = (_tf_jmp == 0) ? setjmp(_tf_fail.jmp) : 0;
        if (_tf_jmp == 0 && _tf_fail_jmp == 0) {
            nova_test_optimal_sizing_2();
            printf("  PASS: optimal sizing\n");
        } else {
            const char* _tf_msg = _tf.fail_msg ? _tf.fail_msg : (_tf_fail.error_msg.ptr ? _tf_fail.error_msg.ptr : "assertion failed");
            printf("  FAIL: optimal sizing — %s\n", _tf_msg);
            _nova_tests_failed++;
        }
        nova_fail_pop();
        _nova_test_frame = NULL;
    }
    {
        NovaTestFrame _tf;
        _tf.fail_msg = NULL;
        _nova_test_frame = &_tf;
        NovaFailFrame _tf_fail;
        _tf_fail.error_msg = (nova_str){.ptr=NULL, .len=0};
        nova_fail_push(&_tf_fail);
        int _tf_jmp = setjmp(_tf.jmp);
        int _tf_fail_jmp = (_tf_jmp == 0) ? setjmp(_tf_fail.jmp) : 0;
        if (_tf_jmp == 0 && _tf_fail_jmp == 0) {
            nova_test_false_positive_rate________________small_set_3();
            printf("  PASS: false positive rate приемлемый для small set\n");
        } else {
            const char* _tf_msg = _tf.fail_msg ? _tf.fail_msg : (_tf_fail.error_msg.ptr ? _tf_fail.error_msg.ptr : "assertion failed");
            printf("  FAIL: false positive rate приемлемый для small set — %s\n", _tf_msg);
            _nova_tests_failed++;
        }
        nova_fail_pop();
        _nova_test_frame = NULL;
    }
    printf("%d/%d passed\n", _nova_tests_total - _nova_tests_failed, _nova_tests_total);
    if (_nova_tests_failed > 0) { exit(1); }
    return NOVA_UNIT;
}

int main(void) {
    nova_gc_init();
    nova_register_effect_storage((void**)&_nova_handler_Fail);
    nova_register_effect_storage((void**)&_nova_handler_Time);
    nova_fn_main_impl();
    nova_gc_shutdown();
    return 0;
}
