/* Generated by nova-codegen. Do not edit. */
#include "nova_rt/nova_rt.h"

typedef struct { nova_int f0; } _NovaTuple1;
typedef struct { nova_int f0; nova_int f1; } _NovaTuple2;
typedef struct { nova_int f0; nova_int f1; nova_int f2; } _NovaTuple3;
typedef struct { nova_int f0; nova_int f1; nova_int f2; nova_int f3; } _NovaTuple4;
typedef struct { nova_int f0; nova_int f1; nova_int f2; nova_int f3; nova_int f4; } _NovaTuple5;
typedef struct { nova_int f0; nova_int f1; nova_int f2; nova_int f3; nova_int f4; nova_int f5; } _NovaTuple6;
typedef struct { nova_int f0; nova_int f1; nova_int f2; nova_int f3; nova_int f4; nova_int f5; nova_int f6; } _NovaTuple7;
typedef struct { nova_int f0; nova_int f1; nova_int f2; nova_int f3; nova_int f4; nova_int f5; nova_int f6; nova_int f7; } _NovaTuple8;

typedef struct Nova_Deque Nova_Deque;
struct Nova_Deque {
    NovaArray_nova_int* items;
};

static Nova_Self* Nova_Deque_static_new(Nova_Deque* nova_self);
static nova_int Nova_Deque_method_len(Nova_Deque* nova_self);
static nova_bool Nova_Deque_method_is_empty(Nova_Deque* nova_self);
static nova_unit Nova_Deque_method_push_back(Nova_Deque* nova_self, void* x);
static nova_unit Nova_Deque_method_push_front(Nova_Deque* nova_self, void* x);
static NovaOpt_nova_int Nova_Deque_method_pop_back(Nova_Deque* nova_self);
static NovaOpt_nova_int Nova_Deque_method_pop_front(Nova_Deque* nova_self);
static NovaOpt_nova_int Nova_Deque_method_front(Nova_Deque* nova_self);
static NovaOpt_nova_int Nova_Deque_method_back(Nova_Deque* nova_self);
static NovaOpt_nova_int Nova_Deque_method_get(Nova_Deque* nova_self, nova_int i);
static nova_unit nova_test_push_back___pop_back_0(void);
static nova_unit nova_test_push_front___pop_front_1(void);
static nova_unit nova_test_mixed_push_back___pop_front__FIFO_queue__2(void);
static nova_unit nova_test_BFS_like_sliding_window_3(void);
static nova_unit nova_test_front_back_________deque_4(void);

static Nova_Self* Nova_Deque_static_new(Nova_Deque* nova_self) {
    /* SRC: { items: [] } */
    Nova_Deque* _nv_tmp_0 = (Nova_Deque*)nova_alloc(sizeof(Nova_Deque));
    NovaArray_nova_int* _nv_tmp_1 = nova_array_new_nova_int(8);
    _nv_tmp_0->items = _nv_tmp_1;
    return _nv_tmp_0;
}

static nova_int Nova_Deque_method_len(Nova_Deque* nova_self) {
    /* SRC: @items.len */
    return ((nova_self->items)->len);
}

static nova_bool Nova_Deque_method_is_empty(Nova_Deque* nova_self) {
    /* SRC: @items.len == 0 */
    return (((nova_self->items)->len) == ((nova_int)0LL));
}

static nova_unit Nova_Deque_method_push_back(Nova_Deque* nova_self, void* x) {
    /* SRC: @items.push(x) */
    nova_array_push_nova_int((nova_self->items), (nova_int)(intptr_t)(x));
    NOVA_UNIT;
    return NOVA_UNIT;
}

static nova_unit Nova_Deque_method_push_front(Nova_Deque* nova_self, void* x) {
    /* SRC: let mut new_items []T = [x] */
    NovaArray_nova_int* _nv_tmp_2 = nova_array_new_nova_int(1);
    nova_array_push_nova_int(_nv_tmp_2, (nova_int)(x));
    NovaArray_nova_int* new_items = _nv_tmp_2;
    /* SRC: for it in @items { new_items.push(it) } */
    NovaArray_nova_int* _nv_tmp_3 = (nova_self->items);
    nova_unit _nv_tmp_5;
    for (nova_int _nv_tmp_4 = 0; _nv_tmp_4 < _nv_tmp_3->len; _nv_tmp_4++) {
        nova_int it = _nv_tmp_3->data[_nv_tmp_4];
        nova_array_push_nova_int(new_items, it);
        (void)(NOVA_UNIT);
    }
    _nv_tmp_5 = NOVA_UNIT;
    _nv_tmp_5;
    /* SRC: @items = new_items */
    (nova_self->items) = new_items;
    return NOVA_UNIT;
}

static NovaOpt_nova_int Nova_Deque_method_pop_back(Nova_Deque* nova_self) {
    /* SRC: if @items.len == 0 { return None } */
    nova_unit _nv_if_6;
    if ((((nova_self->items)->len) == ((nova_int)0LL))) {
        /* SRC: return None */
        return nova_make_Option_None();
        _nv_if_6 = NOVA_UNIT;
    }
    _nv_if_6;
    /* SRC: let last_idx = @items.len - 1 */
    nova_int last_idx = (((nova_self->items)->len) - ((nova_int)1LL));
    /* SRC: let value = @items[last_idx] */
    nova_int value = ((nova_self->items))->data[last_idx];
    /* SRC: let mut new_items []T = [] */
    NovaArray_nova_int* _nv_tmp_7 = nova_array_new_nova_int(8);
    NovaArray_nova_int* new_items = _nv_tmp_7;
    /* SRC: let mut i = 0 */
    nova_int i = ((nova_int)0LL);
    /* SRC: while i < last_idx { */
    nova_unit _nv_while_8;
    while ((i < last_idx)) {
        /* SRC: new_items.push(@items[i]) */
        nova_array_push_nova_int(new_items, ((nova_self->items))->data[i]);
        NOVA_UNIT;
        /* SRC: i += 1 */
        i += ((nova_int)1LL);
    }
    _nv_while_8 = NOVA_UNIT;
    _nv_while_8;
    /* SRC: @items = new_items */
    (nova_self->items) = new_items;
    /* SRC: Some(value) */
    return nova_make_Option_Some(value);
}

static NovaOpt_nova_int Nova_Deque_method_pop_front(Nova_Deque* nova_self) {
    /* SRC: if @items.len == 0 { return None } */
    nova_unit _nv_if_9;
    if ((((nova_self->items)->len) == ((nova_int)0LL))) {
        /* SRC: return None */
        return nova_make_Option_None();
        _nv_if_9 = NOVA_UNIT;
    }
    _nv_if_9;
    /* SRC: let value = @items[0] */
    nova_int value = ((nova_self->items))->data[((nova_int)0LL)];
    /* SRC: let mut new_items []T = [] */
    NovaArray_nova_int* _nv_tmp_10 = nova_array_new_nova_int(8);
    NovaArray_nova_int* new_items = _nv_tmp_10;
    /* SRC: let mut i = 1 */
    nova_int i = ((nova_int)1LL);
    /* SRC: while i < @items.len { */
    nova_unit _nv_while_11;
    while ((i < ((nova_self->items)->len))) {
        /* SRC: new_items.push(@items[i]) */
        nova_array_push_nova_int(new_items, ((nova_self->items))->data[i]);
        NOVA_UNIT;
        /* SRC: i += 1 */
        i += ((nova_int)1LL);
    }
    _nv_while_11 = NOVA_UNIT;
    _nv_while_11;
    /* SRC: @items = new_items */
    (nova_self->items) = new_items;
    /* SRC: Some(value) */
    return nova_make_Option_Some(value);
}

static NovaOpt_nova_int Nova_Deque_method_front(Nova_Deque* nova_self) {
    /* SRC: if @items.len == 0 { None } */
    NovaOpt_nova_int _nv_if_12;
    if ((((nova_self->items)->len) == ((nova_int)0LL))) {
        _nv_if_12 = nova_make_Option_None();
    } else {
        _nv_if_12 = nova_make_Option_Some(((nova_self->items))->data[((nova_int)0LL)]);
    }
    return _nv_if_12;
}

static NovaOpt_nova_int Nova_Deque_method_back(Nova_Deque* nova_self) {
    /* SRC: if @items.len == 0 { None } */
    NovaOpt_nova_int _nv_if_13;
    if ((((nova_self->items)->len) == ((nova_int)0LL))) {
        _nv_if_13 = nova_make_Option_None();
    } else {
        _nv_if_13 = nova_make_Option_Some(((nova_self->items))->data[(((nova_self->items)->len) - ((nova_int)1LL))]);
    }
    return _nv_if_13;
}

static NovaOpt_nova_int Nova_Deque_method_get(Nova_Deque* nova_self, nova_int i) {
    /* SRC: if i < 0 || i >= @items.len { None } */
    NovaOpt_nova_int _nv_if_14;
    if (((i < ((nova_int)0LL)) || (i >= ((nova_self->items)->len)))) {
        _nv_if_14 = nova_make_Option_None();
    } else {
        _nv_if_14 = nova_make_Option_Some(((nova_self->items))->data[i]);
    }
    return _nv_if_14;
}

static nova_unit nova_test_push_back___pop_back_0(void) {
    /* SRC: let mut d = Deque[int].new() */
    Nova_Self* d = Nova_Deque_static_new();
    /* SRC: d.push_back(1) */
    Nova_Deque_method_push_back(d, (void*)(intptr_t)(((nova_int)1LL)));
    /* SRC: d.push_back(2) */
    Nova_Deque_method_push_back(d, (void*)(intptr_t)(((nova_int)2LL)));
    /* SRC: d.push_back(3) */
    Nova_Deque_method_push_back(d, (void*)(intptr_t)(((nova_int)3LL)));
    /* SRC: assert(d.len == 3) */
    nova_assert(((d->len) == ((nova_int)3LL)), "assert == 3");
    /* SRC: assert(d.pop_back() == Some(3)) */
    nova_assert((nova_opt_eq_nova_int(Nova_Deque_method_pop_back(d), nova_make_Option_Some(((nova_int)3LL)))), "assert() == Some(3)");
    /* SRC: assert(d.pop_back() == Some(2)) */
    nova_assert((nova_opt_eq_nova_int(Nova_Deque_method_pop_back(d), nova_make_Option_Some(((nova_int)2LL)))), "assert() == Some(2)");
    /* SRC: assert(d.pop_back() == Some(1)) */
    nova_assert((nova_opt_eq_nova_int(Nova_Deque_method_pop_back(d), nova_make_Option_Some(((nova_int)1LL)))), "assert() == Some(1)");
    /* SRC: assert(d.pop_back() == None) */
    nova_assert((nova_opt_eq_nova_int(Nova_Deque_method_pop_back(d), nova_make_Option_None())), "assert() == None");
    return NOVA_UNIT;
}

static nova_unit nova_test_push_front___pop_front_1(void) {
    /* SRC: let mut d = Deque[int].new() */
    Nova_Self* d = Nova_Deque_static_new();
    /* SRC: d.push_front(1) */
    Nova_Deque_method_push_front(d, (void*)(intptr_t)(((nova_int)1LL)));
    /* SRC: d.push_front(2) */
    Nova_Deque_method_push_front(d, (void*)(intptr_t)(((nova_int)2LL)));
    /* SRC: d.push_front(3) */
    Nova_Deque_method_push_front(d, (void*)(intptr_t)(((nova_int)3LL)));
    /* SRC: assert(d.front() == Some(3)) */
    nova_assert((nova_opt_eq_nova_int(Nova_Deque_method_front(d), nova_make_Option_Some(((nova_int)3LL)))), "assert() == Some(3)");
    /* SRC: assert(d.back() == Some(1)) */
    nova_assert((nova_opt_eq_nova_int(Nova_Deque_method_back(d), nova_make_Option_Some(((nova_int)1LL)))), "assert() == Some(1)");
    /* SRC: assert(d.pop_front() == Some(3)) */
    nova_assert((nova_opt_eq_nova_int(Nova_Deque_method_pop_front(d), nova_make_Option_Some(((nova_int)3LL)))), "assert() == Some(3)");
    /* SRC: assert(d.pop_front() == Some(2)) */
    nova_assert((nova_opt_eq_nova_int(Nova_Deque_method_pop_front(d), nova_make_Option_Some(((nova_int)2LL)))), "assert() == Some(2)");
    /* SRC: assert(d.pop_front() == Some(1)) */
    nova_assert((nova_opt_eq_nova_int(Nova_Deque_method_pop_front(d), nova_make_Option_Some(((nova_int)1LL)))), "assert() == Some(1)");
    /* SRC: assert(d.is_empty()) */
    nova_assert(Nova_Deque_method_is_empty(d), "assert()");
    return NOVA_UNIT;
}

static nova_unit nova_test_mixed_push_back___pop_front__FIFO_queue__2(void) {
    /* SRC: let mut d = Deque[str].new() */
    Nova_Self* d = Nova_Deque_static_new();
    /* SRC: d.push_back("a") */
    nova_str* _nv_tmp_15 = (nova_str*)nova_alloc(sizeof(nova_str));
    *_nv_tmp_15 = (nova_str){.ptr="a", .len=1};
    Nova_Deque_method_push_back(d, (void*)(_nv_tmp_15));
    /* SRC: d.push_back("b") */
    nova_str* _nv_tmp_16 = (nova_str*)nova_alloc(sizeof(nova_str));
    *_nv_tmp_16 = (nova_str){.ptr="b", .len=1};
    Nova_Deque_method_push_back(d, (void*)(_nv_tmp_16));
    /* SRC: d.push_back("c") */
    nova_str* _nv_tmp_17 = (nova_str*)nova_alloc(sizeof(nova_str));
    *_nv_tmp_17 = (nova_str){.ptr="c", .len=1};
    Nova_Deque_method_push_back(d, (void*)(_nv_tmp_17));
    /* SRC: assert(d.pop_front() == Some("a")) */
    nova_assert((nova_opt_eq_nova_int(Nova_Deque_method_pop_front(d), nova_make_Option_Some((nova_str){.ptr="a", .len=1}))), "assert() == Some(\"a\")");
    /* SRC: assert(d.pop_front() == Some("b")) */
    nova_assert((nova_opt_eq_nova_int(Nova_Deque_method_pop_front(d), nova_make_Option_Some((nova_str){.ptr="b", .len=1}))), "assert() == Some(\"b\")");
    /* SRC: assert(d.pop_front() == Some("c")) */
    nova_assert((nova_opt_eq_nova_int(Nova_Deque_method_pop_front(d), nova_make_Option_Some((nova_str){.ptr="c", .len=1}))), "assert() == Some(\"c\")");
    return NOVA_UNIT;
}

static nova_unit nova_test_BFS_like_sliding_window_3(void) {
    /* SRC: let mut d = Deque[int].new() */
    Nova_Self* d = Nova_Deque_static_new();
    /* SRC: let inputs = [1, 2, 3, 4, 5] */
    NovaArray_nova_int* _nv_tmp_18 = nova_array_new_nova_int(5);
    nova_array_push_nova_int(_nv_tmp_18, (nova_int)(((nova_int)1LL)));
    nova_array_push_nova_int(_nv_tmp_18, (nova_int)(((nova_int)2LL)));
    nova_array_push_nova_int(_nv_tmp_18, (nova_int)(((nova_int)3LL)));
    nova_array_push_nova_int(_nv_tmp_18, (nova_int)(((nova_int)4LL)));
    nova_array_push_nova_int(_nv_tmp_18, (nova_int)(((nova_int)5LL)));
    NovaArray_nova_int* inputs = _nv_tmp_18;
    /* SRC: for x in inputs { */
    NovaArray_nova_int* _nv_tmp_19 = inputs;
    nova_unit _nv_tmp_21;
    for (nova_int _nv_tmp_20 = 0; _nv_tmp_20 < _nv_tmp_19->len; _nv_tmp_20++) {
        nova_int x = _nv_tmp_19->data[_nv_tmp_20];
        /* SRC: d.push_back(x) */
        Nova_Deque_method_push_back(d, (void*)(intptr_t)(x));
        nova_unit _nv_if_22;
        if (((d->len) > ((nova_int)3LL))) {
            /* SRC: let _ = d.pop_front() */
            NovaOpt_nova_int _nv_tmp_23 = Nova_Deque_method_pop_front(d);
            _nv_if_22 = NOVA_UNIT;
        }
        (void)(_nv_if_22);
    }
    _nv_tmp_21 = NOVA_UNIT;
    _nv_tmp_21;
    /* SRC: assert(d.len == 3) */
    nova_assert(((d->len) == ((nova_int)3LL)), "assert == 3");
    /* SRC: assert(d.front() == Some(3)) */
    nova_assert((nova_opt_eq_nova_int(Nova_Deque_method_front(d), nova_make_Option_Some(((nova_int)3LL)))), "assert() == Some(3)");
    /* SRC: assert(d.back() == Some(5)) */
    nova_assert((nova_opt_eq_nova_int(Nova_Deque_method_back(d), nova_make_Option_Some(((nova_int)5LL)))), "assert() == Some(5)");
    return NOVA_UNIT;
}

static nova_unit nova_test_front_back_________deque_4(void) {
    /* SRC: let d = Deque[int].new() */
    Nova_Self* d = Nova_Deque_static_new();
    /* SRC: assert(d.front() == None) */
    nova_assert((nova_opt_eq_nova_int(Nova_Deque_method_front(d), nova_make_Option_None())), "assert() == None");
    /* SRC: assert(d.back() == None) */
    nova_assert((nova_opt_eq_nova_int(Nova_Deque_method_back(d), nova_make_Option_None())), "assert() == None");
    return NOVA_UNIT;
}

static nova_unit nova_fn_main_impl(void) {
    int _nova_tests_total = 5;
    int _nova_tests_failed = 0;
    printf("Running %d tests...\n", _nova_tests_total);
    {
        NovaTestFrame _tf;
        _tf.fail_msg = NULL;
        _nova_test_frame = &_tf;
        NovaFailFrame _tf_fail;
        _tf_fail.error_msg = (nova_str){.ptr=NULL, .len=0};
        nova_fail_push(&_tf_fail);
        int _tf_jmp = setjmp(_tf.jmp);
        int _tf_fail_jmp = (_tf_jmp == 0) ? setjmp(_tf_fail.jmp) : 0;
        if (_tf_jmp == 0 && _tf_fail_jmp == 0) {
            nova_test_push_back___pop_back_0();
            printf("  PASS: push_back / pop_back\n");
        } else {
            const char* _tf_msg = _tf.fail_msg ? _tf.fail_msg : (_tf_fail.error_msg.ptr ? _tf_fail.error_msg.ptr : "assertion failed");
            printf("  FAIL: push_back / pop_back — %s\n", _tf_msg);
            _nova_tests_failed++;
        }
        nova_fail_pop();
        _nova_test_frame = NULL;
    }
    {
        NovaTestFrame _tf;
        _tf.fail_msg = NULL;
        _nova_test_frame = &_tf;
        NovaFailFrame _tf_fail;
        _tf_fail.error_msg = (nova_str){.ptr=NULL, .len=0};
        nova_fail_push(&_tf_fail);
        int _tf_jmp = setjmp(_tf.jmp);
        int _tf_fail_jmp = (_tf_jmp == 0) ? setjmp(_tf_fail.jmp) : 0;
        if (_tf_jmp == 0 && _tf_fail_jmp == 0) {
            nova_test_push_front___pop_front_1();
            printf("  PASS: push_front / pop_front\n");
        } else {
            const char* _tf_msg = _tf.fail_msg ? _tf.fail_msg : (_tf_fail.error_msg.ptr ? _tf_fail.error_msg.ptr : "assertion failed");
            printf("  FAIL: push_front / pop_front — %s\n", _tf_msg);
            _nova_tests_failed++;
        }
        nova_fail_pop();
        _nova_test_frame = NULL;
    }
    {
        NovaTestFrame _tf;
        _tf.fail_msg = NULL;
        _nova_test_frame = &_tf;
        NovaFailFrame _tf_fail;
        _tf_fail.error_msg = (nova_str){.ptr=NULL, .len=0};
        nova_fail_push(&_tf_fail);
        int _tf_jmp = setjmp(_tf.jmp);
        int _tf_fail_jmp = (_tf_jmp == 0) ? setjmp(_tf_fail.jmp) : 0;
        if (_tf_jmp == 0 && _tf_fail_jmp == 0) {
            nova_test_mixed_push_back___pop_front__FIFO_queue__2();
            printf("  PASS: mixed push_back + pop_front (FIFO queue)\n");
        } else {
            const char* _tf_msg = _tf.fail_msg ? _tf.fail_msg : (_tf_fail.error_msg.ptr ? _tf_fail.error_msg.ptr : "assertion failed");
            printf("  FAIL: mixed push_back + pop_front (FIFO queue) — %s\n", _tf_msg);
            _nova_tests_failed++;
        }
        nova_fail_pop();
        _nova_test_frame = NULL;
    }
    {
        NovaTestFrame _tf;
        _tf.fail_msg = NULL;
        _nova_test_frame = &_tf;
        NovaFailFrame _tf_fail;
        _tf_fail.error_msg = (nova_str){.ptr=NULL, .len=0};
        nova_fail_push(&_tf_fail);
        int _tf_jmp = setjmp(_tf.jmp);
        int _tf_fail_jmp = (_tf_jmp == 0) ? setjmp(_tf_fail.jmp) : 0;
        if (_tf_jmp == 0 && _tf_fail_jmp == 0) {
            nova_test_BFS_like_sliding_window_3();
            printf("  PASS: BFS-like sliding window\n");
        } else {
            const char* _tf_msg = _tf.fail_msg ? _tf.fail_msg : (_tf_fail.error_msg.ptr ? _tf_fail.error_msg.ptr : "assertion failed");
            printf("  FAIL: BFS-like sliding window — %s\n", _tf_msg);
            _nova_tests_failed++;
        }
        nova_fail_pop();
        _nova_test_frame = NULL;
    }
    {
        NovaTestFrame _tf;
        _tf.fail_msg = NULL;
        _nova_test_frame = &_tf;
        NovaFailFrame _tf_fail;
        _tf_fail.error_msg = (nova_str){.ptr=NULL, .len=0};
        nova_fail_push(&_tf_fail);
        int _tf_jmp = setjmp(_tf.jmp);
        int _tf_fail_jmp = (_tf_jmp == 0) ? setjmp(_tf_fail.jmp) : 0;
        if (_tf_jmp == 0 && _tf_fail_jmp == 0) {
            nova_test_front_back_________deque_4();
            printf("  PASS: front/back пустого deque\n");
        } else {
            const char* _tf_msg = _tf.fail_msg ? _tf.fail_msg : (_tf_fail.error_msg.ptr ? _tf_fail.error_msg.ptr : "assertion failed");
            printf("  FAIL: front/back пустого deque — %s\n", _tf_msg);
            _nova_tests_failed++;
        }
        nova_fail_pop();
        _nova_test_frame = NULL;
    }
    printf("%d/%d passed\n", _nova_tests_total - _nova_tests_failed, _nova_tests_total);
    if (_nova_tests_failed > 0) { exit(1); }
    return NOVA_UNIT;
}

int main(void) {
    nova_gc_init();
    nova_register_effect_storage((void**)&_nova_handler_Fail);
    nova_register_effect_storage((void**)&_nova_handler_Time);
    nova_fn_main_impl();
    nova_gc_shutdown();
    return 0;
}
