/* Generated by nova-codegen. Do not edit. */
#include "nova_rt/nova_rt.h"

typedef struct { nova_int f0; } _NovaTuple1;
typedef struct { nova_int f0; nova_int f1; } _NovaTuple2;
typedef struct { nova_int f0; nova_int f1; nova_int f2; } _NovaTuple3;
typedef struct { nova_int f0; nova_int f1; nova_int f2; nova_int f3; } _NovaTuple4;
typedef struct { nova_int f0; nova_int f1; nova_int f2; nova_int f3; nova_int f4; } _NovaTuple5;
typedef struct { nova_int f0; nova_int f1; nova_int f2; nova_int f3; nova_int f4; nova_int f5; } _NovaTuple6;
typedef struct { nova_int f0; nova_int f1; nova_int f2; nova_int f3; nova_int f4; nova_int f5; nova_int f6; } _NovaTuple7;
typedef struct { nova_int f0; nova_int f1; nova_int f2; nova_int f3; nova_int f4; nova_int f5; nova_int f6; nova_int f7; } _NovaTuple8;

typedef struct Nova_PriorityQueue Nova_PriorityQueue;
struct Nova_PriorityQueue {
    NovaArray_nova_int* items;
};

static Nova_Self* Nova_PriorityQueue_static_new(Nova_PriorityQueue* nova_self);
static nova_int Nova_PriorityQueue_method_len(Nova_PriorityQueue* nova_self);
static nova_bool Nova_PriorityQueue_method_is_empty(Nova_PriorityQueue* nova_self);
static NovaOpt_nova_int Nova_PriorityQueue_method_peek(Nova_PriorityQueue* nova_self);
static nova_unit Nova_PriorityQueue_method_push(Nova_PriorityQueue* nova_self, void* item);
static NovaOpt_nova_int Nova_PriorityQueue_method_pop(Nova_PriorityQueue* nova_self);
static nova_unit Nova_PriorityQueue_method_sift_up(Nova_PriorityQueue* nova_self, nova_int idx);
static nova_unit Nova_PriorityQueue_method_sift_down(Nova_PriorityQueue* nova_self, nova_int idx);
static nova_unit nova_test_empty_queue_0(void);
static nova_unit nova_test_push___pop_________1(void);
static nova_unit nova_test_peek____________2(void);

static Nova_Self* Nova_PriorityQueue_static_new(Nova_PriorityQueue* nova_self) {
    /* SRC: { items: [] } */
    Nova_PriorityQueue* _nv_tmp_0 = (Nova_PriorityQueue*)nova_alloc(sizeof(Nova_PriorityQueue));
    NovaArray_nova_int* _nv_tmp_1 = nova_array_new_nova_int(8);
    _nv_tmp_0->items = _nv_tmp_1;
    return _nv_tmp_0;
}

static nova_int Nova_PriorityQueue_method_len(Nova_PriorityQueue* nova_self) {
    /* SRC: @items.len */
    return ((nova_self->items)->len);
}

static nova_bool Nova_PriorityQueue_method_is_empty(Nova_PriorityQueue* nova_self) {
    /* SRC: @items.len == 0 */
    return (((nova_self->items)->len) == ((nova_int)0LL));
}

static NovaOpt_nova_int Nova_PriorityQueue_method_peek(Nova_PriorityQueue* nova_self) {
    /* SRC: if @items.len == 0 { None } */
    NovaOpt_nova_int _nv_if_2;
    if ((((nova_self->items)->len) == ((nova_int)0LL))) {
        _nv_if_2 = nova_make_Option_None();
    } else {
        _nv_if_2 = nova_make_Option_Some(((nova_self->items))->data[((nova_int)0LL)]);
    }
    return _nv_if_2;
}

static nova_unit Nova_PriorityQueue_method_push(Nova_PriorityQueue* nova_self, void* item) {
    /* SRC: @items.push(item) */
    nova_array_push_nova_int((nova_self->items), (nova_int)(intptr_t)(item));
    NOVA_UNIT;
    /* SRC: @sift_up(@items.len - 1) */
    Nova_PriorityQueue_method_sift_up(nova_self, (void*)(intptr_t)((((nova_self->items)->len) - ((nova_int)1LL))));
    return NOVA_UNIT;
}

static NovaOpt_nova_int Nova_PriorityQueue_method_pop(Nova_PriorityQueue* nova_self) {
    /* SRC: if @items.len == 0 { return None } */
    nova_unit _nv_if_3;
    if ((((nova_self->items)->len) == ((nova_int)0LL))) {
        /* SRC: return None */
        return nova_make_Option_None();
        _nv_if_3 = NOVA_UNIT;
    }
    _nv_if_3;
    /* SRC: let top = @items[0] */
    nova_int top = ((nova_self->items))->data[((nova_int)0LL)];
    /* SRC: let last = @items.len - 1 */
    nova_int last = (((nova_self->items)->len) - ((nova_int)1LL));
    /* SRC: if last > 0 { */
    nova_unit _nv_if_4;
    if ((last > ((nova_int)0LL))) {
        /* SRC: @items[0] = @items[last] */
        ((nova_self->items))->data[((nova_int)0LL)] = ((nova_self->items))->data[last];
        _nv_if_4 = NOVA_UNIT;
    }
    _nv_if_4;
    /* SRC: let mut new_items []T = [] */
    NovaArray_nova_int* _nv_tmp_5 = nova_array_new_nova_int(8);
    NovaArray_nova_int* new_items = _nv_tmp_5;
    /* SRC: let mut i = 0 */
    nova_int i = ((nova_int)0LL);
    /* SRC: while i < last { */
    nova_unit _nv_while_6;
    while ((i < last)) {
        /* SRC: new_items.push(@items[i]) */
        nova_array_push_nova_int(new_items, ((nova_self->items))->data[i]);
        NOVA_UNIT;
        /* SRC: i += 1 */
        i += ((nova_int)1LL);
    }
    _nv_while_6 = NOVA_UNIT;
    _nv_while_6;
    /* SRC: @items = new_items */
    (nova_self->items) = new_items;
    /* SRC: if @items.len > 0 { */
    nova_unit _nv_if_7;
    if ((((nova_self->items)->len) > ((nova_int)0LL))) {
        _nv_if_7 = NOVA_UNIT; (void)(Nova_PriorityQueue_method_sift_down(nova_self, (void*)(intptr_t)(((nova_int)0LL))));
    }
    _nv_if_7;
    /* SRC: Some(top) */
    return nova_make_Option_Some(top);
}

static nova_unit Nova_PriorityQueue_method_sift_up(Nova_PriorityQueue* nova_self, nova_int idx) {
    /* SRC: let mut i = idx */
    nova_int i = idx;
    /* SRC: while i > 0 { */
    nova_unit _nv_while_8;
    while ((i > ((nova_int)0LL))) {
        /* SRC: let parent = (i - 1) / 2 */
        nova_int parent = ((i - ((nova_int)1LL)) / ((nova_int)2LL));
    }
    _nv_while_8 = NOVA_UNIT;
    _nv_while_8;
    return NOVA_UNIT;
}

static nova_unit Nova_PriorityQueue_method_sift_down(Nova_PriorityQueue* nova_self, nova_int idx) {
    /* SRC: let mut i = idx */
    nova_int i = idx;
    /* SRC: let n = @items.len */
    nova_int n = ((nova_self->items)->len);
    /* SRC: while true { */
    nova_unit _nv_while_9;
    while (true) {
        /* SRC: let left = 2 * i + 1 */
        nova_int left = ((((nova_int)2LL) * i) + ((nova_int)1LL));
        /* SRC: let right = 2 * i + 2 */
        nova_int right = ((((nova_int)2LL) * i) + ((nova_int)2LL));
        /* SRC: let mut smallest = i */
        nova_int smallest = i;
        /* SRC: if left < n && @items[left].lt(@items[smallest]) { */
        nova_unit _nv_if_10;
        if (((left < n) && ((nova_self->items))->data[left].lt(((nova_self->items))->data[smallest]))) {
            /* SRC: smallest = left */
            smallest = left;
            _nv_if_10 = NOVA_UNIT;
        }
        _nv_if_10;
        /* SRC: if right < n && @items[right].lt(@items[smallest]) { */
        nova_unit _nv_if_11;
        if (((right < n) && ((nova_self->items))->data[right].lt(((nova_self->items))->data[smallest]))) {
            /* SRC: smallest = right */
            smallest = right;
            _nv_if_11 = NOVA_UNIT;
        }
        _nv_if_11;
        /* SRC: if smallest == i { return () } */
        nova_unit _nv_if_12;
        if ((smallest == i)) {
            /* SRC: return () */
            return NOVA_UNIT;
            _nv_if_12 = NOVA_UNIT;
        }
        _nv_if_12;
        /* SRC: let tmp = @items[i] */
        nova_int tmp = ((nova_self->items))->data[i];
        /* SRC: @items[i] = @items[smallest] */
        ((nova_self->items))->data[i] = ((nova_self->items))->data[smallest];
        /* SRC: @items[smallest] = tmp */
        ((nova_self->items))->data[smallest] = tmp;
        /* SRC: i = smallest */
        i = smallest;
    }
    _nv_while_9 = NOVA_UNIT;
    _nv_while_9;
    return NOVA_UNIT;
}

static nova_unit nova_test_empty_queue_0(void) {
    /* SRC: let pq = PriorityQueue[int].new() */
    Nova_Self* pq = Nova_PriorityQueue_static_new();
    /* SRC: assert(pq.is_empty()) */
    nova_assert(Nova_PriorityQueue_method_is_empty(pq), "assert()");
    /* SRC: assert(pq.peek() == None) */
    nova_assert((nova_opt_eq_nova_int(Nova_PriorityQueue_method_peek(pq), nova_make_Option_None())), "assert() == None");
    /* SRC: let mut pq2 = pq */
    Nova_Self* pq2 = pq;
    /* SRC: assert(pq2.pop() == None) */
    nova_assert((nova_opt_eq_nova_int(Nova_PriorityQueue_method_pop(pq2), nova_make_Option_None())), "assert() == None");
    return NOVA_UNIT;
}

static nova_unit nova_test_push___pop_________1(void) {
    /* SRC: let mut pq = PriorityQueue[int].new() */
    Nova_Self* pq = Nova_PriorityQueue_static_new();
    /* SRC: pq.push(5) */
    Nova_PriorityQueue_method_push(pq, (void*)(intptr_t)(((nova_int)5LL)));
    /* SRC: pq.push(1) */
    Nova_PriorityQueue_method_push(pq, (void*)(intptr_t)(((nova_int)1LL)));
    /* SRC: pq.push(3) */
    Nova_PriorityQueue_method_push(pq, (void*)(intptr_t)(((nova_int)3LL)));
    /* SRC: pq.push(8) */
    Nova_PriorityQueue_method_push(pq, (void*)(intptr_t)(((nova_int)8LL)));
    /* SRC: pq.push(2) */
    Nova_PriorityQueue_method_push(pq, (void*)(intptr_t)(((nova_int)2LL)));
    /* SRC: assert(pq.len == 5) */
    nova_assert(((pq->len) == ((nova_int)5LL)), "assert == 5");
    /* SRC: assert(pq.pop() == Some(1)) */
    nova_assert((nova_opt_eq_nova_int(Nova_PriorityQueue_method_pop(pq), nova_make_Option_Some(((nova_int)1LL)))), "assert() == Some(1)");
    /* SRC: assert(pq.pop() == Some(2)) */
    nova_assert((nova_opt_eq_nova_int(Nova_PriorityQueue_method_pop(pq), nova_make_Option_Some(((nova_int)2LL)))), "assert() == Some(2)");
    /* SRC: assert(pq.pop() == Some(3)) */
    nova_assert((nova_opt_eq_nova_int(Nova_PriorityQueue_method_pop(pq), nova_make_Option_Some(((nova_int)3LL)))), "assert() == Some(3)");
    /* SRC: assert(pq.pop() == Some(5)) */
    nova_assert((nova_opt_eq_nova_int(Nova_PriorityQueue_method_pop(pq), nova_make_Option_Some(((nova_int)5LL)))), "assert() == Some(5)");
    /* SRC: assert(pq.pop() == Some(8)) */
    nova_assert((nova_opt_eq_nova_int(Nova_PriorityQueue_method_pop(pq), nova_make_Option_Some(((nova_int)8LL)))), "assert() == Some(8)");
    /* SRC: assert(pq.pop() == None) */
    nova_assert((nova_opt_eq_nova_int(Nova_PriorityQueue_method_pop(pq), nova_make_Option_None())), "assert() == None");
    return NOVA_UNIT;
}

static nova_unit nova_test_peek____________2(void) {
    /* SRC: let mut pq = PriorityQueue[int].new() */
    Nova_Self* pq = Nova_PriorityQueue_static_new();
    /* SRC: pq.push(5) */
    Nova_PriorityQueue_method_push(pq, (void*)(intptr_t)(((nova_int)5LL)));
    /* SRC: pq.push(1) */
    Nova_PriorityQueue_method_push(pq, (void*)(intptr_t)(((nova_int)1LL)));
    /* SRC: assert(pq.peek() == Some(1)) */
    nova_assert((nova_opt_eq_nova_int(Nova_PriorityQueue_method_peek(pq), nova_make_Option_Some(((nova_int)1LL)))), "assert() == Some(1)");
    /* SRC: assert(pq.peek() == Some(1)) */
    nova_assert((nova_opt_eq_nova_int(Nova_PriorityQueue_method_peek(pq), nova_make_Option_Some(((nova_int)1LL)))), "assert() == Some(1)");
    /* SRC: assert(pq.len == 2) */
    nova_assert(((pq->len) == ((nova_int)2LL)), "assert == 2");
    return NOVA_UNIT;
}

static nova_unit nova_fn_main_impl(void) {
    int _nova_tests_total = 3;
    int _nova_tests_failed = 0;
    printf("Running %d tests...\n", _nova_tests_total);
    {
        NovaTestFrame _tf;
        _tf.fail_msg = NULL;
        _nova_test_frame = &_tf;
        NovaFailFrame _tf_fail;
        _tf_fail.error_msg = (nova_str){.ptr=NULL, .len=0};
        nova_fail_push(&_tf_fail);
        int _tf_jmp = setjmp(_tf.jmp);
        int _tf_fail_jmp = (_tf_jmp == 0) ? setjmp(_tf_fail.jmp) : 0;
        if (_tf_jmp == 0 && _tf_fail_jmp == 0) {
            nova_test_empty_queue_0();
            printf("  PASS: empty queue\n");
        } else {
            const char* _tf_msg = _tf.fail_msg ? _tf.fail_msg : (_tf_fail.error_msg.ptr ? _tf_fail.error_msg.ptr : "assertion failed");
            printf("  FAIL: empty queue — %s\n", _tf_msg);
            _nova_tests_failed++;
        }
        nova_fail_pop();
        _nova_test_frame = NULL;
    }
    {
        NovaTestFrame _tf;
        _tf.fail_msg = NULL;
        _nova_test_frame = &_tf;
        NovaFailFrame _tf_fail;
        _tf_fail.error_msg = (nova_str){.ptr=NULL, .len=0};
        nova_fail_push(&_tf_fail);
        int _tf_jmp = setjmp(_tf.jmp);
        int _tf_fail_jmp = (_tf_jmp == 0) ? setjmp(_tf_fail.jmp) : 0;
        if (_tf_jmp == 0 && _tf_fail_jmp == 0) {
            nova_test_push___pop_________1();
            printf("  PASS: push / pop порядок\n");
        } else {
            const char* _tf_msg = _tf.fail_msg ? _tf.fail_msg : (_tf_fail.error_msg.ptr ? _tf_fail.error_msg.ptr : "assertion failed");
            printf("  FAIL: push / pop порядок — %s\n", _tf_msg);
            _nova_tests_failed++;
        }
        nova_fail_pop();
        _nova_test_frame = NULL;
    }
    {
        NovaTestFrame _tf;
        _tf.fail_msg = NULL;
        _nova_test_frame = &_tf;
        NovaFailFrame _tf_fail;
        _tf_fail.error_msg = (nova_str){.ptr=NULL, .len=0};
        nova_fail_push(&_tf_fail);
        int _tf_jmp = setjmp(_tf.jmp);
        int _tf_fail_jmp = (_tf_jmp == 0) ? setjmp(_tf_fail.jmp) : 0;
        if (_tf_jmp == 0 && _tf_fail_jmp == 0) {
            nova_test_peek____________2();
            printf("  PASS: peek не удаляет\n");
        } else {
            const char* _tf_msg = _tf.fail_msg ? _tf.fail_msg : (_tf_fail.error_msg.ptr ? _tf_fail.error_msg.ptr : "assertion failed");
            printf("  FAIL: peek не удаляет — %s\n", _tf_msg);
            _nova_tests_failed++;
        }
        nova_fail_pop();
        _nova_test_frame = NULL;
    }
    printf("%d/%d passed\n", _nova_tests_total - _nova_tests_failed, _nova_tests_total);
    if (_nova_tests_failed > 0) { exit(1); }
    return NOVA_UNIT;
}

int main(void) {
    nova_gc_init();
    nova_register_effect_storage((void**)&_nova_handler_Fail);
    nova_register_effect_storage((void**)&_nova_handler_Time);
    nova_fn_main_impl();
    nova_gc_shutdown();
    return 0;
}
