/* Generated by nova-codegen. Do not edit. */
#include "nova_rt/nova_rt.h"

typedef struct { nova_int f0; } _NovaTuple1;
typedef struct { nova_int f0; nova_int f1; } _NovaTuple2;
typedef struct { nova_int f0; nova_int f1; nova_int f2; } _NovaTuple3;
typedef struct { nova_int f0; nova_int f1; nova_int f2; nova_int f3; } _NovaTuple4;
typedef struct { nova_int f0; nova_int f1; nova_int f2; nova_int f3; nova_int f4; } _NovaTuple5;
typedef struct { nova_int f0; nova_int f1; nova_int f2; nova_int f3; nova_int f4; nova_int f5; } _NovaTuple6;
typedef struct { nova_int f0; nova_int f1; nova_int f2; nova_int f3; nova_int f4; nova_int f5; nova_int f6; } _NovaTuple7;
typedef struct { nova_int f0; nova_int f1; nova_int f2; nova_int f3; nova_int f4; nova_int f5; nova_int f6; nova_int f7; } _NovaTuple8;

typedef enum {
    NOVA_TAG_StatsError_EmptyInput,
    NOVA_TAG_StatsError_InvalidPercentile,
} Nova_StatsError_Tag;
typedef struct Nova_StatsError Nova_StatsError;
struct Nova_StatsError {
    Nova_StatsError_Tag tag;
    union {
        struct {
            nova_f64 value;
        } InvalidPercentile;
    } payload;
};

static Nova_StatsError* nova_make_StatsError_EmptyInput(void) {
    Nova_StatsError* _r = (Nova_StatsError*)nova_alloc(sizeof(Nova_StatsError));
    _r->tag = NOVA_TAG_StatsError_EmptyInput;
    return _r;
}

static Nova_StatsError* nova_make_StatsError_InvalidPercentile(nova_f64 _0) {
    Nova_StatsError* _r = (Nova_StatsError*)nova_alloc(sizeof(Nova_StatsError));
    _r->tag = NOVA_TAG_StatsError_InvalidPercentile;
    _r->payload.InvalidPercentile.value = _0;
    return _r;
}

typedef struct Nova_StreamingStats Nova_StreamingStats;
struct Nova_StreamingStats {
    nova_int count;
    nova_f64 mean_val;
    nova_f64 m2;
    nova_f64 min_val;
    nova_f64 max_val;
};

static nova_f64 Nova_Stats_static_mean(NovaArray_nova_f64* xs);
static nova_f64 Nova_Stats_static_variance(NovaArray_nova_f64* xs);
static nova_f64 Nova_Stats_static_stddev(NovaArray_nova_f64* xs);
static nova_f64 Nova_Stats_static_median(NovaArray_nova_f64* xs);
static nova_f64 Nova_Stats_static_percentile(NovaArray_nova_f64* xs, nova_f64 p);
static _NovaTuple2 Nova_Stats_static_min_max(NovaArray_nova_f64* xs);
static nova_f64 Nova_Stats_static_sum(NovaArray_nova_f64* xs);
static NovaArray_nova_f64* nova_fn_sort_copy(NovaArray_nova_f64* xs);
static Nova_StreamingStats* Nova_Stats_static_streaming(void);
static nova_unit Nova_StreamingStats_method_add(Nova_StreamingStats* nova_self, nova_f64 x);
static nova_int Nova_StreamingStats_method_count_value(Nova_StreamingStats* nova_self);
static nova_f64 Nova_StreamingStats_method_mean(Nova_StreamingStats* nova_self);
static nova_f64 Nova_StreamingStats_method_variance(Nova_StreamingStats* nova_self);
static nova_f64 Nova_StreamingStats_method_stddev(Nova_StreamingStats* nova_self);
static nova_f64 Nova_StreamingStats_method_min(Nova_StreamingStats* nova_self);
static nova_f64 Nova_StreamingStats_method_max(Nova_StreamingStats* nova_self);
static nova_unit nova_test_mean_________0(void);
static nova_unit nova_test_median__________________________1(void);
static nova_unit nova_test_variance___stddev_2(void);
static nova_unit nova_test_percentile___________3(void);
static nova_unit nova_test_min_max_4(void);
static nova_unit nova_test_____________________5(void);
static nova_unit nova_test_streaming__equivalent_one_shot_6(void);
static nova_unit nova_test_streaming___________________________________7(void);

static nova_f64 Nova_Stats_static_mean(NovaArray_nova_f64* xs) {
    /* SRC: if xs.len == 0 { throw EmptyInput } */
    nova_unit _nv_if_0;
    if (((xs->len) == ((nova_int)0LL))) {
        /* SRC: throw EmptyInput */
        Nova_Fail_fail(nova_int_to_str((nova_int)(nova_make_StatsError_EmptyInput())));
        _nv_if_0 = NOVA_UNIT;
    }
    _nv_if_0;
    /* SRC: let mut sum = 0.0 */
    nova_f64 sum = ((nova_f64)0);
    /* SRC: for x in xs { sum = sum + x } */
    NovaArray_nova_f64* _nv_tmp_1 = xs;
    nova_unit _nv_tmp_3;
    for (nova_int _nv_tmp_2 = 0; _nv_tmp_2 < _nv_tmp_1->len; _nv_tmp_2++) {
        nova_f64 x = _nv_tmp_1->data[_nv_tmp_2];
        /* SRC: sum = sum + x */
        sum = (sum + x);
    }
    _nv_tmp_3 = NOVA_UNIT;
    _nv_tmp_3;
    /* SRC: sum / (xs.len as f64 */
    return (sum / (xs->len));
}

static nova_f64 Nova_Stats_static_variance(NovaArray_nova_f64* xs) {
    /* SRC: if xs.len == 0 { throw EmptyInput } */
    nova_unit _nv_if_4;
    if (((xs->len) == ((nova_int)0LL))) {
        /* SRC: throw EmptyInput */
        Nova_Fail_fail(nova_int_to_str((nova_int)(nova_make_StatsError_EmptyInput())));
        _nv_if_4 = NOVA_UNIT;
    }
    _nv_if_4;
    /* SRC: if xs.len == 1 { return 0.0 } */
    nova_unit _nv_if_5;
    if (((xs->len) == ((nova_int)1LL))) {
        /* SRC: return 0.0 */
        return ((nova_f64)0);
        _nv_if_5 = NOVA_UNIT;
    }
    _nv_if_5;
    /* SRC: let m = Stats.mean(xs) */
    nova_f64 m = nova_fn_Stats_mean(xs);
    /* SRC: let mut sum_sq = 0.0 */
    nova_f64 sum_sq = ((nova_f64)0);
    /* SRC: for x in xs { */
    NovaArray_nova_f64* _nv_tmp_6 = xs;
    nova_unit _nv_tmp_8;
    for (nova_int _nv_tmp_7 = 0; _nv_tmp_7 < _nv_tmp_6->len; _nv_tmp_7++) {
        nova_f64 x = _nv_tmp_6->data[_nv_tmp_7];
        /* SRC: let diff = x - m */
        nova_f64 diff = (x - m);
        /* SRC: sum_sq = sum_sq + diff * diff */
        sum_sq = (sum_sq + (diff * diff));
    }
    _nv_tmp_8 = NOVA_UNIT;
    _nv_tmp_8;
    /* SRC: sum_sq / ((xs.len - 1) as f64 */
    return (sum_sq / ((xs->len) - ((nova_int)1LL)));
}

static nova_f64 Nova_Stats_static_stddev(NovaArray_nova_f64* xs) {
    /* SRC: Stats.variance(xs).sqrt() */
    return sqrt(nova_fn_Stats_variance(xs));
}

static nova_f64 Nova_Stats_static_median(NovaArray_nova_f64* xs) {
    /* SRC: if xs.len == 0 { throw EmptyInput } */
    nova_unit _nv_if_9;
    if (((xs->len) == ((nova_int)0LL))) {
        /* SRC: throw EmptyInput */
        Nova_Fail_fail(nova_int_to_str((nova_int)(nova_make_StatsError_EmptyInput())));
        _nv_if_9 = NOVA_UNIT;
    }
    _nv_if_9;
    /* SRC: let sorted = sort_copy(xs) */
    NovaArray_nova_f64* sorted = nova_fn_sort_copy(xs);
    /* SRC: let n = sorted.len */
    nova_int n = (sorted->len);
    /* SRC: if n % 2 == 1 { */
    nova_f64 _nv_if_10;
    if (((n % ((nova_int)2LL)) == ((nova_int)1LL))) {
        _nv_if_10 = (nova_f64)((sorted)->data[(n / ((nova_int)2LL))]);
    } else {
        _nv_if_10 = (nova_f64)((((sorted)->data[((n / ((nova_int)2LL)) - ((nova_int)1LL))] + (sorted)->data[(n / ((nova_int)2LL))]) / ((nova_f64)2)));
    }
    return _nv_if_10;
}

static nova_f64 Nova_Stats_static_percentile(NovaArray_nova_f64* xs, nova_f64 p) {
    /* SRC: if xs.len == 0 { throw EmptyInput } */
    nova_unit _nv_if_11;
    if (((xs->len) == ((nova_int)0LL))) {
        /* SRC: throw EmptyInput */
        Nova_Fail_fail(nova_int_to_str((nova_int)(nova_make_StatsError_EmptyInput())));
        _nv_if_11 = NOVA_UNIT;
    }
    _nv_if_11;
    /* SRC: if p < 0.0 || p > 100.0 { throw InvalidPercentile { value: p } } */
    nova_unit _nv_if_12;
    if (((p < ((nova_f64)0)) || (p > ((nova_f64)100)))) {
        /* SRC: throw InvalidPercentile { value: p } */
        Nova_StatsError* _nv_tmp_13 = nova_make_StatsError_InvalidPercentile(p);
        Nova_Fail_fail(nova_int_to_str((nova_int)(_nv_tmp_13)));
        _nv_if_12 = NOVA_UNIT;
    }
    _nv_if_12;
    /* SRC: let sorted = sort_copy(xs) */
    NovaArray_nova_f64* sorted = nova_fn_sort_copy(xs);
    /* SRC: let n = sorted.len */
    nova_int n = (sorted->len);
    /* SRC: if n == 1 { return sorted[0] } */
    nova_unit _nv_if_14;
    if ((n == ((nova_int)1LL))) {
        /* SRC: return sorted[0] */
        return (sorted)->data[((nova_int)0LL)];
        _nv_if_14 = NOVA_UNIT;
    }
    _nv_if_14;
    /* SRC: let rank = (p / 100.0) * ((n - 1) as f64 */
    nova_f64 rank = ((p / ((nova_f64)100)) * (n - ((nova_int)1LL)));
    /* SRC: let lower = rank.floor() as int */
    nova_int lower = floor(rank);
    /* SRC: let upper = rank.ceil() as int */
    nova_int upper = ceil(rank);
    /* SRC: if lower == upper { */
    nova_f64 _nv_if_15;
    if ((lower == upper)) {
        _nv_if_15 = (nova_f64)((sorted)->data[lower]);
    } else {
        /* SRC: let frac = rank - (lower as f64 */
        nova_f64 frac = (rank - lower);
        _nv_if_15 = (nova_f64)((((sorted)->data[lower] * (((nova_f64)1) - frac)) + ((sorted)->data[upper] * frac)));
    }
    return _nv_if_15;
}

static _NovaTuple2 Nova_Stats_static_min_max(NovaArray_nova_f64* xs) {
    /* SRC: if xs.len == 0 { throw EmptyInput } */
    nova_unit _nv_if_16;
    if (((xs->len) == ((nova_int)0LL))) {
        /* SRC: throw EmptyInput */
        Nova_Fail_fail(nova_int_to_str((nova_int)(nova_make_StatsError_EmptyInput())));
        _nv_if_16 = NOVA_UNIT;
    }
    _nv_if_16;
    /* SRC: let mut lo = xs[0] */
    nova_f64 lo = (xs)->data[((nova_int)0LL)];
    /* SRC: let mut hi = xs[0] */
    nova_f64 hi = (xs)->data[((nova_int)0LL)];
    /* SRC: for x in xs { */
    NovaArray_nova_f64* _nv_tmp_17 = xs;
    nova_unit _nv_tmp_19;
    for (nova_int _nv_tmp_18 = 0; _nv_tmp_18 < _nv_tmp_17->len; _nv_tmp_18++) {
        nova_f64 x = _nv_tmp_17->data[_nv_tmp_18];
        /* SRC: if x < lo { lo = x } */
        nova_unit _nv_if_20;
        if ((x < lo)) {
            /* SRC: lo = x */
            lo = x;
            _nv_if_20 = NOVA_UNIT;
        }
        _nv_if_20;
        nova_unit _nv_if_21;
        if ((x > hi)) {
            /* SRC: hi = x */
            hi = x;
            _nv_if_21 = NOVA_UNIT;
        }
        (void)(_nv_if_21);
    }
    _nv_tmp_19 = NOVA_UNIT;
    _nv_tmp_19;
    /* SRC: (lo, hi) */
    _NovaTuple2 _nv_tmp_22;
    _nv_tmp_22.f0 = (nova_int)(lo);
    _nv_tmp_22.f1 = (nova_int)(hi);
    return _nv_tmp_22;
}

static nova_f64 Nova_Stats_static_sum(NovaArray_nova_f64* xs) {
    /* SRC: let mut s = 0.0 */
    nova_f64 s = ((nova_f64)0);
    /* SRC: for x in xs { s = s + x } */
    NovaArray_nova_f64* _nv_tmp_23 = xs;
    nova_unit _nv_tmp_25;
    for (nova_int _nv_tmp_24 = 0; _nv_tmp_24 < _nv_tmp_23->len; _nv_tmp_24++) {
        nova_f64 x = _nv_tmp_23->data[_nv_tmp_24];
        /* SRC: s = s + x */
        s = (s + x);
    }
    _nv_tmp_25 = NOVA_UNIT;
    _nv_tmp_25;
    /* SRC: s */
    return s;
}

static NovaArray_nova_f64* nova_fn_sort_copy(NovaArray_nova_f64* xs) {
    /* SRC: let mut sorted []f64 = [] */
    NovaArray_nova_int* _nv_tmp_26 = nova_array_new_nova_int(8);
    NovaArray_nova_f64* sorted = _nv_tmp_26;
    /* SRC: for x in xs { sorted.push(x) } */
    NovaArray_nova_f64* _nv_tmp_27 = xs;
    nova_unit _nv_tmp_29;
    for (nova_int _nv_tmp_28 = 0; _nv_tmp_28 < _nv_tmp_27->len; _nv_tmp_28++) {
        nova_f64 x = _nv_tmp_27->data[_nv_tmp_28];
        nova_array_push_nova_f64(sorted, x);
        (void)(NOVA_UNIT);
    }
    _nv_tmp_29 = NOVA_UNIT;
    _nv_tmp_29;
    /* SRC: let n = sorted.len */
    nova_int n = (sorted->len);
    /* SRC: let mut i = 0 */
    nova_int i = ((nova_int)0LL);
    /* SRC: while i < n { */
    nova_unit _nv_while_30;
    while ((i < n)) {
        /* SRC: let mut j = 0 */
        nova_int j = ((nova_int)0LL);
        /* SRC: while j < n - 1 - i { */
        nova_unit _nv_while_31;
        while ((j < ((n - ((nova_int)1LL)) - i))) {
            /* SRC: if sorted[j] > sorted[j + 1] { */
            nova_unit _nv_if_32;
            if (((sorted)->data[j] > (sorted)->data[(j + ((nova_int)1LL))])) {
                /* SRC: let tmp = sorted[j] */
                nova_f64 tmp = (sorted)->data[j];
                /* SRC: sorted[j] = sorted[j + 1] */
                (sorted)->data[j] = (sorted)->data[(j + ((nova_int)1LL))];
                /* SRC: sorted[j + 1] = tmp */
                (sorted)->data[(j + ((nova_int)1LL))] = tmp;
                _nv_if_32 = NOVA_UNIT;
            }
            _nv_if_32;
            /* SRC: j += 1 */
            j += ((nova_int)1LL);
        }
        _nv_while_31 = NOVA_UNIT;
        _nv_while_31;
        /* SRC: i += 1 */
        i += ((nova_int)1LL);
    }
    _nv_while_30 = NOVA_UNIT;
    _nv_while_30;
    /* SRC: sorted */
    return sorted;
}

static Nova_StreamingStats* Nova_Stats_static_streaming(void) {
    /* SRC: { */
    Nova_StreamingStats* _nv_tmp_33 = (Nova_StreamingStats*)nova_alloc(sizeof(Nova_StreamingStats));
    _nv_tmp_33->count = ((nova_int)0LL);
    _nv_tmp_33->mean_val = ((nova_f64)0);
    _nv_tmp_33->m2 = ((nova_f64)0);
    _nv_tmp_33->min_val = ((nova_f64)0);
    _nv_tmp_33->max_val = ((nova_f64)0);
    return _nv_tmp_33;
}

static nova_unit Nova_StreamingStats_method_add(Nova_StreamingStats* nova_self, nova_f64 x) {
    /* SRC: @count += 1 */
    (nova_self->count) += ((nova_int)1LL);
    /* SRC: if @count == 1 { */
    nova_unit _nv_if_34;
    if (((nova_self->count) == ((nova_int)1LL))) {
        /* SRC: @min_val = x */
        (nova_self->min_val) = x;
        /* SRC: @max_val = x */
        (nova_self->max_val) = x;
        _nv_if_34 = NOVA_UNIT;
    } else {
        /* SRC: if x < @min_val { @min_val = x } */
        nova_unit _nv_if_35;
        if ((x < (nova_self->min_val))) {
            /* SRC: @min_val = x */
            (nova_self->min_val) = x;
            _nv_if_35 = NOVA_UNIT;
        }
        _nv_if_35;
        nova_unit _nv_if_36;
        if ((x > (nova_self->max_val))) {
            /* SRC: @max_val = x */
            (nova_self->max_val) = x;
            _nv_if_36 = NOVA_UNIT;
        }
        _nv_if_34 = NOVA_UNIT; (void)(_nv_if_36);
    }
    _nv_if_34;
    /* SRC: let delta = x - @mean_val */
    nova_f64 delta = (x - (nova_self->mean_val));
    /* SRC: @mean_val = @mean_val + delta / (@count as f64 */
    (nova_self->mean_val) = ((nova_self->mean_val) + (delta / (nova_self->count)));
    /* SRC: let delta2 = x - @mean_val */
    nova_f64 delta2 = (x - (nova_self->mean_val));
    /* SRC: @m2 = @m2 + delta * delta2 */
    (nova_self->m2) = ((nova_self->m2) + (delta * delta2));
    return NOVA_UNIT;
}

static nova_int Nova_StreamingStats_method_count_value(Nova_StreamingStats* nova_self) {
    /* SRC: @count */
    return (nova_self->count);
}

static nova_f64 Nova_StreamingStats_method_mean(Nova_StreamingStats* nova_self) {
    /* SRC: if @count == 0 { throw EmptyInput } */
    nova_unit _nv_if_37;
    if (((nova_self->count) == ((nova_int)0LL))) {
        /* SRC: throw EmptyInput */
        Nova_Fail_fail(nova_int_to_str((nova_int)(nova_make_StatsError_EmptyInput())));
        _nv_if_37 = NOVA_UNIT;
    }
    _nv_if_37;
    /* SRC: @mean_val */
    return (nova_self->mean_val);
}

static nova_f64 Nova_StreamingStats_method_variance(Nova_StreamingStats* nova_self) {
    /* SRC: if @count == 0 { throw EmptyInput } */
    nova_unit _nv_if_38;
    if (((nova_self->count) == ((nova_int)0LL))) {
        /* SRC: throw EmptyInput */
        Nova_Fail_fail(nova_int_to_str((nova_int)(nova_make_StatsError_EmptyInput())));
        _nv_if_38 = NOVA_UNIT;
    }
    _nv_if_38;
    /* SRC: if @count == 1 { return 0.0 } */
    nova_unit _nv_if_39;
    if (((nova_self->count) == ((nova_int)1LL))) {
        /* SRC: return 0.0 */
        return ((nova_f64)0);
        _nv_if_39 = NOVA_UNIT;
    }
    _nv_if_39;
    /* SRC: @m2 / ((@count - 1) as f64 */
    return ((nova_self->m2) / ((nova_self->count) - ((nova_int)1LL)));
}

static nova_f64 Nova_StreamingStats_method_stddev(Nova_StreamingStats* nova_self) {
    /* SRC: @variance().sqrt() */
    return sqrt(Nova_StreamingStats_method_variance(nova_self));
}

static nova_f64 Nova_StreamingStats_method_min(Nova_StreamingStats* nova_self) {
    /* SRC: if @count == 0 { throw EmptyInput } */
    nova_unit _nv_if_40;
    if (((nova_self->count) == ((nova_int)0LL))) {
        /* SRC: throw EmptyInput */
        Nova_Fail_fail(nova_int_to_str((nova_int)(nova_make_StatsError_EmptyInput())));
        _nv_if_40 = NOVA_UNIT;
    }
    _nv_if_40;
    /* SRC: @min_val */
    return (nova_self->min_val);
}

static nova_f64 Nova_StreamingStats_method_max(Nova_StreamingStats* nova_self) {
    /* SRC: if @count == 0 { throw EmptyInput } */
    nova_unit _nv_if_41;
    if (((nova_self->count) == ((nova_int)0LL))) {
        /* SRC: throw EmptyInput */
        Nova_Fail_fail(nova_int_to_str((nova_int)(nova_make_StatsError_EmptyInput())));
        _nv_if_41 = NOVA_UNIT;
    }
    _nv_if_41;
    /* SRC: @max_val */
    return (nova_self->max_val);
}

static nova_unit nova_test_mean_________0(void) {
    /* SRC: assert(Stats.mean([1.0, 2.0, 3.0, 4.0, 5.0]) == 3.0) */
    NovaArray_nova_int* _nv_tmp_42 = nova_array_new_nova_int(5);
    nova_array_push_nova_int(_nv_tmp_42, (nova_int)(((nova_f64)1)));
    nova_array_push_nova_int(_nv_tmp_42, (nova_int)(((nova_f64)2)));
    nova_array_push_nova_int(_nv_tmp_42, (nova_int)(((nova_f64)3)));
    nova_array_push_nova_int(_nv_tmp_42, (nova_int)(((nova_f64)4)));
    nova_array_push_nova_int(_nv_tmp_42, (nova_int)(((nova_f64)5)));
    nova_assert((nova_fn_Stats_mean(_nv_tmp_42) == ((nova_f64)3)), "assert(assert) == assert");
    return NOVA_UNIT;
}

static nova_unit nova_test_median__________________________1(void) {
    /* SRC: assert(Stats.median([1.0, 2.0, 3.0]) == 2.0) */
    NovaArray_nova_int* _nv_tmp_43 = nova_array_new_nova_int(3);
    nova_array_push_nova_int(_nv_tmp_43, (nova_int)(((nova_f64)1)));
    nova_array_push_nova_int(_nv_tmp_43, (nova_int)(((nova_f64)2)));
    nova_array_push_nova_int(_nv_tmp_43, (nova_int)(((nova_f64)3)));
    nova_assert((Nova_Stats_static_median(_nv_tmp_43) == ((nova_f64)2)), "assert(assert) == assert");
    /* SRC: assert(Stats.median([1.0, 2.0, 3.0, 4.0]) == 2.5) */
    NovaArray_nova_int* _nv_tmp_44 = nova_array_new_nova_int(4);
    nova_array_push_nova_int(_nv_tmp_44, (nova_int)(((nova_f64)1)));
    nova_array_push_nova_int(_nv_tmp_44, (nova_int)(((nova_f64)2)));
    nova_array_push_nova_int(_nv_tmp_44, (nova_int)(((nova_f64)3)));
    nova_array_push_nova_int(_nv_tmp_44, (nova_int)(((nova_f64)4)));
    nova_assert((Nova_Stats_static_median(_nv_tmp_44) == ((nova_f64)2.5)), "assert(assert) == assert");
    /* SRC: assert(Stats.median([5.0, 1.0, 3.0]) == 3.0) */
    NovaArray_nova_int* _nv_tmp_45 = nova_array_new_nova_int(3);
    nova_array_push_nova_int(_nv_tmp_45, (nova_int)(((nova_f64)5)));
    nova_array_push_nova_int(_nv_tmp_45, (nova_int)(((nova_f64)1)));
    nova_array_push_nova_int(_nv_tmp_45, (nova_int)(((nova_f64)3)));
    nova_assert((Nova_Stats_static_median(_nv_tmp_45) == ((nova_f64)3)), "assert(assert) == assert");
    return NOVA_UNIT;
}

static nova_unit nova_test_variance___stddev_2(void) {
    /* SRC: let xs = [2.0, 4.0, 4.0, 4.0, 5.0, 5.0, 7.0, 9.0] */
    NovaArray_nova_int* _nv_tmp_46 = nova_array_new_nova_int(8);
    nova_array_push_nova_int(_nv_tmp_46, (nova_int)(((nova_f64)2)));
    nova_array_push_nova_int(_nv_tmp_46, (nova_int)(((nova_f64)4)));
    nova_array_push_nova_int(_nv_tmp_46, (nova_int)(((nova_f64)4)));
    nova_array_push_nova_int(_nv_tmp_46, (nova_int)(((nova_f64)4)));
    nova_array_push_nova_int(_nv_tmp_46, (nova_int)(((nova_f64)5)));
    nova_array_push_nova_int(_nv_tmp_46, (nova_int)(((nova_f64)5)));
    nova_array_push_nova_int(_nv_tmp_46, (nova_int)(((nova_f64)7)));
    nova_array_push_nova_int(_nv_tmp_46, (nova_int)(((nova_f64)9)));
    NovaArray_nova_int* xs = _nv_tmp_46;
    /* SRC: let v = Stats.variance(xs) */
    nova_f64 v = nova_fn_Stats_variance(xs);
    /* SRC: assert (v - 4.5714285714).abs() < 0.0001 */
    (nova_assert((v - ((nova_f64)4.5714285714)), "v - assert").abs() < ((nova_f64)0.0001));
    /* SRC: let s = Stats.stddev(xs) */
    nova_f64 s = nova_fn_Stats_stddev(xs);
    /* SRC: assert (s - 2.1380899352).abs() < 0.0001 */
    (nova_assert((s - ((nova_f64)2.1380899352)), "s - assert").abs() < ((nova_f64)0.0001));
    return NOVA_UNIT;
}

static nova_unit nova_test_percentile___________3(void) {
    /* SRC: let xs = [1.0, 2.0, 3.0, 4.0, 5.0, 6.0, 7.0, 8.0, 9.0, 10.0] */
    NovaArray_nova_int* _nv_tmp_47 = nova_array_new_nova_int(10);
    nova_array_push_nova_int(_nv_tmp_47, (nova_int)(((nova_f64)1)));
    nova_array_push_nova_int(_nv_tmp_47, (nova_int)(((nova_f64)2)));
    nova_array_push_nova_int(_nv_tmp_47, (nova_int)(((nova_f64)3)));
    nova_array_push_nova_int(_nv_tmp_47, (nova_int)(((nova_f64)4)));
    nova_array_push_nova_int(_nv_tmp_47, (nova_int)(((nova_f64)5)));
    nova_array_push_nova_int(_nv_tmp_47, (nova_int)(((nova_f64)6)));
    nova_array_push_nova_int(_nv_tmp_47, (nova_int)(((nova_f64)7)));
    nova_array_push_nova_int(_nv_tmp_47, (nova_int)(((nova_f64)8)));
    nova_array_push_nova_int(_nv_tmp_47, (nova_int)(((nova_f64)9)));
    nova_array_push_nova_int(_nv_tmp_47, (nova_int)(((nova_f64)10)));
    NovaArray_nova_int* xs = _nv_tmp_47;
    /* SRC: assert (Stats.percentile(xs, 50.0) - 5.5).abs() < 0.001 */
    (nova_assert((Nova_Stats_static_percentile(xs, ((nova_f64)50)) - ((nova_f64)5.5)), "assert(xs, assert) - assert").abs() < ((nova_f64)0.001));
    /* SRC: assert (Stats.percentile(xs, 0.0) - 1.0).abs() < 0.001 */
    (nova_assert((Nova_Stats_static_percentile(xs, ((nova_f64)0)) - ((nova_f64)1)), "assert(xs, assert) - assert").abs() < ((nova_f64)0.001));
    /* SRC: assert (Stats.percentile(xs, 100.0) - 10.0).abs() < 0.001 */
    (nova_assert((Nova_Stats_static_percentile(xs, ((nova_f64)100)) - ((nova_f64)10)), "assert(xs, assert) - assert").abs() < ((nova_f64)0.001));
    return NOVA_UNIT;
}

static nova_unit nova_test_min_max_4(void) {
    /* SRC: let (lo, hi) = Stats.min_max([3.0, 1.0, 4.0, 1.0, 5.0, 9.0, 2.0]) */
    NovaArray_nova_int* _nv_tmp_49 = nova_array_new_nova_int(7);
    nova_array_push_nova_int(_nv_tmp_49, (nova_int)(((nova_f64)3)));
    nova_array_push_nova_int(_nv_tmp_49, (nova_int)(((nova_f64)1)));
    nova_array_push_nova_int(_nv_tmp_49, (nova_int)(((nova_f64)4)));
    nova_array_push_nova_int(_nv_tmp_49, (nova_int)(((nova_f64)1)));
    nova_array_push_nova_int(_nv_tmp_49, (nova_int)(((nova_f64)5)));
    nova_array_push_nova_int(_nv_tmp_49, (nova_int)(((nova_f64)9)));
    nova_array_push_nova_int(_nv_tmp_49, (nova_int)(((nova_f64)2)));
    _NovaTuple2 _nv_tmp_48 = Nova_Stats_static_min_max(_nv_tmp_49);
    nova_int lo = _nv_tmp_48.f0;
    nova_int hi = _nv_tmp_48.f1;
    /* SRC: assert(lo == 1.0) */
    nova_assert((lo == ((nova_f64)1)), "lo == assert");
    /* SRC: assert(hi == 9.0) */
    nova_assert((hi == ((nova_f64)9)), "hi == assert");
    return NOVA_UNIT;
}

static nova_int nova_lambda_0_body(void* _env_ptr, nova_int e);
typedef struct { int _dummy; } nova_lambda_0_env;
static nova_int nova_lambda_0_body(void* _env_ptr, nova_int e) {
    nova_interrupt((nova_int)(nova_make_Option_Some(e)));
    return NOVA_UNIT;
}

static nova_unit nova_test_____________________5(void) {
    /* SRC: let r = with Fail[StatsError] = (e) => interrupt Some(e) { */
    nova_lambda_0_env* _nv_tmp_50 = (nova_lambda_0_env*)nova_alloc(sizeof(nova_lambda_0_env));
    NovaClos_ii* _nv_tmp_51 = (NovaClos_ii*)nova_alloc(sizeof(NovaClos_ii));
    _nv_tmp_51->fn = (nova_fn_ii)(nova_lambda_0_body);
    _nv_tmp_51->env = (void*)(_nv_tmp_50);
    NovaVtable_Fail* _nv_tmp_52 = _nova_handler_Fail;
    _nova_handler_Fail = (void*)(_nv_tmp_51);
    NovaFailFrame _nv_tmp_53;
    nova_fail_push(&_nv_tmp_53);
    NovaInterruptFrame _nv_tmp_54;
    nova_int _nv_tmp_55;
    nova_interrupt_push(&_nv_tmp_54);
    if (setjmp(_nv_tmp_53.jmp) == 0) {
        if (setjmp(_nv_tmp_54.jmp) == 0) {
            {
                /* SRC: let _ = Stats.mean([]) */
                NovaArray_nova_int* _nv_tmp_57 = nova_array_new_nova_int(8);
                nova_f64 _nv_tmp_56 = nova_fn_Stats_mean(_nv_tmp_57);
                (void)(nova_make_Option_None());
                _nv_tmp_55 = ((nova_int)0LL);
            }
        } else {
            _nv_tmp_55 = _nv_tmp_54.value;
        }
    } else {
        _nv_tmp_55 = ((nova_int)0LL);
    }
    nova_fail_pop();
    _nova_handler_Fail = _nv_tmp_52;
    nova_interrupt_pop();
    nova_int r = _nv_tmp_55;
    /* SRC: assert(match r { */
    nova_int _nv_scr_58 = r;
    nova_bool _nv_match_59;
    int _nv_matched_60 = 0;
    if (!_nv_matched_60 && (((_nv_scr_58->tag == NOVA_TAG_Option_Some) && (_nv_scr_58->payload.Some._0->tag == NOVA_TAG_StatsError_EmptyInput)))) {
        _nv_match_59 = true;
        _nv_matched_60 = 1;
    }
    if (!_nv_matched_60 && (true)) {
        _nv_match_59 = false;
        _nv_matched_60 = 1;
    }
    nova_assert(_nv_match_59, "assert");
    return NOVA_UNIT;
}

static nova_unit nova_test_streaming__equivalent_one_shot_6(void) {
    /* SRC: let xs = [2.0, 4.0, 4.0, 4.0, 5.0, 5.0, 7.0, 9.0] */
    NovaArray_nova_int* _nv_tmp_61 = nova_array_new_nova_int(8);
    nova_array_push_nova_int(_nv_tmp_61, (nova_int)(((nova_f64)2)));
    nova_array_push_nova_int(_nv_tmp_61, (nova_int)(((nova_f64)4)));
    nova_array_push_nova_int(_nv_tmp_61, (nova_int)(((nova_f64)4)));
    nova_array_push_nova_int(_nv_tmp_61, (nova_int)(((nova_f64)4)));
    nova_array_push_nova_int(_nv_tmp_61, (nova_int)(((nova_f64)5)));
    nova_array_push_nova_int(_nv_tmp_61, (nova_int)(((nova_f64)5)));
    nova_array_push_nova_int(_nv_tmp_61, (nova_int)(((nova_f64)7)));
    nova_array_push_nova_int(_nv_tmp_61, (nova_int)(((nova_f64)9)));
    NovaArray_nova_int* xs = _nv_tmp_61;
    /* SRC: let mut acc = Stats.streaming() */
    Nova_StreamingStats* acc = Nova_Stats_static_streaming();
    /* SRC: for x in xs { acc.add(x) } */
    NovaArray_nova_int* _nv_tmp_62 = xs;
    nova_unit _nv_tmp_64;
    for (nova_int _nv_tmp_63 = 0; _nv_tmp_63 < _nv_tmp_62->len; _nv_tmp_63++) {
        nova_f64 x = _nv_tmp_62->data[_nv_tmp_63];
        (void)(Nova_StreamingStats_method_add(acc, x));
    }
    _nv_tmp_64 = NOVA_UNIT;
    _nv_tmp_64;
    /* SRC: assert (acc.mean() - Stats.mean(xs)).abs() < 0.0001 */
    (nova_assert((Nova_StreamingStats_method_mean(acc) - nova_fn_Stats_mean(xs)), "assert() - assert(xs)").abs() < ((nova_f64)0.0001));
    /* SRC: assert (acc.variance() - Stats.variance(xs)).abs() < 0.0001 */
    (nova_assert((Nova_StreamingStats_method_variance(acc) - nova_fn_Stats_variance(xs)), "assert() - assert(xs)").abs() < ((nova_f64)0.0001));
    /* SRC: assert(acc.min() == 2.0) */
    nova_assert((Nova_StreamingStats_method_min(acc) == ((nova_f64)2)), "assert() == assert");
    /* SRC: assert(acc.max() == 9.0) */
    nova_assert((Nova_StreamingStats_method_max(acc) == ((nova_f64)9)), "assert() == assert");
    return NOVA_UNIT;
}

static nova_unit nova_test_streaming___________________________________7(void) {
    /* SRC: let mut acc = Stats.streaming() */
    Nova_StreamingStats* acc = Nova_Stats_static_streaming();
    /* SRC: let mut i = 0 */
    nova_int i = ((nova_int)0LL);
    /* SRC: while i < 1000 { */
    nova_unit _nv_while_65;
    while ((i < ((nova_int)1000LL))) {
        /* SRC: acc.add(1_000_000.0 + (i as f64)) */
        Nova_StreamingStats_method_add(acc, (((nova_f64)1000000) + i));
        /* SRC: i += 1 */
        i += ((nova_int)1LL);
    }
    _nv_while_65 = NOVA_UNIT;
    _nv_while_65;
    /* SRC: let v = acc.variance() */
    nova_f64 v = Nova_StreamingStats_method_variance(acc);
    /* SRC: assert (v - 83416.666666666).abs() < 0.01 */
    (nova_assert((v - ((nova_f64)83416.666666666)), "v - assert").abs() < ((nova_f64)0.01));
    return NOVA_UNIT;
}

static nova_unit nova_fn_main_impl(void) {
    int _nova_tests_total = 8;
    int _nova_tests_failed = 0;
    printf("Running %d tests...\n", _nova_tests_total);
    {
        NovaTestFrame _tf;
        _tf.fail_msg = NULL;
        _nova_test_frame = &_tf;
        NovaFailFrame _tf_fail;
        _tf_fail.error_msg = (nova_str){.ptr=NULL, .len=0};
        nova_fail_push(&_tf_fail);
        int _tf_jmp = setjmp(_tf.jmp);
        int _tf_fail_jmp = (_tf_jmp == 0) ? setjmp(_tf_fail.jmp) : 0;
        if (_tf_jmp == 0 && _tf_fail_jmp == 0) {
            nova_test_mean_________0();
            printf("  PASS: mean базовый\n");
        } else {
            const char* _tf_msg = _tf.fail_msg ? _tf.fail_msg : (_tf_fail.error_msg.ptr ? _tf_fail.error_msg.ptr : "assertion failed");
            printf("  FAIL: mean базовый — %s\n", _tf_msg);
            _nova_tests_failed++;
        }
        nova_fail_pop();
        _nova_test_frame = NULL;
    }
    {
        NovaTestFrame _tf;
        _tf.fail_msg = NULL;
        _nova_test_frame = &_tf;
        NovaFailFrame _tf_fail;
        _tf_fail.error_msg = (nova_str){.ptr=NULL, .len=0};
        nova_fail_push(&_tf_fail);
        int _tf_jmp = setjmp(_tf.jmp);
        int _tf_fail_jmp = (_tf_jmp == 0) ? setjmp(_tf_fail.jmp) : 0;
        if (_tf_jmp == 0 && _tf_fail_jmp == 0) {
            nova_test_median__________________________1();
            printf("  PASS: median: нечётная и чётная длина\n");
        } else {
            const char* _tf_msg = _tf.fail_msg ? _tf.fail_msg : (_tf_fail.error_msg.ptr ? _tf_fail.error_msg.ptr : "assertion failed");
            printf("  FAIL: median: нечётная и чётная длина — %s\n", _tf_msg);
            _nova_tests_failed++;
        }
        nova_fail_pop();
        _nova_test_frame = NULL;
    }
    {
        NovaTestFrame _tf;
        _tf.fail_msg = NULL;
        _nova_test_frame = &_tf;
        NovaFailFrame _tf_fail;
        _tf_fail.error_msg = (nova_str){.ptr=NULL, .len=0};
        nova_fail_push(&_tf_fail);
        int _tf_jmp = setjmp(_tf.jmp);
        int _tf_fail_jmp = (_tf_jmp == 0) ? setjmp(_tf_fail.jmp) : 0;
        if (_tf_jmp == 0 && _tf_fail_jmp == 0) {
            nova_test_variance___stddev_2();
            printf("  PASS: variance / stddev\n");
        } else {
            const char* _tf_msg = _tf.fail_msg ? _tf.fail_msg : (_tf_fail.error_msg.ptr ? _tf_fail.error_msg.ptr : "assertion failed");
            printf("  FAIL: variance / stddev — %s\n", _tf_msg);
            _nova_tests_failed++;
        }
        nova_fail_pop();
        _nova_test_frame = NULL;
    }
    {
        NovaTestFrame _tf;
        _tf.fail_msg = NULL;
        _nova_test_frame = &_tf;
        NovaFailFrame _tf_fail;
        _tf_fail.error_msg = (nova_str){.ptr=NULL, .len=0};
        nova_fail_push(&_tf_fail);
        int _tf_jmp = setjmp(_tf.jmp);
        int _tf_fail_jmp = (_tf_jmp == 0) ? setjmp(_tf_fail.jmp) : 0;
        if (_tf_jmp == 0 && _tf_fail_jmp == 0) {
            nova_test_percentile___________3();
            printf("  PASS: percentile: квартили\n");
        } else {
            const char* _tf_msg = _tf.fail_msg ? _tf.fail_msg : (_tf_fail.error_msg.ptr ? _tf_fail.error_msg.ptr : "assertion failed");
            printf("  FAIL: percentile: квартили — %s\n", _tf_msg);
            _nova_tests_failed++;
        }
        nova_fail_pop();
        _nova_test_frame = NULL;
    }
    {
        NovaTestFrame _tf;
        _tf.fail_msg = NULL;
        _nova_test_frame = &_tf;
        NovaFailFrame _tf_fail;
        _tf_fail.error_msg = (nova_str){.ptr=NULL, .len=0};
        nova_fail_push(&_tf_fail);
        int _tf_jmp = setjmp(_tf.jmp);
        int _tf_fail_jmp = (_tf_jmp == 0) ? setjmp(_tf_fail.jmp) : 0;
        if (_tf_jmp == 0 && _tf_fail_jmp == 0) {
            nova_test_min_max_4();
            printf("  PASS: min_max\n");
        } else {
            const char* _tf_msg = _tf.fail_msg ? _tf.fail_msg : (_tf_fail.error_msg.ptr ? _tf_fail.error_msg.ptr : "assertion failed");
            printf("  FAIL: min_max — %s\n", _tf_msg);
            _nova_tests_failed++;
        }
        nova_fail_pop();
        _nova_test_frame = NULL;
    }
    {
        NovaTestFrame _tf;
        _tf.fail_msg = NULL;
        _nova_test_frame = &_tf;
        NovaFailFrame _tf_fail;
        _tf_fail.error_msg = (nova_str){.ptr=NULL, .len=0};
        nova_fail_push(&_tf_fail);
        int _tf_jmp = setjmp(_tf.jmp);
        int _tf_fail_jmp = (_tf_jmp == 0) ? setjmp(_tf_fail.jmp) : 0;
        if (_tf_jmp == 0 && _tf_fail_jmp == 0) {
            nova_test_____________________5();
            printf("  PASS: ошибка: пустой ввод\n");
        } else {
            const char* _tf_msg = _tf.fail_msg ? _tf.fail_msg : (_tf_fail.error_msg.ptr ? _tf_fail.error_msg.ptr : "assertion failed");
            printf("  FAIL: ошибка: пустой ввод — %s\n", _tf_msg);
            _nova_tests_failed++;
        }
        nova_fail_pop();
        _nova_test_frame = NULL;
    }
    {
        NovaTestFrame _tf;
        _tf.fail_msg = NULL;
        _nova_test_frame = &_tf;
        NovaFailFrame _tf_fail;
        _tf_fail.error_msg = (nova_str){.ptr=NULL, .len=0};
        nova_fail_push(&_tf_fail);
        int _tf_jmp = setjmp(_tf.jmp);
        int _tf_fail_jmp = (_tf_jmp == 0) ? setjmp(_tf_fail.jmp) : 0;
        if (_tf_jmp == 0 && _tf_fail_jmp == 0) {
            nova_test_streaming__equivalent_one_shot_6();
            printf("  PASS: streaming: equivalent one-shot\n");
        } else {
            const char* _tf_msg = _tf.fail_msg ? _tf.fail_msg : (_tf_fail.error_msg.ptr ? _tf_fail.error_msg.ptr : "assertion failed");
            printf("  FAIL: streaming: equivalent one-shot — %s\n", _tf_msg);
            _nova_tests_failed++;
        }
        nova_fail_pop();
        _nova_test_frame = NULL;
    }
    {
        NovaTestFrame _tf;
        _tf.fail_msg = NULL;
        _nova_test_frame = &_tf;
        NovaFailFrame _tf_fail;
        _tf_fail.error_msg = (nova_str){.ptr=NULL, .len=0};
        nova_fail_push(&_tf_fail);
        int _tf_jmp = setjmp(_tf.jmp);
        int _tf_fail_jmp = (_tf_jmp == 0) ? setjmp(_tf_fail.jmp) : 0;
        if (_tf_jmp == 0 && _tf_fail_jmp == 0) {
            nova_test_streaming___________________________________7();
            printf("  PASS: streaming: больших чисел не теряет точность\n");
        } else {
            const char* _tf_msg = _tf.fail_msg ? _tf.fail_msg : (_tf_fail.error_msg.ptr ? _tf_fail.error_msg.ptr : "assertion failed");
            printf("  FAIL: streaming: больших чисел не теряет точность — %s\n", _tf_msg);
            _nova_tests_failed++;
        }
        nova_fail_pop();
        _nova_test_frame = NULL;
    }
    printf("%d/%d passed\n", _nova_tests_total - _nova_tests_failed, _nova_tests_total);
    if (_nova_tests_failed > 0) { exit(1); }
    return NOVA_UNIT;
}

int main(void) {
    nova_gc_init();
    nova_register_effect_storage((void**)&_nova_handler_Fail);
    nova_register_effect_storage((void**)&_nova_handler_Time);
    nova_fn_main_impl();
    nova_gc_shutdown();
    return 0;
}
