/* Generated by nova-codegen. Do not edit. */
#include "nova_rt/nova_rt.h"

typedef struct {
    void* ctx;
    nova_int (*next)(void*); 
} NovaVtable_Counter;

__declspec(thread) static NovaVtable_Counter* _nova_handler_Counter = NULL;

static inline nova_int Nova_Counter_next(void) {
    return _nova_handler_Counter->next(_nova_handler_Counter->ctx);
}

typedef struct {
    void* ctx;
    nova_bool (*flip)(void*); 
} NovaVtable_Switch;

__declspec(thread) static NovaVtable_Switch* _nova_handler_Switch = NULL;

static inline nova_bool Nova_Switch_flip(void) {
    return _nova_handler_Switch->flip(_nova_handler_Switch->ctx);
}

static nova_int nova_fn_count_three(void);

static nova_int _nova_handler_lit_0_impl_Counter_next(void* _ctx);
static nova_bool _nova_handler_lit_1_impl_Switch_flip(void* _ctx);
static nova_bool _nova_handler_lit_2_impl_Switch_flip(void* _ctx);
static nova_int nova_fn_count_three(void) {
    nova_int a = Nova_Counter_next();
    nova_int b = Nova_Counter_next();
    nova_int c = Nova_Counter_next();
    return ((a + b) + c);
}

static nova_unit nova_fn_main_impl(void) {
    nova_int state = ((nova_int)0LL);
    typedef struct {
        nova_int* state;
    } NovaCtx__nova_handler_lit_0;
    static NovaVtable_Counter _nova_handler_lit_0_vtable;  /* zero-initialized */
    NovaCtx__nova_handler_lit_0 _nova_handler_lit_0_ctx = {0};
    _nova_handler_lit_0_ctx.state = &state;
    _nova_handler_lit_0_vtable.ctx = &_nova_handler_lit_0_ctx;
    _nova_handler_lit_0_vtable.next = _nova_handler_lit_0_impl_Counter_next;
    NovaVtable_Counter* _nova_tmp0 = &_nova_handler_lit_0_vtable;
    NovaVtable_Counter* _nova_tmp1 = _nova_handler_Counter;
    _nova_handler_Counter = _nova_tmp0;
    NovaInterruptFrame _nova_tmp2;
    nova_int _nova_tmp3;
    nova_interrupt_push(&_nova_tmp2);
    if (setjmp(_nova_tmp2.jmp) == 0) {
        {
            nova_int total = nova_fn_count_three();
            nova_unit _nova_tmp4;
            {
                nova_print_str((nova_str){.ptr="total = ", .len=8});
                nova_print_int(total);
                nova_print_newline();
            }
            _nova_tmp4 = NOVA_UNIT;
            (void)(_nova_tmp4);
            _nova_tmp3 = ((nova_int)0LL);
        }
        _nova_handler_Counter = _nova_tmp1;
    } else {
        _nova_handler_Counter = _nova_tmp1;
        _nova_tmp3 = _nova_tmp2.value;
    }
    nova_interrupt_pop();
    _nova_tmp3;
    typedef struct {
        char _dummy;
    } NovaCtx__nova_handler_lit_1;
    static NovaVtable_Switch _nova_handler_lit_1_vtable;  /* zero-initialized */
    NovaCtx__nova_handler_lit_1 _nova_handler_lit_1_ctx = {0};
    _nova_handler_lit_1_vtable.ctx = &_nova_handler_lit_1_ctx;
    _nova_handler_lit_1_vtable.flip = _nova_handler_lit_1_impl_Switch_flip;
    NovaVtable_Switch* _nova_tmp5 = &_nova_handler_lit_1_vtable;
    NovaVtable_Switch* _nova_tmp6 = _nova_handler_Switch;
    _nova_handler_Switch = _nova_tmp5;
    NovaInterruptFrame _nova_tmp7;
    nova_int _nova_tmp8;
    nova_interrupt_push(&_nova_tmp7);
    if (setjmp(_nova_tmp7.jmp) == 0) {
        {
            nova_int _nova_tmp9 = Nova_Switch_flip();
            _nova_tmp8 = (nova_int)(((nova_int)0LL));
        }
        _nova_handler_Switch = _nova_tmp6;
    } else {
        _nova_handler_Switch = _nova_tmp6;
        _nova_tmp8 = _nova_tmp7.value;
    }
    nova_interrupt_pop();
    nova_int r = _nova_tmp8;
    nova_unit _nova_tmp10;
    {
        nova_print_str((nova_str){.ptr="interrupt result = ", .len=19});
        nova_print_int(r);
        nova_print_newline();
    }
    _nova_tmp10 = NOVA_UNIT;
    _nova_tmp10;
    typedef struct {
        char _dummy;
    } NovaCtx__nova_handler_lit_2;
    static NovaVtable_Switch _nova_handler_lit_2_vtable;  /* zero-initialized */
    NovaCtx__nova_handler_lit_2 _nova_handler_lit_2_ctx = {0};
    _nova_handler_lit_2_vtable.ctx = &_nova_handler_lit_2_ctx;
    _nova_handler_lit_2_vtable.flip = _nova_handler_lit_2_impl_Switch_flip;
    NovaVtable_Switch* _nova_tmp11 = &_nova_handler_lit_2_vtable;
    NovaVtable_Switch* switcher = _nova_tmp11;
    nova_bool b = switcher->flip(switcher->ctx);
    nova_unit _nova_tmp12;
    {
        nova_print_str((nova_str){.ptr="direct flip = ", .len=14});
        nova_print_bool(b);
        nova_print_newline();
    }
    _nova_tmp12 = NOVA_UNIT;
    _nova_tmp12;
    return NOVA_UNIT;
}

typedef struct {
    nova_int* state;
} NovaCtx__nova_handler_lit_0;
static nova_int _nova_handler_lit_0_impl_Counter_next(void* _ctx);
static nova_int _nova_handler_lit_0_impl_Counter_next(void* _ctx) {
    NovaCtx__nova_handler_lit_0* _c = (NovaCtx__nova_handler_lit_0*)_ctx;
    #define state (*_c->state)
    state += ((nova_int)1LL);
    return state;
    #undef state
}

typedef struct {
    char _dummy;
} NovaCtx__nova_handler_lit_1;
static nova_bool _nova_handler_lit_1_impl_Switch_flip(void* _ctx);
static nova_bool _nova_handler_lit_1_impl_Switch_flip(void* _ctx) {
    NovaCtx__nova_handler_lit_1* _c = (NovaCtx__nova_handler_lit_1*)_ctx;
    nova_interrupt((nova_int)(((nova_int)999LL)));
    return false;
}

typedef struct {
    char _dummy;
} NovaCtx__nova_handler_lit_2;
static nova_bool _nova_handler_lit_2_impl_Switch_flip(void* _ctx);
static nova_bool _nova_handler_lit_2_impl_Switch_flip(void* _ctx) {
    NovaCtx__nova_handler_lit_2* _c = (NovaCtx__nova_handler_lit_2*)_ctx;
    return true;
}


int main(void) {
    nova_gc_init();
    nova_fn_main_impl();
    nova_gc_shutdown();
    return 0;
}
