/* Generated by nova-codegen. Do not edit. */
#include "nova_rt/nova_rt.h"

typedef struct Nova_Point Nova_Point;
struct Nova_Point {
    nova_int x;
    nova_int y;
};

static Nova_Point* nova_fn_make_point(nova_int x, nova_int y);
static nova_int nova_fn_sum_to(nova_int n);
static nova_unit nova_test_spawn_basic_value(void);
static nova_unit nova_test_spawn_arithmetic(void);
static nova_unit nova_test_spawn_captures_immutable(void);
static nova_unit nova_test_spawn_mutates_captured_var(void);
static nova_unit nova_test_spawn_multiple_mutations(void);
static nova_unit nova_test_spawn_pipeline__output_feeds_next(void);
static nova_unit nova_test_spawn_with_computation(void);
static nova_unit nova_test_spawn_nested__capture_spawn_result(void);
static nova_unit nova_test_GC_stress__many_short_lived_records(void);
static nova_unit nova_test_GC_record_survives_across_statements(void);
static nova_unit nova_test_spawn_captures_record_field(void);
static nova_unit nova_test_spawn_large_computation(void);
static nova_unit nova_test_factorial_via_spawn(void);

static void _nova_spawn_0(mco_coro* _co);
static void _nova_spawn_1(mco_coro* _co);
static void _nova_spawn_2(mco_coro* _co);
static void _nova_spawn_3(mco_coro* _co);
static void _nova_spawn_4(mco_coro* _co);
static void _nova_spawn_5(mco_coro* _co);
static void _nova_spawn_6(mco_coro* _co);
static void _nova_spawn_7(mco_coro* _co);
static void _nova_spawn_8(mco_coro* _co);
static void _nova_spawn_9(mco_coro* _co);
static void _nova_spawn_10(mco_coro* _co);
static void _nova_spawn_11(mco_coro* _co);
static void _nova_spawn_12(mco_coro* _co);
static void _nova_spawn_13(mco_coro* _co);
static Nova_Point* nova_fn_make_point(nova_int x, nova_int y) {
    Nova_Point* _nova_tmp0 = (Nova_Point*)nova_alloc(sizeof(Nova_Point));
    _nova_tmp0->x = x;
    _nova_tmp0->y = y;
    return _nova_tmp0;
}

static nova_int nova_fn_sum_to(nova_int n) {
    nova_int acc = ((nova_int)0LL);
    nova_int i = ((nova_int)0LL);
    nova_unit _nova_tmp1;
    while ((i < n)) {
        i += ((nova_int)1LL);
        acc += i;
    }
    _nova_tmp1 = NOVA_UNIT;
    _nova_tmp1;
    return acc;
}

static nova_unit nova_test_spawn_basic_value(void) {
    typedef struct {
        nova_int result;
    } NovaSpawnCtx_nova_spawn_0;
    NovaSpawnCtx_nova_spawn_0 _nova_spawn_0_ctx = {0};
    nova_fiber_run(_nova_spawn_0, &_nova_spawn_0_ctx);
    nova_int _nova_tmp2 = _nova_spawn_0_ctx.result;
    nova_int r = _nova_tmp2;
    nova_assert((r == ((nova_int)42LL)), "r == 42");
    return NOVA_UNIT;
}

static nova_unit nova_test_spawn_arithmetic(void) {
    typedef struct {
        nova_int result;
    } NovaSpawnCtx_nova_spawn_1;
    NovaSpawnCtx_nova_spawn_1 _nova_spawn_1_ctx = {0};
    nova_fiber_run(_nova_spawn_1, &_nova_spawn_1_ctx);
    nova_int _nova_tmp3 = _nova_spawn_1_ctx.result;
    nova_int r = _nova_tmp3;
    nova_assert((r == ((nova_int)60LL)), "r == 60");
    return NOVA_UNIT;
}

static nova_unit nova_test_spawn_captures_immutable(void) {
    nova_int x = ((nova_int)100LL);
    nova_int y = ((nova_int)200LL);
    typedef struct {
        nova_int* x;
        nova_int* y;
        nova_int result;
    } NovaSpawnCtx_nova_spawn_2;
    NovaSpawnCtx_nova_spawn_2 _nova_spawn_2_ctx = {0};
    _nova_spawn_2_ctx.x = &x;
    _nova_spawn_2_ctx.y = &y;
    nova_fiber_run(_nova_spawn_2, &_nova_spawn_2_ctx);
    nova_int _nova_tmp4 = _nova_spawn_2_ctx.result;
    nova_int r = _nova_tmp4;
    nova_assert((r == ((nova_int)300LL)), "r == 300");
    return NOVA_UNIT;
}

static nova_unit nova_test_spawn_mutates_captured_var(void) {
    nova_int counter = ((nova_int)0LL);
    typedef struct {
        nova_int* counter;
        nova_int result;
    } NovaSpawnCtx_nova_spawn_3;
    NovaSpawnCtx_nova_spawn_3 _nova_spawn_3_ctx = {0};
    _nova_spawn_3_ctx.counter = &counter;
    nova_fiber_run(_nova_spawn_3, &_nova_spawn_3_ctx);
    nova_int _nova_tmp6 = _nova_spawn_3_ctx.result;
    nova_int _nova_tmp5 = _nova_tmp6;
    nova_assert((counter == ((nova_int)7LL)), "counter == 7");
    return NOVA_UNIT;
}

static nova_unit nova_test_spawn_multiple_mutations(void) {
    nova_int a = ((nova_int)0LL);
    nova_int b = ((nova_int)0LL);
    typedef struct {
        nova_int* a;
        nova_int result;
    } NovaSpawnCtx_nova_spawn_4;
    NovaSpawnCtx_nova_spawn_4 _nova_spawn_4_ctx = {0};
    _nova_spawn_4_ctx.a = &a;
    nova_fiber_run(_nova_spawn_4, &_nova_spawn_4_ctx);
    nova_int _nova_tmp8 = _nova_spawn_4_ctx.result;
    nova_int _nova_tmp7 = _nova_tmp8;
    typedef struct {
        nova_int* b;
        nova_int result;
    } NovaSpawnCtx_nova_spawn_5;
    NovaSpawnCtx_nova_spawn_5 _nova_spawn_5_ctx = {0};
    _nova_spawn_5_ctx.b = &b;
    nova_fiber_run(_nova_spawn_5, &_nova_spawn_5_ctx);
    nova_int _nova_tmp10 = _nova_spawn_5_ctx.result;
    nova_int _nova_tmp9 = _nova_tmp10;
    nova_assert((a == ((nova_int)10LL)), "a == 10");
    nova_assert((b == ((nova_int)20LL)), "b == 20");
    return NOVA_UNIT;
}

static nova_unit nova_test_spawn_pipeline__output_feeds_next(void) {
    nova_int x = ((nova_int)5LL);
    typedef struct {
        nova_int* x;
        nova_int result;
    } NovaSpawnCtx_nova_spawn_6;
    NovaSpawnCtx_nova_spawn_6 _nova_spawn_6_ctx = {0};
    _nova_spawn_6_ctx.x = &x;
    nova_fiber_run(_nova_spawn_6, &_nova_spawn_6_ctx);
    nova_int _nova_tmp11 = _nova_spawn_6_ctx.result;
    nova_int r1 = _nova_tmp11;
    typedef struct {
        nova_int* r1;
        nova_int result;
    } NovaSpawnCtx_nova_spawn_7;
    NovaSpawnCtx_nova_spawn_7 _nova_spawn_7_ctx = {0};
    _nova_spawn_7_ctx.r1 = &r1;
    nova_fiber_run(_nova_spawn_7, &_nova_spawn_7_ctx);
    nova_int _nova_tmp12 = _nova_spawn_7_ctx.result;
    nova_int r2 = _nova_tmp12;
    nova_assert((r1 == ((nova_int)25LL)), "r1 == 25");
    nova_assert((r2 == ((nova_int)50LL)), "r2 == 50");
    return NOVA_UNIT;
}

static nova_unit nova_test_spawn_with_computation(void) {
    nova_int n = ((nova_int)10LL);
    typedef struct {
        nova_int* n;
        nova_int result;
    } NovaSpawnCtx_nova_spawn_8;
    NovaSpawnCtx_nova_spawn_8 _nova_spawn_8_ctx = {0};
    _nova_spawn_8_ctx.n = &n;
    nova_fiber_run(_nova_spawn_8, &_nova_spawn_8_ctx);
    nova_int _nova_tmp13 = _nova_spawn_8_ctx.result;
    nova_int r = _nova_tmp13;
    nova_assert((r == ((nova_int)55LL)), "r == 55");
    return NOVA_UNIT;
}

static nova_unit nova_test_spawn_nested__capture_spawn_result(void) {
    nova_int a = ((nova_int)3LL);
    nova_int b = ((nova_int)4LL);
    typedef struct {
        nova_int* a;
        nova_int* b;
        nova_int result;
    } NovaSpawnCtx_nova_spawn_9;
    NovaSpawnCtx_nova_spawn_9 _nova_spawn_9_ctx = {0};
    _nova_spawn_9_ctx.a = &a;
    _nova_spawn_9_ctx.b = &b;
    nova_fiber_run(_nova_spawn_9, &_nova_spawn_9_ctx);
    nova_int _nova_tmp14 = _nova_spawn_9_ctx.result;
    nova_int hyp_sq = _nova_tmp14;
    typedef struct {
        nova_int* hyp_sq;
        nova_int result;
    } NovaSpawnCtx_nova_spawn_10;
    NovaSpawnCtx_nova_spawn_10 _nova_spawn_10_ctx = {0};
    _nova_spawn_10_ctx.hyp_sq = &hyp_sq;
    nova_fiber_run(_nova_spawn_10, &_nova_spawn_10_ctx);
    nova_int _nova_tmp15 = _nova_spawn_10_ctx.result;
    nova_int r = _nova_tmp15;
    nova_assert((r == ((nova_int)25LL)), "r == 25");
    return NOVA_UNIT;
}

static nova_unit nova_test_GC_stress__many_short_lived_records(void) {
    nova_int sum = ((nova_int)0LL);
    nova_int i = ((nova_int)0LL);
    nova_unit _nova_tmp16;
    while ((i < ((nova_int)100LL))) {
        Nova_Point* p = nova_fn_make_point(i, (i * ((nova_int)2LL)));
        sum += ((p->x) + (p->y));
        i += ((nova_int)1LL);
    }
    _nova_tmp16 = NOVA_UNIT;
    _nova_tmp16;
    nova_assert((sum == ((nova_int)14850LL)), "sum == 14850");
    return NOVA_UNIT;
}

static nova_unit nova_test_GC_record_survives_across_statements(void) {
    Nova_Point* p = nova_fn_make_point(((nova_int)7LL), ((nova_int)13LL));
    Nova_Point* q = nova_fn_make_point(((p->x) + ((nova_int)1LL)), ((p->y) + ((nova_int)1LL)));
    nova_assert(((q->x) == ((nova_int)8LL)), "assert == 8");
    nova_assert(((q->y) == ((nova_int)14LL)), "assert == 14");
    return NOVA_UNIT;
}

static nova_unit nova_test_spawn_captures_record_field(void) {
    Nova_Point* p = nova_fn_make_point(((nova_int)3LL), ((nova_int)4LL));
    typedef struct {
        Nova_Point** p;
        nova_int result;
    } NovaSpawnCtx_nova_spawn_11;
    NovaSpawnCtx_nova_spawn_11 _nova_spawn_11_ctx = {0};
    _nova_spawn_11_ctx.p = &p;
    nova_fiber_run(_nova_spawn_11, &_nova_spawn_11_ctx);
    nova_int _nova_tmp17 = _nova_spawn_11_ctx.result;
    nova_int r = _nova_tmp17;
    nova_assert((r == ((nova_int)25LL)), "r == 25");
    return NOVA_UNIT;
}

static nova_unit nova_test_spawn_large_computation(void) {
    nova_int n = ((nova_int)100LL);
    typedef struct {
        nova_int* n;
        nova_int result;
    } NovaSpawnCtx_nova_spawn_12;
    NovaSpawnCtx_nova_spawn_12 _nova_spawn_12_ctx = {0};
    _nova_spawn_12_ctx.n = &n;
    nova_fiber_run(_nova_spawn_12, &_nova_spawn_12_ctx);
    nova_int _nova_tmp18 = _nova_spawn_12_ctx.result;
    nova_int r = _nova_tmp18;
    nova_assert((r == ((nova_int)5050LL)), "r == 5050");
    return NOVA_UNIT;
}

static nova_unit nova_test_factorial_via_spawn(void) {
    nova_int acc = ((nova_int)1LL);
    nova_int i = ((nova_int)1LL);
    nova_unit _nova_tmp19;
    while ((i <= ((nova_int)10LL))) {
        nova_int cur = i;
        typedef struct {
            nova_int* acc;
            nova_int* cur;
            nova_int result;
        } NovaSpawnCtx_nova_spawn_13;
        NovaSpawnCtx_nova_spawn_13 _nova_spawn_13_ctx = {0};
        _nova_spawn_13_ctx.acc = &acc;
        _nova_spawn_13_ctx.cur = &cur;
        nova_fiber_run(_nova_spawn_13, &_nova_spawn_13_ctx);
        nova_int _nova_tmp21 = _nova_spawn_13_ctx.result;
        nova_int _nova_tmp20 = _nova_tmp21;
        i += ((nova_int)1LL);
    }
    _nova_tmp19 = NOVA_UNIT;
    _nova_tmp19;
    nova_assert((acc == ((nova_int)3628800LL)), "acc == 3628800");
    return NOVA_UNIT;
}

typedef struct {
    nova_int result;
} NovaSpawnCtx_nova_spawn_0;
static void _nova_spawn_0(mco_coro* _co) {
    NovaSpawnCtx_nova_spawn_0* _c = (NovaSpawnCtx_nova_spawn_0*)mco_get_user_data(_co);
    _c->result = (nova_int)(((nova_int)42LL));
}

typedef struct {
    nova_int result;
} NovaSpawnCtx_nova_spawn_1;
static void _nova_spawn_1(mco_coro* _co) {
    NovaSpawnCtx_nova_spawn_1* _c = (NovaSpawnCtx_nova_spawn_1*)mco_get_user_data(_co);
    _c->result = (nova_int)(((((nova_int)10LL) + ((nova_int)20LL)) + ((nova_int)30LL)));
}

typedef struct {
    nova_int* x;
    nova_int* y;
    nova_int result;
} NovaSpawnCtx_nova_spawn_2;
static void _nova_spawn_2(mco_coro* _co) {
    NovaSpawnCtx_nova_spawn_2* _c = (NovaSpawnCtx_nova_spawn_2*)mco_get_user_data(_co);
    #define x (*_c->x)
    #define y (*_c->y)
    _c->result = (nova_int)((x + y));
    #undef x
    #undef y
}

typedef struct {
    nova_int* counter;
    nova_int result;
} NovaSpawnCtx_nova_spawn_3;
static void _nova_spawn_3(mco_coro* _co) {
    NovaSpawnCtx_nova_spawn_3* _c = (NovaSpawnCtx_nova_spawn_3*)mco_get_user_data(_co);
    #define counter (*_c->counter)
    counter += ((nova_int)7LL);
    _c->result = (nova_int)(((nova_int)0LL));
    #undef counter
}

typedef struct {
    nova_int* a;
    nova_int result;
} NovaSpawnCtx_nova_spawn_4;
static void _nova_spawn_4(mco_coro* _co) {
    NovaSpawnCtx_nova_spawn_4* _c = (NovaSpawnCtx_nova_spawn_4*)mco_get_user_data(_co);
    #define a (*_c->a)
    a += ((nova_int)10LL);
    _c->result = (nova_int)(((nova_int)0LL));
    #undef a
}

typedef struct {
    nova_int* b;
    nova_int result;
} NovaSpawnCtx_nova_spawn_5;
static void _nova_spawn_5(mco_coro* _co) {
    NovaSpawnCtx_nova_spawn_5* _c = (NovaSpawnCtx_nova_spawn_5*)mco_get_user_data(_co);
    #define b (*_c->b)
    b += ((nova_int)20LL);
    _c->result = (nova_int)(((nova_int)0LL));
    #undef b
}

typedef struct {
    nova_int* x;
    nova_int result;
} NovaSpawnCtx_nova_spawn_6;
static void _nova_spawn_6(mco_coro* _co) {
    NovaSpawnCtx_nova_spawn_6* _c = (NovaSpawnCtx_nova_spawn_6*)mco_get_user_data(_co);
    #define x (*_c->x)
    _c->result = (nova_int)((x * x));
    #undef x
}

typedef struct {
    nova_int* r1;
    nova_int result;
} NovaSpawnCtx_nova_spawn_7;
static void _nova_spawn_7(mco_coro* _co) {
    NovaSpawnCtx_nova_spawn_7* _c = (NovaSpawnCtx_nova_spawn_7*)mco_get_user_data(_co);
    #define r1 (*_c->r1)
    _c->result = (nova_int)((r1 + r1));
    #undef r1
}

typedef struct {
    nova_int* n;
    nova_int result;
} NovaSpawnCtx_nova_spawn_8;
static void _nova_spawn_8(mco_coro* _co) {
    NovaSpawnCtx_nova_spawn_8* _c = (NovaSpawnCtx_nova_spawn_8*)mco_get_user_data(_co);
    #define n (*_c->n)
    _c->result = (nova_int)(nova_fn_sum_to(n));
    #undef n
}

typedef struct {
    nova_int* a;
    nova_int* b;
    nova_int result;
} NovaSpawnCtx_nova_spawn_9;
static void _nova_spawn_9(mco_coro* _co) {
    NovaSpawnCtx_nova_spawn_9* _c = (NovaSpawnCtx_nova_spawn_9*)mco_get_user_data(_co);
    #define a (*_c->a)
    #define b (*_c->b)
    _c->result = (nova_int)(((a * a) + (b * b)));
    #undef a
    #undef b
}

typedef struct {
    nova_int* hyp_sq;
    nova_int result;
} NovaSpawnCtx_nova_spawn_10;
static void _nova_spawn_10(mco_coro* _co) {
    NovaSpawnCtx_nova_spawn_10* _c = (NovaSpawnCtx_nova_spawn_10*)mco_get_user_data(_co);
    #define hyp_sq (*_c->hyp_sq)
    _c->result = (nova_int)((hyp_sq + ((nova_int)0LL)));
    #undef hyp_sq
}

typedef struct {
    Nova_Point** p;
    nova_int result;
} NovaSpawnCtx_nova_spawn_11;
static void _nova_spawn_11(mco_coro* _co) {
    NovaSpawnCtx_nova_spawn_11* _c = (NovaSpawnCtx_nova_spawn_11*)mco_get_user_data(_co);
    #define p (*_c->p)
    _c->result = (nova_int)((((p->x) * (p->x)) + ((p->y) * (p->y))));
    #undef p
}

typedef struct {
    nova_int* n;
    nova_int result;
} NovaSpawnCtx_nova_spawn_12;
static void _nova_spawn_12(mco_coro* _co) {
    NovaSpawnCtx_nova_spawn_12* _c = (NovaSpawnCtx_nova_spawn_12*)mco_get_user_data(_co);
    #define n (*_c->n)
    _c->result = (nova_int)(nova_fn_sum_to(n));
    #undef n
}

typedef struct {
    nova_int* acc;
    nova_int* cur;
    nova_int result;
} NovaSpawnCtx_nova_spawn_13;
static void _nova_spawn_13(mco_coro* _co) {
    NovaSpawnCtx_nova_spawn_13* _c = (NovaSpawnCtx_nova_spawn_13*)mco_get_user_data(_co);
    #define acc (*_c->acc)
    #define cur (*_c->cur)
    acc = (acc * cur);
    _c->result = (nova_int)(((nova_int)0LL));
    #undef acc
    #undef cur
}


static nova_unit nova_fn_main_impl(void) {
    int _nova_tests_total = 13;
    int _nova_tests_failed = 0;
    printf("Running %d tests...\n", _nova_tests_total);
    {
        NovaTestFrame _tf;
        _tf.fail_msg = NULL;
        _nova_test_frame = &_tf;
        if (setjmp(_tf.jmp) == 0) {
            nova_test_spawn_basic_value();
            printf("  PASS: spawn basic value\n");
        } else {
            printf("  FAIL: spawn basic value — %s\n", _tf.fail_msg ? _tf.fail_msg : "assertion failed");
            _nova_tests_failed++;
        }
        _nova_test_frame = NULL;
    }
    {
        NovaTestFrame _tf;
        _tf.fail_msg = NULL;
        _nova_test_frame = &_tf;
        if (setjmp(_tf.jmp) == 0) {
            nova_test_spawn_arithmetic();
            printf("  PASS: spawn arithmetic\n");
        } else {
            printf("  FAIL: spawn arithmetic — %s\n", _tf.fail_msg ? _tf.fail_msg : "assertion failed");
            _nova_tests_failed++;
        }
        _nova_test_frame = NULL;
    }
    {
        NovaTestFrame _tf;
        _tf.fail_msg = NULL;
        _nova_test_frame = &_tf;
        if (setjmp(_tf.jmp) == 0) {
            nova_test_spawn_captures_immutable();
            printf("  PASS: spawn captures immutable\n");
        } else {
            printf("  FAIL: spawn captures immutable — %s\n", _tf.fail_msg ? _tf.fail_msg : "assertion failed");
            _nova_tests_failed++;
        }
        _nova_test_frame = NULL;
    }
    {
        NovaTestFrame _tf;
        _tf.fail_msg = NULL;
        _nova_test_frame = &_tf;
        if (setjmp(_tf.jmp) == 0) {
            nova_test_spawn_mutates_captured_var();
            printf("  PASS: spawn mutates captured var\n");
        } else {
            printf("  FAIL: spawn mutates captured var — %s\n", _tf.fail_msg ? _tf.fail_msg : "assertion failed");
            _nova_tests_failed++;
        }
        _nova_test_frame = NULL;
    }
    {
        NovaTestFrame _tf;
        _tf.fail_msg = NULL;
        _nova_test_frame = &_tf;
        if (setjmp(_tf.jmp) == 0) {
            nova_test_spawn_multiple_mutations();
            printf("  PASS: spawn multiple mutations\n");
        } else {
            printf("  FAIL: spawn multiple mutations — %s\n", _tf.fail_msg ? _tf.fail_msg : "assertion failed");
            _nova_tests_failed++;
        }
        _nova_test_frame = NULL;
    }
    {
        NovaTestFrame _tf;
        _tf.fail_msg = NULL;
        _nova_test_frame = &_tf;
        if (setjmp(_tf.jmp) == 0) {
            nova_test_spawn_pipeline__output_feeds_next();
            printf("  PASS: spawn pipeline: output feeds next\n");
        } else {
            printf("  FAIL: spawn pipeline: output feeds next — %s\n", _tf.fail_msg ? _tf.fail_msg : "assertion failed");
            _nova_tests_failed++;
        }
        _nova_test_frame = NULL;
    }
    {
        NovaTestFrame _tf;
        _tf.fail_msg = NULL;
        _nova_test_frame = &_tf;
        if (setjmp(_tf.jmp) == 0) {
            nova_test_spawn_with_computation();
            printf("  PASS: spawn with computation\n");
        } else {
            printf("  FAIL: spawn with computation — %s\n", _tf.fail_msg ? _tf.fail_msg : "assertion failed");
            _nova_tests_failed++;
        }
        _nova_test_frame = NULL;
    }
    {
        NovaTestFrame _tf;
        _tf.fail_msg = NULL;
        _nova_test_frame = &_tf;
        if (setjmp(_tf.jmp) == 0) {
            nova_test_spawn_nested__capture_spawn_result();
            printf("  PASS: spawn nested: capture spawn result\n");
        } else {
            printf("  FAIL: spawn nested: capture spawn result — %s\n", _tf.fail_msg ? _tf.fail_msg : "assertion failed");
            _nova_tests_failed++;
        }
        _nova_test_frame = NULL;
    }
    {
        NovaTestFrame _tf;
        _tf.fail_msg = NULL;
        _nova_test_frame = &_tf;
        if (setjmp(_tf.jmp) == 0) {
            nova_test_GC_stress__many_short_lived_records();
            printf("  PASS: GC stress: many short-lived records\n");
        } else {
            printf("  FAIL: GC stress: many short-lived records — %s\n", _tf.fail_msg ? _tf.fail_msg : "assertion failed");
            _nova_tests_failed++;
        }
        _nova_test_frame = NULL;
    }
    {
        NovaTestFrame _tf;
        _tf.fail_msg = NULL;
        _nova_test_frame = &_tf;
        if (setjmp(_tf.jmp) == 0) {
            nova_test_GC_record_survives_across_statements();
            printf("  PASS: GC record survives across statements\n");
        } else {
            printf("  FAIL: GC record survives across statements — %s\n", _tf.fail_msg ? _tf.fail_msg : "assertion failed");
            _nova_tests_failed++;
        }
        _nova_test_frame = NULL;
    }
    {
        NovaTestFrame _tf;
        _tf.fail_msg = NULL;
        _nova_test_frame = &_tf;
        if (setjmp(_tf.jmp) == 0) {
            nova_test_spawn_captures_record_field();
            printf("  PASS: spawn captures record field\n");
        } else {
            printf("  FAIL: spawn captures record field — %s\n", _tf.fail_msg ? _tf.fail_msg : "assertion failed");
            _nova_tests_failed++;
        }
        _nova_test_frame = NULL;
    }
    {
        NovaTestFrame _tf;
        _tf.fail_msg = NULL;
        _nova_test_frame = &_tf;
        if (setjmp(_tf.jmp) == 0) {
            nova_test_spawn_large_computation();
            printf("  PASS: spawn large computation\n");
        } else {
            printf("  FAIL: spawn large computation — %s\n", _tf.fail_msg ? _tf.fail_msg : "assertion failed");
            _nova_tests_failed++;
        }
        _nova_test_frame = NULL;
    }
    {
        NovaTestFrame _tf;
        _tf.fail_msg = NULL;
        _nova_test_frame = &_tf;
        if (setjmp(_tf.jmp) == 0) {
            nova_test_factorial_via_spawn();
            printf("  PASS: factorial via spawn\n");
        } else {
            printf("  FAIL: factorial via spawn — %s\n", _tf.fail_msg ? _tf.fail_msg : "assertion failed");
            _nova_tests_failed++;
        }
        _nova_test_frame = NULL;
    }
    printf("%d/%d passed\n", _nova_tests_total - _nova_tests_failed, _nova_tests_total);
    if (_nova_tests_failed > 0) { exit(1); }
    return NOVA_UNIT;
}

int main(void) {
    nova_gc_init();
    nova_fn_main_impl();
    nova_gc_shutdown();
    return 0;
}
