/* Generated by nova-codegen. Do not edit. */
#include "nova_rt/nova_rt.h"

static nova_int nova_fn_count_lines(nova_str s);

static nova_int nova_fn_count_lines(nova_str s) {
    nova_int count = ((nova_int)1LL);
    nova_int i = ((nova_int)0LL);
    nova_unit _nova_tmp0;
    while ((i < ((nova_int)(s.len)))) {
        i += ((nova_int)1LL);
    }
    _nova_tmp0 = NOVA_UNIT;
    _nova_tmp0;
    return count;
}

static nova_unit nova_fn_main_impl(void) {
    nova_str greeting = (nova_str){.ptr="hello, world", .len=12};
    nova_unit _nova_tmp1;
    {
        nova_print_str((nova_str){.ptr="len = ", .len=6});
        nova_print_int(((nova_int)(greeting.len)));
        nova_print_newline();
    }
    _nova_tmp1 = NOVA_UNIT;
    _nova_tmp1;
    nova_unit _nova_tmp2;
    {
        nova_print_str((nova_str){.ptr="upper = ", .len=8});
        nova_print_str(nova_str_to_upper(greeting));
        nova_print_newline();
    }
    _nova_tmp2 = NOVA_UNIT;
    _nova_tmp2;
    nova_unit _nova_tmp3;
    {
        nova_print_str((nova_str){.ptr="starts with 'hello' = ", .len=22});
        nova_print_bool(nova_str_starts_with(greeting, (nova_str){.ptr="hello", .len=5}));
        nova_print_newline();
    }
    _nova_tmp3 = NOVA_UNIT;
    _nova_tmp3;
    nova_unit _nova_tmp4;
    {
        nova_print_str((nova_str){.ptr="contains 'world' = ", .len=19});
        nova_print_bool(nova_str_contains(greeting, (nova_str){.ptr="world", .len=5}));
        nova_print_newline();
    }
    _nova_tmp4 = NOVA_UNIT;
    _nova_tmp4;
    return NOVA_UNIT;
}

int main(void) {
    nova_gc_init();
    nova_fn_main_impl();
    nova_gc_shutdown();
    return 0;
}
