/* Generated by nova-codegen. Do not edit. */
#include "nova_rt/nova_rt.h"

static nova_int nova_fn_double(nova_int x);
static nova_int nova_fn_factorial(nova_int n);
static nova_unit nova_test_double_works(void);
static nova_unit nova_test_factorial_base_case(void);
static nova_unit nova_test_factorial_recursive(void);
static nova_unit nova_test_this_one_fails_on_purpose(void);

static nova_int nova_fn_double(nova_int x) {
    return (x * ((nova_int)2LL));
}

static nova_int nova_fn_factorial(nova_int n) {
    nova_unit _nova_tmp0;
    if ((n <= ((nova_int)1LL))) {
        return ((nova_int)1LL);
        _nova_tmp0 = NOVA_UNIT;
    }
    _nova_tmp0;
    return (n * nova_fn_factorial((n - ((nova_int)1LL))));
}

static nova_unit nova_test_double_works(void) {
    nova_assert((nova_fn_double(((nova_int)5LL)) == ((nova_int)10LL)), "double(5) == 10");
    nova_assert((nova_fn_double(((nova_int)0LL)) == ((nova_int)0LL)), "double(0) == 0");
    nova_assert((nova_fn_double((-((nova_int)3LL))) == (-((nova_int)6LL))), "double(-3) == -6");
    return NOVA_UNIT;
}

static nova_unit nova_test_factorial_base_case(void) {
    nova_assert((nova_fn_factorial(((nova_int)0LL)) == ((nova_int)1LL)), "factorial(0) == 1");
    nova_assert((nova_fn_factorial(((nova_int)1LL)) == ((nova_int)1LL)), "factorial(1) == 1");
    return NOVA_UNIT;
}

static nova_unit nova_test_factorial_recursive(void) {
    nova_assert((nova_fn_factorial(((nova_int)5LL)) == ((nova_int)120LL)), "factorial(5) == 120");
    nova_assert((nova_fn_factorial(((nova_int)6LL)) == ((nova_int)720LL)), "factorial(6) == 720");
    return NOVA_UNIT;
}

static nova_unit nova_test_this_one_fails_on_purpose(void) {
    nova_assert((((nova_int)1LL) == ((nova_int)2LL)), "1 == 2");
    return NOVA_UNIT;
}

static nova_unit nova_fn_main_impl(void) {
    int _nova_tests_total = 4;
    int _nova_tests_failed = 0;
    printf("Running %d tests...\n", _nova_tests_total);
    {
        NovaTestFrame _tf;
        _tf.fail_msg = NULL;
        _nova_test_frame = &_tf;
        if (setjmp(_tf.jmp) == 0) {
            nova_test_double_works();
            printf("  PASS: double works\n");
        } else {
            printf("  FAIL: double works — %s\n", _tf.fail_msg ? _tf.fail_msg : "assertion failed");
            _nova_tests_failed++;
        }
        _nova_test_frame = NULL;
    }
    {
        NovaTestFrame _tf;
        _tf.fail_msg = NULL;
        _nova_test_frame = &_tf;
        if (setjmp(_tf.jmp) == 0) {
            nova_test_factorial_base_case();
            printf("  PASS: factorial base case\n");
        } else {
            printf("  FAIL: factorial base case — %s\n", _tf.fail_msg ? _tf.fail_msg : "assertion failed");
            _nova_tests_failed++;
        }
        _nova_test_frame = NULL;
    }
    {
        NovaTestFrame _tf;
        _tf.fail_msg = NULL;
        _nova_test_frame = &_tf;
        if (setjmp(_tf.jmp) == 0) {
            nova_test_factorial_recursive();
            printf("  PASS: factorial recursive\n");
        } else {
            printf("  FAIL: factorial recursive — %s\n", _tf.fail_msg ? _tf.fail_msg : "assertion failed");
            _nova_tests_failed++;
        }
        _nova_test_frame = NULL;
    }
    {
        NovaTestFrame _tf;
        _tf.fail_msg = NULL;
        _nova_test_frame = &_tf;
        if (setjmp(_tf.jmp) == 0) {
            nova_test_this_one_fails_on_purpose();
            printf("  PASS: this one fails on purpose\n");
        } else {
            printf("  FAIL: this one fails on purpose — %s\n", _tf.fail_msg ? _tf.fail_msg : "assertion failed");
            _nova_tests_failed++;
        }
        _nova_test_frame = NULL;
    }
    printf("%d/%d passed\n", _nova_tests_total - _nova_tests_failed, _nova_tests_total);
    if (_nova_tests_failed > 0) { exit(1); }
    return NOVA_UNIT;
}

int main(void) {
    nova_gc_init();
    nova_fn_main_impl();
    nova_gc_shutdown();
    return 0;
}
