/* Generated by nova-codegen. Do not edit. */
#include "nova_rt/nova_rt.h"

typedef struct { nova_int f0; } _NovaTuple1;
typedef struct { nova_int f0; nova_int f1; } _NovaTuple2;
typedef struct { nova_int f0; nova_int f1; nova_int f2; } _NovaTuple3;
typedef struct { nova_int f0; nova_int f1; nova_int f2; nova_int f3; } _NovaTuple4;
typedef struct { nova_int f0; nova_int f1; nova_int f2; nova_int f3; nova_int f4; } _NovaTuple5;
typedef struct { nova_int f0; nova_int f1; nova_int f2; nova_int f3; nova_int f4; nova_int f5; } _NovaTuple6;
typedef struct { nova_int f0; nova_int f1; nova_int f2; nova_int f3; nova_int f4; nova_int f5; nova_int f6; } _NovaTuple7;
typedef struct { nova_int f0; nova_int f1; nova_int f2; nova_int f3; nova_int f4; nova_int f5; nova_int f6; nova_int f7; } _NovaTuple8;

static uint32_t nova_fn_table_value(uint8_t i);
static uint32_t nova_fn_lookup(uint8_t i);
static uint32_t nova_fn_crc32(NovaArray_nova_byte* data);
static uint32_t nova_fn_crc32_init(void);
static uint32_t nova_fn_crc32_update(uint32_t state, NovaArray_nova_byte* data);
static uint32_t nova_fn_crc32_finalize(uint32_t state);
static nova_unit nova_test_crc32________________0_0(void);
static nova_unit nova_test_crc32__ASCII__123456789____0xCBF43926_______________test_vector__1(void);
static nova_unit nova_test_crc32___hello_world____0x0D4A1185_2(void);
static nova_unit nova_test_crc32____________0x00___0xD202EF8D_3(void);
static nova_unit nova_test_crc32____________0xFF___0xFF000000_4(void);
static nova_unit nova_test_crc32__incremental_______________5(void);
static nova_unit nova_test_crc32_____________________1_______________6(void);
static nova_unit nova_test_crc32________________1KB________7(void);

static uint32_t nova_fn_table_value(uint8_t i) {
    /* SRC: let mut c = i as u32 */
    nova_int c = i;
    /* SRC: let mut k = 0 */
    nova_int k = ((nova_int)0LL);
    /* SRC: while k < 8 { */
    nova_unit _nv_while_0;
    while ((k < ((nova_int)8LL))) {
        /* SRC: c = if c & 1 == 1 { */
        nova_int _nv_if_1;
        if (((c & ((nova_int)1LL)) == ((nova_int)1LL))) {
            _nv_if_1 = (nova_int)((((nova_int)3988292384LL) ^ (c >> ((nova_int)1LL))));
        } else {
            _nv_if_1 = (nova_int)((c >> ((nova_int)1LL)));
        }
        c = _nv_if_1;
        /* SRC: k += 1 */
        k += ((nova_int)1LL);
    }
    _nv_while_0 = NOVA_UNIT;
    _nv_while_0;
    /* SRC: c */
    return c;
}

static uint32_t nova_fn_lookup(uint8_t i) {
    /* SRC: table_value(i) */
    return nova_fn_table_value(i);
}

static uint32_t nova_fn_crc32(NovaArray_nova_byte* data) {
    /* SRC: let mut crc u32 = 0xFFFFFFFF */
    uint32_t crc = ((nova_int)4294967295LL);
    /* SRC: for byte in data { */
    NovaArray_nova_byte* _nv_tmp_2 = data;
    nova_unit _nv_tmp_4;
    for (nova_int _nv_tmp_3 = 0; _nv_tmp_3 < _nv_tmp_2->len; _nv_tmp_3++) {
        nova_byte byte = _nv_tmp_2->data[_nv_tmp_3];
        /* SRC: let idx = ((crc ^ (byte as u32)) & 0xFF) as u8 */
        nova_int idx = ((crc ^ byte) & ((nova_int)255LL));
        /* SRC: crc = lookup(idx) ^ (crc >> 8 */
        crc = (nova_fn_lookup(idx) ^ (crc >> ((nova_int)8LL)));
    }
    _nv_tmp_4 = NOVA_UNIT;
    _nv_tmp_4;
    /* SRC: crc ^ 0xFFFFFFFF */
    return (crc ^ ((nova_int)4294967295LL));
}

static uint32_t nova_fn_crc32_init(void) {
    /* SRC: 0xFFFFFFFF */
    return ((nova_int)4294967295LL);
}

static uint32_t nova_fn_crc32_update(uint32_t state, NovaArray_nova_byte* data) {
    /* SRC: let mut crc = state */
    uint32_t crc = state;
    /* SRC: for byte in data { */
    NovaArray_nova_byte* _nv_tmp_5 = data;
    nova_unit _nv_tmp_7;
    for (nova_int _nv_tmp_6 = 0; _nv_tmp_6 < _nv_tmp_5->len; _nv_tmp_6++) {
        nova_byte byte = _nv_tmp_5->data[_nv_tmp_6];
        /* SRC: let idx = ((crc ^ (byte as u32)) & 0xFF) as u8 */
        nova_int idx = ((crc ^ byte) & ((nova_int)255LL));
        /* SRC: crc = lookup(idx) ^ (crc >> 8 */
        crc = (nova_fn_lookup(idx) ^ (crc >> ((nova_int)8LL)));
    }
    _nv_tmp_7 = NOVA_UNIT;
    _nv_tmp_7;
    /* SRC: crc */
    return crc;
}

static uint32_t nova_fn_crc32_finalize(uint32_t state) {
    /* SRC: state ^ 0xFFFFFFFF */
    return (state ^ ((nova_int)4294967295LL));
}

static nova_unit nova_test_crc32________________0_0(void) {
    /* SRC: let empty []byte = [] */
    NovaArray_nova_int* _nv_tmp_8 = nova_array_new_nova_int(8);
    NovaArray_nova_byte* empty = _nv_tmp_8;
    /* SRC: assert(crc32(empty) == 0) */
    nova_assert((nova_fn_crc32(empty) == ((nova_int)0LL)), "crc32(empty) == 0");
    return NOVA_UNIT;
}

static nova_unit nova_test_crc32__ASCII__123456789____0xCBF43926_______________test_vector__1(void) {
    /* SRC: assert(crc32("123456789".bytes()) == 0xCBF43926) */
    nova_assert((nova_fn_crc32(nova_str_bytes((nova_str){.ptr="123456789", .len=9})) == ((nova_int)3421780262LL)), "crc32(assert()) == 3421780262");
    return NOVA_UNIT;
}

static nova_unit nova_test_crc32___hello_world____0x0D4A1185_2(void) {
    /* SRC: assert(crc32("hello world".bytes()) == 0x0D4A1185) */
    nova_assert((nova_fn_crc32(nova_str_bytes((nova_str){.ptr="hello world", .len=11})) == ((nova_int)222957957LL)), "crc32(assert()) == 222957957");
    return NOVA_UNIT;
}

static nova_unit nova_test_crc32____________0x00___0xD202EF8D_3(void) {
    /* SRC: let data []byte = [0x00] */
    NovaArray_nova_int* _nv_tmp_9 = nova_array_new_nova_int(1);
    nova_array_push_nova_int(_nv_tmp_9, (nova_int)(((nova_int)0LL)));
    NovaArray_nova_byte* data = _nv_tmp_9;
    /* SRC: assert(crc32(data) == 0xD202EF8D) */
    nova_assert((nova_fn_crc32(data) == ((nova_int)3523407757LL)), "crc32(data) == 3523407757");
    return NOVA_UNIT;
}

static nova_unit nova_test_crc32____________0xFF___0xFF000000_4(void) {
    /* SRC: let data []byte = [0xFF] */
    NovaArray_nova_int* _nv_tmp_10 = nova_array_new_nova_int(1);
    nova_array_push_nova_int(_nv_tmp_10, (nova_int)(((nova_int)255LL)));
    NovaArray_nova_byte* data = _nv_tmp_10;
    /* SRC: assert(crc32(data) == 0xFF000000) */
    nova_assert((nova_fn_crc32(data) == ((nova_int)4278190080LL)), "crc32(data) == 4278190080");
    return NOVA_UNIT;
}

static nova_unit nova_test_crc32__incremental_______________5(void) {
    /* SRC: let full = "The quick brown fox jumps over the lazy dog".bytes() */
    NovaArray_nova_byte* full = nova_str_bytes((nova_str){.ptr="The quick brown fox jumps over the lazy dog", .len=43});
    /* SRC: let part1 = "The quick brown ".bytes() */
    NovaArray_nova_byte* part1 = nova_str_bytes((nova_str){.ptr="The quick brown ", .len=16});
    /* SRC: let part2 = "fox jumps over ".bytes() */
    NovaArray_nova_byte* part2 = nova_str_bytes((nova_str){.ptr="fox jumps over ", .len=15});
    /* SRC: let part3 = "the lazy dog".bytes() */
    NovaArray_nova_byte* part3 = nova_str_bytes((nova_str){.ptr="the lazy dog", .len=12});
    /* SRC: let monolithic = crc32(full) */
    uint32_t monolithic = nova_fn_crc32(full);
    /* SRC: let mut state = crc32_init() */
    uint32_t state = nova_fn_crc32_init();
    /* SRC: state = crc32_update(state, part1) */
    state = nova_fn_crc32_update(state, part1);
    /* SRC: state = crc32_update(state, part2) */
    state = nova_fn_crc32_update(state, part2);
    /* SRC: state = crc32_update(state, part3) */
    state = nova_fn_crc32_update(state, part3);
    /* SRC: let incremental = crc32_finalize(state) */
    uint32_t incremental = nova_fn_crc32_finalize(state);
    /* SRC: assert(monolithic == incremental) */
    nova_assert((monolithic == incremental), "monolithic == incremental");
    return NOVA_UNIT;
}

static nova_unit nova_test_crc32_____________________1_______________6(void) {
    /* SRC: let original = "hello".bytes() */
    NovaArray_nova_byte* original = nova_str_bytes((nova_str){.ptr="hello", .len=5});
    /* SRC: let mut modified []byte = [] */
    NovaArray_nova_int* _nv_tmp_11 = nova_array_new_nova_int(8);
    NovaArray_nova_byte* modified = _nv_tmp_11;
    /* SRC: for b in original { modified.push(b) } */
    NovaArray_nova_byte* _nv_tmp_12 = original;
    nova_unit _nv_tmp_14;
    for (nova_int _nv_tmp_13 = 0; _nv_tmp_13 < _nv_tmp_12->len; _nv_tmp_13++) {
        nova_byte b = _nv_tmp_12->data[_nv_tmp_13];
        nova_array_push_nova_byte(modified, b);
        (void)(NOVA_UNIT);
    }
    _nv_tmp_14 = NOVA_UNIT;
    _nv_tmp_14;
    /* SRC: modified[0] = (modified[0] as u32 ^ 1) as byte */
    (modified)->data[((nova_int)0LL)] = ((modified)->data[((nova_int)0LL)] ^ ((nova_int)1LL));
    /* SRC: assert(crc32(original) != crc32(modified)) */
    nova_assert((nova_fn_crc32(original) != nova_fn_crc32(modified)), "crc32(original) != crc32(modified)");
    return NOVA_UNIT;
}

static nova_unit nova_test_crc32________________1KB________7(void) {
    /* SRC: let mut data []byte = [] */
    NovaArray_nova_int* _nv_tmp_15 = nova_array_new_nova_int(8);
    NovaArray_nova_byte* data = _nv_tmp_15;
    /* SRC: let mut i = 0 */
    nova_int i = ((nova_int)0LL);
    /* SRC: while i < 1024 { */
    nova_unit _nv_while_16;
    while ((i < ((nova_int)1024LL))) {
        /* SRC: data.push(0) */
        nova_array_push_nova_byte(data, ((nova_int)0LL));
        NOVA_UNIT;
        /* SRC: i += 1 */
        i += ((nova_int)1LL);
    }
    _nv_while_16 = NOVA_UNIT;
    _nv_while_16;
    /* SRC: let result = crc32(data) */
    uint32_t result = nova_fn_crc32(data);
    /* SRC: assert(result == crc32(data)) */
    nova_assert((result == nova_fn_crc32(data)), "result == crc32(data)");
    return NOVA_UNIT;
}

static nova_unit nova_fn_main_impl(void) {
    int _nova_tests_total = 8;
    int _nova_tests_failed = 0;
    printf("Running %d tests...\n", _nova_tests_total);
    {
        NovaTestFrame _tf;
        _tf.fail_msg = NULL;
        _nova_test_frame = &_tf;
        NovaFailFrame _tf_fail;
        _tf_fail.error_msg = (nova_str){.ptr=NULL, .len=0};
        nova_fail_push(&_tf_fail);
        int _tf_jmp = setjmp(_tf.jmp);
        int _tf_fail_jmp = (_tf_jmp == 0) ? setjmp(_tf_fail.jmp) : 0;
        if (_tf_jmp == 0 && _tf_fail_jmp == 0) {
            nova_test_crc32________________0_0();
            printf("  PASS: crc32: пустой ввод → 0\n");
        } else {
            const char* _tf_msg = _tf.fail_msg ? _tf.fail_msg : (_tf_fail.error_msg.ptr ? _tf_fail.error_msg.ptr : "assertion failed");
            printf("  FAIL: crc32: пустой ввод → 0 — %s\n", _tf_msg);
            _nova_tests_failed++;
        }
        nova_fail_pop();
        _nova_test_frame = NULL;
    }
    {
        NovaTestFrame _tf;
        _tf.fail_msg = NULL;
        _nova_test_frame = &_tf;
        NovaFailFrame _tf_fail;
        _tf_fail.error_msg = (nova_str){.ptr=NULL, .len=0};
        nova_fail_push(&_tf_fail);
        int _tf_jmp = setjmp(_tf.jmp);
        int _tf_fail_jmp = (_tf_jmp == 0) ? setjmp(_tf_fail.jmp) : 0;
        if (_tf_jmp == 0 && _tf_fail_jmp == 0) {
            nova_test_crc32__ASCII__123456789____0xCBF43926_______________test_vector__1();
            printf("  PASS: crc32: ASCII '123456789' → 0xCBF43926 (классический test vector)\n");
        } else {
            const char* _tf_msg = _tf.fail_msg ? _tf.fail_msg : (_tf_fail.error_msg.ptr ? _tf_fail.error_msg.ptr : "assertion failed");
            printf("  FAIL: crc32: ASCII '123456789' → 0xCBF43926 (классический test vector) — %s\n", _tf_msg);
            _nova_tests_failed++;
        }
        nova_fail_pop();
        _nova_test_frame = NULL;
    }
    {
        NovaTestFrame _tf;
        _tf.fail_msg = NULL;
        _nova_test_frame = &_tf;
        NovaFailFrame _tf_fail;
        _tf_fail.error_msg = (nova_str){.ptr=NULL, .len=0};
        nova_fail_push(&_tf_fail);
        int _tf_jmp = setjmp(_tf.jmp);
        int _tf_fail_jmp = (_tf_jmp == 0) ? setjmp(_tf_fail.jmp) : 0;
        if (_tf_jmp == 0 && _tf_fail_jmp == 0) {
            nova_test_crc32___hello_world____0x0D4A1185_2();
            printf("  PASS: crc32: 'hello world' → 0x0D4A1185\n");
        } else {
            const char* _tf_msg = _tf.fail_msg ? _tf.fail_msg : (_tf_fail.error_msg.ptr ? _tf_fail.error_msg.ptr : "assertion failed");
            printf("  FAIL: crc32: 'hello world' → 0x0D4A1185 — %s\n", _tf_msg);
            _nova_tests_failed++;
        }
        nova_fail_pop();
        _nova_test_frame = NULL;
    }
    {
        NovaTestFrame _tf;
        _tf.fail_msg = NULL;
        _nova_test_frame = &_tf;
        NovaFailFrame _tf_fail;
        _tf_fail.error_msg = (nova_str){.ptr=NULL, .len=0};
        nova_fail_push(&_tf_fail);
        int _tf_jmp = setjmp(_tf.jmp);
        int _tf_fail_jmp = (_tf_jmp == 0) ? setjmp(_tf_fail.jmp) : 0;
        if (_tf_jmp == 0 && _tf_fail_jmp == 0) {
            nova_test_crc32____________0x00___0xD202EF8D_3();
            printf("  PASS: crc32: один байт 0x00 → 0xD202EF8D\n");
        } else {
            const char* _tf_msg = _tf.fail_msg ? _tf.fail_msg : (_tf_fail.error_msg.ptr ? _tf_fail.error_msg.ptr : "assertion failed");
            printf("  FAIL: crc32: один байт 0x00 → 0xD202EF8D — %s\n", _tf_msg);
            _nova_tests_failed++;
        }
        nova_fail_pop();
        _nova_test_frame = NULL;
    }
    {
        NovaTestFrame _tf;
        _tf.fail_msg = NULL;
        _nova_test_frame = &_tf;
        NovaFailFrame _tf_fail;
        _tf_fail.error_msg = (nova_str){.ptr=NULL, .len=0};
        nova_fail_push(&_tf_fail);
        int _tf_jmp = setjmp(_tf.jmp);
        int _tf_fail_jmp = (_tf_jmp == 0) ? setjmp(_tf_fail.jmp) : 0;
        if (_tf_jmp == 0 && _tf_fail_jmp == 0) {
            nova_test_crc32____________0xFF___0xFF000000_4();
            printf("  PASS: crc32: один байт 0xFF → 0xFF000000\n");
        } else {
            const char* _tf_msg = _tf.fail_msg ? _tf.fail_msg : (_tf_fail.error_msg.ptr ? _tf_fail.error_msg.ptr : "assertion failed");
            printf("  FAIL: crc32: один байт 0xFF → 0xFF000000 — %s\n", _tf_msg);
            _nova_tests_failed++;
        }
        nova_fail_pop();
        _nova_test_frame = NULL;
    }
    {
        NovaTestFrame _tf;
        _tf.fail_msg = NULL;
        _nova_test_frame = &_tf;
        NovaFailFrame _tf_fail;
        _tf_fail.error_msg = (nova_str){.ptr=NULL, .len=0};
        nova_fail_push(&_tf_fail);
        int _tf_jmp = setjmp(_tf.jmp);
        int _tf_fail_jmp = (_tf_jmp == 0) ? setjmp(_tf_fail.jmp) : 0;
        if (_tf_jmp == 0 && _tf_fail_jmp == 0) {
            nova_test_crc32__incremental_______________5();
            printf("  PASS: crc32: incremental == монолитный\n");
        } else {
            const char* _tf_msg = _tf.fail_msg ? _tf.fail_msg : (_tf_fail.error_msg.ptr ? _tf_fail.error_msg.ptr : "assertion failed");
            printf("  FAIL: crc32: incremental == монолитный — %s\n", _tf_msg);
            _nova_tests_failed++;
        }
        nova_fail_pop();
        _nova_test_frame = NULL;
    }
    {
        NovaTestFrame _tf;
        _tf.fail_msg = NULL;
        _nova_test_frame = &_tf;
        NovaFailFrame _tf_fail;
        _tf_fail.error_msg = (nova_str){.ptr=NULL, .len=0};
        nova_fail_push(&_tf_fail);
        int _tf_jmp = setjmp(_tf.jmp);
        int _tf_fail_jmp = (_tf_jmp == 0) ? setjmp(_tf_fail.jmp) : 0;
        if (_tf_jmp == 0 && _tf_fail_jmp == 0) {
            nova_test_crc32_____________________1_______________6();
            printf("  PASS: crc32: чувствительность к 1-битной ошибке\n");
        } else {
            const char* _tf_msg = _tf.fail_msg ? _tf.fail_msg : (_tf_fail.error_msg.ptr ? _tf_fail.error_msg.ptr : "assertion failed");
            printf("  FAIL: crc32: чувствительность к 1-битной ошибке — %s\n", _tf_msg);
            _nova_tests_failed++;
        }
        nova_fail_pop();
        _nova_test_frame = NULL;
    }
    {
        NovaTestFrame _tf;
        _tf.fail_msg = NULL;
        _nova_test_frame = &_tf;
        NovaFailFrame _tf_fail;
        _tf_fail.error_msg = (nova_str){.ptr=NULL, .len=0};
        nova_fail_push(&_tf_fail);
        int _tf_jmp = setjmp(_tf.jmp);
        int _tf_fail_jmp = (_tf_jmp == 0) ? setjmp(_tf_fail.jmp) : 0;
        if (_tf_jmp == 0 && _tf_fail_jmp == 0) {
            nova_test_crc32________________1KB________7();
            printf("  PASS: crc32: длинный ввод (1KB нулей)\n");
        } else {
            const char* _tf_msg = _tf.fail_msg ? _tf.fail_msg : (_tf_fail.error_msg.ptr ? _tf_fail.error_msg.ptr : "assertion failed");
            printf("  FAIL: crc32: длинный ввод (1KB нулей) — %s\n", _tf_msg);
            _nova_tests_failed++;
        }
        nova_fail_pop();
        _nova_test_frame = NULL;
    }
    printf("%d/%d passed\n", _nova_tests_total - _nova_tests_failed, _nova_tests_total);
    if (_nova_tests_failed > 0) { exit(1); }
    return NOVA_UNIT;
}

int main(void) {
    nova_gc_init();
    nova_register_effect_storage((void**)&_nova_handler_Fail);
    nova_register_effect_storage((void**)&_nova_handler_Time);
    nova_fn_main_impl();
    nova_gc_shutdown();
    return 0;
}
