/* Generated by nova-codegen. Do not edit. */
#include "nova_rt/nova_rt.h"

typedef struct { nova_int f0; } _NovaTuple1;
typedef struct { nova_int f0; nova_int f1; } _NovaTuple2;
typedef struct { nova_int f0; nova_int f1; nova_int f2; } _NovaTuple3;
typedef struct { nova_int f0; nova_int f1; nova_int f2; nova_int f3; } _NovaTuple4;
typedef struct { nova_int f0; nova_int f1; nova_int f2; nova_int f3; nova_int f4; } _NovaTuple5;
typedef struct { nova_int f0; nova_int f1; nova_int f2; nova_int f3; nova_int f4; nova_int f5; } _NovaTuple6;
typedef struct { nova_int f0; nova_int f1; nova_int f2; nova_int f3; nova_int f4; nova_int f5; nova_int f6; } _NovaTuple7;
typedef struct { nova_int f0; nova_int f1; nova_int f2; nova_int f3; nova_int f4; nova_int f5; nova_int f6; nova_int f7; } _NovaTuple8;

typedef struct Nova_Fnv64State Nova_Fnv64State;
struct Nova_Fnv64State {
    uint64_t h;
};

static const uint32_t FNV1A_32_OFFSET = ((nova_int)2166136261LL);
static const uint32_t FNV1A_32_PRIME = ((nova_int)16777619LL);
static const uint64_t FNV1A_64_OFFSET = ((nova_int)-3750763034362895579LL);
static const uint64_t FNV1A_64_PRIME = ((nova_int)1099511628211LL);
static uint32_t Nova_Fnv_static_hash32(NovaArray_nova_byte* data);
static uint64_t Nova_Fnv_static_hash64(NovaArray_nova_byte* data);
static uint64_t Nova_Fnv_static_hash_str(nova_str s);
static Nova_Fnv64State* Nova_Fnv64_static_new(void);
static nova_unit Nova_Fnv64State_method_update(Nova_Fnv64State* nova_self, NovaArray_nova_byte* data);
static uint64_t Nova_Fnv64State_method_finalize(Nova_Fnv64State* nova_self);
static nova_unit nova_test_FNV_1a_32______________0(void);
static nova_unit nova_test_FNV_1a_64______________1(void);
static nova_unit nova_test_FNV_1a_32___a__2(void);
static nova_unit nova_test_FNV_1a_64___foobar__3(void);
static nova_unit nova_test________________________hash____________________4(void);
static nova_unit nova_test________inputs__________hashes_________________5(void);
static nova_unit nova_test_streaming_______chunk____split_chunks_6(void);
static nova_unit nova_test_small_change___big_diff__avalanche_ish__7(void);

static uint32_t Nova_Fnv_static_hash32(NovaArray_nova_byte* data) {
    /* SRC: let mut h = FNV1A_32_OFFSET */
    nova_int h = FNV1A_32_OFFSET;
    /* SRC: for b in data { */
    NovaArray_nova_byte* _nv_tmp_0 = data;
    nova_unit _nv_tmp_2;
    for (nova_int _nv_tmp_1 = 0; _nv_tmp_1 < _nv_tmp_0->len; _nv_tmp_1++) {
        nova_byte b = _nv_tmp_0->data[_nv_tmp_1];
        /* SRC: h = h ^ (b as u32 */
        h = (h ^ b);
        /* SRC: h = h * FNV1A_32_PRIME */
        h = (h * FNV1A_32_PRIME);
    }
    _nv_tmp_2 = NOVA_UNIT;
    _nv_tmp_2;
    /* SRC: h */
    return h;
}

static uint64_t Nova_Fnv_static_hash64(NovaArray_nova_byte* data) {
    /* SRC: let mut h = FNV1A_64_OFFSET */
    nova_int h = FNV1A_64_OFFSET;
    /* SRC: for b in data { */
    NovaArray_nova_byte* _nv_tmp_3 = data;
    nova_unit _nv_tmp_5;
    for (nova_int _nv_tmp_4 = 0; _nv_tmp_4 < _nv_tmp_3->len; _nv_tmp_4++) {
        nova_byte b = _nv_tmp_3->data[_nv_tmp_4];
        /* SRC: h = h ^ (b as u64 */
        h = (h ^ b);
        /* SRC: h = h * FNV1A_64_PRIME */
        h = (h * FNV1A_64_PRIME);
    }
    _nv_tmp_5 = NOVA_UNIT;
    _nv_tmp_5;
    /* SRC: h */
    return h;
}

static uint64_t Nova_Fnv_static_hash_str(nova_str s) {
    /* SRC: Fnv.hash64(s.bytes()) */
    return Nova_Fnv_static_hash64(nova_str_bytes(s));
}

static Nova_Fnv64State* Nova_Fnv64_static_new(void) {
    /* SRC: { h: FNV1A_64_OFFSET } */
    Nova_Fnv64State* _nv_tmp_6 = (Nova_Fnv64State*)nova_alloc(sizeof(Nova_Fnv64State));
    _nv_tmp_6->h = FNV1A_64_OFFSET;
    return _nv_tmp_6;
}

static nova_unit Nova_Fnv64State_method_update(Nova_Fnv64State* nova_self, NovaArray_nova_byte* data) {
    /* SRC: for b in data { */
    NovaArray_nova_byte* _nv_tmp_7 = data;
    nova_unit _nv_tmp_9;
    for (nova_int _nv_tmp_8 = 0; _nv_tmp_8 < _nv_tmp_7->len; _nv_tmp_8++) {
        nova_byte b = _nv_tmp_7->data[_nv_tmp_8];
        /* SRC: @h = @h ^ (b as u64 */
        (nova_self->h) = ((nova_self->h) ^ b);
        /* SRC: @h = @h * FNV1A_64_PRIME */
        (nova_self->h) = ((nova_self->h) * FNV1A_64_PRIME);
    }
    _nv_tmp_9 = NOVA_UNIT;
    _nv_tmp_9;
    return NOVA_UNIT;
}

static uint64_t Nova_Fnv64State_method_finalize(Nova_Fnv64State* nova_self) {
    /* SRC: @h */
    return (nova_self->h);
}

static nova_unit nova_test_FNV_1a_32______________0(void) {
    /* SRC: assert(Fnv.hash32([]) == FNV1A_32_OFFSET) */
    NovaArray_nova_int* _nv_tmp_10 = nova_array_new_nova_int(8);
    nova_assert((Nova_Fnv_static_hash32(_nv_tmp_10) == FNV1A_32_OFFSET), "assert(assert) == FNV1A_32_OFFSET");
    return NOVA_UNIT;
}

static nova_unit nova_test_FNV_1a_64______________1(void) {
    /* SRC: assert(Fnv.hash64([]) == FNV1A_64_OFFSET) */
    NovaArray_nova_int* _nv_tmp_11 = nova_array_new_nova_int(8);
    nova_assert((Nova_Fnv_static_hash64(_nv_tmp_11) == FNV1A_64_OFFSET), "assert(assert) == FNV1A_64_OFFSET");
    return NOVA_UNIT;
}

static nova_unit nova_test_FNV_1a_32___a__2(void) {
    /* SRC: assert(Fnv.hash32("a".bytes()) == 0xE40C292C) */
    nova_assert((Nova_Fnv_static_hash32(nova_str_bytes((nova_str){.ptr="a", .len=1})) == ((nova_int)3826002220LL)), "assert(assert()) == 3826002220");
    return NOVA_UNIT;
}

static nova_unit nova_test_FNV_1a_64___foobar__3(void) {
    /* SRC: assert(Fnv.hash64("foobar".bytes()) == 0x85944171F73967E8) */
    nova_assert((Nova_Fnv_static_hash64(nova_str_bytes((nova_str){.ptr="foobar", .len=6})) == ((nova_int)-8821353812377114648LL)), "assert(assert()) == -8821353812377114648");
    return NOVA_UNIT;
}

static nova_unit nova_test________________________hash____________________4(void) {
    /* SRC: let a = Fnv.hash_str("test") */
    uint64_t a = Nova_Fnv_static_hash_str((nova_str){.ptr="test", .len=4});
    /* SRC: let b = Fnv.hash_str("test") */
    uint64_t b = Nova_Fnv_static_hash_str((nova_str){.ptr="test", .len=4});
    /* SRC: assert(a == b) */
    nova_assert((a == b), "a == b");
    return NOVA_UNIT;
}

static nova_unit nova_test________inputs__________hashes_________________5(void) {
    /* SRC: let a = Fnv.hash_str("hello") */
    uint64_t a = Nova_Fnv_static_hash_str((nova_str){.ptr="hello", .len=5});
    /* SRC: let b = Fnv.hash_str("world") */
    uint64_t b = Nova_Fnv_static_hash_str((nova_str){.ptr="world", .len=5});
    /* SRC: assert(a != b) */
    nova_assert((a != b), "a != b");
    return NOVA_UNIT;
}

static nova_unit nova_test_streaming_______chunk____split_chunks_6(void) {
    /* SRC: let full = "Hello, world!".bytes() */
    NovaArray_nova_byte* full = nova_str_bytes((nova_str){.ptr="Hello, world!", .len=13});
    /* SRC: let one_shot = Fnv.hash64(full) */
    uint64_t one_shot = Nova_Fnv_static_hash64(full);
    /* SRC: let mut state = Fnv64.new() */
    Nova_Fnv64State* state = Nova_Fnv64_static_new();
    /* SRC: state.update("Hello, ".bytes()) */
    Nova_Fnv64State_method_update(state, nova_str_bytes((nova_str){.ptr="Hello, ", .len=7}));
    /* SRC: state.update("world!".bytes()) */
    Nova_Fnv64State_method_update(state, nova_str_bytes((nova_str){.ptr="world!", .len=6}));
    /* SRC: let streaming = state.finalize() */
    uint64_t streaming = Nova_Fnv64State_method_finalize(state);
    /* SRC: assert(one_shot == streaming) */
    nova_assert((one_shot == streaming), "one_shot == streaming");
    return NOVA_UNIT;
}

static nova_unit nova_test_small_change___big_diff__avalanche_ish__7(void) {
    /* SRC: let h1 = Fnv.hash_str("hello") */
    uint64_t h1 = Nova_Fnv_static_hash_str((nova_str){.ptr="hello", .len=5});
    /* SRC: let h2 = Fnv.hash_str("Hello") */
    uint64_t h2 = Nova_Fnv_static_hash_str((nova_str){.ptr="Hello", .len=5});
    /* SRC: assert(h1 != h2) */
    nova_assert((h1 != h2), "h1 != h2");
    /* SRC: let xor_diff = h1 ^ h2 */
    uint64_t xor_diff = (h1 ^ h2);
    /* SRC: assert(xor_diff != 0) */
    nova_assert((xor_diff != ((nova_int)0LL)), "xor_diff != 0");
    return NOVA_UNIT;
}

static nova_unit nova_fn_main_impl(void) {
    int _nova_tests_total = 8;
    int _nova_tests_failed = 0;
    printf("Running %d tests...\n", _nova_tests_total);
    {
        NovaTestFrame _tf;
        _tf.fail_msg = NULL;
        _nova_test_frame = &_tf;
        NovaFailFrame _tf_fail;
        _tf_fail.error_msg = (nova_str){.ptr=NULL, .len=0};
        nova_fail_push(&_tf_fail);
        int _tf_jmp = setjmp(_tf.jmp);
        int _tf_fail_jmp = (_tf_jmp == 0) ? setjmp(_tf_fail.jmp) : 0;
        if (_tf_jmp == 0 && _tf_fail_jmp == 0) {
            nova_test_FNV_1a_32______________0();
            printf("  PASS: FNV-1a 32: пустой ввод\n");
        } else {
            const char* _tf_msg = _tf.fail_msg ? _tf.fail_msg : (_tf_fail.error_msg.ptr ? _tf_fail.error_msg.ptr : "assertion failed");
            printf("  FAIL: FNV-1a 32: пустой ввод — %s\n", _tf_msg);
            _nova_tests_failed++;
        }
        nova_fail_pop();
        _nova_test_frame = NULL;
    }
    {
        NovaTestFrame _tf;
        _tf.fail_msg = NULL;
        _nova_test_frame = &_tf;
        NovaFailFrame _tf_fail;
        _tf_fail.error_msg = (nova_str){.ptr=NULL, .len=0};
        nova_fail_push(&_tf_fail);
        int _tf_jmp = setjmp(_tf.jmp);
        int _tf_fail_jmp = (_tf_jmp == 0) ? setjmp(_tf_fail.jmp) : 0;
        if (_tf_jmp == 0 && _tf_fail_jmp == 0) {
            nova_test_FNV_1a_64______________1();
            printf("  PASS: FNV-1a 64: пустой ввод\n");
        } else {
            const char* _tf_msg = _tf.fail_msg ? _tf.fail_msg : (_tf_fail.error_msg.ptr ? _tf_fail.error_msg.ptr : "assertion failed");
            printf("  FAIL: FNV-1a 64: пустой ввод — %s\n", _tf_msg);
            _nova_tests_failed++;
        }
        nova_fail_pop();
        _nova_test_frame = NULL;
    }
    {
        NovaTestFrame _tf;
        _tf.fail_msg = NULL;
        _nova_test_frame = &_tf;
        NovaFailFrame _tf_fail;
        _tf_fail.error_msg = (nova_str){.ptr=NULL, .len=0};
        nova_fail_push(&_tf_fail);
        int _tf_jmp = setjmp(_tf.jmp);
        int _tf_fail_jmp = (_tf_jmp == 0) ? setjmp(_tf_fail.jmp) : 0;
        if (_tf_jmp == 0 && _tf_fail_jmp == 0) {
            nova_test_FNV_1a_32___a__2();
            printf("  PASS: FNV-1a 32: 'a'\n");
        } else {
            const char* _tf_msg = _tf.fail_msg ? _tf.fail_msg : (_tf_fail.error_msg.ptr ? _tf_fail.error_msg.ptr : "assertion failed");
            printf("  FAIL: FNV-1a 32: 'a' — %s\n", _tf_msg);
            _nova_tests_failed++;
        }
        nova_fail_pop();
        _nova_test_frame = NULL;
    }
    {
        NovaTestFrame _tf;
        _tf.fail_msg = NULL;
        _nova_test_frame = &_tf;
        NovaFailFrame _tf_fail;
        _tf_fail.error_msg = (nova_str){.ptr=NULL, .len=0};
        nova_fail_push(&_tf_fail);
        int _tf_jmp = setjmp(_tf.jmp);
        int _tf_fail_jmp = (_tf_jmp == 0) ? setjmp(_tf_fail.jmp) : 0;
        if (_tf_jmp == 0 && _tf_fail_jmp == 0) {
            nova_test_FNV_1a_64___foobar__3();
            printf("  PASS: FNV-1a 64: 'foobar'\n");
        } else {
            const char* _tf_msg = _tf.fail_msg ? _tf.fail_msg : (_tf_fail.error_msg.ptr ? _tf_fail.error_msg.ptr : "assertion failed");
            printf("  FAIL: FNV-1a 64: 'foobar' — %s\n", _tf_msg);
            _nova_tests_failed++;
        }
        nova_fail_pop();
        _nova_test_frame = NULL;
    }
    {
        NovaTestFrame _tf;
        _tf.fail_msg = NULL;
        _nova_test_frame = &_tf;
        NovaFailFrame _tf_fail;
        _tf_fail.error_msg = (nova_str){.ptr=NULL, .len=0};
        nova_fail_push(&_tf_fail);
        int _tf_jmp = setjmp(_tf.jmp);
        int _tf_fail_jmp = (_tf_jmp == 0) ? setjmp(_tf_fail.jmp) : 0;
        if (_tf_jmp == 0 && _tf_fail_jmp == 0) {
            nova_test________________________hash____________________4();
            printf("  PASS: детерминизм: повторный hash → тот же результат\n");
        } else {
            const char* _tf_msg = _tf.fail_msg ? _tf.fail_msg : (_tf_fail.error_msg.ptr ? _tf_fail.error_msg.ptr : "assertion failed");
            printf("  FAIL: детерминизм: повторный hash → тот же результат — %s\n", _tf_msg);
            _nova_tests_failed++;
        }
        nova_fail_pop();
        _nova_test_frame = NULL;
    }
    {
        NovaTestFrame _tf;
        _tf.fail_msg = NULL;
        _nova_test_frame = &_tf;
        NovaFailFrame _tf_fail;
        _tf_fail.error_msg = (nova_str){.ptr=NULL, .len=0};
        nova_fail_push(&_tf_fail);
        int _tf_jmp = setjmp(_tf.jmp);
        int _tf_fail_jmp = (_tf_jmp == 0) ? setjmp(_tf_fail.jmp) : 0;
        if (_tf_jmp == 0 && _tf_fail_jmp == 0) {
            nova_test________inputs__________hashes_________________5();
            printf("  PASS: разные inputs → разные hashes (статистически)\n");
        } else {
            const char* _tf_msg = _tf.fail_msg ? _tf.fail_msg : (_tf_fail.error_msg.ptr ? _tf_fail.error_msg.ptr : "assertion failed");
            printf("  FAIL: разные inputs → разные hashes (статистически) — %s\n", _tf_msg);
            _nova_tests_failed++;
        }
        nova_fail_pop();
        _nova_test_frame = NULL;
    }
    {
        NovaTestFrame _tf;
        _tf.fail_msg = NULL;
        _nova_test_frame = &_tf;
        NovaFailFrame _tf_fail;
        _tf_fail.error_msg = (nova_str){.ptr=NULL, .len=0};
        nova_fail_push(&_tf_fail);
        int _tf_jmp = setjmp(_tf.jmp);
        int _tf_fail_jmp = (_tf_jmp == 0) ? setjmp(_tf_fail.jmp) : 0;
        if (_tf_jmp == 0 && _tf_fail_jmp == 0) {
            nova_test_streaming_______chunk____split_chunks_6();
            printf("  PASS: streaming: один chunk == split chunks\n");
        } else {
            const char* _tf_msg = _tf.fail_msg ? _tf.fail_msg : (_tf_fail.error_msg.ptr ? _tf_fail.error_msg.ptr : "assertion failed");
            printf("  FAIL: streaming: один chunk == split chunks — %s\n", _tf_msg);
            _nova_tests_failed++;
        }
        nova_fail_pop();
        _nova_test_frame = NULL;
    }
    {
        NovaTestFrame _tf;
        _tf.fail_msg = NULL;
        _nova_test_frame = &_tf;
        NovaFailFrame _tf_fail;
        _tf_fail.error_msg = (nova_str){.ptr=NULL, .len=0};
        nova_fail_push(&_tf_fail);
        int _tf_jmp = setjmp(_tf.jmp);
        int _tf_fail_jmp = (_tf_jmp == 0) ? setjmp(_tf_fail.jmp) : 0;
        if (_tf_jmp == 0 && _tf_fail_jmp == 0) {
            nova_test_small_change___big_diff__avalanche_ish__7();
            printf("  PASS: small change → big diff (avalanche-ish)\n");
        } else {
            const char* _tf_msg = _tf.fail_msg ? _tf.fail_msg : (_tf_fail.error_msg.ptr ? _tf_fail.error_msg.ptr : "assertion failed");
            printf("  FAIL: small change → big diff (avalanche-ish) — %s\n", _tf_msg);
            _nova_tests_failed++;
        }
        nova_fail_pop();
        _nova_test_frame = NULL;
    }
    printf("%d/%d passed\n", _nova_tests_total - _nova_tests_failed, _nova_tests_total);
    if (_nova_tests_failed > 0) { exit(1); }
    return NOVA_UNIT;
}

int main(void) {
    nova_gc_init();
    nova_register_effect_storage((void**)&_nova_handler_Fail);
    nova_register_effect_storage((void**)&_nova_handler_Time);
    nova_fn_main_impl();
    nova_gc_shutdown();
    return 0;
}
