/* Generated by nova-codegen. Do not edit. */
#include "nova_rt/nova_rt.h"

typedef struct { nova_int f0; } _NovaTuple1;
typedef struct { nova_int f0; nova_int f1; } _NovaTuple2;
typedef struct { nova_int f0; nova_int f1; nova_int f2; } _NovaTuple3;
typedef struct { nova_int f0; nova_int f1; nova_int f2; nova_int f3; } _NovaTuple4;
typedef struct { nova_int f0; nova_int f1; nova_int f2; nova_int f3; nova_int f4; } _NovaTuple5;
typedef struct { nova_int f0; nova_int f1; nova_int f2; nova_int f3; nova_int f4; nova_int f5; } _NovaTuple6;
typedef struct { nova_int f0; nova_int f1; nova_int f2; nova_int f3; nova_int f4; nova_int f5; nova_int f6; } _NovaTuple7;
typedef struct { nova_int f0; nova_int f1; nova_int f2; nova_int f3; nova_int f4; nova_int f5; nova_int f6; nova_int f7; } _NovaTuple8;

typedef enum {
    NOVA_TAG_ParseHexError_OddLength,
    NOVA_TAG_ParseHexError_InvalidChar,
} Nova_ParseHexError_Tag;
typedef struct Nova_ParseHexError Nova_ParseHexError;
struct Nova_ParseHexError {
    Nova_ParseHexError_Tag tag;
    union {
        struct {
            nova_int actual;
        } OddLength;
        struct {
            nova_int position;
            Nova_char* char;
        } InvalidChar;
    } payload;
};

static Nova_ParseHexError* nova_make_ParseHexError_OddLength(nova_int _0) {
    Nova_ParseHexError* _r = (Nova_ParseHexError*)nova_alloc(sizeof(Nova_ParseHexError));
    _r->tag = NOVA_TAG_ParseHexError_OddLength;
    _r->payload.OddLength.actual = _0;
    return _r;
}

static Nova_ParseHexError* nova_make_ParseHexError_InvalidChar(nova_int _0, Nova_char* _1) {
    Nova_ParseHexError* _r = (Nova_ParseHexError*)nova_alloc(sizeof(Nova_ParseHexError));
    _r->tag = NOVA_TAG_ParseHexError_InvalidChar;
    _r->payload.InvalidChar.position = _0;
    _r->payload.InvalidChar.char = _1;
    return _r;
}

static nova_str Nova_Hex_static_encode(NovaArray_nova_byte* data);
static nova_str Nova_Hex_static_encode_upper(NovaArray_nova_byte* data);
static nova_str nova_fn_encode_with(NovaArray_nova_byte* data, nova_bool upper);
static Nova_char* nova_fn_digit(uint8_t n, nova_bool upper);
static NovaArray_nova_byte* Nova_Hex_static_decode(nova_str s);
static nova_int nova_fn_digit_value(nova_str s, nova_int pos);
static nova_unit nova_test_encode________________0(void);
static nova_unit nova_test_encode__lowercase______________1(void);
static nova_unit nova_test_encode_upper__uppercase_2(void);
static nova_unit nova_test_encode__leading_zeros_____________3(void);
static nova_unit nova_test_decode__round_trip_4(void);
static nova_unit nova_test_decode__case_insensitive_5(void);
static nova_unit nova_test_decode__________________________6(void);
static nova_unit nova_test_decode_____________________________7(void);

static nova_str Nova_Hex_static_encode(NovaArray_nova_byte* data) {
    /* SRC: encode_with(data, false) */
    return nova_fn_encode_with(data, false);
}

static nova_str Nova_Hex_static_encode_upper(NovaArray_nova_byte* data) {
    /* SRC: encode_with(data, true) */
    return nova_fn_encode_with(data, true);
}

static nova_str nova_fn_encode_with(NovaArray_nova_byte* data, nova_bool upper) {
    /* SRC: let mut buf = Buffer.with_capacity(data.len * 2) */
    Nova_Buffer* buf = Nova_Buffer_static_with_capacity(((data->len) * ((nova_int)2LL)));
    /* SRC: for b in data { */
    NovaArray_nova_byte* _nv_tmp_0 = data;
    nova_unit _nv_tmp_2;
    for (nova_int _nv_tmp_1 = 0; _nv_tmp_1 < _nv_tmp_0->len; _nv_tmp_1++) {
        nova_byte b = _nv_tmp_0->data[_nv_tmp_1];
        /* SRC: let hi = (b as int) / 16 */
        nova_int hi = (b / ((nova_int)16LL));
        /* SRC: let lo = (b as int) % 16 */
        nova_int lo = (b % ((nova_int)16LL));
        /* SRC: buf.add_char(digit(hi as u8, upper)) */
        Nova_Buffer_method_add_char(buf, nova_fn_digit(hi, upper));
        (void)(Nova_Buffer_method_add_char(buf, nova_fn_digit(lo, upper)));
    }
    _nv_tmp_2 = NOVA_UNIT;
    _nv_tmp_2;
    /* SRC: buf.into_str_unchecked() */
    return Nova_Buffer_method_into_str_unchecked(buf);
}

static Nova_char* nova_fn_digit(uint8_t n, nova_bool upper) {
    /* SRC: if n < 10 { */
    nova_int _nv_if_3;
    if ((n < ((nova_int)10LL))) {
        _nv_if_3 = (nova_int)((((nova_int)48LL) + n));
    } else {
        nova_int _nv_if_4;
        if (upper) {
            _nv_if_4 = (nova_int)(((((nova_int)65LL) + n) - ((nova_int)10LL)));
        } else {
            _nv_if_4 = (nova_int)(((((nova_int)97LL) + n) - ((nova_int)10LL)));
        }
        _nv_if_3 = (nova_int)(_nv_if_4);
    }
    return _nv_if_3;
}

static NovaArray_nova_byte* Nova_Hex_static_decode(nova_str s) {
    /* SRC: if s.len % 2 != 0 { */
    nova_unit _nv_if_5;
    if (((nova_str_char_len(s) % ((nova_int)2LL)) != ((nova_int)0LL))) {
        /* SRC: throw OddLength { actual: s.len } */
        Nova_ParseHexError* _nv_tmp_6 = nova_make_ParseHexError_OddLength(nova_str_char_len(s));
        Nova_Fail_fail(nova_int_to_str((nova_int)(_nv_tmp_6)));
        _nv_if_5 = NOVA_UNIT;
    }
    _nv_if_5;
    /* SRC: let mut out []byte = [] */
    NovaArray_nova_int* _nv_tmp_7 = nova_array_new_nova_int(8);
    NovaArray_nova_byte* out = _nv_tmp_7;
    /* SRC: byte.with_capacity(s.len / 2) */
    byte.with_capacity((nova_str_char_len(s) / ((nova_int)2LL)));
    /* SRC: let mut i = 0 */
    nova_int i = ((nova_int)0LL);
    /* SRC: while i < s.len { */
    nova_unit _nv_while_8;
    while ((i < nova_str_char_len(s))) {
        /* SRC: let hi = digit_value(s, i) */
        nova_int hi = nova_fn_digit_value(s, i);
        /* SRC: let lo = digit_value(s, i + 1) */
        nova_int lo = nova_fn_digit_value(s, (i + ((nova_int)1LL)));
        /* SRC: out.push(((hi * 16 + lo) & 0xFF) as byte) */
        nova_array_push_nova_byte(out, (((hi * ((nova_int)16LL)) + lo) & ((nova_int)255LL)));
        NOVA_UNIT;
        /* SRC: i += 2 */
        i += ((nova_int)2LL);
    }
    _nv_while_8 = NOVA_UNIT;
    _nv_while_8;
    /* SRC: out */
    return out;
}

static nova_int nova_fn_digit_value(nova_str s, nova_int pos) {
    /* SRC: match s.char_at(pos) { */
    nova_int _nv_scr_9 = s.char_at(pos);
    uint8_t _nv_match_10;
    int _nv_matched_11 = 0;
    if (!_nv_matched_11 && ((_nv_scr_9->tag == NOVA_TAG_Option_Some))) {
        nova_int c = _nv_scr_9->payload.Some._0;
        /* SRC: let n = c as int */
        nova_int n = c;
        nova_int _nv_if_12;
        if (((n >= ((nova_int)48LL)) && (n <= ((nova_int)57LL)))) {
            _nv_if_12 = (nova_int)((n - ((nova_int)48LL)));
        } else {
            nova_int _nv_if_13;
            if (((n >= ((nova_int)97LL)) && (n <= ((nova_int)102LL)))) {
                _nv_if_13 = (nova_int)(((n - ((nova_int)97LL)) + ((nova_int)10LL)));
            } else {
                nova_int _nv_if_14;
                if (((n >= ((nova_int)65LL)) && (n <= ((nova_int)70LL)))) {
                    _nv_if_14 = (nova_int)(((n - ((nova_int)65LL)) + ((nova_int)10LL)));
                } else {
                    /* SRC: throw InvalidChar { position: pos, char: c } */
                    Nova_ParseHexError* _nv_tmp_15 = nova_make_ParseHexError_InvalidChar(pos, c);
                    Nova_Fail_fail(nova_int_to_str((nova_int)(_nv_tmp_15)));
                    _nv_if_14 = (nova_int)0;
                }
                _nv_if_13 = (nova_int)(_nv_if_14);
            }
            _nv_if_12 = (nova_int)(_nv_if_13);
        }
        _nv_match_10 = _nv_if_12;
        _nv_matched_11 = 1;
    }
    if (!_nv_matched_11 && ((_nv_scr_9->tag == NOVA_TAG_Option_None))) {
        Nova_ParseHexError* _nv_tmp_16 = nova_make_ParseHexError_InvalidChar(pos, ((nova_int)32LL));
        Nova_Fail_fail(_nv_tmp_16);
        _nv_match_10 = ((nova_int)0LL);
        _nv_matched_11 = 1;
    }
    return _nv_match_10;
}

static nova_unit nova_test_encode________________0(void) {
    /* SRC: let empty []byte = [] */
    NovaArray_nova_int* _nv_tmp_17 = nova_array_new_nova_int(8);
    NovaArray_nova_byte* empty = _nv_tmp_17;
    /* SRC: assert(Hex.encode(empty) == "") */
    nova_assert((nova_str_eq(Nova_Hex_static_encode(empty), (nova_str){.ptr="", .len=0})), "assert(empty) == \"\"");
    return NOVA_UNIT;
}

static nova_unit nova_test_encode__lowercase______________1(void) {
    /* SRC: let data []byte = [0xDE, 0xAD, 0xBE, 0xEF] */
    NovaArray_nova_int* _nv_tmp_18 = nova_array_new_nova_int(4);
    nova_array_push_nova_int(_nv_tmp_18, (nova_int)(((nova_int)222LL)));
    nova_array_push_nova_int(_nv_tmp_18, (nova_int)(((nova_int)173LL)));
    nova_array_push_nova_int(_nv_tmp_18, (nova_int)(((nova_int)190LL)));
    nova_array_push_nova_int(_nv_tmp_18, (nova_int)(((nova_int)239LL)));
    NovaArray_nova_byte* data = _nv_tmp_18;
    /* SRC: assert(Hex.encode(data) == "deadbeef") */
    nova_assert((nova_str_eq(Nova_Hex_static_encode(data), (nova_str){.ptr="deadbeef", .len=8})), "assert(data) == \"deadbeef\"");
    return NOVA_UNIT;
}

static nova_unit nova_test_encode_upper__uppercase_2(void) {
    /* SRC: let data []byte = [0xDE, 0xAD, 0xBE, 0xEF] */
    NovaArray_nova_int* _nv_tmp_19 = nova_array_new_nova_int(4);
    nova_array_push_nova_int(_nv_tmp_19, (nova_int)(((nova_int)222LL)));
    nova_array_push_nova_int(_nv_tmp_19, (nova_int)(((nova_int)173LL)));
    nova_array_push_nova_int(_nv_tmp_19, (nova_int)(((nova_int)190LL)));
    nova_array_push_nova_int(_nv_tmp_19, (nova_int)(((nova_int)239LL)));
    NovaArray_nova_byte* data = _nv_tmp_19;
    /* SRC: assert(Hex.encode_upper(data) == "DEADBEEF") */
    nova_assert((nova_str_eq(Nova_Hex_static_encode_upper(data), (nova_str){.ptr="DEADBEEF", .len=8})), "assert(data) == \"DEADBEEF\"");
    return NOVA_UNIT;
}

static nova_unit nova_test_encode__leading_zeros_____________3(void) {
    /* SRC: let data []byte = [0x00, 0x01, 0x0F] */
    NovaArray_nova_int* _nv_tmp_20 = nova_array_new_nova_int(3);
    nova_array_push_nova_int(_nv_tmp_20, (nova_int)(((nova_int)0LL)));
    nova_array_push_nova_int(_nv_tmp_20, (nova_int)(((nova_int)1LL)));
    nova_array_push_nova_int(_nv_tmp_20, (nova_int)(((nova_int)15LL)));
    NovaArray_nova_byte* data = _nv_tmp_20;
    /* SRC: assert(Hex.encode(data) == "00010f") */
    nova_assert((nova_str_eq(Nova_Hex_static_encode(data), (nova_str){.ptr="00010f", .len=6})), "assert(data) == \"00010f\"");
    return NOVA_UNIT;
}

static nova_unit nova_test_decode__round_trip_4(void) {
    /* SRC: let cases = [ */
    NovaArray_nova_int* _nv_tmp_21 = nova_array_new_nova_int(4);
    NovaArray_nova_int* _nv_tmp_22 = nova_array_new_nova_int(8);
    nova_array_push_nova_int(_nv_tmp_21, (nova_int)(_nv_tmp_22));
    NovaArray_nova_int* _nv_tmp_23 = nova_array_new_nova_int(1);
    nova_array_push_nova_int(_nv_tmp_23, (nova_int)(((nova_int)0LL)));
    nova_array_push_nova_int(_nv_tmp_21, (nova_int)(_nv_tmp_23));
    NovaArray_nova_int* _nv_tmp_24 = nova_array_new_nova_int(4);
    nova_array_push_nova_int(_nv_tmp_24, (nova_int)(((nova_int)222LL)));
    nova_array_push_nova_int(_nv_tmp_24, (nova_int)(((nova_int)173LL)));
    nova_array_push_nova_int(_nv_tmp_24, (nova_int)(((nova_int)190LL)));
    nova_array_push_nova_int(_nv_tmp_24, (nova_int)(((nova_int)239LL)));
    nova_array_push_nova_int(_nv_tmp_21, (nova_int)(_nv_tmp_24));
    NovaArray_nova_int* _nv_tmp_25 = nova_array_new_nova_int(4);
    nova_array_push_nova_int(_nv_tmp_25, (nova_int)(((nova_int)0LL)));
    nova_array_push_nova_int(_nv_tmp_25, (nova_int)(((nova_int)1LL)));
    nova_array_push_nova_int(_nv_tmp_25, (nova_int)(((nova_int)255LL)));
    nova_array_push_nova_int(_nv_tmp_25, (nova_int)(((nova_int)128LL)));
    nova_array_push_nova_int(_nv_tmp_21, (nova_int)(_nv_tmp_25));
    NovaArray_nova_int* cases = _nv_tmp_21;
    /* SRC: for data in cases { */
    NovaArray_nova_int* _nv_tmp_26 = cases;
    nova_unit _nv_tmp_28;
    for (nova_int _nv_tmp_27 = 0; _nv_tmp_27 < _nv_tmp_26->len; _nv_tmp_27++) {
        NovaArray_nova_int* data = (NovaArray_nova_int*)_nv_tmp_26->data[_nv_tmp_27];
        /* SRC: let encoded = Hex.encode(data) */
        nova_str encoded = Nova_Hex_static_encode(data);
        /* SRC: let decoded = Hex.decode(encoded) */
        NovaArray_nova_byte* decoded = Nova_Hex_static_decode(encoded);
        (void)(nova_assert((nova_array_eq_nova_byte(decoded, data)), "decoded == data"));
    }
    _nv_tmp_28 = NOVA_UNIT;
    _nv_tmp_28;
    return NOVA_UNIT;
}

static nova_unit nova_test_decode__case_insensitive_5(void) {
    /* SRC: assert(Hex.decode("DEADbeef") == [0xDE, 0xAD, 0xBE, 0xEF]) */
    NovaArray_nova_int* _nv_tmp_29 = nova_array_new_nova_int(4);
    nova_array_push_nova_int(_nv_tmp_29, (nova_int)(((nova_int)222LL)));
    nova_array_push_nova_int(_nv_tmp_29, (nova_int)(((nova_int)173LL)));
    nova_array_push_nova_int(_nv_tmp_29, (nova_int)(((nova_int)190LL)));
    nova_array_push_nova_int(_nv_tmp_29, (nova_int)(((nova_int)239LL)));
    nova_assert((nova_array_eq_nova_byte(Nova_Hex_static_decode((nova_str){.ptr="DEADbeef", .len=8}), _nv_tmp_29)), "assert(\"DEADbeef\") == assert");
    /* SRC: assert(Hex.decode("deadBEEF") == [0xDE, 0xAD, 0xBE, 0xEF]) */
    NovaArray_nova_int* _nv_tmp_30 = nova_array_new_nova_int(4);
    nova_array_push_nova_int(_nv_tmp_30, (nova_int)(((nova_int)222LL)));
    nova_array_push_nova_int(_nv_tmp_30, (nova_int)(((nova_int)173LL)));
    nova_array_push_nova_int(_nv_tmp_30, (nova_int)(((nova_int)190LL)));
    nova_array_push_nova_int(_nv_tmp_30, (nova_int)(((nova_int)239LL)));
    nova_assert((nova_array_eq_nova_byte(Nova_Hex_static_decode((nova_str){.ptr="deadBEEF", .len=8}), _nv_tmp_30)), "assert(\"deadBEEF\") == assert");
    return NOVA_UNIT;
}

static nova_int nova_lambda_0_body(void* _env_ptr, nova_int e);
typedef struct { int _dummy; } nova_lambda_0_env;
static nova_int nova_lambda_0_body(void* _env_ptr, nova_int e) {
    nova_interrupt((nova_int)(nova_make_Option_Some(e)));
    return NOVA_UNIT;
}

static nova_unit nova_test_decode__________________________6(void) {
    /* SRC: let r = with Fail[ParseHexError] = (e) => interrupt Some(e) { */
    nova_lambda_0_env* _nv_tmp_31 = (nova_lambda_0_env*)nova_alloc(sizeof(nova_lambda_0_env));
    NovaClos_ii* _nv_tmp_32 = (NovaClos_ii*)nova_alloc(sizeof(NovaClos_ii));
    _nv_tmp_32->fn = (nova_fn_ii)(nova_lambda_0_body);
    _nv_tmp_32->env = (void*)(_nv_tmp_31);
    NovaVtable_Fail* _nv_tmp_33 = _nova_handler_Fail;
    _nova_handler_Fail = (void*)(_nv_tmp_32);
    NovaFailFrame _nv_tmp_34;
    nova_fail_push(&_nv_tmp_34);
    NovaInterruptFrame _nv_tmp_35;
    nova_int _nv_tmp_36;
    nova_interrupt_push(&_nv_tmp_35);
    if (setjmp(_nv_tmp_34.jmp) == 0) {
        if (setjmp(_nv_tmp_35.jmp) == 0) {
            {
                /* SRC: let _ = Hex.decode("abc") */
                NovaArray_nova_byte* _nv_tmp_37 = Nova_Hex_static_decode((nova_str){.ptr="abc", .len=3});
                (void)(nova_make_Option_None());
                _nv_tmp_36 = ((nova_int)0LL);
            }
        } else {
            _nv_tmp_36 = _nv_tmp_35.value;
        }
    } else {
        _nv_tmp_36 = ((nova_int)0LL);
    }
    nova_fail_pop();
    _nova_handler_Fail = _nv_tmp_33;
    nova_interrupt_pop();
    nova_int r = _nv_tmp_36;
    /* SRC: assert(match r { */
    nova_int _nv_scr_38 = r;
    nova_bool _nv_match_39;
    int _nv_matched_40 = 0;
    if (!_nv_matched_40 && (((_nv_scr_38->tag == NOVA_TAG_Option_Some) && ((_nv_scr_38->payload.Some._0->tag == NOVA_TAG_ParseHexError_OddLength))))) {
        _nv_match_39 = true;
        _nv_matched_40 = 1;
    }
    if (!_nv_matched_40 && (true)) {
        _nv_match_39 = false;
        _nv_matched_40 = 1;
    }
    nova_assert(_nv_match_39, "assert");
    return NOVA_UNIT;
}

static nova_int nova_lambda_1_body(void* _env_ptr, nova_int e);
typedef struct { int _dummy; } nova_lambda_1_env;
static nova_int nova_lambda_1_body(void* _env_ptr, nova_int e) {
    nova_interrupt((nova_int)(nova_make_Option_Some(e)));
    return NOVA_UNIT;
}

static nova_unit nova_test_decode_____________________________7(void) {
    /* SRC: let r = with Fail[ParseHexError] = (e) => interrupt Some(e) { */
    nova_lambda_1_env* _nv_tmp_41 = (nova_lambda_1_env*)nova_alloc(sizeof(nova_lambda_1_env));
    NovaClos_ii* _nv_tmp_42 = (NovaClos_ii*)nova_alloc(sizeof(NovaClos_ii));
    _nv_tmp_42->fn = (nova_fn_ii)(nova_lambda_1_body);
    _nv_tmp_42->env = (void*)(_nv_tmp_41);
    NovaVtable_Fail* _nv_tmp_43 = _nova_handler_Fail;
    _nova_handler_Fail = (void*)(_nv_tmp_42);
    NovaFailFrame _nv_tmp_44;
    nova_fail_push(&_nv_tmp_44);
    NovaInterruptFrame _nv_tmp_45;
    nova_int _nv_tmp_46;
    nova_interrupt_push(&_nv_tmp_45);
    if (setjmp(_nv_tmp_44.jmp) == 0) {
        if (setjmp(_nv_tmp_45.jmp) == 0) {
            {
                /* SRC: let _ = Hex.decode("abXY") */
                NovaArray_nova_byte* _nv_tmp_47 = Nova_Hex_static_decode((nova_str){.ptr="abXY", .len=4});
                (void)(nova_make_Option_None());
                _nv_tmp_46 = ((nova_int)0LL);
            }
        } else {
            _nv_tmp_46 = _nv_tmp_45.value;
        }
    } else {
        _nv_tmp_46 = ((nova_int)0LL);
    }
    nova_fail_pop();
    _nova_handler_Fail = _nv_tmp_43;
    nova_interrupt_pop();
    nova_int r = _nv_tmp_46;
    /* SRC: assert(match r { */
    nova_int _nv_scr_48 = r;
    nova_bool _nv_match_49;
    int _nv_matched_50 = 0;
    if (!_nv_matched_50 && (((_nv_scr_48->tag == NOVA_TAG_Option_Some) && ((_nv_scr_48->payload.Some._0->tag == NOVA_TAG_ParseHexError_InvalidChar))))) {
        _nv_match_49 = true;
        _nv_matched_50 = 1;
    }
    if (!_nv_matched_50 && (true)) {
        _nv_match_49 = false;
        _nv_matched_50 = 1;
    }
    nova_assert(_nv_match_49, "assert");
    return NOVA_UNIT;
}

static nova_unit nova_fn_main_impl(void) {
    int _nova_tests_total = 8;
    int _nova_tests_failed = 0;
    printf("Running %d tests...\n", _nova_tests_total);
    {
        NovaTestFrame _tf;
        _tf.fail_msg = NULL;
        _nova_test_frame = &_tf;
        NovaFailFrame _tf_fail;
        _tf_fail.error_msg = (nova_str){.ptr=NULL, .len=0};
        nova_fail_push(&_tf_fail);
        int _tf_jmp = setjmp(_tf.jmp);
        int _tf_fail_jmp = (_tf_jmp == 0) ? setjmp(_tf_fail.jmp) : 0;
        if (_tf_jmp == 0 && _tf_fail_jmp == 0) {
            nova_test_encode________________0();
            printf("  PASS: encode: пустой массив\n");
        } else {
            const char* _tf_msg = _tf.fail_msg ? _tf.fail_msg : (_tf_fail.error_msg.ptr ? _tf_fail.error_msg.ptr : "assertion failed");
            printf("  FAIL: encode: пустой массив — %s\n", _tf_msg);
            _nova_tests_failed++;
        }
        nova_fail_pop();
        _nova_test_frame = NULL;
    }
    {
        NovaTestFrame _tf;
        _tf.fail_msg = NULL;
        _nova_test_frame = &_tf;
        NovaFailFrame _tf_fail;
        _tf_fail.error_msg = (nova_str){.ptr=NULL, .len=0};
        nova_fail_push(&_tf_fail);
        int _tf_jmp = setjmp(_tf.jmp);
        int _tf_fail_jmp = (_tf_jmp == 0) ? setjmp(_tf_fail.jmp) : 0;
        if (_tf_jmp == 0 && _tf_fail_jmp == 0) {
            nova_test_encode__lowercase______________1();
            printf("  PASS: encode: lowercase по умолчанию\n");
        } else {
            const char* _tf_msg = _tf.fail_msg ? _tf.fail_msg : (_tf_fail.error_msg.ptr ? _tf_fail.error_msg.ptr : "assertion failed");
            printf("  FAIL: encode: lowercase по умолчанию — %s\n", _tf_msg);
            _nova_tests_failed++;
        }
        nova_fail_pop();
        _nova_test_frame = NULL;
    }
    {
        NovaTestFrame _tf;
        _tf.fail_msg = NULL;
        _nova_test_frame = &_tf;
        NovaFailFrame _tf_fail;
        _tf_fail.error_msg = (nova_str){.ptr=NULL, .len=0};
        nova_fail_push(&_tf_fail);
        int _tf_jmp = setjmp(_tf.jmp);
        int _tf_fail_jmp = (_tf_jmp == 0) ? setjmp(_tf_fail.jmp) : 0;
        if (_tf_jmp == 0 && _tf_fail_jmp == 0) {
            nova_test_encode_upper__uppercase_2();
            printf("  PASS: encode_upper: uppercase\n");
        } else {
            const char* _tf_msg = _tf.fail_msg ? _tf.fail_msg : (_tf_fail.error_msg.ptr ? _tf_fail.error_msg.ptr : "assertion failed");
            printf("  FAIL: encode_upper: uppercase — %s\n", _tf_msg);
            _nova_tests_failed++;
        }
        nova_fail_pop();
        _nova_test_frame = NULL;
    }
    {
        NovaTestFrame _tf;
        _tf.fail_msg = NULL;
        _nova_test_frame = &_tf;
        NovaFailFrame _tf_fail;
        _tf_fail.error_msg = (nova_str){.ptr=NULL, .len=0};
        nova_fail_push(&_tf_fail);
        int _tf_jmp = setjmp(_tf.jmp);
        int _tf_fail_jmp = (_tf_jmp == 0) ? setjmp(_tf_fail.jmp) : 0;
        if (_tf_jmp == 0 && _tf_fail_jmp == 0) {
            nova_test_encode__leading_zeros_____________3();
            printf("  PASS: encode: leading zeros сохраняются\n");
        } else {
            const char* _tf_msg = _tf.fail_msg ? _tf.fail_msg : (_tf_fail.error_msg.ptr ? _tf_fail.error_msg.ptr : "assertion failed");
            printf("  FAIL: encode: leading zeros сохраняются — %s\n", _tf_msg);
            _nova_tests_failed++;
        }
        nova_fail_pop();
        _nova_test_frame = NULL;
    }
    {
        NovaTestFrame _tf;
        _tf.fail_msg = NULL;
        _nova_test_frame = &_tf;
        NovaFailFrame _tf_fail;
        _tf_fail.error_msg = (nova_str){.ptr=NULL, .len=0};
        nova_fail_push(&_tf_fail);
        int _tf_jmp = setjmp(_tf.jmp);
        int _tf_fail_jmp = (_tf_jmp == 0) ? setjmp(_tf_fail.jmp) : 0;
        if (_tf_jmp == 0 && _tf_fail_jmp == 0) {
            nova_test_decode__round_trip_4();
            printf("  PASS: decode: round-trip\n");
        } else {
            const char* _tf_msg = _tf.fail_msg ? _tf.fail_msg : (_tf_fail.error_msg.ptr ? _tf_fail.error_msg.ptr : "assertion failed");
            printf("  FAIL: decode: round-trip — %s\n", _tf_msg);
            _nova_tests_failed++;
        }
        nova_fail_pop();
        _nova_test_frame = NULL;
    }
    {
        NovaTestFrame _tf;
        _tf.fail_msg = NULL;
        _nova_test_frame = &_tf;
        NovaFailFrame _tf_fail;
        _tf_fail.error_msg = (nova_str){.ptr=NULL, .len=0};
        nova_fail_push(&_tf_fail);
        int _tf_jmp = setjmp(_tf.jmp);
        int _tf_fail_jmp = (_tf_jmp == 0) ? setjmp(_tf_fail.jmp) : 0;
        if (_tf_jmp == 0 && _tf_fail_jmp == 0) {
            nova_test_decode__case_insensitive_5();
            printf("  PASS: decode: case-insensitive\n");
        } else {
            const char* _tf_msg = _tf.fail_msg ? _tf.fail_msg : (_tf_fail.error_msg.ptr ? _tf_fail.error_msg.ptr : "assertion failed");
            printf("  FAIL: decode: case-insensitive — %s\n", _tf_msg);
            _nova_tests_failed++;
        }
        nova_fail_pop();
        _nova_test_frame = NULL;
    }
    {
        NovaTestFrame _tf;
        _tf.fail_msg = NULL;
        _nova_test_frame = &_tf;
        NovaFailFrame _tf_fail;
        _tf_fail.error_msg = (nova_str){.ptr=NULL, .len=0};
        nova_fail_push(&_tf_fail);
        int _tf_jmp = setjmp(_tf.jmp);
        int _tf_fail_jmp = (_tf_jmp == 0) ? setjmp(_tf_fail.jmp) : 0;
        if (_tf_jmp == 0 && _tf_fail_jmp == 0) {
            nova_test_decode__________________________6();
            printf("  PASS: decode: ошибка — нечётная длина\n");
        } else {
            const char* _tf_msg = _tf.fail_msg ? _tf.fail_msg : (_tf_fail.error_msg.ptr ? _tf_fail.error_msg.ptr : "assertion failed");
            printf("  FAIL: decode: ошибка — нечётная длина — %s\n", _tf_msg);
            _nova_tests_failed++;
        }
        nova_fail_pop();
        _nova_test_frame = NULL;
    }
    {
        NovaTestFrame _tf;
        _tf.fail_msg = NULL;
        _nova_test_frame = &_tf;
        NovaFailFrame _tf_fail;
        _tf_fail.error_msg = (nova_str){.ptr=NULL, .len=0};
        nova_fail_push(&_tf_fail);
        int _tf_jmp = setjmp(_tf.jmp);
        int _tf_fail_jmp = (_tf_jmp == 0) ? setjmp(_tf_fail.jmp) : 0;
        if (_tf_jmp == 0 && _tf_fail_jmp == 0) {
            nova_test_decode_____________________________7();
            printf("  PASS: decode: ошибка — невалидный символ\n");
        } else {
            const char* _tf_msg = _tf.fail_msg ? _tf.fail_msg : (_tf_fail.error_msg.ptr ? _tf_fail.error_msg.ptr : "assertion failed");
            printf("  FAIL: decode: ошибка — невалидный символ — %s\n", _tf_msg);
            _nova_tests_failed++;
        }
        nova_fail_pop();
        _nova_test_frame = NULL;
    }
    printf("%d/%d passed\n", _nova_tests_total - _nova_tests_failed, _nova_tests_total);
    if (_nova_tests_failed > 0) { exit(1); }
    return NOVA_UNIT;
}

int main(void) {
    nova_gc_init();
    nova_register_effect_storage((void**)&_nova_handler_Fail);
    nova_register_effect_storage((void**)&_nova_handler_Time);
    nova_fn_main_impl();
    nova_gc_shutdown();
    return 0;
}
