/* nova-effect-count: 6 */
/* Generated by nova-codegen. Do not edit. */
#include "nova_rt/nova_rt.h"

/* Plan 148 Ф.4: legacy all-int tuple typedefs (erased-generic fallback, on-demand). */
#ifndef NOVA_TUPLE_TYPEDEF__NovaTuple2
#define NOVA_TUPLE_TYPEDEF__NovaTuple2
typedef struct { nova_int f0; nova_int f1; } _NovaTuple2;
#endif

/* Plan 36: forward decls для user types — нужны для NovaOpt_<T> */
typedef struct Nova_ScopeOutcome Nova_ScopeOutcome;
typedef struct Nova_ReadBufferError Nova_ReadBufferError;
typedef int64_t Nova_RuntimeNoneError;
typedef struct Nova_MultiError Nova_MultiError;
typedef struct Nova_TimeoutError Nova_TimeoutError;
typedef struct Nova_MultiErrorTruncated Nova_MultiErrorTruncated;
typedef int64_t Nova_CharFromError;
typedef int64_t Nova_TryFromCharError;
typedef int64_t Nova_RangeError;
typedef struct NovaValue_CharsIter NovaValue_CharsIter;
typedef struct NovaValue_CharIndicesIter NovaValue_CharIndicesIter;
typedef int64_t Nova_RawMem;
typedef struct Nova_Vec Nova_Vec;
typedef struct NovaValue_VecIter NovaValue_VecIter;
typedef struct NovaValue_Range NovaValue_Range;
typedef struct NovaValue_RangeIter NovaValue_RangeIter;
typedef struct NovaValue_StepRangeIter NovaValue_StepRangeIter;
typedef struct NovaValue_ReverseRangeIter NovaValue_ReverseRangeIter;
typedef struct NovaValue_Utf8Error NovaValue_Utf8Error;
typedef struct Nova_InvalidCodepoint Nova_InvalidCodepoint;
typedef struct Nova_ParseIntError Nova_ParseIntError;
typedef struct Nova_ParseFloatError Nova_ParseFloatError;
typedef struct Nova_ParseBoolError Nova_ParseBoolError;
typedef struct Nova_ParseCharError Nova_ParseCharError;
typedef struct Nova_Slot Nova_Slot;
typedef struct Nova_HashMap Nova_HashMap;
typedef struct Nova_HashMapIter Nova_HashMapIter;
typedef struct Nova_KeysIter Nova_KeysIter;
typedef struct Nova_ValuesIter Nova_ValuesIter;
typedef struct Nova_Set Nova_Set;
typedef struct NovaValue_MapIter NovaValue_MapIter;
typedef struct NovaValue_FilterIter NovaValue_FilterIter;
typedef struct NovaValue_FilterMapIter NovaValue_FilterMapIter;
typedef struct NovaValue_TakeIter NovaValue_TakeIter;
typedef struct NovaValue_SkipIter NovaValue_SkipIter;
typedef struct NovaValue_EnumerateIter NovaValue_EnumerateIter;
typedef struct NovaValue_StepByIter NovaValue_StepByIter;
typedef struct NovaValue_SplitIter NovaValue_SplitIter;
typedef struct NovaValue_RSplitIter NovaValue_RSplitIter;
typedef struct Nova_Align Nova_Align;
typedef struct Nova_FloatKind Nova_FloatKind;
typedef struct Nova_Sign Nova_Sign;
typedef struct Nova_FmtKind Nova_FmtKind;
typedef struct NovaValue_FmtSpec NovaValue_FmtSpec;
typedef struct Nova_StringBuilder Nova_StringBuilder;
typedef struct Nova_WriteBuffer Nova_WriteBuffer;
typedef struct Nova_ReadBuffer Nova_ReadBuffer;
typedef struct Nova_FmtCtx Nova_FmtCtx;
typedef int64_t Nova_Mem;
typedef struct Nova_Decision Nova_Decision;
typedef struct Nova_Outcome Nova_Outcome;
typedef struct Nova_EmbeddedEntry Nova_EmbeddedEntry;
typedef struct Nova_EmbeddedDir Nova_EmbeddedDir;
typedef struct Nova_Acc Nova_Acc;
typedef struct Nova_E Nova_E;
typedef struct Nova_F Nova_F;
typedef struct Nova_I Nova_I;
typedef struct Nova_K Nova_K;
typedef struct Nova_S Nova_S;
typedef struct Nova_T Nova_T;
typedef struct Nova_U Nova_U;
typedef struct Nova_V Nova_V;
typedef struct { void* data; const NovaVtable_Hash* vtable; } NovaBox_Hash;
/* Plan 72 P3-B / Plan 97.1: vtable for Equal instantiated with (non-generic) */
typedef struct NovaVtable_Equal {
    nova_bool (*equal)(void*, void*); 
} NovaVtable_Equal;
typedef struct { void* data; const NovaVtable_Equal* vtable; } NovaBox_Equal;
typedef struct { void* data; const NovaVtable_Compare* vtable; } NovaBox_Compare;
/* Plan 72 P3-B / Plan 97.1: vtable for Clone instantiated with (non-generic) */
typedef struct NovaVtable_Clone {
    nova_unit (*clone)(void*); 
} NovaVtable_Clone;
typedef struct { void* data; const NovaVtable_Clone* vtable; } NovaBox_Clone;
typedef struct Nova_Vec____nova_byte Nova_Vec____nova_byte;
/* Plan 72 P3-B / Plan 97.1: vtable for Write instantiated with (non-generic) */
typedef struct NovaVtable_Write {
    nova_unit (*write)(void*, Nova_Vec____nova_byte*); 
} NovaVtable_Write;
typedef struct { void* data; const NovaVtable_Write* vtable; } NovaBox_Write;
/* Plan 72 P3-B / Plan 97.1: vtable for Fmt instantiated with (non-generic) */
typedef struct NovaVtable_Fmt {
    NovaOpt_nova_int (*width)(void*); 
    NovaOpt_nova_int (*precision)(void*); 
    NovaOpt_nova_int (*align)(void*); 
    nova_char (*fill)(void*); 
    Nova_Sign* (*sign)(void*); 
    nova_bool (*alternate)(void*); 
    Nova_FmtKind* (*kind)(void*); 
    nova_unit (*pad)(void*, Nova_Vec____nova_byte*); 
    nova_unit (*write)(void*, Nova_Vec____nova_byte*); 
} NovaVtable_Fmt;
typedef struct { void* data; const NovaVtable_Fmt* vtable; } NovaBox_Fmt;
typedef struct { void* data; const NovaVtable_Display* vtable; } NovaBox_Display;
/* Plan 72 P3-B / Plan 97.1: vtable for Debug instantiated with (non-generic) */
typedef struct NovaVtable_Debug {
    nova_unit (*debug)(void*, Nova_FmtCtx*); 
} NovaVtable_Debug;
typedef struct { void* data; const NovaVtable_Debug* vtable; } NovaBox_Debug;
/* Plan 72 P3-B / Plan 97.1: vtable for WithExitTimeout instantiated with (non-generic) */
typedef struct NovaVtable_WithExitTimeout {
    nova_int (*exit_timeout_ms)(void*); 
} NovaVtable_WithExitTimeout;
typedef struct { void* data; const NovaVtable_WithExitTimeout* vtable; } NovaBox_WithExitTimeout;
typedef struct Nova_Vec____NovaRes_nova_int_nova_str_p Nova_Vec____NovaRes_nova_int_nova_str_p;
typedef struct Nova_Vec____void_p Nova_Vec____void_p;
typedef struct Nova_Vec____nova_str Nova_Vec____nova_str;
typedef struct Nova_Vec____nova_byte Nova_Vec____nova_byte;
typedef struct Nova_Vec____nova_int Nova_Vec____nova_int;
typedef struct Nova_Vec____Nova_Slot____Nova_K_p__Nova_V_p_p Nova_Vec____Nova_Slot____Nova_K_p__Nova_V_p_p;
typedef struct Nova_Vec_____NovaTuple2 Nova_Vec_____NovaTuple2;
typedef void* Nova_CancelToken;
typedef struct Nova_Vec____Nova_EmbeddedEntry_p Nova_Vec____Nova_EmbeddedEntry_p;
typedef struct Nova_Vec____Nova_Slot____nova_int__nova_unit_p Nova_Vec____Nova_Slot____nova_int__nova_unit_p;

/* Plan 61 Ф.1: per-type NovaTypeId constants. */
#define NOVA_TID_USER_TimeoutError ((NovaTypeId)17)

/* Diagnostic helper для user-types (called from Plan 61
 * unhandled-fail path; static, не overrides typeid.c weak). */
static inline const char* nova_typeid_user_name(NovaTypeId tid) {
    switch (tid) {
        case NOVA_TID_USER_TimeoutError: return "TimeoutError";
        default: return nova_typeid_to_name(tid);
    }
}

/* Plan 174.3: per-type NovaTypeInfo statics (any-boxing). */
static const NovaTypeInfo NOVA_TYPEINFO_nova_str = { NOVA_TID_nova_str, "nova_str" };


/* Value-record / generic-instance / tuple / fixed-array struct definitions (complete, topologically sorted — реестр 221.1 №139 Round 3): */
typedef struct NovaValue_CharsIter NovaValue_CharsIter;
struct NovaValue_CharsIter {
    nova_str buf;
    nova_int pos;
};

typedef struct NovaValue_CharIndicesIter NovaValue_CharIndicesIter;
struct NovaValue_CharIndicesIter {
    nova_str buf;
    nova_int pos;
};

typedef struct NovaValue_Range NovaValue_Range;
struct NovaValue_Range {
    nova_int start;
    nova_int end;
};

typedef struct NovaValue_RangeIter NovaValue_RangeIter;
struct NovaValue_RangeIter {
    nova_int end;
    nova_int cur;
};

typedef struct NovaValue_StepRangeIter NovaValue_StepRangeIter;
struct NovaValue_StepRangeIter {
    nova_int end;
    nova_int step;
    nova_int cur;
};

typedef struct NovaValue_ReverseRangeIter NovaValue_ReverseRangeIter;
struct NovaValue_ReverseRangeIter {
    nova_int start;
    nova_int cur;
    nova_bool done;
};

typedef struct NovaValue_Utf8Error NovaValue_Utf8Error;
struct NovaValue_Utf8Error {
    nova_int byte_offset;
};

typedef struct NovaValue_SplitIter NovaValue_SplitIter;
struct NovaValue_SplitIter {
    nova_str src;
    nova_str sep;
    nova_int start;
    nova_bool done;
    nova_int limit;
    nova_int splits;
    nova_bool terminator;
};

typedef struct NovaValue_RSplitIter NovaValue_RSplitIter;
struct NovaValue_RSplitIter {
    nova_str src;
    nova_str sep;
    nova_int end;
    nova_bool done;
    nova_int limit;
    nova_int splits;
};

typedef struct NovaValue_FmtSpec NovaValue_FmtSpec;
struct NovaValue_FmtSpec {
    nova_int width;
    nova_int radix;
    nova_bool upper;
    nova_bool zero_pad;
    nova_bool sign_plus;
    nova_bool alt;
};

typedef struct Nova_Vec____NovaRes_nova_int_nova_str_p Nova_Vec____NovaRes_nova_int_nova_str_p;
struct Nova_Vec____NovaRes_nova_int_nova_str_p {
    NovaRes_nova_int_nova_str** data;
    nova_int len;
    nova_int cap;
};

typedef struct Nova_Vec____nova_byte Nova_Vec____nova_byte;
struct Nova_Vec____nova_byte {
    nova_byte* data;
    nova_int len;
    nova_int cap;
};

typedef struct Nova_Vec____void_p Nova_Vec____void_p;
struct Nova_Vec____void_p {
    void** data;
    nova_int len;
    nova_int cap;
};

typedef struct Nova_Vec____nova_str Nova_Vec____nova_str;
struct Nova_Vec____nova_str {
    nova_str* data;
    nova_int len;
    nova_int cap;
};

typedef struct Nova_Vec____nova_int Nova_Vec____nova_int;
struct Nova_Vec____nova_int {
    nova_int* data;
    nova_int len;
    nova_int cap;
};

typedef struct Nova_Slot____Nova_K_p__Nova_V_p Nova_Slot____Nova_K_p__Nova_V_p;
typedef struct Nova_Vec____Nova_Slot____Nova_K_p__Nova_V_p_p Nova_Vec____Nova_Slot____Nova_K_p__Nova_V_p_p;
struct Nova_Vec____Nova_Slot____Nova_K_p__Nova_V_p_p {
    Nova_Slot____Nova_K_p__Nova_V_p** data;
    nova_int len;
    nova_int cap;
};

typedef struct Nova_Vec_____NovaTuple2 Nova_Vec_____NovaTuple2;
struct Nova_Vec_____NovaTuple2 {
    _NovaTuple2* data;
    nova_int len;
    nova_int cap;
};

typedef struct Nova_EmbeddedEntry Nova_EmbeddedEntry;
typedef struct Nova_Vec____Nova_EmbeddedEntry_p Nova_Vec____Nova_EmbeddedEntry_p;
struct Nova_Vec____Nova_EmbeddedEntry_p {
    Nova_EmbeddedEntry** data;
    nova_int len;
    nova_int cap;
};

typedef struct Nova_HashMapIter____nova_int__nova_unit Nova_HashMapIter____nova_int__nova_unit;
typedef struct Nova_KeysIter____nova_int__nova_unit Nova_KeysIter____nova_int__nova_unit;
struct Nova_KeysIter____nova_int__nova_unit {
    Nova_HashMapIter____nova_int__nova_unit* inner;
};

typedef struct NovaValue_FilterIter____NovaValue_SplitIter__nova_str NovaValue_FilterIter____NovaValue_SplitIter__nova_str;
struct NovaValue_FilterIter____NovaValue_SplitIter__nova_str {
    NovaValue_SplitIter src;
    void* pred;
};

typedef struct NovaValue_TakeIter____NovaValue_SplitIter__nova_str NovaValue_TakeIter____NovaValue_SplitIter__nova_str;
struct NovaValue_TakeIter____NovaValue_SplitIter__nova_str {
    NovaValue_SplitIter src;
    nova_int left;
};

typedef struct NovaValue_SkipIter____NovaValue_SplitIter__nova_str NovaValue_SkipIter____NovaValue_SplitIter__nova_str;
struct NovaValue_SkipIter____NovaValue_SplitIter__nova_str {
    NovaValue_SplitIter src;
    nova_int to_skip;
};

typedef struct NovaValue_EnumerateIter____NovaValue_SplitIter__nova_str NovaValue_EnumerateIter____NovaValue_SplitIter__nova_str;
struct NovaValue_EnumerateIter____NovaValue_SplitIter__nova_str {
    NovaValue_SplitIter src;
    nova_int i;
};

typedef struct NovaValue_StepByIter____NovaValue_SplitIter__nova_str NovaValue_StepByIter____NovaValue_SplitIter__nova_str;
struct NovaValue_StepByIter____NovaValue_SplitIter__nova_str {
    NovaValue_SplitIter src;
    nova_int step;
    nova_bool first;
    nova_int rem;
};

typedef struct NovaValue_FilterIter____NovaValue_RSplitIter__nova_str NovaValue_FilterIter____NovaValue_RSplitIter__nova_str;
struct NovaValue_FilterIter____NovaValue_RSplitIter__nova_str {
    NovaValue_RSplitIter src;
    void* pred;
};

typedef struct NovaValue_TakeIter____NovaValue_RSplitIter__nova_str NovaValue_TakeIter____NovaValue_RSplitIter__nova_str;
struct NovaValue_TakeIter____NovaValue_RSplitIter__nova_str {
    NovaValue_RSplitIter src;
    nova_int left;
};

typedef struct NovaValue_SkipIter____NovaValue_RSplitIter__nova_str NovaValue_SkipIter____NovaValue_RSplitIter__nova_str;
struct NovaValue_SkipIter____NovaValue_RSplitIter__nova_str {
    NovaValue_RSplitIter src;
    nova_int to_skip;
};

typedef struct NovaValue_EnumerateIter____NovaValue_RSplitIter__nova_str NovaValue_EnumerateIter____NovaValue_RSplitIter__nova_str;
struct NovaValue_EnumerateIter____NovaValue_RSplitIter__nova_str {
    NovaValue_RSplitIter src;
    nova_int i;
};

typedef struct NovaValue_StepByIter____NovaValue_RSplitIter__nova_str NovaValue_StepByIter____NovaValue_RSplitIter__nova_str;
struct NovaValue_StepByIter____NovaValue_RSplitIter__nova_str {
    NovaValue_RSplitIter src;
    nova_int step;
    nova_bool first;
    nova_int rem;
};

typedef struct Nova_HashMap____nova_int__nova_unit Nova_HashMap____nova_int__nova_unit;
typedef struct Nova_HashMapIter____nova_int__nova_unit Nova_HashMapIter____nova_int__nova_unit;
struct Nova_HashMapIter____nova_int__nova_unit {
    Nova_HashMap____nova_int__nova_unit* map;
    nova_int pos;
};

typedef struct Nova_Vec____Nova_Slot____nova_int__nova_unit_p Nova_Vec____Nova_Slot____nova_int__nova_unit_p;
typedef struct Nova_HashMap____nova_int__nova_unit Nova_HashMap____nova_int__nova_unit;
struct Nova_HashMap____nova_int__nova_unit {
    Nova_Vec____Nova_Slot____nova_int__nova_unit_p* buckets;
    nova_int count;
    nova_int tombstones;
};

typedef struct Nova_Slot____nova_int__nova_unit Nova_Slot____nova_int__nova_unit;
typedef struct Nova_Vec____Nova_Slot____nova_int__nova_unit_p Nova_Vec____Nova_Slot____nova_int__nova_unit_p;
struct Nova_Vec____Nova_Slot____nova_int__nova_unit_p {
    Nova_Slot____nova_int__nova_unit** data;
    nova_int len;
    nova_int cap;
};

#ifndef NOVA_TUPLE_TYPEDEF__NovaTuple_2_22_Nova_Vec____nova_int_p_22_Nova_Vec____nova_int_p
#define NOVA_TUPLE_TYPEDEF__NovaTuple_2_22_Nova_Vec____nova_int_p_22_Nova_Vec____nova_int_p
typedef struct _NovaTuple_2_22_Nova_Vec____nova_int_p_22_Nova_Vec____nova_int_p { Nova_Vec____nova_int* f0; Nova_Vec____nova_int* f1; } _NovaTuple_2_22_Nova_Vec____nova_int_p_22_Nova_Vec____nova_int_p;
#endif
#ifndef NOVA_TUPLE_TYPEDEF__NovaTuple_2_8_nova_int_9_nova_char
#define NOVA_TUPLE_TYPEDEF__NovaTuple_2_8_nova_int_9_nova_char
typedef struct _NovaTuple_2_8_nova_int_9_nova_char { nova_int f0; nova_char f1; } _NovaTuple_2_8_nova_int_9_nova_char;
#endif
#ifndef NOVA_TUPLE_TYPEDEF__NovaTuple_2_8_nova_int_8_nova_int
#define NOVA_TUPLE_TYPEDEF__NovaTuple_2_8_nova_int_8_nova_int
typedef struct _NovaTuple_2_8_nova_int_8_nova_int { nova_int f0; nova_int f1; } _NovaTuple_2_8_nova_int_8_nova_int;
#endif
#ifndef NOVA_TUPLE_TYPEDEF__NovaTuple_2_8_nova_str_8_nova_str
#define NOVA_TUPLE_TYPEDEF__NovaTuple_2_8_nova_str_8_nova_str
typedef struct _NovaTuple_2_8_nova_str_8_nova_str { nova_str f0; nova_str f1; } _NovaTuple_2_8_nova_str_8_nova_str;
#endif
#ifndef NOVA_FIXARR_TYPEDEF__NovaFixArr_4_9_nova_byte
#define NOVA_FIXARR_TYPEDEF__NovaFixArr_4_9_nova_byte
typedef struct _NovaFixArr_4_9_nova_byte { nova_byte data[4]; } _NovaFixArr_4_9_nova_byte;
#endif
#ifndef NOVA_TUPLE_TYPEDEF__NovaTuple_2_25__NovaFixArr_4_9_nova_byte_8_nova_int
#define NOVA_TUPLE_TYPEDEF__NovaTuple_2_25__NovaFixArr_4_9_nova_byte_8_nova_int
typedef struct _NovaTuple_2_25__NovaFixArr_4_9_nova_byte_8_nova_int { _NovaFixArr_4_9_nova_byte f0; nova_int f1; } _NovaTuple_2_25__NovaFixArr_4_9_nova_byte_8_nova_int;
#endif

/* Plan 14 Ф.1: lazy NovaOpt_<T> typedef'ы — для T без NOVA_ARRAY_DECL в runtime. Order: registration */
typedef struct NovaOpt_Nova_Align_p { Nova_Align* value; } NovaOpt_Nova_Align_p;
static inline nova_bool nova_opt_eq_Nova_Align_p(NovaOpt_Nova_Align_p a, NovaOpt_Nova_Align_p b);
typedef struct NovaOpt_Nova_CharFromError_p { Nova_CharFromError* value; } NovaOpt_Nova_CharFromError_p;
static inline nova_bool nova_opt_eq_Nova_CharFromError_p(NovaOpt_Nova_CharFromError_p a, NovaOpt_Nova_CharFromError_p b);
typedef struct NovaOpt_Nova_TryFromCharError_p { Nova_TryFromCharError* value; } NovaOpt_Nova_TryFromCharError_p;
static inline nova_bool nova_opt_eq_Nova_TryFromCharError_p(NovaOpt_Nova_TryFromCharError_p a, NovaOpt_Nova_TryFromCharError_p b);
typedef struct NovaOpt__NovaTuple_2_8_nova_int_9_nova_char { int tag; _NovaTuple_2_8_nova_int_9_nova_char value; } NovaOpt__NovaTuple_2_8_nova_int_9_nova_char;
static inline nova_bool nova_opt_eq__NovaTuple_2_8_nova_int_9_nova_char(NovaOpt__NovaTuple_2_8_nova_int_9_nova_char a, NovaOpt__NovaTuple_2_8_nova_int_9_nova_char b) {
    if (a.tag != b.tag) return 0;
    if (a.tag == NOVA_TAG_Option_None) return 1;
    return ((((a.value).f0) == ((b.value).f0)) && (((a.value).f1) == ((b.value).f1)));
}
typedef struct NovaOpt_NovaValue_Utf8Error { int tag; NovaValue_Utf8Error value; } NovaOpt_NovaValue_Utf8Error;
static inline nova_bool nova_opt_eq_NovaValue_Utf8Error(NovaOpt_NovaValue_Utf8Error a, NovaOpt_NovaValue_Utf8Error b) {
    if (a.tag != b.tag) return 0;
    if (a.tag == NOVA_TAG_Option_None) return 1;
    return ((((a.value).byte_offset) == ((b.value).byte_offset)));
}
typedef struct NovaOpt_Nova_InvalidCodepoint_p { Nova_InvalidCodepoint* value; } NovaOpt_Nova_InvalidCodepoint_p;
static inline nova_bool nova_opt_eq_Nova_InvalidCodepoint_p(NovaOpt_Nova_InvalidCodepoint_p a, NovaOpt_Nova_InvalidCodepoint_p b);
typedef struct NovaOpt_Nova_ParseIntError_p { Nova_ParseIntError* value; } NovaOpt_Nova_ParseIntError_p;
static inline nova_bool nova_opt_eq_Nova_ParseIntError_p(NovaOpt_Nova_ParseIntError_p a, NovaOpt_Nova_ParseIntError_p b);
typedef struct NovaOpt_nova_uint { int tag; nova_uint value; } NovaOpt_nova_uint;
static inline nova_bool nova_opt_eq_nova_uint(NovaOpt_nova_uint a, NovaOpt_nova_uint b) {
    if (a.tag != b.tag) return 0;
    if (a.tag == NOVA_TAG_Option_None) return 1;
    return (memcmp(&a.value, &b.value, sizeof(nova_uint)) == 0);
}
typedef struct NovaOpt_Nova_ParseFloatError_p { Nova_ParseFloatError* value; } NovaOpt_Nova_ParseFloatError_p;
static inline nova_bool nova_opt_eq_Nova_ParseFloatError_p(NovaOpt_Nova_ParseFloatError_p a, NovaOpt_Nova_ParseFloatError_p b);
typedef struct NovaOpt_Nova_ParseBoolError_p { Nova_ParseBoolError* value; } NovaOpt_Nova_ParseBoolError_p;
static inline nova_bool nova_opt_eq_Nova_ParseBoolError_p(NovaOpt_Nova_ParseBoolError_p a, NovaOpt_Nova_ParseBoolError_p b);
typedef struct NovaOpt_Nova_ParseCharError_p { Nova_ParseCharError* value; } NovaOpt_Nova_ParseCharError_p;
static inline nova_bool nova_opt_eq_Nova_ParseCharError_p(NovaOpt_Nova_ParseCharError_p a, NovaOpt_Nova_ParseCharError_p b);
typedef struct NovaOpt_int64_t { int tag; int64_t value; } NovaOpt_int64_t;
static inline nova_bool nova_opt_eq_int64_t(NovaOpt_int64_t a, NovaOpt_int64_t b) {
    if (a.tag != b.tag) return 0;
    if (a.tag == NOVA_TAG_Option_None) return 1;
    return ((a.value) == (b.value));
}
typedef struct NovaOpt__NovaTuple_2_8_nova_str_8_nova_str { int tag; _NovaTuple_2_8_nova_str_8_nova_str value; } NovaOpt__NovaTuple_2_8_nova_str_8_nova_str;
static inline nova_bool nova_opt_eq__NovaTuple_2_8_nova_str_8_nova_str(NovaOpt__NovaTuple_2_8_nova_str_8_nova_str a, NovaOpt__NovaTuple_2_8_nova_str_8_nova_str b) {
    if (a.tag != b.tag) return 0;
    if (a.tag == NOVA_TAG_Option_None) return 1;
    return (nova_str_eq((a.value).f0, (b.value).f0) && nova_str_eq((a.value).f1, (b.value).f1));
}
typedef struct NovaOpt_Nova_ReadBufferError_p { Nova_ReadBufferError* value; } NovaOpt_Nova_ReadBufferError_p;
static inline nova_bool nova_opt_eq_Nova_ReadBufferError_p(NovaOpt_Nova_ReadBufferError_p a, NovaOpt_Nova_ReadBufferError_p b);
typedef struct Nova_Vec____nova_byte Nova_Vec____nova_byte;
typedef struct NovaOpt_Nova_Vec____nova_byte_p { Nova_Vec____nova_byte* value; } NovaOpt_Nova_Vec____nova_byte_p;
static inline nova_bool nova_opt_eq_Nova_Vec____nova_byte_p(NovaOpt_Nova_Vec____nova_byte_p a, NovaOpt_Nova_Vec____nova_byte_p b);
typedef struct NovaOpt__NovaTuple_2_8_nova_int_8_nova_int { int tag; _NovaTuple_2_8_nova_int_8_nova_int value; } NovaOpt__NovaTuple_2_8_nova_int_8_nova_int;
static inline nova_bool nova_opt_eq__NovaTuple_2_8_nova_int_8_nova_int(NovaOpt__NovaTuple_2_8_nova_int_8_nova_int a, NovaOpt__NovaTuple_2_8_nova_int_8_nova_int b) {
    if (a.tag != b.tag) return 0;
    if (a.tag == NOVA_TAG_Option_None) return 1;
    return ((((a.value).f0) == ((b.value).f0)) && (((a.value).f1) == ((b.value).f1)));
}
typedef struct NovaOpt_Nova_RangeError_p { Nova_RangeError* value; } NovaOpt_Nova_RangeError_p;
static inline nova_bool nova_opt_eq_Nova_RangeError_p(NovaOpt_Nova_RangeError_p a, NovaOpt_Nova_RangeError_p b);
typedef struct NovaOpt_Nova_Vec_p { Nova_Vec* value; } NovaOpt_Nova_Vec_p;
static inline nova_bool nova_opt_eq_Nova_Vec_p(NovaOpt_Nova_Vec_p a, NovaOpt_Nova_Vec_p b) {
    return a.value == b.value;
}

/* Plan 59 Ф.7.5: mono'd NovaRes_<ok>_<err> Result typedef'ы. Order: registration */
typedef struct NovaRes_nova_char_Nova_CharFromError_p { int tag; union { struct { nova_char _0; } Ok; struct { Nova_CharFromError* _0; } Err; } payload; void* err_typed_payload; NovaTypeId err_typed_type_id; } NovaRes_nova_char_Nova_CharFromError_p;
static inline NovaRes_nova_char_Nova_CharFromError_p* nova_make_NovaRes_nova_char_Nova_CharFromError_p_Ok(nova_char v) { NovaRes_nova_char_Nova_CharFromError_p* r = (NovaRes_nova_char_Nova_CharFromError_p*)nova_alloc(sizeof(NovaRes_nova_char_Nova_CharFromError_p)); r->tag = NOVA_TAG_Result_Ok; r->payload.Ok._0 = v; r->err_typed_payload = NULL; r->err_typed_type_id = NOVA_TID_NONE; return r; }
static inline NovaRes_nova_char_Nova_CharFromError_p* nova_make_NovaRes_nova_char_Nova_CharFromError_p_Err(Nova_CharFromError* v) { NovaRes_nova_char_Nova_CharFromError_p* r = (NovaRes_nova_char_Nova_CharFromError_p*)nova_alloc(sizeof(NovaRes_nova_char_Nova_CharFromError_p)); r->tag = NOVA_TAG_Result_Err; r->payload.Err._0 = v; r->err_typed_payload = NULL; r->err_typed_type_id = NOVA_TID_NONE; return r; }
typedef struct NovaRes_nova_byte_Nova_TryFromCharError_p { int tag; union { struct { nova_byte _0; } Ok; struct { Nova_TryFromCharError* _0; } Err; } payload; void* err_typed_payload; NovaTypeId err_typed_type_id; } NovaRes_nova_byte_Nova_TryFromCharError_p;
static inline NovaRes_nova_byte_Nova_TryFromCharError_p* nova_make_NovaRes_nova_byte_Nova_TryFromCharError_p_Ok(nova_byte v) { NovaRes_nova_byte_Nova_TryFromCharError_p* r = (NovaRes_nova_byte_Nova_TryFromCharError_p*)nova_alloc(sizeof(NovaRes_nova_byte_Nova_TryFromCharError_p)); r->tag = NOVA_TAG_Result_Ok; r->payload.Ok._0 = v; r->err_typed_payload = NULL; r->err_typed_type_id = NOVA_TID_NONE; return r; }
static inline NovaRes_nova_byte_Nova_TryFromCharError_p* nova_make_NovaRes_nova_byte_Nova_TryFromCharError_p_Err(Nova_TryFromCharError* v) { NovaRes_nova_byte_Nova_TryFromCharError_p* r = (NovaRes_nova_byte_Nova_TryFromCharError_p*)nova_alloc(sizeof(NovaRes_nova_byte_Nova_TryFromCharError_p)); r->tag = NOVA_TAG_Result_Err; r->payload.Err._0 = v; r->err_typed_payload = NULL; r->err_typed_type_id = NOVA_TID_NONE; return r; }
typedef struct NovaRes_nova_int_nova_int { int tag; union { struct { nova_int _0; } Ok; struct { nova_int _0; } Err; } payload; void* err_typed_payload; NovaTypeId err_typed_type_id; } NovaRes_nova_int_nova_int;
static inline NovaRes_nova_int_nova_int* nova_make_NovaRes_nova_int_nova_int_Ok(nova_int v) { NovaRes_nova_int_nova_int* r = (NovaRes_nova_int_nova_int*)nova_alloc(sizeof(NovaRes_nova_int_nova_int)); r->tag = NOVA_TAG_Result_Ok; r->payload.Ok._0 = v; r->err_typed_payload = NULL; r->err_typed_type_id = NOVA_TID_NONE; return r; }
static inline NovaRes_nova_int_nova_int* nova_make_NovaRes_nova_int_nova_int_Err(nova_int v) { NovaRes_nova_int_nova_int* r = (NovaRes_nova_int_nova_int*)nova_alloc(sizeof(NovaRes_nova_int_nova_int)); r->tag = NOVA_TAG_Result_Err; r->payload.Err._0 = v; r->err_typed_payload = NULL; r->err_typed_type_id = NOVA_TID_NONE; return r; }
typedef struct NovaRes_nova_str_NovaValue_Utf8Error { int tag; union { struct { nova_str _0; } Ok; struct { NovaValue_Utf8Error _0; } Err; } payload; void* err_typed_payload; NovaTypeId err_typed_type_id; } NovaRes_nova_str_NovaValue_Utf8Error;
static inline NovaRes_nova_str_NovaValue_Utf8Error* nova_make_NovaRes_nova_str_NovaValue_Utf8Error_Ok(nova_str v) { NovaRes_nova_str_NovaValue_Utf8Error* r = (NovaRes_nova_str_NovaValue_Utf8Error*)nova_alloc(sizeof(NovaRes_nova_str_NovaValue_Utf8Error)); r->tag = NOVA_TAG_Result_Ok; r->payload.Ok._0 = v; r->err_typed_payload = NULL; r->err_typed_type_id = NOVA_TID_NONE; return r; }
static inline NovaRes_nova_str_NovaValue_Utf8Error* nova_make_NovaRes_nova_str_NovaValue_Utf8Error_Err(NovaValue_Utf8Error v) { NovaRes_nova_str_NovaValue_Utf8Error* r = (NovaRes_nova_str_NovaValue_Utf8Error*)nova_alloc(sizeof(NovaRes_nova_str_NovaValue_Utf8Error)); r->tag = NOVA_TAG_Result_Err; r->payload.Err._0 = v; r->err_typed_payload = NULL; r->err_typed_type_id = NOVA_TID_NONE; return r; }
typedef struct NovaRes_nova_str_Nova_InvalidCodepoint_p { int tag; union { struct { nova_str _0; } Ok; struct { Nova_InvalidCodepoint* _0; } Err; } payload; void* err_typed_payload; NovaTypeId err_typed_type_id; } NovaRes_nova_str_Nova_InvalidCodepoint_p;
static inline NovaRes_nova_str_Nova_InvalidCodepoint_p* nova_make_NovaRes_nova_str_Nova_InvalidCodepoint_p_Ok(nova_str v) { NovaRes_nova_str_Nova_InvalidCodepoint_p* r = (NovaRes_nova_str_Nova_InvalidCodepoint_p*)nova_alloc(sizeof(NovaRes_nova_str_Nova_InvalidCodepoint_p)); r->tag = NOVA_TAG_Result_Ok; r->payload.Ok._0 = v; r->err_typed_payload = NULL; r->err_typed_type_id = NOVA_TID_NONE; return r; }
static inline NovaRes_nova_str_Nova_InvalidCodepoint_p* nova_make_NovaRes_nova_str_Nova_InvalidCodepoint_p_Err(Nova_InvalidCodepoint* v) { NovaRes_nova_str_Nova_InvalidCodepoint_p* r = (NovaRes_nova_str_Nova_InvalidCodepoint_p*)nova_alloc(sizeof(NovaRes_nova_str_Nova_InvalidCodepoint_p)); r->tag = NOVA_TAG_Result_Err; r->payload.Err._0 = v; r->err_typed_payload = NULL; r->err_typed_type_id = NOVA_TID_NONE; return r; }
typedef struct NovaRes_nova_int_Nova_ParseIntError_p { int tag; union { struct { nova_int _0; } Ok; struct { Nova_ParseIntError* _0; } Err; } payload; void* err_typed_payload; NovaTypeId err_typed_type_id; } NovaRes_nova_int_Nova_ParseIntError_p;
static inline NovaRes_nova_int_Nova_ParseIntError_p* nova_make_NovaRes_nova_int_Nova_ParseIntError_p_Ok(nova_int v) { NovaRes_nova_int_Nova_ParseIntError_p* r = (NovaRes_nova_int_Nova_ParseIntError_p*)nova_alloc(sizeof(NovaRes_nova_int_Nova_ParseIntError_p)); r->tag = NOVA_TAG_Result_Ok; r->payload.Ok._0 = v; r->err_typed_payload = NULL; r->err_typed_type_id = NOVA_TID_NONE; return r; }
static inline NovaRes_nova_int_Nova_ParseIntError_p* nova_make_NovaRes_nova_int_Nova_ParseIntError_p_Err(Nova_ParseIntError* v) { NovaRes_nova_int_Nova_ParseIntError_p* r = (NovaRes_nova_int_Nova_ParseIntError_p*)nova_alloc(sizeof(NovaRes_nova_int_Nova_ParseIntError_p)); r->tag = NOVA_TAG_Result_Err; r->payload.Err._0 = v; r->err_typed_payload = NULL; r->err_typed_type_id = NOVA_TID_NONE; return r; }
typedef struct NovaRes_nova_uint_Nova_ParseIntError_p { int tag; union { struct { nova_uint _0; } Ok; struct { Nova_ParseIntError* _0; } Err; } payload; void* err_typed_payload; NovaTypeId err_typed_type_id; } NovaRes_nova_uint_Nova_ParseIntError_p;
static inline NovaRes_nova_uint_Nova_ParseIntError_p* nova_make_NovaRes_nova_uint_Nova_ParseIntError_p_Ok(nova_uint v) { NovaRes_nova_uint_Nova_ParseIntError_p* r = (NovaRes_nova_uint_Nova_ParseIntError_p*)nova_alloc(sizeof(NovaRes_nova_uint_Nova_ParseIntError_p)); r->tag = NOVA_TAG_Result_Ok; r->payload.Ok._0 = v; r->err_typed_payload = NULL; r->err_typed_type_id = NOVA_TID_NONE; return r; }
static inline NovaRes_nova_uint_Nova_ParseIntError_p* nova_make_NovaRes_nova_uint_Nova_ParseIntError_p_Err(Nova_ParseIntError* v) { NovaRes_nova_uint_Nova_ParseIntError_p* r = (NovaRes_nova_uint_Nova_ParseIntError_p*)nova_alloc(sizeof(NovaRes_nova_uint_Nova_ParseIntError_p)); r->tag = NOVA_TAG_Result_Err; r->payload.Err._0 = v; r->err_typed_payload = NULL; r->err_typed_type_id = NOVA_TID_NONE; return r; }
typedef struct NovaRes_nova_f64_Nova_ParseFloatError_p { int tag; union { struct { nova_f64 _0; } Ok; struct { Nova_ParseFloatError* _0; } Err; } payload; void* err_typed_payload; NovaTypeId err_typed_type_id; } NovaRes_nova_f64_Nova_ParseFloatError_p;
static inline NovaRes_nova_f64_Nova_ParseFloatError_p* nova_make_NovaRes_nova_f64_Nova_ParseFloatError_p_Ok(nova_f64 v) { NovaRes_nova_f64_Nova_ParseFloatError_p* r = (NovaRes_nova_f64_Nova_ParseFloatError_p*)nova_alloc(sizeof(NovaRes_nova_f64_Nova_ParseFloatError_p)); r->tag = NOVA_TAG_Result_Ok; r->payload.Ok._0 = v; r->err_typed_payload = NULL; r->err_typed_type_id = NOVA_TID_NONE; return r; }
static inline NovaRes_nova_f64_Nova_ParseFloatError_p* nova_make_NovaRes_nova_f64_Nova_ParseFloatError_p_Err(Nova_ParseFloatError* v) { NovaRes_nova_f64_Nova_ParseFloatError_p* r = (NovaRes_nova_f64_Nova_ParseFloatError_p*)nova_alloc(sizeof(NovaRes_nova_f64_Nova_ParseFloatError_p)); r->tag = NOVA_TAG_Result_Err; r->payload.Err._0 = v; r->err_typed_payload = NULL; r->err_typed_type_id = NOVA_TID_NONE; return r; }
typedef struct NovaRes_nova_bool_Nova_ParseBoolError_p { int tag; union { struct { nova_bool _0; } Ok; struct { Nova_ParseBoolError* _0; } Err; } payload; void* err_typed_payload; NovaTypeId err_typed_type_id; } NovaRes_nova_bool_Nova_ParseBoolError_p;
static inline NovaRes_nova_bool_Nova_ParseBoolError_p* nova_make_NovaRes_nova_bool_Nova_ParseBoolError_p_Ok(nova_bool v) { NovaRes_nova_bool_Nova_ParseBoolError_p* r = (NovaRes_nova_bool_Nova_ParseBoolError_p*)nova_alloc(sizeof(NovaRes_nova_bool_Nova_ParseBoolError_p)); r->tag = NOVA_TAG_Result_Ok; r->payload.Ok._0 = v; r->err_typed_payload = NULL; r->err_typed_type_id = NOVA_TID_NONE; return r; }
static inline NovaRes_nova_bool_Nova_ParseBoolError_p* nova_make_NovaRes_nova_bool_Nova_ParseBoolError_p_Err(Nova_ParseBoolError* v) { NovaRes_nova_bool_Nova_ParseBoolError_p* r = (NovaRes_nova_bool_Nova_ParseBoolError_p*)nova_alloc(sizeof(NovaRes_nova_bool_Nova_ParseBoolError_p)); r->tag = NOVA_TAG_Result_Err; r->payload.Err._0 = v; r->err_typed_payload = NULL; r->err_typed_type_id = NOVA_TID_NONE; return r; }
typedef struct NovaRes_nova_char_Nova_ParseCharError_p { int tag; union { struct { nova_char _0; } Ok; struct { Nova_ParseCharError* _0; } Err; } payload; void* err_typed_payload; NovaTypeId err_typed_type_id; } NovaRes_nova_char_Nova_ParseCharError_p;
static inline NovaRes_nova_char_Nova_ParseCharError_p* nova_make_NovaRes_nova_char_Nova_ParseCharError_p_Ok(nova_char v) { NovaRes_nova_char_Nova_ParseCharError_p* r = (NovaRes_nova_char_Nova_ParseCharError_p*)nova_alloc(sizeof(NovaRes_nova_char_Nova_ParseCharError_p)); r->tag = NOVA_TAG_Result_Ok; r->payload.Ok._0 = v; r->err_typed_payload = NULL; r->err_typed_type_id = NOVA_TID_NONE; return r; }
static inline NovaRes_nova_char_Nova_ParseCharError_p* nova_make_NovaRes_nova_char_Nova_ParseCharError_p_Err(Nova_ParseCharError* v) { NovaRes_nova_char_Nova_ParseCharError_p* r = (NovaRes_nova_char_Nova_ParseCharError_p*)nova_alloc(sizeof(NovaRes_nova_char_Nova_ParseCharError_p)); r->tag = NOVA_TAG_Result_Err; r->payload.Err._0 = v; r->err_typed_payload = NULL; r->err_typed_type_id = NOVA_TID_NONE; return r; }
typedef struct NovaRes_int64_t_Nova_ParseIntError_p { int tag; union { struct { int64_t _0; } Ok; struct { Nova_ParseIntError* _0; } Err; } payload; void* err_typed_payload; NovaTypeId err_typed_type_id; } NovaRes_int64_t_Nova_ParseIntError_p;
static inline NovaRes_int64_t_Nova_ParseIntError_p* nova_make_NovaRes_int64_t_Nova_ParseIntError_p_Ok(int64_t v) { NovaRes_int64_t_Nova_ParseIntError_p* r = (NovaRes_int64_t_Nova_ParseIntError_p*)nova_alloc(sizeof(NovaRes_int64_t_Nova_ParseIntError_p)); r->tag = NOVA_TAG_Result_Ok; r->payload.Ok._0 = v; r->err_typed_payload = NULL; r->err_typed_type_id = NOVA_TID_NONE; return r; }
static inline NovaRes_int64_t_Nova_ParseIntError_p* nova_make_NovaRes_int64_t_Nova_ParseIntError_p_Err(Nova_ParseIntError* v) { NovaRes_int64_t_Nova_ParseIntError_p* r = (NovaRes_int64_t_Nova_ParseIntError_p*)nova_alloc(sizeof(NovaRes_int64_t_Nova_ParseIntError_p)); r->tag = NOVA_TAG_Result_Err; r->payload.Err._0 = v; r->err_typed_payload = NULL; r->err_typed_type_id = NOVA_TID_NONE; return r; }
typedef struct NovaRes_uint64_t_Nova_ParseIntError_p { int tag; union { struct { uint64_t _0; } Ok; struct { Nova_ParseIntError* _0; } Err; } payload; void* err_typed_payload; NovaTypeId err_typed_type_id; } NovaRes_uint64_t_Nova_ParseIntError_p;
static inline NovaRes_uint64_t_Nova_ParseIntError_p* nova_make_NovaRes_uint64_t_Nova_ParseIntError_p_Ok(uint64_t v) { NovaRes_uint64_t_Nova_ParseIntError_p* r = (NovaRes_uint64_t_Nova_ParseIntError_p*)nova_alloc(sizeof(NovaRes_uint64_t_Nova_ParseIntError_p)); r->tag = NOVA_TAG_Result_Ok; r->payload.Ok._0 = v; r->err_typed_payload = NULL; r->err_typed_type_id = NOVA_TID_NONE; return r; }
static inline NovaRes_uint64_t_Nova_ParseIntError_p* nova_make_NovaRes_uint64_t_Nova_ParseIntError_p_Err(Nova_ParseIntError* v) { NovaRes_uint64_t_Nova_ParseIntError_p* r = (NovaRes_uint64_t_Nova_ParseIntError_p*)nova_alloc(sizeof(NovaRes_uint64_t_Nova_ParseIntError_p)); r->tag = NOVA_TAG_Result_Err; r->payload.Err._0 = v; r->err_typed_payload = NULL; r->err_typed_type_id = NOVA_TID_NONE; return r; }
typedef struct NovaRes_uint32_t_Nova_ParseIntError_p { int tag; union { struct { uint32_t _0; } Ok; struct { Nova_ParseIntError* _0; } Err; } payload; void* err_typed_payload; NovaTypeId err_typed_type_id; } NovaRes_uint32_t_Nova_ParseIntError_p;
static inline NovaRes_uint32_t_Nova_ParseIntError_p* nova_make_NovaRes_uint32_t_Nova_ParseIntError_p_Ok(uint32_t v) { NovaRes_uint32_t_Nova_ParseIntError_p* r = (NovaRes_uint32_t_Nova_ParseIntError_p*)nova_alloc(sizeof(NovaRes_uint32_t_Nova_ParseIntError_p)); r->tag = NOVA_TAG_Result_Ok; r->payload.Ok._0 = v; r->err_typed_payload = NULL; r->err_typed_type_id = NOVA_TID_NONE; return r; }
static inline NovaRes_uint32_t_Nova_ParseIntError_p* nova_make_NovaRes_uint32_t_Nova_ParseIntError_p_Err(Nova_ParseIntError* v) { NovaRes_uint32_t_Nova_ParseIntError_p* r = (NovaRes_uint32_t_Nova_ParseIntError_p*)nova_alloc(sizeof(NovaRes_uint32_t_Nova_ParseIntError_p)); r->tag = NOVA_TAG_Result_Err; r->payload.Err._0 = v; r->err_typed_payload = NULL; r->err_typed_type_id = NOVA_TID_NONE; return r; }
typedef struct NovaRes_nova_byte_Nova_ParseIntError_p { int tag; union { struct { nova_byte _0; } Ok; struct { Nova_ParseIntError* _0; } Err; } payload; void* err_typed_payload; NovaTypeId err_typed_type_id; } NovaRes_nova_byte_Nova_ParseIntError_p;
static inline NovaRes_nova_byte_Nova_ParseIntError_p* nova_make_NovaRes_nova_byte_Nova_ParseIntError_p_Ok(nova_byte v) { NovaRes_nova_byte_Nova_ParseIntError_p* r = (NovaRes_nova_byte_Nova_ParseIntError_p*)nova_alloc(sizeof(NovaRes_nova_byte_Nova_ParseIntError_p)); r->tag = NOVA_TAG_Result_Ok; r->payload.Ok._0 = v; r->err_typed_payload = NULL; r->err_typed_type_id = NOVA_TID_NONE; return r; }
static inline NovaRes_nova_byte_Nova_ParseIntError_p* nova_make_NovaRes_nova_byte_Nova_ParseIntError_p_Err(Nova_ParseIntError* v) { NovaRes_nova_byte_Nova_ParseIntError_p* r = (NovaRes_nova_byte_Nova_ParseIntError_p*)nova_alloc(sizeof(NovaRes_nova_byte_Nova_ParseIntError_p)); r->tag = NOVA_TAG_Result_Err; r->payload.Err._0 = v; r->err_typed_payload = NULL; r->err_typed_type_id = NOVA_TID_NONE; return r; }
typedef struct NovaRes_int8_t_Nova_ParseIntError_p { int tag; union { struct { int8_t _0; } Ok; struct { Nova_ParseIntError* _0; } Err; } payload; void* err_typed_payload; NovaTypeId err_typed_type_id; } NovaRes_int8_t_Nova_ParseIntError_p;
static inline NovaRes_int8_t_Nova_ParseIntError_p* nova_make_NovaRes_int8_t_Nova_ParseIntError_p_Ok(int8_t v) { NovaRes_int8_t_Nova_ParseIntError_p* r = (NovaRes_int8_t_Nova_ParseIntError_p*)nova_alloc(sizeof(NovaRes_int8_t_Nova_ParseIntError_p)); r->tag = NOVA_TAG_Result_Ok; r->payload.Ok._0 = v; r->err_typed_payload = NULL; r->err_typed_type_id = NOVA_TID_NONE; return r; }
static inline NovaRes_int8_t_Nova_ParseIntError_p* nova_make_NovaRes_int8_t_Nova_ParseIntError_p_Err(Nova_ParseIntError* v) { NovaRes_int8_t_Nova_ParseIntError_p* r = (NovaRes_int8_t_Nova_ParseIntError_p*)nova_alloc(sizeof(NovaRes_int8_t_Nova_ParseIntError_p)); r->tag = NOVA_TAG_Result_Err; r->payload.Err._0 = v; r->err_typed_payload = NULL; r->err_typed_type_id = NOVA_TID_NONE; return r; }
typedef struct NovaRes_int16_t_Nova_ParseIntError_p { int tag; union { struct { int16_t _0; } Ok; struct { Nova_ParseIntError* _0; } Err; } payload; void* err_typed_payload; NovaTypeId err_typed_type_id; } NovaRes_int16_t_Nova_ParseIntError_p;
static inline NovaRes_int16_t_Nova_ParseIntError_p* nova_make_NovaRes_int16_t_Nova_ParseIntError_p_Ok(int16_t v) { NovaRes_int16_t_Nova_ParseIntError_p* r = (NovaRes_int16_t_Nova_ParseIntError_p*)nova_alloc(sizeof(NovaRes_int16_t_Nova_ParseIntError_p)); r->tag = NOVA_TAG_Result_Ok; r->payload.Ok._0 = v; r->err_typed_payload = NULL; r->err_typed_type_id = NOVA_TID_NONE; return r; }
static inline NovaRes_int16_t_Nova_ParseIntError_p* nova_make_NovaRes_int16_t_Nova_ParseIntError_p_Err(Nova_ParseIntError* v) { NovaRes_int16_t_Nova_ParseIntError_p* r = (NovaRes_int16_t_Nova_ParseIntError_p*)nova_alloc(sizeof(NovaRes_int16_t_Nova_ParseIntError_p)); r->tag = NOVA_TAG_Result_Err; r->payload.Err._0 = v; r->err_typed_payload = NULL; r->err_typed_type_id = NOVA_TID_NONE; return r; }
typedef struct NovaRes_int32_t_Nova_ParseIntError_p { int tag; union { struct { int32_t _0; } Ok; struct { Nova_ParseIntError* _0; } Err; } payload; void* err_typed_payload; NovaTypeId err_typed_type_id; } NovaRes_int32_t_Nova_ParseIntError_p;
static inline NovaRes_int32_t_Nova_ParseIntError_p* nova_make_NovaRes_int32_t_Nova_ParseIntError_p_Ok(int32_t v) { NovaRes_int32_t_Nova_ParseIntError_p* r = (NovaRes_int32_t_Nova_ParseIntError_p*)nova_alloc(sizeof(NovaRes_int32_t_Nova_ParseIntError_p)); r->tag = NOVA_TAG_Result_Ok; r->payload.Ok._0 = v; r->err_typed_payload = NULL; r->err_typed_type_id = NOVA_TID_NONE; return r; }
static inline NovaRes_int32_t_Nova_ParseIntError_p* nova_make_NovaRes_int32_t_Nova_ParseIntError_p_Err(Nova_ParseIntError* v) { NovaRes_int32_t_Nova_ParseIntError_p* r = (NovaRes_int32_t_Nova_ParseIntError_p*)nova_alloc(sizeof(NovaRes_int32_t_Nova_ParseIntError_p)); r->tag = NOVA_TAG_Result_Err; r->payload.Err._0 = v; r->err_typed_payload = NULL; r->err_typed_type_id = NOVA_TID_NONE; return r; }
typedef struct NovaRes_uint16_t_Nova_ParseIntError_p { int tag; union { struct { uint16_t _0; } Ok; struct { Nova_ParseIntError* _0; } Err; } payload; void* err_typed_payload; NovaTypeId err_typed_type_id; } NovaRes_uint16_t_Nova_ParseIntError_p;
static inline NovaRes_uint16_t_Nova_ParseIntError_p* nova_make_NovaRes_uint16_t_Nova_ParseIntError_p_Ok(uint16_t v) { NovaRes_uint16_t_Nova_ParseIntError_p* r = (NovaRes_uint16_t_Nova_ParseIntError_p*)nova_alloc(sizeof(NovaRes_uint16_t_Nova_ParseIntError_p)); r->tag = NOVA_TAG_Result_Ok; r->payload.Ok._0 = v; r->err_typed_payload = NULL; r->err_typed_type_id = NOVA_TID_NONE; return r; }
static inline NovaRes_uint16_t_Nova_ParseIntError_p* nova_make_NovaRes_uint16_t_Nova_ParseIntError_p_Err(Nova_ParseIntError* v) { NovaRes_uint16_t_Nova_ParseIntError_p* r = (NovaRes_uint16_t_Nova_ParseIntError_p*)nova_alloc(sizeof(NovaRes_uint16_t_Nova_ParseIntError_p)); r->tag = NOVA_TAG_Result_Err; r->payload.Err._0 = v; r->err_typed_payload = NULL; r->err_typed_type_id = NOVA_TID_NONE; return r; }
typedef struct NovaRes_nova_byte_Nova_ReadBufferError_p { int tag; union { struct { nova_byte _0; } Ok; struct { Nova_ReadBufferError* _0; } Err; } payload; void* err_typed_payload; NovaTypeId err_typed_type_id; } NovaRes_nova_byte_Nova_ReadBufferError_p;
static inline NovaRes_nova_byte_Nova_ReadBufferError_p* nova_make_NovaRes_nova_byte_Nova_ReadBufferError_p_Ok(nova_byte v) { NovaRes_nova_byte_Nova_ReadBufferError_p* r = (NovaRes_nova_byte_Nova_ReadBufferError_p*)nova_alloc(sizeof(NovaRes_nova_byte_Nova_ReadBufferError_p)); r->tag = NOVA_TAG_Result_Ok; r->payload.Ok._0 = v; r->err_typed_payload = NULL; r->err_typed_type_id = NOVA_TID_NONE; return r; }
static inline NovaRes_nova_byte_Nova_ReadBufferError_p* nova_make_NovaRes_nova_byte_Nova_ReadBufferError_p_Err(Nova_ReadBufferError* v) { NovaRes_nova_byte_Nova_ReadBufferError_p* r = (NovaRes_nova_byte_Nova_ReadBufferError_p*)nova_alloc(sizeof(NovaRes_nova_byte_Nova_ReadBufferError_p)); r->tag = NOVA_TAG_Result_Err; r->payload.Err._0 = v; r->err_typed_payload = NULL; r->err_typed_type_id = NOVA_TID_NONE; return r; }
typedef struct NovaRes_Nova_Vec____nova_byte_p_Nova_ReadBufferError_p { int tag; union { struct { Nova_Vec____nova_byte* _0; } Ok; struct { Nova_ReadBufferError* _0; } Err; } payload; void* err_typed_payload; NovaTypeId err_typed_type_id; } NovaRes_Nova_Vec____nova_byte_p_Nova_ReadBufferError_p;
static inline NovaRes_Nova_Vec____nova_byte_p_Nova_ReadBufferError_p* nova_make_NovaRes_Nova_Vec____nova_byte_p_Nova_ReadBufferError_p_Ok(Nova_Vec____nova_byte* v) { NovaRes_Nova_Vec____nova_byte_p_Nova_ReadBufferError_p* r = (NovaRes_Nova_Vec____nova_byte_p_Nova_ReadBufferError_p*)nova_alloc(sizeof(NovaRes_Nova_Vec____nova_byte_p_Nova_ReadBufferError_p)); r->tag = NOVA_TAG_Result_Ok; r->payload.Ok._0 = v; r->err_typed_payload = NULL; r->err_typed_type_id = NOVA_TID_NONE; return r; }
static inline NovaRes_Nova_Vec____nova_byte_p_Nova_ReadBufferError_p* nova_make_NovaRes_Nova_Vec____nova_byte_p_Nova_ReadBufferError_p_Err(Nova_ReadBufferError* v) { NovaRes_Nova_Vec____nova_byte_p_Nova_ReadBufferError_p* r = (NovaRes_Nova_Vec____nova_byte_p_Nova_ReadBufferError_p*)nova_alloc(sizeof(NovaRes_Nova_Vec____nova_byte_p_Nova_ReadBufferError_p)); r->tag = NOVA_TAG_Result_Err; r->payload.Err._0 = v; r->err_typed_payload = NULL; r->err_typed_type_id = NOVA_TID_NONE; return r; }
typedef struct NovaRes_int8_t_Nova_ReadBufferError_p { int tag; union { struct { int8_t _0; } Ok; struct { Nova_ReadBufferError* _0; } Err; } payload; void* err_typed_payload; NovaTypeId err_typed_type_id; } NovaRes_int8_t_Nova_ReadBufferError_p;
static inline NovaRes_int8_t_Nova_ReadBufferError_p* nova_make_NovaRes_int8_t_Nova_ReadBufferError_p_Ok(int8_t v) { NovaRes_int8_t_Nova_ReadBufferError_p* r = (NovaRes_int8_t_Nova_ReadBufferError_p*)nova_alloc(sizeof(NovaRes_int8_t_Nova_ReadBufferError_p)); r->tag = NOVA_TAG_Result_Ok; r->payload.Ok._0 = v; r->err_typed_payload = NULL; r->err_typed_type_id = NOVA_TID_NONE; return r; }
static inline NovaRes_int8_t_Nova_ReadBufferError_p* nova_make_NovaRes_int8_t_Nova_ReadBufferError_p_Err(Nova_ReadBufferError* v) { NovaRes_int8_t_Nova_ReadBufferError_p* r = (NovaRes_int8_t_Nova_ReadBufferError_p*)nova_alloc(sizeof(NovaRes_int8_t_Nova_ReadBufferError_p)); r->tag = NOVA_TAG_Result_Err; r->payload.Err._0 = v; r->err_typed_payload = NULL; r->err_typed_type_id = NOVA_TID_NONE; return r; }
typedef struct NovaRes_uint16_t_Nova_ReadBufferError_p { int tag; union { struct { uint16_t _0; } Ok; struct { Nova_ReadBufferError* _0; } Err; } payload; void* err_typed_payload; NovaTypeId err_typed_type_id; } NovaRes_uint16_t_Nova_ReadBufferError_p;
static inline NovaRes_uint16_t_Nova_ReadBufferError_p* nova_make_NovaRes_uint16_t_Nova_ReadBufferError_p_Ok(uint16_t v) { NovaRes_uint16_t_Nova_ReadBufferError_p* r = (NovaRes_uint16_t_Nova_ReadBufferError_p*)nova_alloc(sizeof(NovaRes_uint16_t_Nova_ReadBufferError_p)); r->tag = NOVA_TAG_Result_Ok; r->payload.Ok._0 = v; r->err_typed_payload = NULL; r->err_typed_type_id = NOVA_TID_NONE; return r; }
static inline NovaRes_uint16_t_Nova_ReadBufferError_p* nova_make_NovaRes_uint16_t_Nova_ReadBufferError_p_Err(Nova_ReadBufferError* v) { NovaRes_uint16_t_Nova_ReadBufferError_p* r = (NovaRes_uint16_t_Nova_ReadBufferError_p*)nova_alloc(sizeof(NovaRes_uint16_t_Nova_ReadBufferError_p)); r->tag = NOVA_TAG_Result_Err; r->payload.Err._0 = v; r->err_typed_payload = NULL; r->err_typed_type_id = NOVA_TID_NONE; return r; }
typedef struct NovaRes_int16_t_Nova_ReadBufferError_p { int tag; union { struct { int16_t _0; } Ok; struct { Nova_ReadBufferError* _0; } Err; } payload; void* err_typed_payload; NovaTypeId err_typed_type_id; } NovaRes_int16_t_Nova_ReadBufferError_p;
static inline NovaRes_int16_t_Nova_ReadBufferError_p* nova_make_NovaRes_int16_t_Nova_ReadBufferError_p_Ok(int16_t v) { NovaRes_int16_t_Nova_ReadBufferError_p* r = (NovaRes_int16_t_Nova_ReadBufferError_p*)nova_alloc(sizeof(NovaRes_int16_t_Nova_ReadBufferError_p)); r->tag = NOVA_TAG_Result_Ok; r->payload.Ok._0 = v; r->err_typed_payload = NULL; r->err_typed_type_id = NOVA_TID_NONE; return r; }
static inline NovaRes_int16_t_Nova_ReadBufferError_p* nova_make_NovaRes_int16_t_Nova_ReadBufferError_p_Err(Nova_ReadBufferError* v) { NovaRes_int16_t_Nova_ReadBufferError_p* r = (NovaRes_int16_t_Nova_ReadBufferError_p*)nova_alloc(sizeof(NovaRes_int16_t_Nova_ReadBufferError_p)); r->tag = NOVA_TAG_Result_Err; r->payload.Err._0 = v; r->err_typed_payload = NULL; r->err_typed_type_id = NOVA_TID_NONE; return r; }
typedef struct NovaRes_uint32_t_Nova_ReadBufferError_p { int tag; union { struct { uint32_t _0; } Ok; struct { Nova_ReadBufferError* _0; } Err; } payload; void* err_typed_payload; NovaTypeId err_typed_type_id; } NovaRes_uint32_t_Nova_ReadBufferError_p;
static inline NovaRes_uint32_t_Nova_ReadBufferError_p* nova_make_NovaRes_uint32_t_Nova_ReadBufferError_p_Ok(uint32_t v) { NovaRes_uint32_t_Nova_ReadBufferError_p* r = (NovaRes_uint32_t_Nova_ReadBufferError_p*)nova_alloc(sizeof(NovaRes_uint32_t_Nova_ReadBufferError_p)); r->tag = NOVA_TAG_Result_Ok; r->payload.Ok._0 = v; r->err_typed_payload = NULL; r->err_typed_type_id = NOVA_TID_NONE; return r; }
static inline NovaRes_uint32_t_Nova_ReadBufferError_p* nova_make_NovaRes_uint32_t_Nova_ReadBufferError_p_Err(Nova_ReadBufferError* v) { NovaRes_uint32_t_Nova_ReadBufferError_p* r = (NovaRes_uint32_t_Nova_ReadBufferError_p*)nova_alloc(sizeof(NovaRes_uint32_t_Nova_ReadBufferError_p)); r->tag = NOVA_TAG_Result_Err; r->payload.Err._0 = v; r->err_typed_payload = NULL; r->err_typed_type_id = NOVA_TID_NONE; return r; }
typedef struct NovaRes_int32_t_Nova_ReadBufferError_p { int tag; union { struct { int32_t _0; } Ok; struct { Nova_ReadBufferError* _0; } Err; } payload; void* err_typed_payload; NovaTypeId err_typed_type_id; } NovaRes_int32_t_Nova_ReadBufferError_p;
static inline NovaRes_int32_t_Nova_ReadBufferError_p* nova_make_NovaRes_int32_t_Nova_ReadBufferError_p_Ok(int32_t v) { NovaRes_int32_t_Nova_ReadBufferError_p* r = (NovaRes_int32_t_Nova_ReadBufferError_p*)nova_alloc(sizeof(NovaRes_int32_t_Nova_ReadBufferError_p)); r->tag = NOVA_TAG_Result_Ok; r->payload.Ok._0 = v; r->err_typed_payload = NULL; r->err_typed_type_id = NOVA_TID_NONE; return r; }
static inline NovaRes_int32_t_Nova_ReadBufferError_p* nova_make_NovaRes_int32_t_Nova_ReadBufferError_p_Err(Nova_ReadBufferError* v) { NovaRes_int32_t_Nova_ReadBufferError_p* r = (NovaRes_int32_t_Nova_ReadBufferError_p*)nova_alloc(sizeof(NovaRes_int32_t_Nova_ReadBufferError_p)); r->tag = NOVA_TAG_Result_Err; r->payload.Err._0 = v; r->err_typed_payload = NULL; r->err_typed_type_id = NOVA_TID_NONE; return r; }
typedef struct NovaRes_uint64_t_Nova_ReadBufferError_p { int tag; union { struct { uint64_t _0; } Ok; struct { Nova_ReadBufferError* _0; } Err; } payload; void* err_typed_payload; NovaTypeId err_typed_type_id; } NovaRes_uint64_t_Nova_ReadBufferError_p;
static inline NovaRes_uint64_t_Nova_ReadBufferError_p* nova_make_NovaRes_uint64_t_Nova_ReadBufferError_p_Ok(uint64_t v) { NovaRes_uint64_t_Nova_ReadBufferError_p* r = (NovaRes_uint64_t_Nova_ReadBufferError_p*)nova_alloc(sizeof(NovaRes_uint64_t_Nova_ReadBufferError_p)); r->tag = NOVA_TAG_Result_Ok; r->payload.Ok._0 = v; r->err_typed_payload = NULL; r->err_typed_type_id = NOVA_TID_NONE; return r; }
static inline NovaRes_uint64_t_Nova_ReadBufferError_p* nova_make_NovaRes_uint64_t_Nova_ReadBufferError_p_Err(Nova_ReadBufferError* v) { NovaRes_uint64_t_Nova_ReadBufferError_p* r = (NovaRes_uint64_t_Nova_ReadBufferError_p*)nova_alloc(sizeof(NovaRes_uint64_t_Nova_ReadBufferError_p)); r->tag = NOVA_TAG_Result_Err; r->payload.Err._0 = v; r->err_typed_payload = NULL; r->err_typed_type_id = NOVA_TID_NONE; return r; }
typedef struct NovaRes_int64_t_Nova_ReadBufferError_p { int tag; union { struct { int64_t _0; } Ok; struct { Nova_ReadBufferError* _0; } Err; } payload; void* err_typed_payload; NovaTypeId err_typed_type_id; } NovaRes_int64_t_Nova_ReadBufferError_p;
static inline NovaRes_int64_t_Nova_ReadBufferError_p* nova_make_NovaRes_int64_t_Nova_ReadBufferError_p_Ok(int64_t v) { NovaRes_int64_t_Nova_ReadBufferError_p* r = (NovaRes_int64_t_Nova_ReadBufferError_p*)nova_alloc(sizeof(NovaRes_int64_t_Nova_ReadBufferError_p)); r->tag = NOVA_TAG_Result_Ok; r->payload.Ok._0 = v; r->err_typed_payload = NULL; r->err_typed_type_id = NOVA_TID_NONE; return r; }
static inline NovaRes_int64_t_Nova_ReadBufferError_p* nova_make_NovaRes_int64_t_Nova_ReadBufferError_p_Err(Nova_ReadBufferError* v) { NovaRes_int64_t_Nova_ReadBufferError_p* r = (NovaRes_int64_t_Nova_ReadBufferError_p*)nova_alloc(sizeof(NovaRes_int64_t_Nova_ReadBufferError_p)); r->tag = NOVA_TAG_Result_Err; r->payload.Err._0 = v; r->err_typed_payload = NULL; r->err_typed_type_id = NOVA_TID_NONE; return r; }
typedef struct NovaRes_nova_f32_Nova_ReadBufferError_p { int tag; union { struct { nova_f32 _0; } Ok; struct { Nova_ReadBufferError* _0; } Err; } payload; void* err_typed_payload; NovaTypeId err_typed_type_id; } NovaRes_nova_f32_Nova_ReadBufferError_p;
static inline NovaRes_nova_f32_Nova_ReadBufferError_p* nova_make_NovaRes_nova_f32_Nova_ReadBufferError_p_Ok(nova_f32 v) { NovaRes_nova_f32_Nova_ReadBufferError_p* r = (NovaRes_nova_f32_Nova_ReadBufferError_p*)nova_alloc(sizeof(NovaRes_nova_f32_Nova_ReadBufferError_p)); r->tag = NOVA_TAG_Result_Ok; r->payload.Ok._0 = v; r->err_typed_payload = NULL; r->err_typed_type_id = NOVA_TID_NONE; return r; }
static inline NovaRes_nova_f32_Nova_ReadBufferError_p* nova_make_NovaRes_nova_f32_Nova_ReadBufferError_p_Err(Nova_ReadBufferError* v) { NovaRes_nova_f32_Nova_ReadBufferError_p* r = (NovaRes_nova_f32_Nova_ReadBufferError_p*)nova_alloc(sizeof(NovaRes_nova_f32_Nova_ReadBufferError_p)); r->tag = NOVA_TAG_Result_Err; r->payload.Err._0 = v; r->err_typed_payload = NULL; r->err_typed_type_id = NOVA_TID_NONE; return r; }
typedef struct NovaRes_nova_f64_Nova_ReadBufferError_p { int tag; union { struct { nova_f64 _0; } Ok; struct { Nova_ReadBufferError* _0; } Err; } payload; void* err_typed_payload; NovaTypeId err_typed_type_id; } NovaRes_nova_f64_Nova_ReadBufferError_p;
static inline NovaRes_nova_f64_Nova_ReadBufferError_p* nova_make_NovaRes_nova_f64_Nova_ReadBufferError_p_Ok(nova_f64 v) { NovaRes_nova_f64_Nova_ReadBufferError_p* r = (NovaRes_nova_f64_Nova_ReadBufferError_p*)nova_alloc(sizeof(NovaRes_nova_f64_Nova_ReadBufferError_p)); r->tag = NOVA_TAG_Result_Ok; r->payload.Ok._0 = v; r->err_typed_payload = NULL; r->err_typed_type_id = NOVA_TID_NONE; return r; }
static inline NovaRes_nova_f64_Nova_ReadBufferError_p* nova_make_NovaRes_nova_f64_Nova_ReadBufferError_p_Err(Nova_ReadBufferError* v) { NovaRes_nova_f64_Nova_ReadBufferError_p* r = (NovaRes_nova_f64_Nova_ReadBufferError_p*)nova_alloc(sizeof(NovaRes_nova_f64_Nova_ReadBufferError_p)); r->tag = NOVA_TAG_Result_Err; r->payload.Err._0 = v; r->err_typed_payload = NULL; r->err_typed_type_id = NOVA_TID_NONE; return r; }
typedef struct NovaRes__NovaTuple_2_8_nova_int_8_nova_int_Nova_ReadBufferError_p { int tag; union { struct { _NovaTuple_2_8_nova_int_8_nova_int _0; } Ok; struct { Nova_ReadBufferError* _0; } Err; } payload; void* err_typed_payload; NovaTypeId err_typed_type_id; } NovaRes__NovaTuple_2_8_nova_int_8_nova_int_Nova_ReadBufferError_p;
static inline NovaRes__NovaTuple_2_8_nova_int_8_nova_int_Nova_ReadBufferError_p* nova_make_NovaRes__NovaTuple_2_8_nova_int_8_nova_int_Nova_ReadBufferError_p_Ok(_NovaTuple_2_8_nova_int_8_nova_int v) { NovaRes__NovaTuple_2_8_nova_int_8_nova_int_Nova_ReadBufferError_p* r = (NovaRes__NovaTuple_2_8_nova_int_8_nova_int_Nova_ReadBufferError_p*)nova_alloc(sizeof(NovaRes__NovaTuple_2_8_nova_int_8_nova_int_Nova_ReadBufferError_p)); r->tag = NOVA_TAG_Result_Ok; r->payload.Ok._0 = v; r->err_typed_payload = NULL; r->err_typed_type_id = NOVA_TID_NONE; return r; }
static inline NovaRes__NovaTuple_2_8_nova_int_8_nova_int_Nova_ReadBufferError_p* nova_make_NovaRes__NovaTuple_2_8_nova_int_8_nova_int_Nova_ReadBufferError_p_Err(Nova_ReadBufferError* v) { NovaRes__NovaTuple_2_8_nova_int_8_nova_int_Nova_ReadBufferError_p* r = (NovaRes__NovaTuple_2_8_nova_int_8_nova_int_Nova_ReadBufferError_p*)nova_alloc(sizeof(NovaRes__NovaTuple_2_8_nova_int_8_nova_int_Nova_ReadBufferError_p)); r->tag = NOVA_TAG_Result_Err; r->payload.Err._0 = v; r->err_typed_payload = NULL; r->err_typed_type_id = NOVA_TID_NONE; return r; }
typedef struct NovaRes_nova_char_Nova_ReadBufferError_p { int tag; union { struct { nova_char _0; } Ok; struct { Nova_ReadBufferError* _0; } Err; } payload; void* err_typed_payload; NovaTypeId err_typed_type_id; } NovaRes_nova_char_Nova_ReadBufferError_p;
static inline NovaRes_nova_char_Nova_ReadBufferError_p* nova_make_NovaRes_nova_char_Nova_ReadBufferError_p_Ok(nova_char v) { NovaRes_nova_char_Nova_ReadBufferError_p* r = (NovaRes_nova_char_Nova_ReadBufferError_p*)nova_alloc(sizeof(NovaRes_nova_char_Nova_ReadBufferError_p)); r->tag = NOVA_TAG_Result_Ok; r->payload.Ok._0 = v; r->err_typed_payload = NULL; r->err_typed_type_id = NOVA_TID_NONE; return r; }
static inline NovaRes_nova_char_Nova_ReadBufferError_p* nova_make_NovaRes_nova_char_Nova_ReadBufferError_p_Err(Nova_ReadBufferError* v) { NovaRes_nova_char_Nova_ReadBufferError_p* r = (NovaRes_nova_char_Nova_ReadBufferError_p*)nova_alloc(sizeof(NovaRes_nova_char_Nova_ReadBufferError_p)); r->tag = NOVA_TAG_Result_Err; r->payload.Err._0 = v; r->err_typed_payload = NULL; r->err_typed_type_id = NOVA_TID_NONE; return r; }
typedef struct NovaRes_nova_str_Nova_ReadBufferError_p { int tag; union { struct { nova_str _0; } Ok; struct { Nova_ReadBufferError* _0; } Err; } payload; void* err_typed_payload; NovaTypeId err_typed_type_id; } NovaRes_nova_str_Nova_ReadBufferError_p;
static inline NovaRes_nova_str_Nova_ReadBufferError_p* nova_make_NovaRes_nova_str_Nova_ReadBufferError_p_Ok(nova_str v) { NovaRes_nova_str_Nova_ReadBufferError_p* r = (NovaRes_nova_str_Nova_ReadBufferError_p*)nova_alloc(sizeof(NovaRes_nova_str_Nova_ReadBufferError_p)); r->tag = NOVA_TAG_Result_Ok; r->payload.Ok._0 = v; r->err_typed_payload = NULL; r->err_typed_type_id = NOVA_TID_NONE; return r; }
static inline NovaRes_nova_str_Nova_ReadBufferError_p* nova_make_NovaRes_nova_str_Nova_ReadBufferError_p_Err(Nova_ReadBufferError* v) { NovaRes_nova_str_Nova_ReadBufferError_p* r = (NovaRes_nova_str_Nova_ReadBufferError_p*)nova_alloc(sizeof(NovaRes_nova_str_Nova_ReadBufferError_p)); r->tag = NOVA_TAG_Result_Err; r->payload.Err._0 = v; r->err_typed_payload = NULL; r->err_typed_type_id = NOVA_TID_NONE; return r; }
typedef struct NovaRes_int8_t_Nova_RangeError_p { int tag; union { struct { int8_t _0; } Ok; struct { Nova_RangeError* _0; } Err; } payload; void* err_typed_payload; NovaTypeId err_typed_type_id; } NovaRes_int8_t_Nova_RangeError_p;
static inline NovaRes_int8_t_Nova_RangeError_p* nova_make_NovaRes_int8_t_Nova_RangeError_p_Ok(int8_t v) { NovaRes_int8_t_Nova_RangeError_p* r = (NovaRes_int8_t_Nova_RangeError_p*)nova_alloc(sizeof(NovaRes_int8_t_Nova_RangeError_p)); r->tag = NOVA_TAG_Result_Ok; r->payload.Ok._0 = v; r->err_typed_payload = NULL; r->err_typed_type_id = NOVA_TID_NONE; return r; }
static inline NovaRes_int8_t_Nova_RangeError_p* nova_make_NovaRes_int8_t_Nova_RangeError_p_Err(Nova_RangeError* v) { NovaRes_int8_t_Nova_RangeError_p* r = (NovaRes_int8_t_Nova_RangeError_p*)nova_alloc(sizeof(NovaRes_int8_t_Nova_RangeError_p)); r->tag = NOVA_TAG_Result_Err; r->payload.Err._0 = v; r->err_typed_payload = NULL; r->err_typed_type_id = NOVA_TID_NONE; return r; }
typedef struct NovaRes_int16_t_Nova_RangeError_p { int tag; union { struct { int16_t _0; } Ok; struct { Nova_RangeError* _0; } Err; } payload; void* err_typed_payload; NovaTypeId err_typed_type_id; } NovaRes_int16_t_Nova_RangeError_p;
static inline NovaRes_int16_t_Nova_RangeError_p* nova_make_NovaRes_int16_t_Nova_RangeError_p_Ok(int16_t v) { NovaRes_int16_t_Nova_RangeError_p* r = (NovaRes_int16_t_Nova_RangeError_p*)nova_alloc(sizeof(NovaRes_int16_t_Nova_RangeError_p)); r->tag = NOVA_TAG_Result_Ok; r->payload.Ok._0 = v; r->err_typed_payload = NULL; r->err_typed_type_id = NOVA_TID_NONE; return r; }
static inline NovaRes_int16_t_Nova_RangeError_p* nova_make_NovaRes_int16_t_Nova_RangeError_p_Err(Nova_RangeError* v) { NovaRes_int16_t_Nova_RangeError_p* r = (NovaRes_int16_t_Nova_RangeError_p*)nova_alloc(sizeof(NovaRes_int16_t_Nova_RangeError_p)); r->tag = NOVA_TAG_Result_Err; r->payload.Err._0 = v; r->err_typed_payload = NULL; r->err_typed_type_id = NOVA_TID_NONE; return r; }
typedef struct NovaRes_int32_t_Nova_RangeError_p { int tag; union { struct { int32_t _0; } Ok; struct { Nova_RangeError* _0; } Err; } payload; void* err_typed_payload; NovaTypeId err_typed_type_id; } NovaRes_int32_t_Nova_RangeError_p;
static inline NovaRes_int32_t_Nova_RangeError_p* nova_make_NovaRes_int32_t_Nova_RangeError_p_Ok(int32_t v) { NovaRes_int32_t_Nova_RangeError_p* r = (NovaRes_int32_t_Nova_RangeError_p*)nova_alloc(sizeof(NovaRes_int32_t_Nova_RangeError_p)); r->tag = NOVA_TAG_Result_Ok; r->payload.Ok._0 = v; r->err_typed_payload = NULL; r->err_typed_type_id = NOVA_TID_NONE; return r; }
static inline NovaRes_int32_t_Nova_RangeError_p* nova_make_NovaRes_int32_t_Nova_RangeError_p_Err(Nova_RangeError* v) { NovaRes_int32_t_Nova_RangeError_p* r = (NovaRes_int32_t_Nova_RangeError_p*)nova_alloc(sizeof(NovaRes_int32_t_Nova_RangeError_p)); r->tag = NOVA_TAG_Result_Err; r->payload.Err._0 = v; r->err_typed_payload = NULL; r->err_typed_type_id = NOVA_TID_NONE; return r; }
typedef struct NovaRes_int64_t_Nova_RangeError_p { int tag; union { struct { int64_t _0; } Ok; struct { Nova_RangeError* _0; } Err; } payload; void* err_typed_payload; NovaTypeId err_typed_type_id; } NovaRes_int64_t_Nova_RangeError_p;
static inline NovaRes_int64_t_Nova_RangeError_p* nova_make_NovaRes_int64_t_Nova_RangeError_p_Ok(int64_t v) { NovaRes_int64_t_Nova_RangeError_p* r = (NovaRes_int64_t_Nova_RangeError_p*)nova_alloc(sizeof(NovaRes_int64_t_Nova_RangeError_p)); r->tag = NOVA_TAG_Result_Ok; r->payload.Ok._0 = v; r->err_typed_payload = NULL; r->err_typed_type_id = NOVA_TID_NONE; return r; }
static inline NovaRes_int64_t_Nova_RangeError_p* nova_make_NovaRes_int64_t_Nova_RangeError_p_Err(Nova_RangeError* v) { NovaRes_int64_t_Nova_RangeError_p* r = (NovaRes_int64_t_Nova_RangeError_p*)nova_alloc(sizeof(NovaRes_int64_t_Nova_RangeError_p)); r->tag = NOVA_TAG_Result_Err; r->payload.Err._0 = v; r->err_typed_payload = NULL; r->err_typed_type_id = NOVA_TID_NONE; return r; }
typedef struct NovaRes_nova_int_Nova_RangeError_p { int tag; union { struct { nova_int _0; } Ok; struct { Nova_RangeError* _0; } Err; } payload; void* err_typed_payload; NovaTypeId err_typed_type_id; } NovaRes_nova_int_Nova_RangeError_p;
static inline NovaRes_nova_int_Nova_RangeError_p* nova_make_NovaRes_nova_int_Nova_RangeError_p_Ok(nova_int v) { NovaRes_nova_int_Nova_RangeError_p* r = (NovaRes_nova_int_Nova_RangeError_p*)nova_alloc(sizeof(NovaRes_nova_int_Nova_RangeError_p)); r->tag = NOVA_TAG_Result_Ok; r->payload.Ok._0 = v; r->err_typed_payload = NULL; r->err_typed_type_id = NOVA_TID_NONE; return r; }
static inline NovaRes_nova_int_Nova_RangeError_p* nova_make_NovaRes_nova_int_Nova_RangeError_p_Err(Nova_RangeError* v) { NovaRes_nova_int_Nova_RangeError_p* r = (NovaRes_nova_int_Nova_RangeError_p*)nova_alloc(sizeof(NovaRes_nova_int_Nova_RangeError_p)); r->tag = NOVA_TAG_Result_Err; r->payload.Err._0 = v; r->err_typed_payload = NULL; r->err_typed_type_id = NOVA_TID_NONE; return r; }
typedef struct NovaRes_nova_byte_Nova_RangeError_p { int tag; union { struct { nova_byte _0; } Ok; struct { Nova_RangeError* _0; } Err; } payload; void* err_typed_payload; NovaTypeId err_typed_type_id; } NovaRes_nova_byte_Nova_RangeError_p;
static inline NovaRes_nova_byte_Nova_RangeError_p* nova_make_NovaRes_nova_byte_Nova_RangeError_p_Ok(nova_byte v) { NovaRes_nova_byte_Nova_RangeError_p* r = (NovaRes_nova_byte_Nova_RangeError_p*)nova_alloc(sizeof(NovaRes_nova_byte_Nova_RangeError_p)); r->tag = NOVA_TAG_Result_Ok; r->payload.Ok._0 = v; r->err_typed_payload = NULL; r->err_typed_type_id = NOVA_TID_NONE; return r; }
static inline NovaRes_nova_byte_Nova_RangeError_p* nova_make_NovaRes_nova_byte_Nova_RangeError_p_Err(Nova_RangeError* v) { NovaRes_nova_byte_Nova_RangeError_p* r = (NovaRes_nova_byte_Nova_RangeError_p*)nova_alloc(sizeof(NovaRes_nova_byte_Nova_RangeError_p)); r->tag = NOVA_TAG_Result_Err; r->payload.Err._0 = v; r->err_typed_payload = NULL; r->err_typed_type_id = NOVA_TID_NONE; return r; }
typedef struct NovaRes_uint16_t_Nova_RangeError_p { int tag; union { struct { uint16_t _0; } Ok; struct { Nova_RangeError* _0; } Err; } payload; void* err_typed_payload; NovaTypeId err_typed_type_id; } NovaRes_uint16_t_Nova_RangeError_p;
static inline NovaRes_uint16_t_Nova_RangeError_p* nova_make_NovaRes_uint16_t_Nova_RangeError_p_Ok(uint16_t v) { NovaRes_uint16_t_Nova_RangeError_p* r = (NovaRes_uint16_t_Nova_RangeError_p*)nova_alloc(sizeof(NovaRes_uint16_t_Nova_RangeError_p)); r->tag = NOVA_TAG_Result_Ok; r->payload.Ok._0 = v; r->err_typed_payload = NULL; r->err_typed_type_id = NOVA_TID_NONE; return r; }
static inline NovaRes_uint16_t_Nova_RangeError_p* nova_make_NovaRes_uint16_t_Nova_RangeError_p_Err(Nova_RangeError* v) { NovaRes_uint16_t_Nova_RangeError_p* r = (NovaRes_uint16_t_Nova_RangeError_p*)nova_alloc(sizeof(NovaRes_uint16_t_Nova_RangeError_p)); r->tag = NOVA_TAG_Result_Err; r->payload.Err._0 = v; r->err_typed_payload = NULL; r->err_typed_type_id = NOVA_TID_NONE; return r; }
typedef struct NovaRes_uint32_t_Nova_RangeError_p { int tag; union { struct { uint32_t _0; } Ok; struct { Nova_RangeError* _0; } Err; } payload; void* err_typed_payload; NovaTypeId err_typed_type_id; } NovaRes_uint32_t_Nova_RangeError_p;
static inline NovaRes_uint32_t_Nova_RangeError_p* nova_make_NovaRes_uint32_t_Nova_RangeError_p_Ok(uint32_t v) { NovaRes_uint32_t_Nova_RangeError_p* r = (NovaRes_uint32_t_Nova_RangeError_p*)nova_alloc(sizeof(NovaRes_uint32_t_Nova_RangeError_p)); r->tag = NOVA_TAG_Result_Ok; r->payload.Ok._0 = v; r->err_typed_payload = NULL; r->err_typed_type_id = NOVA_TID_NONE; return r; }
static inline NovaRes_uint32_t_Nova_RangeError_p* nova_make_NovaRes_uint32_t_Nova_RangeError_p_Err(Nova_RangeError* v) { NovaRes_uint32_t_Nova_RangeError_p* r = (NovaRes_uint32_t_Nova_RangeError_p*)nova_alloc(sizeof(NovaRes_uint32_t_Nova_RangeError_p)); r->tag = NOVA_TAG_Result_Err; r->payload.Err._0 = v; r->err_typed_payload = NULL; r->err_typed_type_id = NOVA_TID_NONE; return r; }
typedef struct NovaRes_uint64_t_Nova_RangeError_p { int tag; union { struct { uint64_t _0; } Ok; struct { Nova_RangeError* _0; } Err; } payload; void* err_typed_payload; NovaTypeId err_typed_type_id; } NovaRes_uint64_t_Nova_RangeError_p;
static inline NovaRes_uint64_t_Nova_RangeError_p* nova_make_NovaRes_uint64_t_Nova_RangeError_p_Ok(uint64_t v) { NovaRes_uint64_t_Nova_RangeError_p* r = (NovaRes_uint64_t_Nova_RangeError_p*)nova_alloc(sizeof(NovaRes_uint64_t_Nova_RangeError_p)); r->tag = NOVA_TAG_Result_Ok; r->payload.Ok._0 = v; r->err_typed_payload = NULL; r->err_typed_type_id = NOVA_TID_NONE; return r; }
static inline NovaRes_uint64_t_Nova_RangeError_p* nova_make_NovaRes_uint64_t_Nova_RangeError_p_Err(Nova_RangeError* v) { NovaRes_uint64_t_Nova_RangeError_p* r = (NovaRes_uint64_t_Nova_RangeError_p*)nova_alloc(sizeof(NovaRes_uint64_t_Nova_RangeError_p)); r->tag = NOVA_TAG_Result_Err; r->payload.Err._0 = v; r->err_typed_payload = NULL; r->err_typed_type_id = NOVA_TID_NONE; return r; }
typedef struct NovaRes_nova_uint_Nova_RangeError_p { int tag; union { struct { nova_uint _0; } Ok; struct { Nova_RangeError* _0; } Err; } payload; void* err_typed_payload; NovaTypeId err_typed_type_id; } NovaRes_nova_uint_Nova_RangeError_p;
static inline NovaRes_nova_uint_Nova_RangeError_p* nova_make_NovaRes_nova_uint_Nova_RangeError_p_Ok(nova_uint v) { NovaRes_nova_uint_Nova_RangeError_p* r = (NovaRes_nova_uint_Nova_RangeError_p*)nova_alloc(sizeof(NovaRes_nova_uint_Nova_RangeError_p)); r->tag = NOVA_TAG_Result_Ok; r->payload.Ok._0 = v; r->err_typed_payload = NULL; r->err_typed_type_id = NOVA_TID_NONE; return r; }
static inline NovaRes_nova_uint_Nova_RangeError_p* nova_make_NovaRes_nova_uint_Nova_RangeError_p_Err(Nova_RangeError* v) { NovaRes_nova_uint_Nova_RangeError_p* r = (NovaRes_nova_uint_Nova_RangeError_p*)nova_alloc(sizeof(NovaRes_nova_uint_Nova_RangeError_p)); r->tag = NOVA_TAG_Result_Err; r->payload.Err._0 = v; r->err_typed_payload = NULL; r->err_typed_type_id = NOVA_TID_NONE; return r; }

/* Plan 95 Ф.2.4: forward decls для mono'd Nova-body методов на Option/Result (placed after NovaOpt/NovaRes typedefs — by-value/by-pointer signature requires complete/forward typedef visible). */
static NovaRes_nova_char_Nova_ParseCharError_p* Nova_Option_method_ok_or_nova_char____Nova_ParseCharError_p(NovaOpt_nova_char nova_self, Nova_ParseCharError* err);

/* Plan 139 Ф.6: interned string literals (rodata dedup). */
static const uint8_t _nova_strlit_5b5c98ef514dbfa5_buf[] = "true";
static const nova_str _nova_strlit_5b5c98ef514dbfa5 = { .ptr = _nova_strlit_5b5c98ef514dbfa5_buf, .len = 4 };
static const uint8_t _nova_strlit_b5fae2c14238b978_buf[] = "false";
static const nova_str _nova_strlit_b5fae2c14238b978 = { .ptr = _nova_strlit_b5fae2c14238b978_buf, .len = 5 };
static const uint8_t _nova_strlit_af63a04c86018698_buf[] = "-";
static const nova_str _nova_strlit_af63a04c86018698 = { .ptr = _nova_strlit_af63a04c86018698_buf, .len = 1 };
/*__NOVAC_STRLITS__*/
typedef struct {
    void* ctx;
    nova_unit (*register_finalizer)(void*, void*); 
    nova_int (*default_exit_timeout_ms)(void*); 
} NovaVtable_Application;
#ifdef _MSC_VER
__declspec(thread) NovaVtable_Application* _nova_handler_Application = NULL;
#else
__thread NovaVtable_Application* _nova_handler_Application = NULL;
#endif
typedef struct {
    void* ctx;
    uint64_t (*u64)(void*); 
    Nova_Vec____nova_byte* (*bytes)(void*, nova_int); 
} NovaVtable_Random;
#ifdef _MSC_VER
__declspec(thread) NovaVtable_Random* _nova_handler_Random = NULL;
#else
__thread NovaVtable_Random* _nova_handler_Random = NULL;
#endif
typedef struct {
    void* ctx;
    nova_unit (*on_resource_enter)(void*, nova_str); 
    nova_unit (*on_resource_exit)(void*, nova_str, Nova_ScopeOutcome*, nova_int, nova_bool); 
} NovaVtable_ResourceTrace;
#ifdef _MSC_VER
__declspec(thread) NovaVtable_ResourceTrace* _nova_handler_ResourceTrace = NULL;
#else
__thread NovaVtable_ResourceTrace* _nova_handler_ResourceTrace = NULL;
#endif
typedef struct {
    void* ctx;
    Nova_Decision* (*on_child_fail)(void*, nova_int, void*); 
} NovaVtable_Supervisor;
#ifdef _MSC_VER
__declspec(thread) NovaVtable_Supervisor* _nova_handler_Supervisor = NULL;
#else
__thread NovaVtable_Supervisor* _nova_handler_Supervisor = NULL;
#endif
struct Nova_TimeoutError {
    int64_t deadline_ns;
};
typedef enum {
    NOVA_TAG_Decision_Escalate,
    NOVA_TAG_Decision_Stop,
} Nova_Decision_Tag;
struct Nova_Decision {
    Nova_Decision_Tag tag;
    union {
        char _dummy;
    } payload;
};

/*__NOVAC_BODY__*/

static void nova_consts_init(void) {
}

static void _nova_register_all_effects_(void) {
    nova_register_effect_storage((void**)&_nova_handler_Fail);
    nova_register_effect_storage((void**)&_nova_handler_Application);
    nova_register_effect_storage((void**)&_nova_handler_Random);
    nova_register_effect_storage((void**)&_nova_handler_ResourceTrace);
    nova_register_effect_storage((void**)&_nova_handler_Supervisor);
}

/* Plan 174 (D349): typed TimeoutError throw — assigned to
* _nova_throw_scope_timeout_fn in main(). Replaces the string-fallback in
* nova_throw_scope_timeout when TimeoutError is referenced. */
static void _nova_throw_scope_timeout_impl(int64_t deadline_ns) {
Nova_TimeoutError* _e = (Nova_TimeoutError*)nova_alloc(sizeof(Nova_TimeoutError));
_e->deadline_ns = (int64_t)deadline_ns;
(void)nova_throw_typed(nova_str_from_cstr("supervised-timeout: scope deadline exceeded"), (void*)_e, NOVA_TID_USER_TimeoutError);
/* unreachable */
}

/* Plan 173.2: Supervisor decision bridge — assigned to
* _nova_supervisor_decide_fn in main(). Called by the runtime's serialized
* decision pass (nova_supervised_process_decisions, fibers.h) once per
* retained child failure, on the scope's drive thread. Maps the ambient
* Nova `Supervisor.on_child_fail(idx, err)` handler's Decision to the
* NOVA_SUPERVISE_* codes. No handler → Escalate (the default policy). */
static nova_int _nova_supervisor_decide_impl(void* _scope_v, nova_int _idx, const void* _err_v) {
NovaFiberQueue* _scope = (NovaFiberQueue*)_scope_v;
const NovaChildError* _err = (const NovaChildError*)_err_v;
NovaVtable_Supervisor* _h = _nova_handler_Supervisor;
if (!_h) return (nova_int)NOVA_SUPERVISE_ESCALATE;
/* Box the failure into Nova `any`: typed-throw payload keeps its type
* (narrowable via `err is T`); string throws / panics box the message
* as `str`. */
void* _e_any = NULL;
if (_err->payload != NULL && _err->tid != 0) {
_e_any = nova_any_from_boxed(_err->payload, _err->tid);
} else {
nova_str _m = nova_str_from_cstr(_err->msg ? _err->msg : "");
_e_any = nova_any_box(&NOVA_TYPEINFO_nova_str, &_m, sizeof(nova_str));
}
/* Q-block (173.2): `Fail` is allowed inside the handler = Escalate-with-
* handler-error. Guard the invocation with a local fail-frame so a
* handler throw cannot longjmp past the drive loop (which would abandon
* still-running children); the thrown error is fed into the scope's
* primary machinery and the child failure escalates normally (rank
* precedence decides the surviving primary — a child PANIC still wins,
* D13). */
NovaFailFrame _sf;
nova_fail_push(&_sf);
if (setjmp(_sf.jmp) == 0) {
Nova_Decision* _d = _h->on_child_fail(_h->ctx, _idx, _e_any);
nova_fail_pop();
if (_d == NULL) return (nova_int)NOVA_SUPERVISE_ESCALATE;
switch (_d->tag) {
case NOVA_TAG_Decision_Stop:     return (nova_int)NOVA_SUPERVISE_STOP;
/* Escalate + defensive default: словарь Decision = Escalate|Stop
* (Restart-семейство ретрактировано, D416-амендмент 2026-07-10). */
case NOVA_TAG_Decision_Escalate:
default:                         return (nova_int)NOVA_SUPERVISE_ESCALATE;
}
} else {
nova_fail_pop();
nova_fiber_report_atomic_kinded(_scope, _sf.error_msg.ptr, _sf.error_kind,
_sf.error_reason_ptr, _sf.error_user_payload,
_sf.error_user_type_id);
return (nova_int)NOVA_SUPERVISE_ESCALATE;
}
}

static void _nova_main_fiber_entry(mco_coro* _co) {
    NovaSpawnCtxBase* _c = (NovaSpawnCtxBase*)mco_get_user_data(_co);
    _nova_main_fiber_co = (void*)_co;
    _c->_nova_worker_slot = -1;
    NovaFailFrame _ff;
    nova_fail_push(&_ff);
    if (setjmp(_ff.jmp) == 0) {
        nova_fn_main_impl();
        nova_fail_pop();
    } else {
        nova_fail_pop();
        if (_ff.error_msg.ptr && _ff.error_msg.len == 18 && memcmp(_ff.error_msg.ptr, "__nova_interrupt__", 18) == 0) {
            /* interrupt: scope state already set, fiber dies cleanly (mirrors emit_spawn). */
        } else {
            nova_fiber_report_error_kinded(_ff.error_msg.ptr, _ff.error_kind, _ff.error_reason_ptr);
        }
    }
    _nova_main_fiber_co = NULL;
}

int main(int argc, char** argv) {
    nova_gc_init();
    nova_consts_init();
    nova_os_set_args(argc, argv);
    nova_runtime_auto_arm();
    nova_evloop_init();
    _nova_register_effects_fn = _nova_register_all_effects_;
    _nova_register_all_effects_();
        _nova_throw_scope_timeout_fn = &_nova_throw_scope_timeout_impl;
        _nova_supervisor_decide_fn = &_nova_supervisor_decide_impl;
    NovaFiberQueue _nova_main_scope; nova_scope_init(&_nova_main_scope);
    _nova_active_scope = &_nova_main_scope;
    _nova_active_slot  = -1;
    nova_evloop_install_sigint(&_nova_main_scope);
    {
        NovaSpawnCtxBase* _nova_main_ctx = (NovaSpawnCtxBase*)nova_alloc(sizeof(NovaSpawnCtxBase));
        _nova_main_ctx->_nova_worker_slot = -1;
        _nova_main_ctx->_nova_parent_slot = -1;
        _nova_main_ctx->_nova_parent_scope = NULL;
        _nova_main_ctx->_nova_init_snapshot = NULL;
        nova_fiber_spawn_into(&_nova_main_scope, _nova_main_fiber_entry, _nova_main_ctx);
        nova_supervised_run(&_nova_main_scope);
    }
    nova_supervised_drain_main_scope(&_nova_main_scope);
    _nova_active_scope = NULL;
    _nova_active_slot  = -1;
    nova_runtime_drain_orphans();
    nova_runtime_shutdown();
    nova_evloop_close();
    nova_gc_shutdown();
    return 0;
}

